/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
'use client'

import { Box, type SxProps, type Theme } from '@mui/material'
import { resolveMediaSrc } from '@aglyn/aglyn/app-utils/media-ref'

/**
 * A listing's publisher-chosen artwork, resolved (AGL-1424).
 *
 * `marketplaceListings.previewImageUrl` was rendered by handing the stored
 * string straight to a `src`, on the browse card and again at the top of the
 * detail page. That is a buyer-facing surface, so the stored raw
 * `firebasestorage` URL leaks the bucket path and the publishing org's id,
 * gets no CDN delivery or WebP variants, and — because the embedded
 * `&token=` is regenerated by `media/replace/route.ts` on every replace, and
 * an AGL-1215 folder move copies the object and deletes the original — rots
 * silently the first time the publisher touches the asset.
 *
 * The repair is a `media:{scope}/{mediaId}` reference in the field, which
 * names the ASSET rather than a location. This component is the render half
 * of that, and it has to ship BEFORE any value is converted: to a renderer
 * that does not know the scheme a reference is just a nonsense URL, and the
 * listing image goes dark. That ordering is the whole lesson of AGL-1407.
 *
 * {@link resolveMediaSrc} carries the three stored generations, so nothing
 * needs converting for this to be correct today: a reference becomes the CDN
 * path, and a raw storage URL, a legacy `/api/media/cdn/…` path and an
 * author-typed external URL are all passed through untouched. Both apps that
 * render marketplace UI serve `/api/media/cdn/[...path]`, so the root-relative
 * result resolves on the console origin the listing pages are served from.
 *
 * Renders NOTHING when there is no usable source — absent, empty, or a
 * `media:` value too malformed to resolve. Each call site previously wrote
 * that conditional itself; a malformed reference reaching a `src` would be a
 * broken-image icon on a store page and a console error nobody reads.
 *
 * A plain MUI `Box component="img"`, deliberately: the besigner's standalone
 * image block is what broke tenant SSR in AGL-579, and every image on these
 * pages is already this element. This adds a resolver, not a rendering
 * strategy.
 */
export interface ListingImageProps {
  /** The stored value: a `media:` reference, or any URL. */
  src?: string | null
  alt: string
  sx?: SxProps<Theme>
  loading?: 'eager' | 'lazy'
  onClick?: () => void
}

export function ListingImage({
  src,
  alt,
  sx,
  loading,
  onClick,
}: ListingImageProps) {
  const resolved = resolveMediaSrc(src)
  if (!resolved) return null
  return (
    <Box
      component="img"
      src={resolved}
      alt={alt}
      {...(loading ? { loading } : {})}
      {...(onClick ? { onClick } : {})}
      sx={sx}
    />
  )
}

export default ListingImage
