/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// VENDORS THE GATE FROM THE WORKSPACE BUILD — it is never hand-copied.
//
// The 5xx gate and the signature check are the security boundary of a public
// endpoint, and `vercel-log-drain.spec.ts` / `vercel-drain-signature.spec.ts`
// are what keep them honest. A second hand-written implementation in this
// directory would be untested from the day it drifted, so `lib/` is GENERATED
// from `nx build tenant-data-admin` and regenerated on every deploy.
//
// This is a COPY rather than a bundle because it can be: `vercel-log-drain.js`
// compiles with no static imports at all (its only Firebase reach is a lazy
// `await import` that this receiver never triggers — it always passes its own
// `target`), and `vercel-drain-signature.js` imports nothing but `node:crypto`.
// So the deployed service has zero npm dependencies and needs no bundler.
//
//   npm --prefix cloud/log-drain run prepare
//
// `deploy.sh` runs it, so a stale `lib/` cannot reach Cloud Run.
import { execFileSync } from 'node:child_process'
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const repo = resolve(here, '../..')
const built = join(repo, 'dist/libs/tenant/data/admin/src/lib/server')
const out = join(here, 'lib')

const MODULES = ['vercel-log-drain.js', 'vercel-drain-signature.js']

console.log('building tenant-data-admin…')
execFileSync('npx', ['nx', 'build', 'tenant-data-admin'], {
  cwd: repo,
  stdio: 'inherit',
})

mkdirSync(out, { recursive: true })
for (const file of MODULES) {
  const src = join(built, file)
  const body = readFileSync(src, 'utf8')
  // A STATIC import here would mean npm dependencies in the image and, for
  // firebase-admin, a module that cannot even resolve on Cloud Run. Fail the
  // prepare rather than discover it as a boot crash in production.
  const statics = [...body.matchAll(/^import\s.*?from\s+'([^']+)'/gm)]
    .map((m) => m[1])
    .filter((s) => !s.startsWith('node:'))
  if (statics.length) {
    console.error(
      `\n${file} gained static imports that this service cannot resolve:\n` +
        statics.map((s) => `  - ${s}`).join('\n') +
        `\n\nEither keep them out of the drain modules, or switch this step to a bundler.\n`,
    )
    process.exit(1)
  }
  writeFileSync(
    join(out, file),
    `// GENERATED by cloud/log-drain/prepare.mjs from\n` +
      `// libs/tenant/data/admin/src/lib/server/${file.replace(/\.js$/, '.ts')}\n` +
      `// DO NOT EDIT. Run: npm --prefix cloud/log-drain run prepare\n` +
      body,
  )
  console.log(`vendored ${file}`)
}
