/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * The Vercel log-drain receiver, on Cloud Run (AGL-1921).
 *
 * ## Why this is not a Vercel route any more
 *
 * It was `apps/console/app/api/log-drain/route.ts`, on `aglyn-console`, and
 * the `aglyn-console-runtime-5xx` drain watched `aglyn-console`. **A delivery
 * POST is a request to whatever hosts the receiver, and a request produces a
 * log.** So each delivery manufactured its own next input: measured
 * 2026-08-26 at 695K invocations in nine hours, ~21/sec, billing simultaneously
 * on function invocations, function duration, edge requests, observability
 * events and drains volume.
 *
 * The route's own docstring argued the loop could not happen, and its
 * reasoning was sound — `RECEIVER_ROUTE_PATH` and the 5xx gate really do stop
 * the receiver's entries reaching Cloud Logging. But those are cuts on the
 * WRITE. The cost is the DELIVERY, and nothing inside the receiver can
 * decline to be requested.
 *
 * ⛔ **Vercel's drain `sampling` rules are not the answer, and this was
 * measured rather than assumed.** A single `{environment:"production",
 * rate:0}` rule with no path prefix — literally "drop everything" — moved
 * delivery volume from 31 to 32 per five minutes. The whole `schemas.log`
 * filter block (`sources`, `environments`, `sampling`) is accepted by
 * `POST`/`PATCH /v1/drains`, echoed back on `GET`, and never applied. Do not
 * try to solve this with drain configuration.
 *
 * ## Why here specifically
 *
 * The loop is positional: it exists exactly when a drain's watched project is
 * also the receiver's host. Cloud Run is watched by no drain, so BOTH drains
 * can point here and neither can feed itself. It is also where the data was
 * always going — the gate writes to Cloud Logging in `aglyn-main` — so this
 * removes a hop rather than adding one, and Application Default Credentials
 * replace the Firebase admin credential the Vercel route had to carry.
 *
 * ## The gate is BUNDLED, not reimplemented
 *
 * `lib/` is GENERATED by `prepare.mjs` from `nx build tenant-data-admin`, so
 * `vercel-log-drain.spec.ts` and `vercel-drain-signature.spec.ts` still cover
 * the code that actually runs here. A hand-written second copy of a public
 * endpoint's security boundary would be untested from the day it drifted.
 *
 * A copy suffices rather than a bundle because both modules compile with no
 * static imports beyond `node:crypto` — so this service has zero npm
 * dependencies. `prepare.mjs` FAILS if that ever stops being true.
 */

import { createServer } from 'node:http'
import {
  DRAIN_SECRET_ENV,
  ingestDrainDelivery,
  parseDrainPayload,
} from './lib/vercel-log-drain.js'
import { isValidDrainSignature } from './lib/vercel-drain-signature.js'

/**
 * Byte cap before parse, carried over from the Vercel route: deliveries are
 * batched so this is generous, but an unbounded read on a public endpoint is
 * a memory-exhaustion primitive for whoever finds the URL.
 */
const MAX_BODY_BYTES = 2 * 1_024 * 1_024

const PORT = Number(process.env['PORT'] ?? 8080)

/**
 * Cloud Logging credentials from the instance metadata server.
 *
 * Cached until shortly before expiry. The metadata server is local and cheap,
 * but a token fetch per delivery would be a round trip on the hot path of an
 * endpoint whose whole point is to be cheap.
 */
let cachedToken = null

async function metadataLoggingTarget() {
  const now = Date.now()
  if (cachedToken && cachedToken.expiresAt > now + 60_000) {
    return { token: cachedToken.token, projectId: cachedToken.projectId }
  }
  try {
    const headers = { 'Metadata-Flavor': 'Google' }
    const root = 'http://metadata.google.internal/computeMetadata/v1'
    const [tokenRes, projectRes] = await Promise.all([
      fetch(`${root}/instance/service-accounts/default/token`, { headers }),
      fetch(`${root}/project/project-id`, { headers }),
    ])
    if (!tokenRes.ok || !projectRes.ok) return null
    const token = await tokenRes.json()
    const projectId = (await projectRes.text()).trim()
    if (!token?.access_token || !projectId) return null
    cachedToken = {
      token: token.access_token,
      projectId,
      expiresAt: now + Math.max(0, Number(token.expires_in ?? 0)) * 1000,
    }
    return { token: cachedToken.token, projectId }
  } catch {
    // Never throw: a credential outage must not turn into a 5xx, or Vercel
    // disables the drain during the incident it exists to report.
    return null
  }
}

/** Read the RAW body, capped. The signature is over these exact bytes. */
function readRawBody(req) {
  return new Promise((resolve, reject) => {
    let size = 0
    const chunks = []
    req.on('data', (chunk) => {
      size += chunk.length
      if (size > MAX_BODY_BYTES) {
        reject(new Error('body-too-large'))
        req.destroy()
        return
      }
      chunks.push(chunk)
    })
    req.on('end', () => resolve(Buffer.concat(chunks).toString('utf8')))
    req.on('error', reject)
  })
}

function send(res, status, body, extraHeaders = {}) {
  res.writeHead(status, {
    'Content-Type': 'application/json',
    'X-Content-Type-Options': 'nosniff',
    ...extraHeaders,
  })
  res.end(JSON.stringify(body))
}

const server = createServer(async (req, res) => {
  // Echoed on EVERY response, including refusals. The `x-vercel-verify`
  // handshake is only loosely documented (see the drains memo), so the header
  // is cheap insurance rather than a considered protocol step.
  const verify = process.env['VERCEL_LOG_DRAIN_VERIFY']
  const verifyHeader = verify ? { 'x-vercel-verify': verify } : {}

  // Cloud Run's own health probe, and a human checking the URL is alive.
  if (req.method === 'GET') {
    send(res, 200, { ok: true, service: 'aglyn-log-drain' }, verifyHeader)
    return
  }
  if (req.method !== 'POST') {
    send(res, 405, { error: 'Method not allowed' }, {
      ...verifyHeader,
      Allow: 'GET, POST',
    })
    return
  }

  let raw
  try {
    raw = await readRawBody(req)
  } catch {
    send(res, 413, { error: 'Body too large' }, verifyHeader)
    return
  }

  // Vercel probes the endpoint with an empty body when the drain is created.
  // Answer 200 so creation succeeds; there is nothing to verify or ingest.
  if (!raw.trim()) {
    send(res, 200, { ok: true }, verifyHeader)
    return
  }

  // FAILS CLOSED. No secret configured, no header, or a bad one, and nothing
  // is read. The URL is not a secret — it is in the Vercel dashboard and in
  // this repo — so the signature is the entire boundary.
  const secret = process.env[DRAIN_SECRET_ENV]
  const signature = req.headers['x-vercel-signature']
  if (!isValidDrainSignature(raw, Array.isArray(signature) ? signature[0] : signature, secret)) {
    send(res, 401, { error: 'Bad signature' }, verifyHeader)
    return
  }

  const entries = parseDrainPayload(raw)
  const result = await ingestDrainDelivery(entries, {
    target: metadataLoggingTarget,
  })
  send(res, 200, result, verifyHeader)
})

server.listen(PORT, () => {
  // One line at boot, so a container that starts but cannot serve is
  // distinguishable from one that never started.
  console.log(
    JSON.stringify({ tag: 'AGL-1921:log-drain-receiver', listening: PORT }),
  )
})
