/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import type { PluginTrustSigner } from '@aglyn/aglyn/plugin-manager/plugin-trust-signing'
import { createPrivateKey, sign as nodeSign } from 'node:crypto'

/**
 * This app's implementation of `core.plugin-trust-signer` (AGL-3080), in its
 * own file so `instrumentation.ts` can DEFER IT BY RELATIVE PATH — `node:crypto`
 * has no business in the edge bundle, and the AGL-1921 rule says defer a
 * MODULE, never a lib specifier.
 *
 * `PLUGIN_TRUST_PRIVATE_KEY` is the base64 PKCS8 DER Ed25519 private key
 * (pair generated by `tools/scripts/generate-plugin-trust-key.mjs`) —
 * deployed ONLY to the console app, never to tenant runtimes, and never to
 * a published package. It stays here, behind the contract, for exactly that
 * reason: the marketplace decides what is worth signing, and the platform
 * signs it.
 *
 * Reads the key per call rather than at module load, so rotating it takes a
 * redeploy and not a cache-busting trick, and so an unconfigured deployment
 * says so on the attempt rather than at boot.
 */
export const consolePluginTrustSigner: PluginTrustSigner = {
  sign: async (sha256) => {
    const privateKeyBase64 = process.env.PLUGIN_TRUST_PRIVATE_KEY
    if (!privateKeyBase64) {
      return {
        signed: false,
        reason:
          'Trust signing is not configured (missing PLUGIN_TRUST_PRIVATE_KEY)',
      }
    }
    const privateKey = createPrivateKey({
      key: Buffer.from(privateKeyBase64, 'base64'),
      format: 'der',
      type: 'pkcs8',
    })
    // Ed25519 signs the message directly (no digest algorithm).
    return {
      signed: true,
      signature: nodeSign(null, Buffer.from(sha256), privateKey).toString(
        'base64',
      ),
    }
  },
}

export default consolePluginTrustSigner
