# Add 'dependencies' label to any change to npm or yarn related stuff
'dependencies':
  - package.json
  - yarn.lock

'tsconfig':
  - tsconfig.json
  - tsconfig.*.json

'jest-config':
  - jest.json
  - jest.*.json

'Nx Config':
  - nx.json
  - workspace.*.json

'Monorepo Libs':
  - libs/*
  - libs/**/*

'Monorepo Apps':
  - apps/*
  - apps/**/*

'Shared':
  - libs/shared/*
  - libs/shared/**/*

'App: WWW':
  - apps/www/*
  - apps/www/**/*

'App: Console':
  - apps/console/*
  - apps/console/**/*

'SDK: Framework':
  - libs/data/framework/*
  - libs/data/framework/**/*

'SDK: Extension':
  - libs/data/*
  - libs/data/**/*
  - !libs/data/framework/*
  - !libs/data/framework/**/*

'View: Renderer':
  - libs/ui/renderer/*
  - libs/ui/renderer/**/*

'View: Builder':
  - libs/ui/builder/*
  - libs/ui/builder/**/*
