// GENERATED by tools/scripts/generate-mobile-theme-tokens.mjs — do not edit.
// Source: the console's resolved MUI theme (libs/shared/ui/theme), light and dark.

package com.aglyn.ui

import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material3.ColorScheme
import androidx.compose.material3.Shapes
import androidx.compose.material3.Typography
import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.TextStyle
import androidx.compose.ui.text.font.FontFamily
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp

/** One theme intent: its fill, the text on that fill, its readable text color on the page background, and its pressed fill. */
data class AglynIntent(val main: Color, val contrastText: Color, val text: Color, val pressed: Color)

data class AglynPalette(
  val primary: AglynIntent,
  val secondary: AglynIntent,
  val tertiary: AglynIntent,
  val error: AglynIntent,
  val warning: AglynIntent,
  val success: AglynIntent,
  val info: AglynIntent,
  val background: Color,
  val paper: Color,
  val textPrimary: Color,
  val textSecondary: Color,
  val textDisabled: Color,
  val divider: Color,
  val grey: Map<Int, Color>,
)

/** One step of the console's type scale: sizes in sp, weight 100–900, tracking in sp. */
data class AglynTextStyle(
  val size: Float,
  val weight: Int,
  val lineHeight: Float,
  val letterSpacing: Float,
  /** The console sets this variant in capitals. */
  val uppercase: Boolean,
) {
  fun toTextStyle(fontFamily: FontFamily = FontFamily.Default) = TextStyle(
    fontFamily = fontFamily,
    fontWeight = FontWeight(weight),
    fontSize = size.sp,
    lineHeight = lineHeight.sp,
    letterSpacing = letterSpacing.sp,
  )
}

object AglynTokens {
  /** Corner radius in dp. */
  const val RADIUS = 4
  /** The spacing unit in dp. */
  const val SPACING = 8
  /** The family the console's type stack asks for first; the app bundles it. */
  const val FONT_FAMILY = "Roboto Flex"
  /** The bundled variable face's Compose resource name: `Res.font.robotoflex_variable`. */
  const val FONT_RESOURCE = "robotoflex_variable"

  val light = AglynPalette(
    primary = AglynIntent(main = Color(0xFF00B0FF), contrastText = Color(0xFFFFFFFF), text = Color(0xFF0073A8), pressed = Color(0xFF0077AD)),
    secondary = AglynIntent(main = Color(0xFFE040FB), contrastText = Color(0xFFFFFFFF), text = Color(0xFF9D2DB0), pressed = Color(0xFF9D2DB0)),
    tertiary = AglynIntent(main = Color(0xFF404C5C), contrastText = Color(0xFFFFFFFF), text = Color(0xFF2C3540), pressed = Color(0xFF2C3540)),
    error = AglynIntent(main = Color(0xFFE32C27), contrastText = Color(0xFFFFFFFF), text = Color(0xFF9E1E1B), pressed = Color(0xFF9E1E1B)),
    warning = AglynIntent(main = Color(0xFFFFAB40), contrastText = Color(0xDE000000), text = Color(0xFF956425), pressed = Color(0xFFFFC479)),
    success = AglynIntent(main = Color(0xFF4CAF50), contrastText = Color(0xDE000000), text = Color(0xFF357A38), pressed = Color(0xFF81C784)),
    info = AglynIntent(main = Color(0xFF1878CD), contrastText = Color(0xFFFFFFFF), text = Color(0xFF10548F), pressed = Color(0xFF10548F)),
    background = Color(0xFFF5F5F5),
    paper = Color(0xFFFFFFFF),
    textPrimary = Color(0xDE000000),
    textSecondary = Color(0x99000000),
    textDisabled = Color(0x61000000),
    divider = Color(0x1F000000),
    grey = mapOf(50 to Color(0xFFFAFAFA), 100 to Color(0xFFF5F5F5), 200 to Color(0xFFEEEEEE), 300 to Color(0xFFE0E0E0), 400 to Color(0xFFBDBDBD), 500 to Color(0xFF9E9E9E), 600 to Color(0xFF757575), 700 to Color(0xFF616161), 800 to Color(0xFF424242), 900 to Color(0xFF212121)),
  )

  val dark = AglynPalette(
    primary = AglynIntent(main = Color(0xFF00B0FF), contrastText = Color(0xFFFFFFFF), text = Color(0xFF4DC8FF), pressed = Color(0xFF007BB2)),
    secondary = AglynIntent(main = Color(0xFFE040FB), contrastText = Color(0xFFFFFFFF), text = Color(0xFFE979FC), pressed = Color(0xFF9C2CAF)),
    tertiary = AglynIntent(main = Color(0xFF7C8CA3), contrastText = Color(0xDE000000), text = Color(0xFFA3AFBF), pressed = Color(0xFFA3AFBF)),
    error = AglynIntent(main = Color(0xFFE32C27), contrastText = Color(0xFFFFFFFF), text = Color(0xFFEE7C7B), pressed = Color(0xFF9E1E1B)),
    warning = AglynIntent(main = Color(0xFFFFAB40), contrastText = Color(0xDE000000), text = Color(0xFFFFC479), pressed = Color(0xFFFFC479)),
    success = AglynIntent(main = Color(0xFF4CAF50), contrastText = Color(0xDE000000), text = Color(0xFF82C785), pressed = Color(0xFF82C785)),
    info = AglynIntent(main = Color(0xFF1878CD), contrastText = Color(0xFFFFFFFF), text = Color(0xFF65A6DE), pressed = Color(0xFF10548F)),
    background = Color(0xFF161C21),
    paper = Color(0xFF2A3440),
    textPrimary = Color(0xFFFFFFFF),
    textSecondary = Color(0xB3FFFFFF),
    textDisabled = Color(0x80FFFFFF),
    divider = Color(0x1FFFFFFF),
    grey = mapOf(50 to Color(0xFFFAFAFA), 100 to Color(0xFFF5F5F5), 200 to Color(0xFFEEEEEE), 300 to Color(0xFFE0E0E0), 400 to Color(0xFFBDBDBD), 500 to Color(0xFF9E9E9E), 600 to Color(0xFF757575), 700 to Color(0xFF616161), 800 to Color(0xFF424242), 900 to Color(0xFF212121)),
  )

  /** The console's type scale (MUI variants), at the phone size. */
  object Typography {
    val h1 = AglynTextStyle(size = 34.29f, weight = 900, lineHeight = 36f, letterSpacing = -0.857f, uppercase = false)
    val h2 = AglynTextStyle(size = 27.83f, weight = 800, lineHeight = 32f, letterSpacing = -0.557f, uppercase = false)
    val h3 = AglynTextStyle(size = 26.67f, weight = 700, lineHeight = 32f, letterSpacing = -0.4f, uppercase = false)
    val h4 = AglynTextStyle(size = 25.91f, weight = 400, lineHeight = 32f, letterSpacing = 0f, uppercase = false)
    val h5 = AglynTextStyle(size = 20.99f, weight = 400, lineHeight = 28f, letterSpacing = 0f, uppercase = false)
    val h6 = AglynTextStyle(size = 17.5f, weight = 500, lineHeight = 28f, letterSpacing = 0f, uppercase = false)
    val subtitle1 = AglynTextStyle(size = 16f, weight = 400, lineHeight = 28f, letterSpacing = 0f, uppercase = false)
    val subtitle2 = AglynTextStyle(size = 14f, weight = 500, lineHeight = 21.98f, letterSpacing = 0f, uppercase = false)
    val body1 = AglynTextStyle(size = 16f, weight = 400, lineHeight = 24f, letterSpacing = 0f, uppercase = false)
    val body2 = AglynTextStyle(size = 14f, weight = 400, lineHeight = 20.02f, letterSpacing = 0f, uppercase = false)
    val caption = AglynTextStyle(size = 12f, weight = 400, lineHeight = 19.92f, letterSpacing = 0f, uppercase = false)
    val button = AglynTextStyle(size = 14f, weight = 500, lineHeight = 24.5f, letterSpacing = 0f, uppercase = true)
    val overline = AglynTextStyle(size = 12f, weight = 400, lineHeight = 31.92f, letterSpacing = 0f, uppercase = true)
  }
}

/** The light palette on Material 3's roles. Dynamic color stays off, so the brand holds. */
val AglynLightColorScheme: ColorScheme = lightColorScheme(
  primary = Color(0xFF00B0FF),
  onPrimary = Color(0xFFFFFFFF),
  primaryContainer = Color(0xFFDBF4FF),
  onPrimaryContainer = Color(0xFF0073A8),
  inversePrimary = Color(0xFF00B0FF),
  secondary = Color(0xFF9D2DB0),
  onSecondary = Color(0xFFFFFFFF),
  secondaryContainer = Color(0xFFFBE4FE),
  onSecondaryContainer = Color(0xFF9D2DB0),
  tertiary = Color(0xFF404C5C),
  onTertiary = Color(0xFFFFFFFF),
  tertiaryContainer = Color(0xFFE4E6E8),
  onTertiaryContainer = Color(0xFF2C3540),
  error = Color(0xFFE32C27),
  onError = Color(0xFFFFFFFF),
  errorContainer = Color(0xFFFBE1E1),
  onErrorContainer = Color(0xFF9E1E1B),
  background = Color(0xFFF5F5F5),
  onBackground = Color(0xDE000000),
  surface = Color(0xFFF5F5F5),
  onSurface = Color(0xDE000000),
  surfaceVariant = Color(0xFFEEEEEE),
  onSurfaceVariant = Color(0x99000000),
  surfaceContainerLowest = Color(0xFFFFFFFF),
  surfaceContainerLow = Color(0xFFFFFFFF),
  surfaceContainer = Color(0xFFF5F5F5),
  surfaceContainerHigh = Color(0xFFEEEEEE),
  surfaceContainerHighest = Color(0xFFE0E0E0),
  outline = Color(0x61000000),
  outlineVariant = Color(0x1F000000),
)

/** The dark palette on Material 3's roles. */
val AglynDarkColorScheme: ColorScheme = darkColorScheme(
  primary = Color(0xFF00B0FF),
  onPrimary = Color(0xFFFFFFFF),
  primaryContainer = Color(0xFF20526E),
  onPrimaryContainer = Color(0xFF4DC8FF),
  inversePrimary = Color(0xFF00B0FF),
  secondary = Color(0xFFE979FC),
  onSecondary = Color(0xFFFFFFFF),
  secondaryContainer = Color(0xFF56376D),
  onSecondaryContainer = Color(0xFFE979FC),
  tertiary = Color(0xFF7C8CA3),
  onTertiary = Color(0xDE000000),
  tertiaryContainer = Color(0xFF3E4958),
  onTertiaryContainer = Color(0xFFA3AFBF),
  error = Color(0xFFE32C27),
  onError = Color(0xFFFFFFFF),
  errorContainer = Color(0xFF56323A),
  onErrorContainer = Color(0xFFEE7C7B),
  background = Color(0xFF161C21),
  onBackground = Color(0xFFFFFFFF),
  surface = Color(0xFF161C21),
  onSurface = Color(0xFFFFFFFF),
  surfaceVariant = Color(0xFF424242),
  onSurfaceVariant = Color(0xB3FFFFFF),
  surfaceContainerLowest = Color(0xFF2A3440),
  surfaceContainerLow = Color(0xFF2A3440),
  surfaceContainer = Color(0xFF2A3440),
  surfaceContainerHigh = Color(0xFF37404B),
  surfaceContainerHighest = Color(0xFF3F4853),
  outline = Color(0x80FFFFFF),
  outlineVariant = Color(0x1FFFFFFF),
)

/** The console's type scale on Material 3's roles, in [fontFamily] (the bundled face), sized in sp so it follows the font scale. */
fun aglynTypography(fontFamily: FontFamily = FontFamily.Default) = Typography(
  displayLarge = AglynTokens.Typography.h1.toTextStyle(fontFamily),
  displayMedium = AglynTokens.Typography.h2.toTextStyle(fontFamily),
  displaySmall = AglynTokens.Typography.h3.toTextStyle(fontFamily),
  headlineLarge = AglynTokens.Typography.h4.toTextStyle(fontFamily),
  headlineMedium = AglynTokens.Typography.h5.toTextStyle(fontFamily),
  headlineSmall = AglynTokens.Typography.h6.toTextStyle(fontFamily),
  titleLarge = AglynTokens.Typography.h6.toTextStyle(fontFamily),
  titleMedium = AglynTokens.Typography.subtitle1.toTextStyle(fontFamily),
  titleSmall = AglynTokens.Typography.subtitle2.toTextStyle(fontFamily),
  bodyLarge = AglynTokens.Typography.body1.toTextStyle(fontFamily),
  bodyMedium = AglynTokens.Typography.body2.toTextStyle(fontFamily),
  bodySmall = AglynTokens.Typography.caption.toTextStyle(fontFamily),
  labelMedium = AglynTokens.Typography.caption.toTextStyle(fontFamily),
  labelLarge = AglynTokens.Typography.button.toTextStyle(fontFamily),
  labelSmall = AglynTokens.Typography.overline.toTextStyle(fontFamily),
)

/** Material 3's shape steps from the console's radius: 1×, 2×, 3×, 4× and 7×. */
val AglynShapes = Shapes(
  extraSmall = RoundedCornerShape(4.dp),
  small = RoundedCornerShape(8.dp),
  medium = RoundedCornerShape(12.dp),
  large = RoundedCornerShape(16.dp),
  extraLarge = RoundedCornerShape(28.dp),
)
