/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// GENERATED FILE — do not edit. Regenerate with:
//   node tools/scripts/generate-docs-help.mjs
// Source of truth: apps/docs/docs frontmatter + headings (AGL-602).

import type { PluginDocsKey } from './docs-help.generated'

/**
 * The opening sentence under each heading a plugin card links — that card's
 * tooltip prose (AGL-3707).
 *
 * A module of its own because the plugin help subset is imported by every
 * plugin console up front, and four hundred sections of prose are ~30 KB
 * gzipped that no page needs until someone opens a tooltip.
 * `PluginDocsSectionExcerpt` fetches this module when one does.
 */
export const PLUGIN_DOCS_SECTION_EXCERPTS: {
  readonly [K in PluginDocsKey]?: { readonly [anchor: `#${string}`]: string }
} = {
  abuseReports: {
    '#abuse-queue-page': 'Staff → Abuse reports lists every report filed from the public form, newest first: triage each one by severity, act with Lockdown or Disabled files, then save its status with what you did.',
    '#counter-notice-steps': 'Each counter-notice is its own card in the queue: move it to the step that matches what happened, write what you did and why, and press Save step — each step changes what happens to the site.',
    '#counter-notices': 'A subscriber whose material we removed can answer with a counter-notice under §512(g).',
    '#reading-a-report': 'Each report is its own card: read the header and the reported address, decide which lever answers it, then set its status and write what you did before you press Save status.',
    '#reported-listings': 'Staff → Marketplace reports is the queue for reports users file against a marketplace listing or a review: read the reason each reporter gave, then move it to Reviewing, Actioned or Dismiss it, with a note saying…',
    '#statuses': 'Dismissed is not the same as unread. If you dismiss without a reason, the next person to receive a report about the same site has no idea whether we already considered it.',
    '#triage-by-severity': 'Every category carries a severity. It is not a mood — it says how fast a human has to look.',
  },
  actionsBuilder: {
    '#create-an-action': 'Open the actions builder from Automation → Actions. That\'s it — no multi-step logic to manage.',
  },
  aglynAssist: {
    '#what-it-can-do': 'Answer how-to questions about building sites, publishing, domains, commerce, bookings, workflows, datasets, team roles, and billing.',
  },
  aiAutomations: {
    '#change': 'Open a saved action and use the box under Explain it: Change with AI — describe the change: "also tag them newsletter, and wait a day before the email".',
    '#draft': 'Choose Create with AI beside Add action and Recipes on Automation → Actions, or at the top of Automation → Workflows (in its empty state while it has none).',
    '#explain': 'Open a saved action or workflow and choose Explain it at the top of the editor.',
    '#org-automations': 'An org automation is written once for your workspace and runs on the sites you choose.',
  },
  aiBusinessProfile: {
    '#what-aglyn-ai-learned': 'When you apply an Assist edit that shows a preference, such as asking for shorter copy, a friendlier tone, no emoji, or removing a testimonials section, Aglyn AI keeps that as a short preference for the site.',
  },
  aiCrm: {
    '#draft-an-email': 'In the email composer on a contact, a deal or a lead, describe what the email should say (for example, "follow up on the quote and offer a call next week") and press Draft the message.',
    '#match-columns': 'In a contacts, companies, deals or leads import, choose your file, then press Match columns.',
    '#summarize-a-record': 'On a contact\'s, company\'s, deal\'s or lead\'s page, Summarize this contact (or company, deal or lead) writes at most two sentences from the record\'s timeline: when it was last in touch and how, and what is still open.',
  },
  aiExperiments: {
    '#the-verdict': 'This is the part worth understanding, because it is the opposite of how it looks.',
    '#write-variants': 'The card sits in the experiment editor, beneath the list of variants it writes for.',
  },
  aiLogic: {
    '#change': 'Open a saved function. The box at the top of its editor offers: Explain it — what the function works out from what it is given, operation by operation, and anything worth checking, such as a condition that can never…',
    '#function': 'Choose Create with AI at the top of the Functions card and describe what it should work out — "a shipping quote: free over our free-shipping amount, otherwise the flat rate plus 2 per kilo".',
    '#variable': 'Create with AI at the top of the Variables card writes one site variable — a name, a type and a value in that type\'s stored form, such as a dictionary of plan prices {"starter":19,"pro":49}.',
  },
  aiMarketing: {
    '#create-a-campaign': 'On Marketing → Campaigns, beside Create campaign and on the list while it is empty, Create with AI turns a brief into a campaign.',
  },
  aiMonitoring: {
    '#ai-conversations': 'Below the AI card, AI conversations shows what people in the organization typed to Aglyn AI and what it answered.',
    '#one-account': 'Staff → Users → an account carries a card named after the AI add-on with the account\'s credits in every workspace it belongs to, month by month — the same rollup the customer\'s Team and Usage pages read, kept…',
    '#the-ai-card': 'On Staff → Organizations → an organization, between Effective entitlements and Metered usage, the card named after the AI add-on carries everything about that organization\'s AI in one place.',
    '#the-spend-leaderboard': 'Staff → Assist signal opens with AI spend this month, by workspace: each organization\'s plan, whether the add-on is on, credits drawn, provider dollars and refusals for the current month, dearest first, above the…',
  },
  aiSeo: {
    '#fix-what-the-seo-check-finds': 'The SEO check on Setup → SEO lists what is wrong with each page; it is free and needs no AI.',
  },
  assistSignals: {
    '#docs-gaps': 'Cited pages ranked by thumbs-down first, then by how often a question landed there.',
    '#fleet': 'Totals across the scanned sample: messages, tokens, estimated cost, the thumbs tally, and how turns stopped.',
    '#questions-the-docs-could-not-answer': 'A turn with no cited docs paths is a question the corpus could not match at all, so the model answered ungrounded — from its own knowledge of the product, with nothing to link.',
    '#tokens-by-kind': 'What each kind of model request costs and weighs, one row per kind, dearest first: the console assistant (assist), the Besigner\'s copy modes (element, section, blog) and each generation job kind.',
    '#what-assist-costs-by-workspace': 'The same estimated cost as Where the money goes, per workspace, dearest first, with each workspace\'s thumbs-down count beside it.',
    '#what-people-actually-asked': 'The verbatim question behind each failing turn, with the answer it got.',
    '#where-the-money-goes': 'Costs on this board are our estimated provider cost at the serving model\'s list rates.',
  },
  billing: {
    '#ai-allotments': 'Beneath that table, AI allotments gives a team member, a site collaborator on one site, or a whole site a monthly share of the workspace\'s AI credits.',
    '#api-access': 'The customer REST API is a Business tier and above feature — mint scoped API keys and call the versioned /v1 endpoints from anywhere.',
    '#assist-overage': 'Paid plans include a monthly band of AI assist credits — the Aglyn Assist credits meter on the billing page shows how much of it this month\'s assistant use has drawn.',
    '#billing-address': 'The address Aglyn issues your invoices to, and the address sales tax on your Aglyn subscription is calculated from.',
    '#billing-address-on-profile': 'Settings → Profile shows your billing address read-only, beside the workspace\'s other details; change it on Billing → Settings.',
    '#billing-email': 'Invoices are sent to the billing email, along with receipts and — the one that matters most — the notices we send when a card fails and a subscription is about to lapse.',
    '#billing-history': 'The Billing history table on the Invoices tab lists every invoice Stripe has issued your workspace — its number, date, status and amount — with links to view it, download the PDF and open the receipt.',
    '#billing-link': 'A billing link in an email from Aglyn — a failed-payment notice, say — opens the Billing page of your workspace, asking you to sign in first if you need to.',
    '#billing-page': 'Organization → Billing is where your workspace\'s plan, usage, invoices and billing details live, in four tabs: Plan, Usage, Invoices and Settings.',
    '#campaign-sending-pace': 'Campaign emails (this hour, organization) shows how many campaign emails your workspace has sent this hour against the most it may send in an hour, so a very large send is spread out rather than refused.',
    '#crm-records': 'Your CRM — the contacts captured from forms, member sign-ups, buyers and bookings, and the companies and deals your team files beside them — is priced as one CRM records band, not a hard cap.',
    '#current-plan': 'The Current plan card at the top of the Plan tab names your plan, the state of its subscription and its price, with the plan\'s headline limits — sites, team seats and campaign emails a month — beside it.',
    '#if-you-would-rather-uploads-stopped': 'Set a monthly storage cap on the Storage cap card under Billing → Usage when you would rather new uploads stopped than pay for extra storage past a figure you choose.',
    '#made-with-badge': 'Published pages on the Free plan show a small Made with Aglyn badge; plans that include badge removal drop it automatically, with nothing to switch on.',
    '#metered-usage-estimate': 'The Metered usage estimate card prices this month\'s usage so far, using the same arithmetic as the invoice: only what goes past your plan\'s included amount is charged, at our cost plus 30% after card fees.',
    '#one-to-one-email': 'A one-to-one email is a message a teammate writes to one person from a CRM record — Send email on a contact\'s, a lead\'s or a deal\'s page, described under Activities & the timeline — as against a campaign, which is…',
    '#outstanding': 'If a payment fails, the invoice stays open and the Outstanding card — on both the Plan and Invoices tabs of the Billing page — shows it with a Pay now button.',
    '#payment-methods': 'The cards your subscription and any usage overage are charged to.',
    '#seats': 'Team seats (workspace-wide) and per-site collaborator seats are metered and enforced per tier — seats cover the people who build and manage your sites.',
    '#storage-overage': 'Your plan includes an amount of storage for each of its sites, and the workspace shares it as one allowance: every site\'s media library and the organization library draw on the same total.',
    '#tax-ids': 'A business tax ID — VAT, ABN, GST, EIN and the rest — printed on the invoices we issue you.',
    '#upgrade-proposal': 'When the Aglyn team proposes a plan for your workspace, the owner gets an email, and everyone who manages billing sees a card on the workspace\'s home and at the top of the Billing page: "*Workspace*\'s Aglyn team…',
    '#usage-budget': 'A usage budget is a monthly amount you choose, plus the percentages of it you want to hear about — the same shape as a Google Cloud billing budget.',
    '#usage-card': 'The Usage card on Billing → Usage shows every quota on your plan as a meter — sites, team seats, storage, bandwidth, CRM records, campaign emails and the rest — with what you have used against what the plan includes.',
    '#usage-history': 'The Usage history card charts the last twelve months of your workspace\'s usage, one bar per month, so you can tell whether this month is unusual.',
    '#usage-meters': 'The billing page shows meters for every quota — storage, bandwidth, datasets, seats, sends, CRM records (with the contacts, companies and deals beneath the total), one-to-one emails sent today, AI assist credits,…',
    '#what-you-will-pay': 'The What you will pay card appears on the Plan tab once you pick a plan to move to, and quotes that plan\'s total for the billing interval you chose, tax included, straight from Stripe.',
    '#who-is-generating-what': 'Beneath the meters on Billing → Usage, a table lists each member\'s AI credits for a month — their share of the workspace\'s spend, requests, and how often the assistant refused them — dearest first, with the kinds of…',
  },
  bindings: {
    '#functions-card': 'The Functions card on a site\'s Logic page lists every function the site has, each with its parameters and the value it returns — press Add function to build one, or Edit to change it.',
    '#insert-a-variable': 'You never have to hand-type token syntax. Every text-capable attribute field in the Besigner (Text, Link URL, Image URL, …) has a small {x} insert button at its end.',
    '#no-code-functions': 'Build functions in the in-editor function builder with a safe evaluator — no arbitrary code execution.',
    '#site-details': '{{host.*}} tokens name the site itself instead of hard-coding it, so copy stays right when the site is renamed, and a template installed on another site fills in that site\'s details.',
    '#typed-variables': 'Create typed site variables and reference them as {{name}} in any prop.',
    '#where-used--safety': 'Before you rename or delete a variable or function, run the where-used scan to see every page and prop that references it, so changes are safe.',
  },
  bookings: {
    '#manage': 'The Upcoming bookings card on the site\'s Bookings page lists every booking still to come, with the customer and the time each one holds.',
    '#reminders': 'Every confirmed booking gets one reminder email roughly a day before it starts.',
    '#set-up-bookings': 'The Services card on the site\'s Bookings page defines what visitors can book: each service\'s length, price and the weekly hours it is offered in.',
  },
  buildAWorkflow: {
    '#1-open-the-workflows-page': 'In the console, go to Automation → Workflows and choose New workflow.',
    '#4-save-and-test': 'Save the workflow. When the trigger fires, the workflow runs and each run counts once toward your tier\'s metered allowance — however many steps it has, and whatever they are.',
  },
  catalog: {
    '#categories-and-tags': 'The Categories & collections card, in the products hub\'s catalog, organizes your products into categories and collections that storefront pages and filters use.',
    '#product-reviews': 'The Review moderation card, in the products hub\'s Promotions section, holds the reviews shoppers leave on your products until you approve or reject them.',
  },
  commerce: {
    '#commerce-analytics': 'The Commerce analytics card, in the Analytics section of the products hub, shows the last 30 days of revenue, orders and average order value, a 14-day revenue trend and your top products.',
    '#commerce-glance': 'The Commerce card on your site\'s overview and Analytics pages shows the last 30 days of sales at a glance: revenue, orders, average order value, and how many products are low on stock.',
    '#coupons': 'The Coupons card makes simple percent-off codes buyers enter at checkout, with an optional limit on uses and an expiry date.',
    '#discounts': 'The Discounts card makes codes buyers type at checkout, or automatic promotions that apply on their own, for a percent off, an amount off or free shipping.',
    '#dropshipping': 'Assign a supplier to a product and paid orders route automatically — by email and/or HMAC-signed webhook — with a token link the supplier uses to post tracking back, which fulfills the order.',
    '#gift-cards': 'Gift cards lists every card your store has issued, what is left on each one, and what that adds up to.',
    '#inventory-locations': 'The Inventory locations card, in the store\'s settings, splits your stock across warehouses or storefronts: add a location for each place you keep stock, then set each variant\'s count per location.',
    '#orders-screen': 'Open your site\'s Products hub and choose the Orders tab. Before your first sale the tab is an invitation rather than a table: it explains where orders come from and offers Draft order, so you can invoice a customer…',
    '#payment-methods': 'The Payment methods card, in the store\'s settings, chooses what shoppers may pay with besides a card, once your Stripe account is connected on the Payments card.',
    '#pickup-and-local-delivery': 'Buyers can choose to pick up an order at one of your locations, or have your own driver deliver it, instead of shipping.',
    '#products-hub': 'The Products page is the catalog manager: Products with up to 3 options and 100 variants each — per-variant SKU, barcode, price, compare-at (sale badge), weight, and stock.',
    '#recovery-and-alerts': 'The Recovery & alerts card, in the Orders section of the products hub, shows the abandoned-checkout reminders and back-in-stock alerts Aglyn sends for you.',
    '#stock-movements': 'Inventory → Stock movements is the history behind every tracked count — the answer to "the shelf says four and the console says six, what happened?"',
    '#store-settings': 'The Store settings card, in the store\'s settings, sets the pages product and collection links open, the currency prices show in, guest checkout, your terms link and the receipt footer.',
    '#storefront-sales-tax': 'Analytics → Storefront sales tax shows what your storefront collected in a period.',
    '#tax-settings': 'The Taxes card, in the store\'s settings, decides how your store charges sales tax: rates you enter, Stripe Tax, or none at all.',
  },
  commerceEndToEnd: {
    '#1-connect-payments': 'The Payments card, in the store\'s settings, connects your own Stripe account so buyers pay you directly; checkout stays off until Stripe reports charges enabled.',
    '#member-updates': 'The Member updates card, in the products hub\'s catalog, posts updates only your subscribers can see, and can email each one to them.',
  },
  companies: {
    '#a-companys-page': 'The page names the company in the heading and the trail, and holds its properties, its contacts, its deals, its open tasks and the activity logged against it.',
    '#contacts-at-a-company': 'The Contacts card lists the people linked to this company a page at a time, most recently updated first, with the total counted by the database in its footer; each row opens the person\'s page.',
    '#create-a-company': 'Choose New company above the list. A company needs a name; everything else is optional: Domain — the bare hostname (acme.com).',
    '#the-companies-list': 'The list shows every company your site may see, most recently changed first, with its domain, how many contacts are linked to it, its owner, when it was last changed and its next activity — when the earliest open…',
  },
  connectQuickbooksOnline: {
    '#choose-your-books': 'When a connection links more than one set of books, the Accounting page asks which one this workspace posts to: pick it and select Use these books.',
  },
  connectXero: {
    '#choose-an-organization': 'When your Xero login reaches more than one organization, the Accounting page asks which one this workspace posts to: pick it and select Use this organization.',
  },
  consoleTour: {
    '#a-site-card': 'Each card on All Sites is one site: Visit opens the live site in a new tab, and Manage opens its dashboard in the console, where its pages, media, users and settings are.',
    '#a-sites-dashboard': 'Opening a site lands you on its dashboard.',
    '#alerts-on-this-device': 'At the foot of the Settings section, three switches control how a new notification reaches you in this browser: Unread count in tab title — badges the browser tab, e.g.',
    '#all-notifications': 'The All notifications card is your whole feed, newest first, across every workspace you belong to: Mark all read clears it, and Filters narrows it by type or status.',
    '#daily-digests': 'Daily CRM digest is on by default. Each morning it sends you one notification and one email listing your overdue and due-today tasks and the leads nobody has worked, across every workspace you belong to.',
    '#notification-settings': 'Everything about what reaches you lives on the second section, Settings.',
    '#organization-general': 'The General card renames the organization, changes its workspace URL and sets the time zone its sites inherit — "workspace" is the console\'s word for your organization\'s home.',
    '#organization-settings': 'Organization → Settings is where you run the workspace itself: its name and workspace URL under General, then — for owners and admins — Profile, Plugins, API keys, Branding, Single sign-on, Privacy, Holds & reviews…',
    '#the-app-bar': 'Site switcher (left) — jump between the sites you belong to, search them by name with Find site…, or create a new one.',
    '#the-sites-list': 'All Sites is the front door of a workspace: one card per site, for the workspace currently selected in the switcher, in name order.',
    '#workspace-and-site-overrides': 'One workspace or one site sets the same answers for a single workspace or a single site, rather than for your whole account.',
  },
  contactActivities: {
    '#four-kinds-of-history': 'A contact\'s timeline is one newest-first stream drawn from four sources, and every entry says which it is: A captured entry from this site carries a link to its record: Open submission lands on the Inbox with the…',
    '#logging-an-activity': 'Open the record — a contact\'s page under CRM › Contacts, a company\'s under Companies, a deal\'s under Deals, or a lead\'s under Leads — and choose Log activity in the header of the Timeline or Activity card.',
    '#the-recent-activity-feed': 'The Contacts section shows the newest activity logged across the CRM in a Recent activity card of its own under the contacts list — the calls, emails, meetings and notes anyone on the team filed against any record —…',
  },
  contactFields: {
    '#define-a-field': 'Open CRM → Fields, pick the tab for the record the field describes — Contacts, Companies, Deals or Leads — and choose New field.',
    '#save-a-form-field': 'On a form\'s own page (Forms → the form), Saves to contact fields lists every field the published design declares, with a choice beside each.',
  },
  contactRecord: {
    '#contact-properties': 'The Properties card is the person\'s editable profile: change any field, then Save in the card\'s header writes everything at once, and Discard changes beside it puts back what you had not saved.',
    '#likely-duplicates': 'The Likely duplicates card on the record page looks for other records with the same name and the same phone number, or the same name and the same company, among the contacts your site may see.',
    '#the-record-page': 'Clicking a row in the list opens the person\'s own page at …/crm/contacts/{id} — an address you can paste and that every other CRM record links to.',
    '#what-each-site-keeps-to-itself': 'A contact document is shared by every site in your workspace — one human who touched two of your sites is one row.',
  },
  contacts: {
    '#known-by': 'The Known by card, on a contact\'s page in the organization\'s CRM, lists every site that has captured the person, each with their marketing consent for that site and a link that opens the person in that site\'s hub.',
    '#the-contacts-page': 'The Contacts section is the list the rest of the CRM is built on.',
  },
  crmEmailTemplates: {
    '#managing-templates': 'CRM → Settings carries an Email templates card: every template and snippet you can use, with its kind and whether it is shared or personal.',
  },
  crmLeads: {
    '#a-leads-page': 'A lead\'s page is where you work one lead: set its status and owner, call or email the person, and Convert it once it is real.',
    '#captured-history': 'Captured history is read-only: when the person was first and last seen, how many times your site captured them, every source that did, and — under Where this lead came from — the campaign the capture is credited to,…',
    '#filter-the-leads': 'The table\'s own toolbar filters the list: Filters opens the filter panel, and Search finds a lead by a word of its name, its email address — and each part of the address, so the domain alone finds it — its company,…',
    '#lead-campaigns': 'Campaigns is your own filing of the lead under the site\'s campaigns: Filed under campaigns offers the site\'s campaigns by name, and Save filing in the card\'s header writes the pick.',
    '#lead-details': 'Details is the lead\'s profile, laid out as Salesforce lays out a lead: the salutation and the name\'s parts, then Lead information — company, job title, industry, rating, lead source, tags, employees and annual…',
  },
  crmReports: {
    '#activity-by-teammate': 'Who did what in the period, busiest first. Activities logged — every call, email, meeting, note and other activity logged in the period, counted on the server, with the change against the previous period.',
    '#contacts': 'New contacts in the period, with the change against the previous period.',
    '#conversion-by-source': 'Of the people each capture surface brought in during the period, how many are customers now.',
    '#crm-at-a-glance': 'The site dashboard carries a CRM at a glance card with five numbers: contacts, new contacts this week, the value of every open deal, tasks due today or overdue, and leads to work — the leads on this site that are…',
    '#forecast-by-close-month': 'Every open deal, laid out by the month it is expected to close — one row per month for the next six, starting with the current month — and one column per pipeline, with a column for all of them together when there is…',
    '#lead-funnel': 'Of the leads this site captured in the period, where each one stands now, and why the ones closed without converting were closed.',
    '#lead-sources': 'Of the leads first seen in the period, how many came from each lead source, and how many of each were qualified — converted to a contact.',
    '#pipeline': 'Open deals and their pipeline value — the face value of every open deal, counted on the server.',
    '#sources-and-lifecycle': 'By source — how many contacts came through each capture surface (forms, orders, bookings, members, and so on).',
    '#tasks': 'Open tasks, Overdue (due before today) and Due today. Today and overdue are decided on your calendar day, the same way the Tasks list decides them, so the two never disagree about the same task.',
    '#won-and-lost': 'Won in the period, with the value of what was won.',
    '#won-and-lost-by-owner': 'The same closed deals, grouped by the person who owned each one at the close — not by whoever created it, so a deal reassigned mid-cycle counts for whoever carried it over the line.',
  },
  crmSettings: {
    '#assignment-rules': 'An ordered list of rules tried, top to bottom, for every new contact captured on any site in the workspace.',
    '#default-owner': 'Who gets the contacts captured on this site when no assignment rule claims them.',
    '#email-capture': 'The Email capture card holds the workspace\'s one capture address, with Copy and Rotate address.',
    '#recipes': 'At the organization level only — …/{organization}/crm/settings — the Settings section ends with a Recipes card: the four automation recipes, each with the sites that already carry it and an Install button.',
    '#round-robin': 'The members handed contacts in turn by a round-robin rule, or by an automation set to round robin.',
    '#your-sending-addresses': 'Directly under Email capture, Your sending addresses lists the addresses you send from besides the one you sign in with, such as a Gmail Send mail as alias on an outbound domain.',
  },
  crmSharing: {
    '#access-read-only-or-read-and-edit': 'Read-only is the default. A site with read-only access can see the record, open its page, and add its own tasks, notes and activity to it.',
    '#sharing-card': 'The Sharing card on a lead\'s, contact\'s, company\'s or deal\'s page lists every site that can see the record and why; an owner or admin shares it with more sites from Share with sites… in the card\'s header.',
    '#sharing-rules': 'CRM → Settings → Sharing rules, at the organization level, lists your rules.',
  },
  crmTasks: {
    '#tasks-on-a-contact-company-or-deal': 'Each record\'s page has a Tasks card listing that record\'s open tasks, soonest due first, with the same checkbox to complete one inline; the card\'s heading counts how many are open and how many are done.',
    '#the-dashboard-card': 'The site dashboard shows a Tasks due card: how many of your tasks are overdue, how many are due today, and the next five assigned to you, each with its due date.',
    '#the-tasks-page': 'The Tasks section is one list with six views, chosen under Show in the table\'s Filters panel — My tasks unless you choose another.',
  },
  crmViews: {
    '#the-views-control': 'Above each list, a button names the view the list is showing — All contacts when none is — and opens the views menu: My views are the ones you saved for yourself.',
  },
  datasets: {
    '#default-dataset-sharing': 'Default sharing for new datasets, at the top of the organization Data page, decides what a dataset created on a site\'s Data page starts shared with: All sites, or only that site.',
    '#filter-records': 'The records table filters through its own toolbar: Filters opens the filter panel, where each filterable field of the dataset\'s model is a column, and Search finds records by the words in their text.',
    '#organization-data-page': 'The organization Data page manages every dataset in the workspace in one place — create a dataset, edit its schema, add and import records — and sets where new datasets start shared.',
  },
  deals: {
    '#a-deals-page': 'A deal\'s page is where you work one deal: its stage, what it is worth, the people on it and what is owed on it, each on a card of its own.',
    '#contact-roles': 'A deal can name more than one person: Salesforce\'s Opportunity Contact Roles.',
    '#deal-properties': 'The Properties card lists what the deal is worth and where it stands; to change any of it, choose Edit in the page\'s header, which carries a control for each.',
    '#deals-on-a-record': 'The Deals card on a contact\'s or a company\'s page lists every deal that names that record, newest first, and New deal in its header starts one already linked to them.',
    '#line-items': 'A deal\'s amount can be a number you type, or the sum of the products behind it.',
    '#moving-winning-and-losing': 'Stage changes go through the server rather than being written directly, so that automations can hear them.',
    '#the-board-and-the-table': 'The section opens as a board of the chosen pipeline: one column per open stage, with Won and Lost folded away at the end until you expand them; a board wider than the window scrolls sideways.',
  },
  deliveryApps: {
    '#taking-orders': 'Delivery orders appear on the register, oldest first, and a short message announces each new one.',
  },
  designedEmails: {
    '#find-a-template': 'The templates table filters through its toolbar by Template, the name (it contains a word, it is, or it starts with), and Search matches the start of any word of a template\'s name, up to its first twelve characters.',
    '#template-page': 'Open a template from the list to see it on its own page: rename it under Name (the name the campaign composer\'s design picker shows), and open it in the besigner with Edit in besigner to change the design.',
    '#template-preview': 'The Preview card draws the template as an inbox receives it, with the same renderer the send uses; merge tokens are left standing, because a real send fills them from each recipient.',
    '#template-report': 'The Sent from this template card lists every email sent from the template and adds up what they did, each rate over the population it was measured against.',
  },
  emailCampaigns: {
    '#a-domain-we-set-up-is-a-request': 'This is the part worth reading before you plan around it. Nothing is provisioned automatically.',
    '#add-a-sender': 'Add sender on the Sending page, or a sender\'s row, opens a drawer with the three fields: the Mailbox before the @, the Sender name and the Reply address.',
    '#add-to-a-list': 'Type an address (or paste a whole column of them) and press Check.',
    '#campaign-page': 'Open a campaign from Marketing → Campaigns to see its dates, its lists and every email inside it, with their figures added up; Edit campaign and Delete campaign are in the card\'s menu (⋮).',
    '#campaigns-group-emails': 'A campaign is a container, not a single message. It carries a name, a start and end date, and the lists it is aimed at; the emails you send inside it are its contents, and the campaign\'s page adds their figures up.',
    '#consent-group-confirmation': 'Where your organization has declared several sites one sender — a consent group, named on every signup form — a confirmation belongs to the site whose form asked for it.',
    '#consent-group-join': 'Edit group, in a group\'s menu, opens the same dialog with its sites ticked.',
    '#consent-groups': 'Every site is its own sender until you say otherwise: someone who signs up on one site hears only from that site, and an unsubscribe applies to that site alone.',
    '#conversions': 'Marketing → Conversions lists what a site\'s campaigns caused, from the conversions\' end: form submissions, leads, contacts and bookings, one kind at a time.',
    '#domain-states': 'Add a domain and you are given the exact DNS records to publish — an authorization record, a signing key and a bounce-routing record.',
    '#email-lists': 'Lists are audiences shared across your organization\'s sites.',
    '#email-page': 'Open any email from Messages to see what it did on its own: where it went and its state, its delivery and engagement figures with every rate over the population it is measured against, the links followed, and who it…',
    '#email-preview': 'The Preview card at the foot of an email\'s page draws the email as an inbox receives it, with the same renderer the send uses; merge tokens are left standing, because a real send fills them from each recipient.',
    '#email-recipients': 'An email\'s Recipients table lists everyone it was sent to; to see only the people who opened it, or only those who clicked something, choose Engagement in the table\'s Filters panel.',
    '#experiments': 'Business plans can A/B test pages, sections, and emails from the Experiments card on the Marketing page: weighted variants, deterministic visitor assignment, a conversion goal, and per-variant exposure/conversion…',
    '#experiments-across-sites': 'Your organization\'s own Marketing → A/B testing lists every site\'s tests, grouped by site, with what each one tests, how many variants it has and its status.',
    '#last-campaign-card': 'The Last campaign card on a site\'s dashboard shows how many emails your most recent sent campaign sent, and how many opens and clicks it has had; Campaigns in its header opens the full history.',
    '#list-members': 'Press Members on any list row to open it. You get the membership a page at a time — address, name, when they joined, how they got there, and what their consent record says — plus the controls to change it.',
    '#lists-built-from-a-rule': 'A dynamic list holds everyone matching a rule, re-checked about every fifteen minutes.',
    '#manual-lists': 'A manual list holds the people you put in it. Grow it with the "Enroll in a list" automation step (e.g.',
    '#messages-list': 'Emails → Messages lists every email this site has sent, scheduled or is still writing, newest first, a page at a time, and each row opens that email\'s own page.',
    '#monthly-send-cap': 'From Pro up, a plan includes a number of campaign emails per calendar month.',
    '#org-sending-domain': 'Opened from your organization\'s Emails → Sending, a domain\'s page shows the same records to publish and the same Request records and Check DNS, and lists the sites sending as it, each with Stop sending as this domain.',
    '#org-suppressions': 'Your organization\'s Emails → Suppressions counts each site\'s list by reason, one row per site; open a site\'s row to see who is on its list, or to add or remove an address.',
    '#organization-emails-page': 'Your organization has its own Emails page beside CRM and Marketing, with the same seven sections a site\'s has, each answering for every site at once.',
    '#preference-page': 'The link at the bottom of every campaign opens a page where the recipient sees your topics, ticks the ones they want to keep, and saves.',
    '#send-a-campaign': 'Create a campaign on Marketing → Campaigns — a name, the dates it runs between, the lists it is aimed at, and the sites it runs on.',
    '#senders': 'Under the domain, the same page lists this site\'s senders: the addresses it may send as, each a mailbox on the site\'s sending domain with a display name and a reply address.',
    '#sending-domains': 'Emails → Sending is where you see what this site sends as, and where a workspace proves it owns a domain of its own.',
    '#suppressions': 'Emails ▸ Suppressions lists every address your campaigns skip, with the reason and the date: This is where the gap between a campaign\'s recipient count and what it actually sent comes from, and a rising Bounced count…',
    '#the-campaign-report': 'Report, beside any campaign that has been sent, opens the full picture for that one send.',
    '#topics': 'A topic is a stream of email somebody can leave on its own. Every campaign belongs to one, picked in the composer, and the link in that email offers to stop that stream rather than all of them.',
    '#two-ways-to-get-a-domain': 'A site\'s mail can leave from three places, and only the first is guaranteed.',
    '#what-belongs-to-a-campaign': 'A push is rarely only its mail. A campaign can also hold the landing pages, the forms those pages place, the contacts and leads you have filed under it, and the sequences a rep sends as part of it — so the campaign\'s…',
  },
  events: {
    '#manage-events': 'The console Events page lists your site\'s events, newest start first.',
  },
  forms: {
    '#every-sites-inbox-at-once': 'Your organization has an Inbox of its own, beside CRM and Marketing, for the people who span the whole organization — owners, admins, and members with access to every site.',
    '#field-types': 'Each Form Field has a type that controls what visitors see and what is submitted: Dropdown, radio, and checkbox fields take their choices from the field\'s Options setting — enter one choice per line (or separate them…',
    '#filter-the-inbox': 'Every Inbox table filters and searches through its toolbar, and every filter and the search reach everything the site holds, not only the page on screen: the table asks for the matches, newest first, and paging…',
    '#find-a-form': 'The Forms table filters through its toolbar by every column it shows: Display name, by the start of a word in it: contains "audit" finds "Multi-brand site audit".',
    '#form-collected': 'What this form has collected counts this form\'s views, submissions and leads, and the rates between them, so you can see how the form is doing.',
    '#form-crm-routing': 'CRM routing says what the CRM does with a submission. The switch — Also create a lead from the address someone gives this form — makes the form a lead surface: a submission files a lead in CRM → Leads for the sales…',
    '#form-details': 'Details holds the form\'s display name and the campaigns it belongs to; rename it or file it under a campaign, then Save.',
    '#form-submissions': 'Submissions to this form is the same table the Inbox shows, narrowed to this form; press Show submissions to load it.',
    '#form-versions': 'Versions lists the form\'s designs; Open one in the Besigner to edit it, and Publish it to update every page that places the form.',
    '#inbox-card': 'The Inbox card on a site\'s dashboard shows the three newest form submissions, with the same unread dot, sender and form name as the Inbox itself; Open inbox takes you to the full list.',
    '#one-forms-own-page': 'Each form has its own page: open it from the Forms list to rename it, route its submissions, publish a new version and see how it is doing.',
    '#replying-to-a-submission': 'Open a submission and, under the fields, there is a Reply composer.',
    '#the-inbox': 'The site\'s Inbox page collects everything visitors send, in three tabs — Submissions, Members & leads, and Campaigns.',
  },
  funnels: {
    '#create': 'Open your site\'s Analytics page and find Funnels.',
  },
  installYourFirstPlugin: {
    '#a-plugins-page': 'Open a plugin from the Plugins section to manage it for the workspace.',
    '#built-in-plugins': 'The Built in card lists the plugins that ship with Aglyn, each with its own switch.',
    '#find-plugins': 'Plugins is its own section in the organization navigation, next to Marketplace.',
    '#manage-plugins': 'Plugins, in the organization navigation, is where you switch plugins on and off for the whole workspace — the ones you installed from the Marketplace, listed first, and Aglyn\'s own built-in plugins below them.',
    '#permissions-and-data': 'The Permissions & data card shows what a marketplace plugin declared it can reach, so you can check it before you rely on it.',
    '#plugin-on-one-site': 'Open a plugin from Site Admin → Plugins to see whether it runs on this site, and why: the workspace switch, and this site\'s own choice.',
    '#site-plugins': 'A site can run fewer plugins than the workspace enables. Site Admin → Plugins lists the workspace-enabled plugins in two groups, Built in and Installed from the marketplace; turn a switch off and press Save site…',
    '#step-3-reviews': 'Ratings on a listing come only from people with a verified email whose organization actually installed it.',
    '#where-a-plugin-runs': 'The Where it runs card on a plugin\'s page answers which of your sites have it.',
  },
  inviteTeammates: {
    '#activity-log': 'The organization\'s Team page shows a Recent Activity log: what happened at organization level — renames, workspace URL changes, ownership transfers, members added/removed or re-roled, and invites sent, revoked, or…',
    '#ai-usage': 'Each member\'s page carries an AI usage card: their AI credits this month and last, their share of the workspace\'s pool, their requests, the kinds of request they mostly made, and the split by site.',
    '#help-a-teammate-who-is-locked-out': 'When a teammate cannot sign in, open them from the Team page and use the Password card to email them a reset link — or, when their account belongs to your organization alone, to set a password for them.',
    '#invite-someone': 'Open the organization\'s Team page and choose Add or invite.',
    '#member-access': 'The Member card sets this person\'s organization role and job title and, for an editor or viewer, which sites they can reach.',
    '#member-activity': 'Activity by this member lists everything this person has done in the organization — on its sites as well as at organization level — newest first.',
    '#member-page': 'Open anyone from the Team page to see their own page: their role and site access, a Password card for helping them back in, what has been changed about them, everything they have done in the organization, and their…',
    '#site-activity-log': 'A site\'s Admin → Activity lists every change made to that site in the console — who did what, and when, newest first — with each entry linking to the thing it changed.',
  },
  loyalty: {
    '#members-and-store-credit': 'The Rewards members card under Products → Promotions lists every member, newest first.',
    '#on-an-order': 'An order\'s dialog shows a Rewards section when rewards touched it: the points it earned and for whom, the rewards it spent, and anything a refund changed.',
    '#set-up-your-program': 'Go to Products → Promotions and find the Rewards card. The card also shows how many members you have, the points they hold and what those points are worth, and the store credit they hold.',
  },
  loyaltyConnectors: {
    '#connect-your-account': 'Open your store, go to Promotions, and find the Rewards account card.',
  },
  manifestAndEnvs: {
    '#listed-plugins': 'Listed plugins lists the plugin listings that are already installable, the step that makes a version reachable from Browse.',
    '#review-checklist': 'The Review checklist is what a reviewer works through for one version, and it is re-earned per version: a new release starts with none of it ticked.',
    '#review-overview': 'Overview shows the listing as a customer will see it — name, description, media and links, all supplied by the publisher — and flags what is missing, such as no license or no README.',
    '#review-queue': 'Awaiting review lists the plugin submissions waiting on a staff verdict; open one to read its listing, manifest and verifier findings, then act on it.',
    '#review-verdict': 'Review verdict moves a submission through the lifecycle: approve the version, or reject it with a reason the publisher is sent.',
    '#review-versions': 'Versions lists every version the publisher has submitted, because review lives on the version and each one is judged on its own.',
    '#submission-status': 'Status says where the version under review stands — submitted, listed, verified or rejected — and, when the listing was taken down or unpublished by its publisher, says so with the reason on file.',
    '#take-down': 'Take down, in the review page\'s danger zone, de-lists a plugin and writes the kill switch: every workspace that installed it stops loading it on the next render, and new installs are refused.',
    '#verification-requests': 'Verification requested lists publishers who asked to be verified — a claim about who they are, separate from reviewing any one version.',
  },
  marketingOverlays: {
    '#announcement-bar': 'A site-wide announcement bar shows a message across every page — ideal for sales, notices, or launches.',
    '#engagement-stats': 'Each overlay tracks its own lifetime views, clicks, and dismissals, shown in the Engagement column of the overlays table — so you can tell whether a bar earns its screen space.',
    '#frequency': 'In the popup editor, Frequency offers two mutually exclusive choices.',
    '#org-marketing-overview': 'The organization\'s Overview leads with the email figures for every site\'s sends, then lists your sites one per row with their overlay views and clicks and their running and decided A/B tests, totaled underneath.',
    '#org-overlays': 'The organization\'s Overlays section lists every site\'s bars and popups, grouped by site, and switches any of them on or off right from the list.',
    '#promotional-popups': 'Popups give you more control: Triggers — After a delay (a number of seconds), On scroll (a percentage of the page), or On exit intent.',
  },
  membersOnly: {
    '#manage-your-members': 'The site\'s Users page lists everyone who signed up on your published site — paged, newest first.',
  },
  orderNotifications: {
    '#customer-emails': 'A dropship supplier who posts tracking for their part of an order sends the customer the same Order shipped email.',
  },
  ordersAndReturns: {
    '#buyer-requests': 'A buyer asks for a return themselves, from either of two places: the Request a return link beside an order in their account on your store, when they are signed in;',
    '#order-webhooks': 'An order webhook posts each order event to an address you choose, as it happens: a warehouse system, an ERP, a spreadsheet script.',
    '#run-a-return': 'Open a return from the list, or from the Returns section of its order\'s dialog, where Start return opens one for the buyer.',
  },
  orgAutomations: {
    '#every-sites-own-automations': 'The organization hub\'s Workflows, Actions and Webhooks sections list every site\'s own workflows, actions and webhooks side by side, with the site each belongs to.',
    '#pause-it-on-one-site': 'Each site\'s Automation → Actions section shows Org automations on this site: the ones placed on it, whether each runs here, and Pause here / Resume here.',
    '#what-an-org-automation-is': 'An org automation has a trigger, optional conditions and an ordered list of steps, exactly like an action — and a placement: the sites it runs on.',
  },
  pickupAndDelivery: {
    '#set-up-local-delivery': 'The Local delivery card, in the store\'s settings, lets your own driver deliver orders: buyers enter their postal code at the cart, pay your fee and book a delivery time.',
  },
  plugins: {
    '#a-dependency-that-is-off-for-one-site': 'A site can switch off a plugin that another plugin on that same site depends on — by disabling it directly, or simply by never opting in.',
    '#browse-card': 'Every card in Browse All carries the same four claims, so two listings side by side are comparable: A price chip, always.',
    '#configure': 'A plugin declares the settings it takes, and the console renders the form.',
    '#configure-site': 'A site that needs a different answer overrides that one field and keeps inheriting the rest — including later changes the workspace makes to the fields it did not override.',
    '#install--upgrade': 'Open Marketplace in the organization navigation and Browse the listings.',
    '#what-the-badges-on-a-listing-mean': 'Two badges can appear on a listing, and they say different things.',
    '#when-one-plugin-depends-on-another': 'Some plugins cannot run without another one. User Accounts is the case that exists today: its Members blocks and its membership/* API handlers ship inside the Commerce bundle, so User Accounts with Commerce switched…',
  },
  pos: {
    '#card-readers': 'A card reader takes card payments at the counter: the customer taps, inserts or swipes, and the reader can ask for a tip.',
    '#registers': 'Create your registers under Commerce → Settings → POS registers — one per till or device that takes in-person payments.',
    '#reservations': 'For stays (cabins, rooms, rentals): Add resources on the Products page — nightly rate, weekend multiplier, minimum nights, deposit percent, and free-cancellation window.',
  },
  posHardware: {
    '#receipt-printers': 'A cloud receipt printer collects its work from Aglyn over the internet, so a receipt prints from the register on any device, even one with no printer driver, and even when the printer is on a different network.',
  },
  posOperations: {
    '#shifts-and-the-cash-drawer': 'A shift is one stretch of trading on one register, counted against one cash drawer.',
    '#staff-pins': 'A shared tablet stays signed in; each person switches in with their own PIN instead of signing out.',
  },
  postPurchase: {
    '#connect-a-service': 'Open the store\'s settings and find the card for the service: AfterShip, Route or Narvar.',
    '#on-the-order': 'Open an order to see its Tracking and protection section: the protection status and what the buyer paid for it, each parcel a service is following, and when the order was last sent to Narvar.',
  },
  publishAPlugin: {
    '#listing-publisher-card': 'The Publisher card on every listing names who published it, with their logo, and links to their publisher page, so a buyer can see what else they ship.',
    '#paid-listings': 'You can list a plugin as paid: Payments run through Stripe Connect.',
    '#profile-card': 'The card at the top of a publisher\'s page shows their logo, display name, handle and bio — what a buyer reads before deciding to trust a listing.',
    '#your-publisher-profile': 'Your publisher profile is a storefront: its own page in the marketplace listing everything you\'ve published, reachable from the Publisher card on any of your listings and from the by @handle link on every browse card.',
  },
  publisherHandbook: {
    '#asking-to-be-verified': 'Verification used to be something only a reviewer could start, which meant there was no way to ask and no sign that asking was allowed.',
    '#authoring-your-listing': 'Your listing IS your storefront — it renders on the detail page every buyer sees.',
    '#before-you-publish': 'The last section of the page asks you to confirm a short checklist, in full view of the publish button, and publishing is blocked until you do.',
    '#bundle-and-manifest': 'The Bundle and manifest section of the publish page takes your built bundle and its manifest: choose the bundle file, then choose the manifest file or paste its JSON.',
    '#edit-listing': 'Select Edit listing on your own listing\'s detail page and the page becomes the editor for what buyers see: name, summary, rich-text body and media.',
    '#install-card': 'The Install card on a listing\'s detail page is where an install happens: choose where it lands — all sites, selected sites, or the whole organization for a plugin — then confirm.',
    '#installed-from-the-marketplace': 'Installed from the marketplace, on the workspace\'s Plugins page, lists every marketplace item this workspace has installed — org-wide, or the sites it is on — with the version it is pinned to and whether an update is…',
    '#licenses-you-bought': 'Bought by you lists your own purchases across every workspace you belong to, with the workspace each one licenses.',
    '#listing-changelog': 'The Changelog card on a listing shows what each approved version changed, newest first, in the words its publisher wrote when publishing it.',
    '#listing-links': 'The Links card on a listing shows the Homepage and Source repository its publisher gave, so a buyer can read the source before installing.',
    '#private-plugins': 'Choose Only this organization under Who can install this when you upload, and the listing becomes private: never browsable in the marketplace by anyone, and installable only by your own organization\'s sites.',
    '#public-profile': 'The Public profile card on Marketplace → Profile is your publisher identity: set a handle, display name, bio and logo, then Save profile before you publish.',
    '#publishing-a-version': 'Run the local verifier first — the publish API enforces the same checks and rejects with the exact problem list: The verifier parses your bundle rather than reading it as text, so it sees what a source scan could…',
    '#purchases-and-fees': 'Every paid purchase records what the buyer paid and the platform fee taken from it, and Aglyn staff see recent purchases on their marketplace overview with the fee from each sale.',
    '#refund-reversals': 'When a sale is refunded, your share is pulled back from your Connect account; if Stripe refuses that reversal, you keep the share and the platform absorbs the refund until it is recovered.',
    '#review-what-happens-after-you-publish': 'New plugin listings enter the queue as submitted and don\'t appear in public browse until staff list them.',
    '#set-up-payouts': 'The Payouts card on Marketplace → Payouts connects your organization\'s Stripe account so paid listings can pay you: select Set up payouts and finish Stripe\'s onboarding.',
    '#the-publisher-agreement': 'Your organization — not you personally — is the publishing party, so the organization accepts the Marketplace Publisher Agreement once.',
    '#the-two-badges-and-what-each-one-promises': 'The marketplace shows two separate claims, because they answer different questions and conflating them would let one vouch for the other.',
    '#version-history': 'Version history on a listing\'s detail page lists every published version with its changelog, a Latest marker on the newest, and a Realm-trusted chip on versions that carry it.',
    '#watching-your-own-submission': 'Open your own listing and the Review status card — visible only to you — answers what an email cannot: Which version installs today, from the newest approved version rather than the newest one you published.',
    '#where-to-publish-from': 'Publishing lives at the organization level — Marketplace → Publish.',
    '#workspace-licenses': 'This workspace lists the marketplace licenses this workspace owns — installable by any member with install permission, whoever on the team paid for it.',
    '#your-listings': 'Marketplace → Listings lists everything your organization has published, with its preview image; a row\'s menu is where you Publish new version…, Edit listing, or switch a plugin between private and public.',
  },
  redirects: {
    '#manage-redirects': 'Create, edit, and delete redirect rules from the redirect manager page.',
  },
  salesChannels: {
    '#brand-barcode-and-category': 'Channels match your listings to products they know by brand, barcode and category: set them for each product in the product editor, and store-wide on Defaults for every feed.',
    '#how-fresh-the-feed-is': 'A product you edit and save reaches the next fetch at once. Stock that a sale takes reaches it within 30 minutes.',
    '#set-up-sales-channels': 'The Sales channels card, in the store\'s settings, lists your products on shopping channels: set the feed defaults, check your products, then turn on each channel and paste its feed address there.',
    '#turn-on-a-channel': 'Each channel has its own card: switch its feed on, copy the feed\'s address and paste it into the channel\'s own setup, which then fetches your products on a schedule.',
  },
  sandboxSecurity: {
    '#what-a-reviewer-checks': 'A reviewer\'s Security panel sets what a bundle asked for — its declared network origins and capabilities — against what the sandbox enforces regardless of what it asked for, beside the static verifier\'s findings for…',
  },
  sequences: {
    '#allowed-countries': 'The countries a sequence may send to at all, United States by default.',
    '#build-a-sequence': 'Select New sequence, name it, and choose the site whose CRM the people you enroll are contacts of and the mailbox it sends from.',
    '#compliance-settings': 'Every email a sequence sends ends with a footer saying who sent it, where they can be reached by post, that the email is a sales email, and how to stop more of them.',
    '#connect-a-mailbox': 'Each rep connects their own Google or Microsoft 365 mailbox in Sequences → Mailboxes: Select Connect with Google or Connect with Microsoft and choose your account.',
    '#do-not-contact-domains': 'The domains no sequence emails anyone at, whoever enrolls them.',
    '#enroll': 'Select Enroll people on an active sequence, and choose them from a saved Contacts or Leads view, by searching your contacts at the sequence\'s site, or from the Leads tab — the site\'s open leads — up to 50 at a time.',
    '#link-domains': 'With Count link clicks on, every link in a sequence email is a short link that counts the click and then takes the reader where you meant.',
    '#mailbox-actions': 'Send a test to myself sends a short plain-text message from the mailbox to its own address, so you can check it arrives.',
    '#person-activity': 'The Activity card lists everything the sequence did to one person, newest first, and Open thread in Gmail opens the conversation in the sending mailbox.',
    '#person-details': 'The Details card is closed until you open it, and holds what the enrollment was made with: the personal line, the attestations, the mailbox, the campaigns, what your mail has met at their domain, each curated email…',
    '#person-history': 'Select a person\'s row on a sequence\'s Enrollments tab — or focus it and press Enter — to open their page, which shows where they are in the sequence and everything it has done to them.',
    '#send-a-test': 'Send a test on any email step of a saved sequence sends that step to your own inbox through the sequence\'s mailbox, so you read it as a recipient would — the merge fields filled, the footer on, the links as they will…',
    '#sequence-sending-settings': 'The editor\'s Who it sends to, and when card sets the countries a sequence may reach, whether customers are included, and its own sending hours when its mailbox\'s should not apply.',
    '#sequences': 'A sequence is the emails, and the tasks between them, one person gets from one rep.',
  },
  shipping: {
    '#carrier-accounts': 'The Carrier accounts card lists the carriers your labels and checkout rates come from, for every site in the workspace.',
    '#shipping-labels': 'A label bought on Aglyn\'s carrier accounts is charged to the workspace at the carrier\'s price, with nothing added.',
    '#where-parcels-ship-from': 'Each inventory location (the Inventory locations card in the store\'s settings) can carry a postal address: choose Add address on its row, or Edit address once it has one.',
    '#zones-and-rates': 'The Shipping card, in the store\'s settings, prices every parcel: group the countries you ship to into zones, then give each zone one or more rates.',
  },
  shippingEasy: {
    '#connect': 'The ShippingEasy card, in the store\'s settings, sends each paid order to your ShippingEasy account and takes each label back, using the API keys from Before you start.',
  },
  shipStation: {
    '#connect': 'The ShipStation card, in the store\'s settings, connects your store to ShipStation as a Custom Store, so ShipStation imports your paid orders and sends each shipment back.',
  },
  staffConsole: {
    '#access': 'Access is gated on a staff claim, enforced per handler and by scoped Firestore rules.',
    '#acquisition': 'An Acquisition card on the detail page — and on each organization\'s page, for the account that created it — says where the account came from in one line ("Referral from g2.com → /pricing → signed up with password"):…',
    '#audit-admin-actions': 'The Admin actions table lists every staff change, newest first: filter or search it to find an entry, click the entry to read its reason, note and before/after, and use Export CSV to keep what the filters match.',
    '#audit-archival': 'Audit entries older than 90 days move nightly into a compliance trail in Storage and are kept a further 365 days: on the Audit log\'s Archive card, pick the month an entry was written to read it back.',
    '#audit-log': 'A record of staff actions, newest first. Click an entry to read its reason, note and before/after below the list.',
    '#billing-insight': 'Every organization\'s Stripe invoice history and default payment method (with delinquency state) render on its detail page.',
    '#broadcast-announcements': 'Push a product announcement or maintenance notice as an in-app notification to every organization\'s owner/admins (optionally one plan tier), respecting each recipient\'s mute preferences; audited.',
    '#contact-suppressions': 'The platform do-not-contact list for phone numbers — calls and texts.',
    '#coupons': 'Discount codes for Aglyn\'s own subscriptions. They live in Stripe — the console creates them there and reads them back, so a coupon made in the Stripe Dashboard shows up here and vice versa.',
    '#create-a-coupon': 'Make a discount code for Aglyn\'s own subscriptions here: give it a name, a type and a duration, read the cost warnings the form shows, then create it.',
    '#discount-floors': 'A coupon applied from an organization\'s page is judged on that organization: its plan, its entitlement overrides, the sites and seats it bought, the price it actually pays and its billing interval, on the charges the…',
    '#edit-a-system-email': 'The System emails card lists every email Aglyn sends, each marked Using default or Customized: press Design (or Edit) to replace a row\'s built-in copy with a template from the besigner, Send test to see it in an…',
    '#email-delivery': 'An Email delivery card on the same detail page answers "they say they never got it." It lists every message we sent the account\'s addresses, newest first, a page at a time: the subject, which of our senders produced…',
    '#emails-sent': 'Emails sent — on a site\'s staff page, and on an organization\'s for all of its sites — lists every email the site sent, newest first: the recipient, the subject and the sender tag (a campaign, a form notification,…',
    '#enterprise-custom-billing': 'Provision a negotiated price for an organization: enter the Custom price per month, how it is Billed, the Base plan it rides on, and whether to Invoice now (net-30, no card) or Send a Checkout link, then provision it.',
    '#existing-coupons': 'Existing coupons lists Stripe coupons with their promotion codes, redemption count, and a valid or expired state, a page at a time.',
    '#filter-the-directory': 'The grid\'s toolbar filters and searches the whole directory, not the page on screen.',
    '#filter-the-site-list': 'The grid\'s toolbar filters and searches every site, not the page on screen.',
    '#first-party-hosts': 'The hosts the platform serves itself, on Staff → Platform settings.',
    '#free-workspace-limit': 'How many free workspaces one account may hold, on a card at the top of the organizations page.',
    '#import-delivery-history': 'On Staff → System emails there is an Import delivery history card.',
    '#legal-acceptances': 'A Legal acceptances card on the same page answers the two questions a terms dispute asks: which version of the Terms and Privacy Policy this person accepted and when, and whether the 30-day arbitration opt-out window…',
    '#margin-by-organization': 'One row per organization scanned, thinnest margin first; select a row to open that organization\'s staff page.',
    '#margin-fleet-margin': 'The median margin of the organizations scanned, how many are under the margin floor and how many are underwater (below zero), and total cost against net revenue, with the AI add-on\'s share of that revenue.',
    '#margin-fleet-utilization': 'The median and spread of each included band across the organizations scanned, each measured against the band its own plan sells.',
    '#margin-scan': 'Press Scan organizations to read the figures: nothing is read until you do, because each organization costs four Firestore reads.',
    '#margin-utilization': 'Staff → Margin measures how much of its plan\'s included bands each organization uses and what margin the plan leaves after infrastructure cost: press Scan organizations, then read the fleet figures and the table,…',
    '#org-edit': 'Correct the organization\'s Name, logos, Contact email, Phone and Website for the customer, then Save organization; the change is written to the organization\'s activity log.',
    '#org-effective-entitlements': 'Every limit as it resolves for this organization — Effective beside its Plan default and how much is Used — with an override chip where staff changed it and the AI add-on marked where it adds to a band.',
    '#org-members': 'The organization\'s roster: each member\'s role, all sites for a member who can reach every site, and staff · no seat for a staff member, who takes none of the organization\'s seats.',
    '#org-metered-usage': 'The organization\'s monthly usage rollups — page views, storage, form submissions and their cost — with the change from the month before.',
    '#org-recent-admin-actions': 'The staff audit entries that reference this organization, from the latest 200 in the log: each shows the action, who did it, when, and the reason they gave.',
    '#org-sites': 'Every site the organization owns, each with the same row menu as the Sites list: open a site for its staff page, visit it live, or open its preview.',
    '#org-staff-actions': 'The Staff actions card holds the audited controls for the whole organization: Override its plan and limits, Suspend it, flag it for GDPR Erasure, or Pause AI.',
    '#organization-detail': 'An organization\'s staff page lists its Sites with the same row menu as the Sites list — visit the live site, open its preview, open the site\'s page — and, below the cards, Emails sent across its sites, then the Email…',
    '#organization-page-cards': 'What each card on an organization\'s staff page is for, top to bottom.',
    '#organizations-admin': 'Audited plan and entitlement overrides, suspension, and GDPR-erasure flags, per organization.',
    '#password-help': 'On that detail page, a Password card can email the account a reset link, or set its password directly for an account that cannot receive mail.',
    '#platform-send-rate': 'At the top of the same page. Everything Aglyn sends leaves on one Resend key and the provider\'s rate limit is per account, so a throttle lands on every customer\'s password resets at the same time whatever domain each…',
    '#platform-settings': 'Staff → Platform settings holds the settings that describe the platform rather than one organization, each changed without a deploy and audited with the reason you give.',
    '#platform-suppressions': 'Also on the System emails page: every address that bounced permanently or reported spam on any send from any site.',
    '#plugin-reviews': 'The marketplace review queue, plus a Listed plugins — realm trust table for granting or revoking realm trust per version.',
    '#record-a-dnc-request': 'Record a request is for an opt-out that arrived outside the product — by email to the privacy address, or spoken on a call.',
    '#sign-one-device-out': 'A Sign-in history card on the same detail page lists every device that has signed in to the account — browser and system, location, IP, first and last seen — and can end the sessions on one of them.',
    '#site-content': 'The Content card lists what the site is built from, one tab per kind: Pages, Email designs, Layouts, Components, Templates and Forms.',
    '#site-detail': 'A site\'s staff page opens from its row in Sites, or from the Sites card on its organization\'s page.',
    '#site-ownership': 'A site belongs to an organization, and the organization has one owner.',
    '#site-settings-snapshot': 'A read-only look at the site\'s settings that support questions turn on: its Locales, its Google Analytics measurement id, whether it is password protected, and which pages are its store\'s product and collection…',
    '#site-usage': 'Live counts for this site — published pages, all pages, the organization\'s media files, site members and storage in MB — the figures its organization\'s plan limits are measured against.',
    '#sites-admin': 'Sites lists every site on the platform, across every organization, read server-side with the Admin SDK so it shows sites you are not a member of.',
    '#staff-automations': 'The Automations card — on a site\'s page, and Organization automations on an organization\'s — comes from the Automation plugin.',
    '#staff-notes': 'Free-text support/billing context on each organization\'s detail page, visible to staff only (never in tenant-readable data) and audited.',
    '#staff-org-automations': 'The Organization automations card on an organization\'s staff page lists that organization\'s automations, whether each is on, and on how many of its sites each is paused.',
    '#staff-org-email': 'The Email campaigns card, from the Marketing plugin, has two tabs, each paged in id order: Sends — every campaign send: its subject and site, status (and held for review when the outbound screen stopped it), how many…',
    '#staff-overview': 'Platform metrics, the newest organizations, purchases, and per-org usage; plus search.',
    '#staff-overview-newest-orgs': 'The most recently created organizations, newest first, each with its plan and the day it was created.',
    '#staff-overview-organizations': 'The total number of organizations on the platform — one per customer workspace, whatever its plan.',
    '#staff-overview-signups': 'How many organizations were created in the last 30 days. It counts workspaces, not people: one account that opens two workspaces counts twice.',
    '#staff-overview-sites': 'Every site across every organization, published and draft alike.',
    '#staff-overview-users': 'The total number of user accounts across every sign-in pool — the same directory the Users page lists, one per person.',
    '#success-manager': 'Name the success manager an organization is promised: enter their Name and Email and Save.',
    '#suppressed-numbers': 'Suppressed numbers lists every record, most recently changed first, a page at a time, and its heading counts every number currently suppressed across the whole list, not only the page on screen.',
    '#system-emails': 'The mail Aglyn itself sends: organization invites, the monthly usage summary, the email copy of console notifications, staff alerts, workspace notices, the CRM digest and task reminders, the weekly insights digest,…',
    '#user-activity': 'The console actions this account took itself, across every organization and site, newest first — as distinct from the staff actions taken on it.',
    '#user-audit-trail': 'On the detail page, Recent audit trail (what was done by or to the account) and Data access by staff (who only looked at its data) each page through the account\'s whole audit trail, newest first.',
    '#user-data-access': 'Data access by staff lists each time a staff member opened this account\'s private data without changing it — reading a sent email, for one.',
    '#user-detail': 'An account\'s staff page shows its identity, staff role, organizations and audit trail, with the support tools beside them: password help, sign-in history and email delivery.',
    '#user-identity': 'The Identity card shows whether the account is Active or Disabled, its staff role, its sign-in providers, when it was created and last signed in, and its phone number with any do-not-contact record against it.',
    '#user-organizations': 'Every organization this account belongs to, each with its type, the account\'s role in it, and the sites it can reach — All sites, or each site with its own role.',
    '#users-accounts': 'The Accounts list holds every account in every sign-in pool: type a whole email to look one up, or filter the directory, then View an account for its detail page.',
    '#users-admin': 'Staff-claim management and disabling users, with gated listing; a whole email address typed in the search box looks the account up directly.',
  },
  taxServices: {
    '#connect': 'Open the store\'s settings and find the Tax service card. Only an admin of the site can connect, test or disconnect a service and change its address.',
    '#how-sales-are-taxed': 'A product you marked tax-exempt is sent as non-taxable and charged no tax.',
  },
  webhooks: {
    '#outbound-webhooks': 'Send an HTTP request to a URL you control when a site event fires — for example, post to a Slack endpoint or your own API when a form is submitted or a new booking comes in.',
  },
  zapier: {
    '#see-and-disconnect-your-zaps': 'The Zapier card on a site\'s setup page lists every Zap that takes the site\'s records: what it takes, the API key it connected with, and when it was last sent something.',
  },
}
