/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// GENERATED FILE — do not edit. Regenerate with:
//   node tools/scripts/generate-docs-help.mjs
// Source of truth: apps/docs/docs frontmatter + headings (AGL-602).

import type { PluginDocsKey } from './docs-help.generated'

/**
 * The opening sentence under each heading a plugin card links — that card's
 * tooltip prose (AGL-3707).
 *
 * A module of its own because the plugin help subset is imported by every
 * plugin console up front, and four hundred sections of prose are ~30 KB
 * gzipped that no page needs until someone opens a tooltip.
 * `PluginDocsSectionExcerpt` fetches this module when one does.
 */
export const PLUGIN_DOCS_SECTION_EXCERPTS: {
  readonly [K in PluginDocsKey]?: { readonly [anchor: `#${string}`]: string }
} = {
  abuseReports: {
    '#abuse-queue-page': 'Aim. The abuseReports collection is allow read: if isStaff() and allow write: if false — every write comes from the Admin SDK, so nothing you do in a Firestore console tab is a supported path.',
    '#counter-notice-steps': 'To fail quietly and nobody to remember. The queue shows the earliest and latest lawful instants either side of the date we picked, so you can see it sits inside the window rather than take our word.',
    '#counter-notices': 'Oth. And until the publication lands, still do not tell a reporter or a customer that we are operating inside the safe harbor: the registration is necessary and is not sufficient.',
    '#reading-a-report': 'And that block does not distinguish the phishing subdomain from the four hundred honest customer sites beside it.',
    '#reported-listings': 'Istings)). Early fraud warnings and disputes on marketplace sales count toward the seller fraud pattern under the publisher\'s workspace, never the buyer\'s.',
    '#statuses': 'Scope is the wrong scope. Whatever you pull, the lockdown and quarantine surfaces both read the state back after they write it and say NOT CONFIRMED when the re-read disagrees.',
    '#triage-by-severity': 'S own template on the System emails page (risk-… keys). Notices about a workspace\'s own customers\' payments wear the workspace\'s brand; everything the platform does wears the platform\'s.',
  },
  actionsBuilder: {
    '#create-an-action': 'Metered runs. You build both in the same place; steps that need a higher plan are labeled in the editor.',
  },
  aglynAssist: {
    '#what-it-can-do': 'E, connect a domain, set up shipping, invite a teammate — and it answers from this documentation, linking the exact docs section and the console page where you do it.',
  },
  aiAllotments: {
    '#a-members-allotment': 'E site. A collaborator who is the site\'s Admin can set the other collaborators\' allotments on that site.',
    '#a-sites-allotment': 'Er site for a site collaborator. It shows what they have drawn this month and whether the allotment is hard or soft.',
    '#allotments': 'Each month, so one client site, one contractor or one teammate cannot spend what everyone else was counting on.',
    '#choosing-a-model': 'Warns, and at a hard allotment it says who can raise it. The line updates from the answer to each request, so it never costs a request of its own; after a reload it shows where you stood at your last request.',
    '#usage-strip': 'Eryone on that site may draw together each month. Use it to keep one client site from spending what the others need: when a hard site allotment is used, AI stops on that site and keeps working on the rest.',
  },
  aiAssistBuilds: {
    '#the-plan-card': 'S. On the Free plan it holds 2 pages, and some parts, such as templates, campaigns, automations, products and edits to existing pages, need a paid plan.',
  },
  aiAutomations: {
    '#change': 'Tion, switched off. Choose the sites it runs on, check its steps, and save it with the editor\'s own Save — or close the editor, and nothing changes.',
    '#draft': 'At one does, and tell you why one of its runs failed. None of them runs an automation, switches one on, or changes one you have saved: what it drafts arrives as a new automation, switched off.',
    '#explain': 'Hen an expression is true — cannot be changed this way, so that nothing you did not ask to lose goes missing; edit it in the editor instead.',
    '#org-automations': 'N more than one of — is left as a placeholder for you to pick.',
  },
  aiBusinessProfile: {
    '#what-aglyn-ai-learned': 'Tered, and Aglyn AI writes around it, or leaves a bracketed placeholder such as [phone number] for you to fill, instead of making one up.',
  },
  aiComponent: {
    '#from-a-brief': '*Generate with AI permission. Free includes one reusable component per site, and Starter and above include as many as you need: on a site already holding the components its plan includes, the job says so before it…',
  },
  aiCreate: {
    '#without-the-add-on': 'Ds, an automation that is switched off. It uses your theme and reuses what the site already has, following the building rules, and reads your business profile.',
  },
  aiCredits: {
    '#before-a-job-starts': 'Photos.md) in an AI site | Nothing | A model you choose with the Model switch can cost more or less than Auto; the switch shows each model\'s cost.',
    '#past-the-band': 'N hour. See Paused, or out of credits.',
    '#see-your-credits': 'Re not given back when you cancel a job yourself (you pay for what ran until then), or when the AI declines what the brief asked for.',
  },
  aiCrm: {
    '#draft-an-email': 'New timeline entry, a new or finished task, or an edited note makes the next summary a new one.',
    '#match-columns': 'R. What you type into the request is kept with the AI request, as every AI request is, and members of your workspace can see it in the list of AI jobs, so describe the email rather than pasting private details into…',
    '#summarize-a-record': 'T, company, deal or lead, with a suggested next step.',
  },
  aiEmail: {
    '#where-to-start-it': 'Eaders to choose between. Ask for a campaign instead and it writes the same design plus the draft campaign that would send it.',
    '#write-the-brief': 'Er, the rest as alternatives. Change which one leads at any time, or write your own.',
  },
  aiExperiments: {
    '#the-verdict': 'Id not give it, and to write in that copy\'s own language.',
    '#write-variants': 'Leaves the test exactly as it was. Explain this result with AI has nothing to apply at all.',
  },
  aiForm: {
    '#describe-the-form': 'Ge. No page on your site places it, so nothing on the live site changes.',
  },
  aiImages: {
    '#credits': 'Google\'s image models, an invisible watermark. Google marks every picture its image models make with its SynthID watermark, so the picture can later be identified as generated.',
    '#declined-pictures': 'The people in a Lifestyle with people picture are asked for as made-up people, and a Cartoon or anime picture as original characters.',
    '#make-a-picture': 'On; where it is not, the menu lists the Vector kinds alone. Each picture is stored the way a file you upload is stored: in the open folder, counted toward your storage, served from the same addresses, and with alt…',
    '#shapes-and-how-many': 'Y a few seconds later, selected, so you can move, tag or open them at once.',
    '#who-can-use-it': 'R site, no file from your library, and no name, email address or account identifier.',
  },
  aiInsights: {
    '#asking-a-question': 'Ws is left out.',
  },
  aiJobs: {
    '#ai-jobs-in-assist': 'To build only the parts that failed; For a new site this is the Building your site page; see Start a new site with AI.',
  },
  aiLayout: {
    '#generate-a-layout-with-aglyn-ai': 'Copy until you assign it, so nothing on the live site changes.',
  },
  aiLogic: {
    '#change': 'Ariable} Create with AI at the top of the Variables card writes one site variable — a name, a type and a value in that type\'s stored form, such as a dictionary of plan prices {"starter":19,"pro":49}.',
    '#function': '. Nothing is saved for you. What Aglyn AI writes opens in the function or variable editor, unsaved, exactly as if you had typed it.',
    '#variable': 'Tten, saying why. Where your description needs a number your site does not hold, it becomes a parameter rather than a guess.',
  },
  aiMarketing: {
    '#create-a-campaign': 'N the editor. A fact the brief did not give — a discount, a date, a price — arrives in square brackets for you to fill rather than invented.',
  },
  aiMonitoring: {
    '#ai-conversations': 'Credits once. It does not touch the daily request or message caps, which reset at midnight UTC on their own, and it does not change what the month cost us: the margin and spend figures keep the real provider spend.',
    '#one-account': 'I add-on\'s share, and the fleet summary totals it. The add-on was already inside the net revenue figure — this names it, so the assist band\'s cost reads against what it brings in rather than as pure drag.',
    '#the-ai-card': 'Trun what a subscription brings in on its own. This page is where staff watch that happen — per organization, on the page they already open to look at an organization, and across the fleet on the boards that already…',
    '#the-spend-leaderboard': 'Answer to "is this one person driving the spend in three workspaces".',
  },
  aiPage: {
    '#describe-the-page': 'D forms your site already has. It arrives as an unpublished draft, and nothing on your live site changes until you publish it.',
  },
  aiProducts: {
    '#propose-a-first-catalog': 'Criptions, search listings and tags with AI as they land. Once the import has created your products, their copy is written as above and waits in the review table on the products page.',
    '#write-a-products-copy': 'Th AI Aglyn AI can write the copy for your products and help you set up a store.',
  },
  aiSeo: {
    '#fix-what-the-seo-check-finds': 'Sting section has the same Write with AI control. It proposes an SEO title and an SEO description from the product\'s name and description.',
    '#write-a-pages-listing': 'The editor or the form as unsaved changes, or in a new draft version, and your live site changes only when you save or publish.',
    '#write-a-products-listing': 'Picture. | The listing is written from the version you are looking at, in the language of its text.',
  },
  aiSite: {
    '#generate-for-several-sites-at-once': 'Builds.md#finding-your-ai-jobs). Every other planned job — a page, a form, a site generated for an existing site — still stops after its plan: it shows the plan with its estimate and Confirm plan, and builds nothing…',
  },
  aiSiteLooks: {
    '#choose-a-style': 'Onts, and the style of its buttons, cards and forms. The style you choose decides the family that look comes from.',
  },
  aiStart: {
    '#details': 'Nt, a blog and so on. One is picked for you from your first answer; choose another to change it.',
    '#how-do-you-want-to-start': 'Hrough each question and what happens after you choose Plan my site.',
    '#the-sites-search-listing': 'Se the site\'s search indexing setting. Until the site is built, its address shows a short coming soon page with the site\'s name, which search engines are asked not to index.',
    '#your-business': 'Ite does not ask again. If you have typed or picked something, the window first asks Leave without your answers?, because what you typed is not saved.',
  },
  aiTemplate: {
    '#generate-a-page-template-with-aglyn-ai': 'Ate is linked back to the template afterwards. Editing a page will never change the template, and updating a template will never change pages you already made.',
  },
  aiThemes: {
    '#describe-a-change': 'Olors, font, corner radius, spacing, navigation heights, dark scheme and component overrides you can set by hand.',
  },
  assistSignals: {
    '#docs-gaps': 'That left writes out would read it as healthy. A signal recorded before kinds were kept is read by its route: the Besigner modes name themselves, a generation job reads as job, and every other turn as assist.',
    '#fleet': 'Iting an existing page creates one.',
    '#questions-the-docs-could-not-answer': 'More people hit is the more expensive one to leave broken. Read a top row as: this page is being found, and it is not answering.',
    '#tokens-by-kind': 'Aper model on the common path fix this?" — where the entire point is that turns and dollars do not move together.',
    '#what-assist-costs-by-workspace': 'Leted, so an older failure shows its counts with the words gone.',
    '#what-people-actually-asked': 'Gs settings page" is a docs assignment. This is the sharper of the two gap signals.',
    '#where-the-money-goes': 'Nput tokens and cache reads cost far less, so a prefix that is written on every turn and read on none is the worst of the three outcomes — and it looks, from every other panel, exactly like normal traffic.',
  },
  billing: {
    '#api-access': 'Closes. Clearing datasets after a month has ended lowers the next invoice, not the one for the month that just finished.',
    '#billing-address': 'Hat you meant.',
    '#billing-address-on-profile': 'It affects your next invoice. Invoices already issued are never re-rated.',
    '#billing-email': 'Rst; Load older invoices reaches further back, and the filters above the table narrow what is shown.',
    '#billing-history': 'Manage billing you can enter a promotion code on the card and see it applied before you confirm.',
    '#billing-link': 'Current period renews or ends, and any add-ons you hold are listed at the bottom.',
    '#billing-page': ', Advanced, and Agency unlock progressively more, and Enterprise sits above them all.',
    '#campaign-sending-pace': 'D, because it is still accruing; the chart appears once there are two months to compare.',
    '#crm-records': 'E or joined it to help. See Aglyn staff on your team.',
    '#current-plan': 'E plan, add-ons, caps, cards, the billing address — needs Manage billing.',
    '#if-you-would-rather-uploads-stopped': 'Ou cross it, so the invoice is never the first you hear of it.',
    '#made-with-badge': 'A site already holds, so a site that moves to a smaller plan keeps everything it built.',
    '#metered-usage-estimate': 'Ast the included amount are billed rather than refused, as the sections below explain.',
    '#one-to-one-email': 'Settings → Privacy — see Privacy requests.',
    '#outstanding': 'H card saves on its own, so editing your address never touches your tax ID and vice versa.',
    '#payment-methods': 'Dress on the account that signed up. Once you are on a paid plan you can send them somewhere else.',
    '#seats': 'The amount clears the alert history for the month, so a budget you lower starts warning you against the new number straight away.',
    '#storage-overage': 'Ng; changing them requires Manage billing. See AI allotments, usage and model choice.',
    '#tax-ids': 'Rom the one shown, the card warns you, and saving the address again on the billing page brings the two back in step.',
    '#upgrade-proposal': 'Lan still goes through us, because there is no subscription to move down from.',
    '#usage-budget': 'Ps until next month or an upgrade. The same warning appears as a banner in the console, with a link to Billing → Usage.',
    '#usage-card': 'Ail your customers never receive.',
    '#usage-history': '. On a plan whose limits are included caps rather than meters, the card says there are no usage charges.',
    '#what-you-will-pay': 'Or expired code is refused immediately, with the reason — not at the moment you are charged.',
    '#who-is-generating-what': 'Reach. Transactional mail — receipts, invites, password resets — is never paced by it.',
  },
  bindings: {
    '#functions-card': 'N explain, change or fix it — each opens unsaved in the editor.',
    '#insert-a-variable': 'K. A published page resolves only the id form, so a name token that was never converted — because no variable had that name — shows exactly as typed.',
    '#no-code-functions': 'E.',
    '#site-details': 'Taset/webhook, and computed variables pick their workflow. Renaming an entity never breaks anything that references it — the display name is just a label.',
    '#typed-variables': 'The site you are editing, exactly as the published page does.',
    '#where-used--safety': 'Riable for every figure on the page, and a true/false for every row a filter can turn off.',
  },
  bookings: {
    '#manage': 'Ne whether service tax applies to you, at what rate, or where it should be paid.',
    '#reminders': 'Ents double-booking during checkout.',
    '#set-up-bookings': 'Y never touch Stripe. Connect your account from the Payments card on the Products hub; see Commerce.',
  },
  buildAWorkflow: {
    '#1-open-the-workflows-page': 'Re metered per tier. ::.',
    '#4-save-and-test': 'Ces](actions-builder.md#sequences) for the rest, including what a wait means for the emails sent after it.',
  },
  catalog: {
    '#categories-and-tags': 'Eir prices left empty, and proposed discounts are created switched off.',
    '#product-reviews': ', so that collection\'s grid is in price order — high to low if that is the sort chosen, low to high otherwise.',
  },
  commerce: {
    '#commerce-analytics': 'Hat was refunded, and leaves out test-mode orders. The card lists the five latest orders, and Open store takes you to the products hub.',
    '#commerce-glance': 'Row shows the code, the percent off, its uses and its expiry.',
    '#coupons': 'Many times it has been used; Edit changes it and Delete removes it.',
    '#discounts': 'Code, both in the Promotions section of the products hub. They are your codes for your buyers — not the coupons Aglyn applies to your own subscription.',
    '#dropshipping': 'Re, what is waiting to be collected and what is out for delivery, and the buyer is emailed at each step.',
    '#gift-cards': 'A count of zero moves the count by nothing, and both numbers are shown so the discrepancy is legible rather than silently rounded away.',
    '#inventory-locations': 'Location.',
    '#orders-screen': 'Build an order in the console and send the buyer a payment link (Shopify parity).',
    '#payment-methods': ':.',
    '#pickup-and-local-delivery': 'No rates on it refuses Europe even when a * zone exists. Cover a destination by pricing a rate on the zone that claims it.',
    '#products-hub': 'Up, while digital and service products carry 3% on Pro, 2% on Business, 1% on Scale and 0% from Advanced up.',
    '#recovery-and-alerts': 'Is left on it. The holder can no longer redeem it and the action cannot be undone, so you are asked to confirm the remaining amount first.',
    '#stock-movements': 'Ling past zero. Sales at the register are not affected — the till never refuses a sale, because the shelf in front of the cashier is the truth.',
    '#store-settings': 'From then on, each paid order for that product is sent to the supplier.',
    '#storefront-sales-tax': 'Stay at booking, on the deposit, or at check-out. If tax is due on more than the deposit, collect the difference the way you collect the rest of the balance.',
    '#tax-settings': 'Per-region rates (state beats country, VAT-style inclusive pricing supported) or Stripe Tax automatic calculation; products can be tax-exempt.',
  },
  commerceEndToEnd: {
    '#1-connect-payments': 'N availability Selling needs a paid plan (fees drop as you upgrade — see Billing & plans).',
    '#member-updates': 'Zen at what the first charge was. Stripe keeps its own copy of every invoice, reachable from the Billing Portal.',
  },
  companies: {
    '#a-companys-page': 'Ource | Your lead sources | Every organization has the standard values; you can rename, reorder, deactivate or set a default on them, and add your own.',
    '#contacts-at-a-company': 'Stom field](./custom-fields.md) defined on the Companies tab of the Fields section, and Edit carries a control for each, so a company\'s own properties are saved in the same form as its name and domain.',
    '#create-a-company': 'Ink, so a page of companies costs no lookup per row. A company linked before the count existed can read lower than its page shows; the company\'s own page counts live, and is the figure to trust when the two differ.',
    '#the-companies-list': 'The rest of the CRM. A company is a CRM record, counted with contacts and deals against your plan\'s records band — see CRM records.',
  },
  connectQuickbooksOnline: {
    '#choose-your-books': 'The connection. You come back to the Accounting page, which shows the company\'s name.',
  },
  connectXero: {
    '#choose-an-organization': 'Ign in and to allow access.',
  },
  consoleTour: {
    '#a-site-card': 'Doesn\'t store its plan, owner or template. See Filter and search a list.',
    '#a-sites-dashboard': 'It is a billing change — see Billing & plans.',
    '#alerts-on-this-device': 'D by clearing its Remind me field. See Reminders.',
    '#all-notifications': '-search). There is no search box, because a notification\'s words are not indexed.',
    '#daily-digests': 'Are about the platform, not about any one workspace, so there is nothing for a workspace answer to change.',
    '#notification-settings': 'Nder the table\'s Columns, Filters and Export controls](/img/getting-started/notifications-page.png)',
    '#organization-general': 'Ith the organization name and workspace URL](/img/getting-started/org-settings-page.png)',
    '#organization-settings': 'Nding and installing new ones, not for administering what you already run.',
    '#the-app-bar': 'Er — switch between the sites in your workspace.',
    '#the-sites-list': 'N you want to design it, open the Besigner.',
    '#workspace-and-site-overrides': 'Ins: a workspace or site answer overrides what you said about the kind of notification here.',
  },
  contactActivities: {
    '#four-kinds-of-history': 'E worth keeping. It is logged by hand, from the record it is about — or, for an email, written and sent from there — and it sits in one timeline beside everything the platform captured about that person on its own…',
    '#logging-an-activity': 'T recent open or click across all of these is the record\'s Last engaged stamp, which a re-engagement audience can be built from.',
    '#the-recent-activity-feed': 'The whole organization when the organization has chosen an org-wide default.',
  },
  contactFields: {
    '#define-a-field': 'O Plan availability Custom fields are part of the CRM, included from Starter.',
    '#save-a-form-field': 'Xports and the API carry the values under their keys. A value belongs to the site that recorded it.',
  },
  contactRecord: {
    '#contact-properties': 'Checkbox to complete it, and a New task shortcut — see Tasks & follow-ups.',
    '#likely-duplicates': 'Covers the whole workspace, because a contact is shared by every site that captured the person and the merge touches each site\'s records of them.',
    '#the-record-page': 'So. On a plan whose records band is a hard limit, a full band refuses the new record with the same wording the list shows.',
    '#what-each-site-keeps-to-itself': 'Re gone, and the request is complete. If the person asks what was removed, the workspace\'s audit trail records counts of what the sweep touched — never the address.',
  },
  contacts: {
    '#known-by': 'On. A collaborator added to particular sites is refused here, with a note pointing at the sites they hold, because this is the one surface that reads across every site; they open the CRM from a site they have access…',
    '#the-contacts-page': 'D\'s activity log is bounded at 5,000 logged activities per record — a call a day for fourteen years — after which the log dialog, the automation step and the API refuse another entry on that record with a message…',
  },
  couriers: {
    '#connect-doordash-drive': '*, at DoorDash\'s price for that delivery. Aglyn doesn\'t charge, collect or mark up the courier\'s fee.',
  },
  crmEmailTemplates: {
    '#managing-templates': 'A template {#saving} Write the email as you would send it, then Save as template… beneath the message asks for a name and whose it is.',
  },
  crmLeads: {
    '#a-leads-page': 'Verted lead\'s owner with it. Assigning an owner from the row menu or the lead\'s page changes the lead alone; the contact, when there is one, is assigned from its own record.',
    '#captured-history': 'Aign mails its lists — and it is the same picker the contact\'s Relationship card carries, so a lead and the contact it becomes are filed the same way.',
    '#filter-the-leads': 'D, and counts the Nurturing ones on a line of their own ("12 leads are in sequences or campaigns"), because email is already reaching them.',
    '#lead-campaigns': 'E Save in the card\'s header. Once the lead converts, the profile is read-only here, because the contact is the record then; the notes can still be written.',
    '#lead-details': 'Converts, Open contact, Open company and Open deal in place of Convert.',
  },
  crmReports: {
    '#activity-by-teammate': 'He card above them reports. This card reads the same 500 most recently closed of each outcome the Won and lost card does, and says so when the period held more.',
    '#contacts': 'Ast by close month and Tasks cards describe what is open now; "the pipeline over the last 30 days" would be a different question.',
    '#conversion-by-source': 'Ep. These two charts need a field off each contact, which the database cannot aggregate, so they are read from the newest 1,000 contacts your site can see.',
    '#crm-at-a-glance': 'Ile holds the rows grouped from that window rather than from every record.',
    '#forecast-by-close-month': 'Inst them. Painted as a warning above zero and a link to the deals list, where Next activity › is empty lists them.',
    '#lead-funnel': 'Earned; a long-standing customer who bought again this month is not evidence about this period\'s sources.',
    '#lead-sources': 'O the workspace, this card reports the site you are looking at; at the organization level it reads every site — at most 200 leads per site — and totals them, naming the per-site window when any site held more.',
    '#pipeline': 'They stand now: move a value to another group, or rename it, and the report follows on its next read.',
    '#sources-and-lifecycle': 'Total contacts visible to this site. A contact is "new" on the day it was first captured, not the day it was last edited.',
    '#tasks': 'D with, so a former member\'s work still reads under their name.',
    '#won-and-lost': 'W adding them up. A deal\'s category is its own, set by its stage when it last moved and changeable on the deal; a deal from before categories existed reads its stage\'s.',
    '#won-and-lost-by-owner': 'St Won in the period, with the value of what was won.',
  },
  crmSettings: {
    '#assignment-rules': ') with an owner column, or converted from a lead with an owner picked keeps the owner you chose.',
    '#companies': 'Saying why. Two cards are exceptions: the Email templates card, which every CRM editor may write to, because a template is working material, not policy; and Your sending addresses, which is each member\'s own list.',
    '#default-owner': 'Y somebody in the address book — is not linked again. A contact added by hand with a company picked, or imported with a company column, keeps the company you chose; the domain is not consulted.',
    '#email-capture': 'Late written under a site is that site\'s; one written from the organization\'s own CRM is the whole workspace\'s, and every site lists it.',
    '#recipes': 'Ses. Leaving the workspace, or erasing your account, removes your list.',
    '#round-robin': '-a-lead) without an owner picked, and only on a contact that has no owner yet.',
    '#your-sending-addresses': 'Le or a saved shortcut that carried the old address has to be updated.',
  },
  crmSharing: {
    '#access-read-only-or-read-and-edit': 'S saved. Switching a rule off keeps it and removes the visibility it granted.',
    '#sharing-card': 'Es sites you add to the workspace later.',
    '#sharing-rules': 'Says who shared it and with which sites, and the workspace activity log records it too.',
  },
  crmTasks: {
    '#tasks-on-a-contact-company-or-deal': 'With the organization — no site* — where a site\'s task names its site.',
    '#the-dashboard-card': 'Digest is on. (A reminder is the other way round: the category mute is its only switch, and stops its email too.) See Workspace settings & notifications.',
    '#the-tasks-page': 'Aming or deleting a suggestion changes no task\'s subject. Rename, reorder, deactivate, add or make a value the default on the Fields page; a new task starts on each list\'s default (Not Started, Normal, To-do).',
  },
  crmViews: {
    '#the-views-control': 'Lability Saved views are part of the CRM, included from Starter.',
  },
  datasets: {
    '#default-dataset-sharing': 'H the REST API — it starts on All sites too. Both act for the whole organization, not for one site.',
    '#filter-records': 'S Edit records in the typed document editor — each field renders the right input for its type, so data stays clean.',
    '#organization-data-page': 'Ans have no data store; higher tiers raise the dataset and record caps, and extra-dataset add-ons are available.',
  },
  deals: {
    '#a-deals-page': 'Ys contact now a customer. An automation on Deal won is for what happens next — the Follow up a won deal recipe books a check-in call and sets no stage, because the win already did.',
    '#contact-roles': 'Ated. When a lead is converted with a deal, the deal takes the lead\'s lead source, and the Type the convert dialog shows — the list\'s default until you pick another.',
    '#deal-properties': 'The line items behind the amount, with the door to add one from the catalog or by hand.',
    '#deals-on-a-record': 'He owner, links to the contact and the company, the campaign, the notes, and one row per custom field defined on the Deals tab of the Fields section.',
    '#line-items': 'Ort reads past: a contact is put on a deal from its page.',
    '#moving-winning-and-losing': 'Type again, starting from the last sum. A deal carries at most fifty lines, all in the deal\'s currency.',
    '#the-board-and-the-table': 'Exactly one Won and one Lost.',
  },
  deliveryApps: {
    '#taking-orders': 'E product\'s SKU here. An order item that matches no product still comes in, by name, with no stock taken, and it is listed under Items on the service\'s card.',
  },
  designedEmails: {
    '#find-a-template': 'Rice, and image fill in at send time (renames never break it).',
    '#template-page': 'A campaign picks it — so a copy is the safe way to try a variation without touching the design a campaign is already using.',
    '#template-preview': 'Se emails reached is the card under it — the same Recipients table an email\'s own page carries.',
    '#template-report': 'Sioned by whoever published it. Under it come what the emails sent from it did, who received them, and a preview.',
  },
  emailCampaigns: {
    '#a-domain-we-set-up-is-a-request': 'Registrar you do not have access to. Neither is issued automatically, and a site with neither keeps sending on the shared address in the meantime.',
    '#add-a-sender': 'One has taken over, because every site sends as something and picking the replacement for you would decide what your mail looks like from an ordering you never saw.',
    '#add-to-a-list': 'St from the same panel. The name is what the campaign composer\'s audience picker shows, so renaming it is safe at any time — the list, its members and any campaign already sent are untouched.',
    '#campaign-page': 'D. The toggle above the campaigns list switches it between Campaigns and Single sends (the emails filed under no campaign); both show in the same table, newest first, a page at a time.',
    '#campaigns-group-emails': 'E you have more sites than one page holds. The page is for members who can see the whole organization — somebody invited to one site keeps using that site\'s Emails page.',
    '#consent-group-confirmation': 'Ed from a topic is never sent a confirmation for it. A signup form must not become a way to email somebody who told you to stop by asking them again.',
    '#consent-group-join': 'Added together.',
    '#consent-groups': 'Roup, it shows what the person has left on any of its sites, and whatever they choose on it applies to every one of them: unsubscribing, leaving a topic, asking for less, and coming back.',
    '#conversions': 'Thing in the browser. Both are counted across every site the campaign is placed on, from the day counting started rather than the day the campaign did, and the page says from when.',
    '#domain-states': 'Main" ticked on the plan comparison, and that is on purpose: a tick in a checklist reads as an inclusion, and this is a request we answer rather than something your plan hands you.',
    '#email-lists': 'Ssage, sender and design, under the name you give it. Its audience and send time are cleared, so a copy can never mail the original\'s recipients by accident: you choose who receives it and when, as with any new email.',
    '#email-page': 'A time, and each row opens that email\'s own page. On your organization\'s Emails page it lists every site\'s, with a Site column, and writing a new one there first asks which site it is sent as.',
    '#email-preview': 'Y, Write this email while it is unsent, and Open template for a designed one — beside All messages.',
    '#email-recipients': 'Is not stored — it is rendered for each recipient at send time — so the preview draws the template as it is now, and says so when the email went out before the template was last edited.',
    '#experiments': 'S refused, telling you the number it found.',
    '#experiments-across-sites': 'Start checks every experiment on the site, not only the page on screen, and refuses a second test running on the same page: the page runner serves only the first.',
    '#last-campaign-card': 'Igured, campaign history shows opens and clicks per campaign, and clicks on A/B sends count as that variant\'s conversions — so the experiment results table fills in by itself.',
    '#list-members': 'St" automation step (e.g. on form completion), popup email capture, the Add to a list card in the Inbox, or by hand from the list itself.',
    '#lists-built-from-a-rule': 'Not record that they asked you to stop. If somebody has asked to stop hearing from you, suppress the address instead — that is the record that holds across every list and every campaign.',
    '#manual-lists': 'Arch both match words of the name, so only one of them applies at a time, and a note above the table says which was set aside.',
    '#messages-list': 'St campaign card on a site\'s dashboard shows how many emails your most recent sent campaign sent, and how many opens and clicks it has had; Campaigns in its header opens the full history.',
    '#monthly-send-cap': 'Anybody. Send test is the other half: it delivers one real message to an inbox you can open, which is the way to check how a mail client renders it.',
    '#org-sending-domain': 'Ddress, where campaigns are held to the tighter complaint and bounce limits.',
    '#org-suppressions': 'The link was in, so the campaign report can show an unsubscribe rate for that send.',
    '#organization-emails-page': 'Sent as that site; the organization\'s Emails page lists all of them.',
    '#preference-page': 'Ever changes what anyone chose: who left a topic stays with each site, and is never in a package.',
    '#send-a-campaign': 'Er refused by a campaign cap. See sending domains for why the two are treated differently.',
    '#senders': 'Ation owner or admin. Anyone else still sees the domain\'s state and the sites sending as it, and is told why the records are not shown.',
    '#sending-domains': 'Ply-To:` answer to it. An address invented for one campaign is an address nobody serves.',
    '#suppressions': 'Emoved from an audience, and no contact is deleted. A reminder or alert that was skipped is retried on the next sweep once the window rolls; a campaign is never refused by this limit, though it does count toward it.',
    '#the-campaign-report': 'D, it lists the newest first. The table has no search box, because the delivery log can only be narrowed by engagement.',
    '#topics': 'Ing? The 5,000 is a setting, EMAIL_LIST_UNSUBSCRIBE_BULK_THRESHOLD, and the header is two ordinary headers on the message, so it works with any sending provider.',
    '#two-ways-to-get-a-domain': 'Your audience. On a domain of this site\'s own the limits are the looser ones (0.30% and 10%), because there the only reputation being spent is yours.',
    '#what-belongs-to-a-campaign': ', and says so when there are more; a campaign\'s own page adds up 50 of its emails.',
  },
  events: {
    '#manage-events': 'Ce-and-billing/billing-and-plans/add-ons.md)). Until it\'s enabled the Events page explains the add-on, and the Event List element renders nothing on your site.',
  },
  forms: {
    '#every-sites-inbox-at-once': 'Still to be worked, a last line counts the open leads and links to the CRM\'s Leads list.',
    '#field-types': 'Lmost always means a bot found one of your forms. If it was real traffic, contact support and we will raise the ceiling for your site.',
    '#filter-the-inbox': 'Ked read; Mark unread puts it back.',
    '#find-a-form': 'Sions themselves. Submissions can\'t be imported. A submission is what a visitor sent through a published form, stamped with the time and the page it came from; a file can\'t have sent one.',
    '#form-collected': 'It is refused — with the reasons listed on the card — when the design does not meet what the form\'s settings require, such as the email and consent fields CRM routing needs.',
    '#form-crm-routing': 'Since the same signup form is often placed by more than one push.',
    '#form-details': 'Something in that card differs from what\'s saved, and saving one card never saves the other.',
    '#form-submissions': 'R.',
    '#form-versions': 'Scribe* or marketing consent — counts even before you pick it as the consent field.',
    '#inbox-card': 'Ad no email field cannot be replied to, and says so instead of offering a Send that would fail.',
    '#one-forms-own-page': 'Goes straight to that site\'s view, with no filter to set. Collaborators invited to particular sites don\'t see the organization\'s Inbox — they keep each site\'s own, which is unchanged.',
    '#replying-to-a-submission': 'Saved to Inbox on a form you bound to a dataset is the signal to go and check the dataset.',
    '#the-inbox': 'Leads — only when the form\'s CRM routing card has the lead switch on.',
  },
  funnels: {
    '#create': 'Ne. A visit is only tied to an address while the visitor\'s consent allows analytics, the address goes when the visit expires after 90 days, and erasing a person from your workspace deletes every visit tied to them.',
  },
  installYourFirstPlugin: {
    '#a-plugins-page': 'Ts own switch. Switching one off removes it from every site in the workspace — its navigation, the editor, published pages and the API — and switching it back on restores it.',
    '#built-in-plugins': 'Plugins, in the organization navigation, is where you switch plugins on and off for the whole workspace — the ones you installed from the Marketplace, listed first, and Aglyn\'s own built-in plugins below them.',
    '#find-plugins': 'A component or template you installed and then edited is now your copy.',
    '#manage-plugins': 'A plugin created. Reinstall it and it picks up where it left off.',
    '#permissions-and-data': 'E and followed by every site — its Dependencies, and, for a marketplace plugin, the version you are pinned to and what it is allowed to reach.',
    '#plugin-on-one-site': 'Cks every outbound request. Built-in plugins have no card, because they are not sandboxed.',
    '#site-plugins': 'Ed to](#step-4-targeting) — All sites, including ones you add later, or the sites you picked.',
    '#step-3-reviews': '/overview.md#what-the-badges-on-a-listing-mean).',
    '#where-a-plugin-runs': 'S them off for itself — see A plugin on one site.',
  },
  inviteTeammates: {
    '#activity-log': 'Ons are recorded in the organization\'s activity log, along with who performed them.',
    '#ai-usage': 'Size, never the brief you wrote or the copy the AI produced — that is your site\'s content and stays in the site.',
    '#help-a-teammate-who-is-locked-out': 'Oth need the Activity & audit log permission, the same as the organization\'s activity log.',
    '#invite-someone': 'Invite row, with the Email field, the Role picker and All sites, above the members roster](/img/teams-and-roles/org-team-page.png)',
    '#member-access': 'Been changed about them, everything they have done in the organization, and their AI usage and allotment.',
    '#member-activity': 'In role. The owner\'s role is not edited here — ownership moves under Settings → Transfer ownership.',
    '#member-page': 'E you will be relaying rather than reproducing. Someone invited to the whole organization keeps Support unchanged.',
    '#site-activity-log': 'First page. See Filter and search a list.',
  },
  liveChat: {
    '#set-up-live-chat': 'Ts, greetings and chatbots stay in your Tidio or LiveChat account; Aglyn only puts the chat on your pages.',
  },
  loyalty: {
    '#members-and-store-credit': 'Nd\'s first order only: it is refused for an email that has already ordered or already used a referral, and a member cannot use their own code.',
    '#on-an-order': 'The same for any email, and makes them a member if they are not one yet.',
    '#set-up-your-program': 'Ny customer store credit by hand, beside your gift cards. Rewards comes with every plan that includes selling, at no extra cost.',
  },
  loyaltyConnectors: {
    '#connect-your-account': 'Account too. A store runs one program at a time. While an account is connected, Aglyn\'s built-in points, welcome points and referral rewards are off, so nobody is rewarded twice.',
  },
  manifestAndEnvs: {
    '#listed-plugins': 'Ing/publisher-handbook.md#asking-to-be-verified) — a claim about who they are, separate from reviewing any one version.',
    '#review-checklist': 'Ew shows the listing as a customer will see it — name, description, media and links, all supplied by the publisher — and flags what is missing, such as no license or no README.',
    '#review-overview': 'Version under review stands — submitted, listed, verified or rejected — and, when the listing was taken down or unpublished by its publisher, says so with the reason on file.',
    '#review-queue': 'E rest of this section is the reviewer\'s side of that lifecycle — the staff review queue and a submission\'s review page — so a publisher can see what their submission is checked against.',
    '#review-verdict': 'N, and it is re-earned per version: a new release starts with none of it ticked.',
    '#review-versions': 'Approve the version, or reject it with a reason the publisher is sent.',
    '#submission-status': 'The plugin listings that are already installable, the step that makes a version reachable from Browse.',
    '#take-down': 'D on its own. Each row shows its state — Latest, Stopped, or Rejected but still running — with Stop this version and, for super-staff, granting or revoking realm trust.',
    '#verification-requests': 'En one to read its listing, manifest and verifier findings, then act on it.',
  },
  marketingOverlays: {
    '#announcement-bar': 'Ated by the marketingOverlays entitlement.',
    '#engagement-stats': 'N call, would reach visitors exactly as typed, so the field turns red and names it.',
    '#frequency': '— don\'t nag returning visitors. See below.',
    '#org-marketing-overview': 'Itlement the organization\'s Overlays section is locked, and the Overview leaves the overlay columns out.',
    '#org-overlays': 'Ts the overlays live right now. The table covers your first 25 sites; a site past that has its figures on its own page.',
    '#promotional-popups': 'S controlled centrally and gated by the marketing-overlays entitlement.',
  },
  membersOnly: {
    '#manage-your-members': 'Mark it members-only.',
  },
  orderNotifications: {
    '#customer-emails': 'Ery one of these emails links to a private order status page on your site where the customer can see the order, its shipments and their tracking.',
  },
  ordersAndReturns: {
    '#buyer-requests': 'Return label, what went back in stock, and the refund. Every return is listed under Returns in the Products hub, newest first; the Status filter shows one state at a time.',
    '#order-webhooks': 'Eturn already put back. The four return emails — Return requested, Return approved, Return declined and Return refunded — are designed like your other store emails.',
    '#run-a-return': 'In days — counted from the last shipment, or from the order date for an order with nothing to ship.',
  },
  orgAutomations: {
    '#every-sites-own-automations': 'He people waiting inside it on the sites affected, on their next step — the same as switching off an action does.',
    '#pause-it-on-one-site': 'Site the automation runs on, so the step works wherever it runs.',
    '#what-an-org-automation-is': 'Pro+, like the actions builder, and their runs are metered on the same allowance a site\'s own actions use.',
  },
  pickupAndDelivery: {
    '#set-up-local-delivery': 'Ion. The Offer free local pickup switch on the Shipping card is the older, unnamed pickup choice.',
  },
  plugins: {
    '#a-dependency-that-is-off-for-one-site': 'Elated plugin links to its own page at the same scope, so a site page links to site pages.',
    '#browse-card': 'Site keeps its own pin. Uninstalling never deletes the data a plugin created — reinstall and it picks up where it left off.',
    '#configure': 'S off for this site and warns rather than showing a neutral label.',
    '#configure-site': 'And per-site-override behavior, with nothing for the publisher to build.',
    '#install--upgrade': 'Oose which sites get it, install, upgrade, remove — start with Install your first marketplace item.',
    '#what-the-badges-on-a-listing-mean': 'Lyn collects no manifest of that, and counting it would mean inventing a number, so the box stays to facts the listing actually carries.',
    '#when-one-plugin-depends-on-another': 'Ges — not by the browser, and not in the page the server sends either, even when the server has the plugin loaded for another site.',
  },
  pos: {
    '#card-readers': 'T printer with a system print driver works; see POS hardware.',
    '#registers': 'Es not give you more registers; each sale runs through a register you\'ve created.',
    '#reservations': 'Nutes. Paired kiosks are listed with your customer displays under Commerce → Settings → POS devices, where Sign out unpairs one.',
  },
  posHardware: {
    '#receipt-printers': 'Choice at a busy counter.',
  },
  posOperations: {
    '#shifts-and-the-cash-drawer': 'D Pro or above, like the register itself. Only members who can use the register — a site admin or editor whose Manage POS permission is on — can open shifts, switch in, look customers up or take returns.',
    '#staff-pins': 'Pens a shift. Off by default.',
  },
  postPurchase: {
    '#connect-a-service': 'Er pays Route\'s price, and Aglyn adds nothing to it. Each service uses your own account; Aglyn does not sell one.',
    '#on-the-order': 'Hich parcel the covered goods left in. A whole refund or a cancellation ends the policy.',
  },
  publishAPlugin: {
    '#listing-publisher-card': 'Sher-handbook.md#public-profile) on Marketplace → Profile.',
    '#paid-listings': 'Ce listing needs first — a description, a README, and a license.',
    '#profile-card': 'Est, so the handle, display name, and bio you set are worth the same care as a listing.',
    '#your-publisher-profile': 'Lled back out of your account is shown on its own line so a total that shrank can be reconciled.',
  },
  publisherHandbook: {
    '#asking-to-be-verified': 'Blish checklist above asks you to confirm. A confirmation that turns out to be false is a dated statement by a named publisher, and it\'s grounds for removal.',
    '#authoring-your-listing': 'T — a description, a README, and a license — via Make public on the Listings row.',
    '#before-you-publish': 'Ing\'s changelog tab before deciding to update. On a first version there is nothing to compare against — say what the plugin does instead, or leave it empty.',
    '#bundle-and-manifest': 'L not let a page hold a file across a reload, so you re-choose them, and the page says so rather than pretending it is ready to publish.',
    '#edit-listing': 'Reviewers check them. The repository is asked for at publish and required — editing it here changes the listing, not what past versions declared.',
    '#install-card': 'Organizations and sites that currently hold a pin — it goes down when someone uninstalls.',
    '#installed-from-the-marketplace': 'S for the purchase first, and the same card offers Uninstall (or Uninstall org-wide) once it is installed.',
    '#licenses-you-bought': 'Installable by any member with install permission, whoever on the team paid for it.',
    '#listing-changelog': 'Listing that crosses it is rejected with the reason rather than quietly edited, so you get to fix your own words.',
    '#listing-links': 'Switch a plugin between private and public. Private plugins never appear in Browse, so this list — and View on a row — is where you find them.',
    '#private-plugins': 'Nation your customers read is the one you read. Their two ways out are the two buttons already on that row — upgrade to a later version if one exists, or uninstall.',
    '#public-profile': 'Listings only): complete Stripe Connect onboarding from Marketplace → Payouts.',
    '#publishing-a-version': 'Plugins are different: a plugin is a code bundle, not a site artifact, so it\'s published from your built bundle (below) rather than the source-site picker.',
    '#purchases-and-fees': 'Ipe, or an account to reconnect — and links to your payouts in Stripe.',
    '#refund-reversals': 'Heir marketplace overview with the fee from each sale. Your share is what is left once that fee is taken, before sales tax.',
    '#review-what-happens-after-you-publish': 'Version` in the manifest and upload again — see Shipping a new version.',
    '#set-up-payouts': 'Lost chargebacks are excluded from that total: your share is pulled back from your Connect account, and the amount returned is listed separately.',
    '#the-publisher-agreement': 'Me card takes optional support contacts — a support email and URL — and links to your website, GitHub, X and LinkedIn, so buyers know where to ask for help.',
    '#the-two-badges-and-what-each-one-promises': 'Ditionally sign a version so it runs in the app realm instead of the sandbox — first-party-grade placement for plugins that earn it.',
    '#version-history': 'The publish page every time you ship; a listing whose publisher has never written one shows no Changelog card at all, rather than an empty one.',
    '#watching-your-own-submission': 'Your listing\'s Review status card warns you when an unapproved version still has live installs, so a test install cannot quietly become permanent.',
    '#where-to-publish-from': 'Ard — that is the whole reason the agreement is versioned. Nothing already published is affected, and reviewers can see which version each publisher is under.',
    '#workspace-licenses': 'Are is refused with a note asking for more of it. See Filter and search a list.',
    '#your-listings': ', and the listing changes at once — no new version, and no new review, because review is about the bundle\'s bytes rather than the words around them.',
  },
  redirects: {
    '#manage-redirects': 'Rects/redirects-page.png)',
  },
  salesChannels: {
    '#brand-barcode-and-category': 'Ping: the cheapest rate to each country your shipping zones name, from the same rates checkout charges.',
    '#how-fresh-the-feed-is': 'Number, no description (its name is sent instead), a name longer than the channel shows, clothing without a Color and a Size option, or missing shipping.',
    '#set-up-sales-channels': 'Ad. Sales channels come with every plan that sells online. They are set up in the store\'s settings, under Sales channels, with one card per channel.',
    '#turn-on-a-channel': 'The channel. See Turn on a channel. After that, the channel reads your feed on its own schedule, and each card shows when it last did.',
  },
  sandboxSecurity: {
    '#what-a-reviewer-checks': 'What overcomes it.',
  },
  sequences: {
    '#allowed-countries': 'E. No sequence can be activated while the legal name or the postal address is empty, and an email with neither is never sent.',
    '#build-a-sequence': 'The table rather than applied to some rows. See Filter and search a list.',
    '#compliance-settings': 'Link domain; its sequence links keep the app\'s address. Mailbox providers\' own domains, such as gmail.com, are never offered.',
    '#connect-a-mailbox': 'Nt-editor), or turn release_outreach on for every organization under Feature flags.',
    '#do-not-contact-domains': 'Ever goes outside the United States, whatever this list says.',
    '#enroll': 'Nd of a step, or move the sequence to another site or mailbox — people in it are partway through those steps.',
    '#link-domains': 'Voke the access of every mailbox in it. Access another connected mailbox still uses is left in place for that mailbox, as with a disconnect.',
    '#mailbox-actions': 'E addresses in the mailbox\'s sequences, then select Resume. Only bounces that arrive after you resume are judged again.',
    '#person-activity': 'Eir activity](#person-activity).',
    '#person-details': 'Rather than guessing at the rest. Someone enrolled but not yet emailed shows Nothing yet and when their first step sends.',
    '#person-history': 'Clicked figure to see the people who clicked, or a destination under Links followed to see the people who followed it.',
    '#send-a-test': 'T as plain text again; the figures already counted stay, and the card says they cover only the emails sent while it was on.',
    '#sequence-sending-settings': 'Real footer, and the editor lists anything that stops the sequence from being saved beside the field it is about.',
    '#sequences': 'Rather than removed, and one that Sequences added on its own since — a reply asking not to be emailed, an unsubscribe or a bounce — is always kept.',
  },
  shipping: {
    '#carrier-accounts': 'Tment or suite, city, state or region, postal code, the two-letter country code and a phone number, saved beside the location\'s name.',
    '#shipping-labels': 'Account and not kept by Aglyn. Labels bought on your own account are billed to you by the carrier, so Aglyn charges nothing for them.',
    '#where-parcels-ship-from': 'Te. The destination coverage rules explain what your zones make checkout ask and refuse.',
    '#zones-and-rates': 'Ced from the zones and rates you save there, at the storefront\'s cart, on a product\'s Buy button, and on a draft order\'s payment link.',
  },
  shippingEasy: {
    '#connect': 'Nto this store.',
  },
  shipStation: {
    '#connect': 'With the tracking link. You need to be an admin of the site to connect ShipStation, because the connection can read every order\'s name and address.',
  },
  staffConsole: {
    '#access': 'Eading counts every number currently suppressed across the whole list, not only the page on screen.',
    '#acquisition': 'In the console the next time they sign in, as is anyone whose accepted version has been superseded by a newer publish.',
    '#audit-admin-actions': 'Rd of staff actions, newest first. Click an entry to read its reason, note and before/after below the list.',
    '#audit-archival': '-architecture} How organizations, membership, security rules, subdomains, and billing attribution fit together.',
    '#audit-log': 'Res for Texas, see every row the sweep could not fully read, and export the working papers for the Webfile session.',
    '#billing-insight': 'Adcast reaches every organization in the audience and cannot be recalled, so read it twice before you send it.',
    '#broadcast-announcements': 'Organization\'s detail page, visible to staff only (never in tenant-readable data) and audited.',
    '#contact-suppressions': 'Ks each coupon as covering its cost or under it, with the worst plan\'s coverage; hover it for the figures.',
    '#coupons': 'Entries, and says when there were more. See Filter and search a list.',
    '#create-a-coupon': 'Count codes a customer creates for their own storefront; those belong to the commerce plugin on their site.',
    '#discount-floors': 'Es it once it costs more than the floor, which no organization\'s usage does yet.',
    '#edit-a-system-email': 'K, if it set one. On the marketing site, a block\'s Used by lists the system emails that place it.',
    '#email-delivery': 'Is not the same as "no other devices": do not tell anyone their account is clean from that page until it loads.',
    '#emails-sent': 'Each is on, and on how many of its sites each is paused. It is read-only: click a row to read its trigger and steps.',
    '#enterprise-custom-billing': 'Before. A warning that the rollups could not be read means a failed read, not zero usage.',
    '#existing-coupons': 'Unlimited cannot be costed, so a deal on one cannot be provisioned until an entitlement override bounds it.',
    '#filter-the-directory': 'Ld leave it out of the list. AI spend (month) sorts the page on screen by this month\'s figures.',
    '#filter-the-site-list': '*Open organization and Open owner go to the staff pages for the organization and its owner.',
    '#first-party-hosts': 'T" is a real answer. Today that is done by raising the platform number; there is no per-account override.',
    '#free-workspace-limit': 'In a new tab.',
    '#import-delivery-history': 'Ged keeps its older mail under the old one. An empty table is not proof that nothing was sent.',
    '#legal-acceptances': 'Organization, newest first. The action group chips above it are shortcuts for the actions a plugin names.',
    '#margin-by-organization': 'Structure COGS, on the same arithmetic the discount guardrail uses — not a profit.',
    '#margin-fleet-margin': 'Is left out rather than counted as 0%, and a dash means no organization in the scan has a percentage on that band.',
    '#margin-fleet-utilization': 'Ead, a warning above the figures says they describe only the organizations read so far.',
    '#margin-scan': 'Aves after infrastructure cost: press Scan organizations, then read the fleet figures and the table, worst margin first.',
    '#margin-utilization': 'Same name words. See Filter and search a list.',
    '#org-edit': 'Lockdown.md) for what a suspension does and Pausing AI for one workspace for the AI pause.',
    '#org-effective-entitlements': 'Ne of the organization\'s seats. Seats themselves are counted in Effective entitlements.',
    '#org-members': 'List that could not be read in full says so, because the count also feeds the organization\'s site usage against its plan.',
    '#org-metered-usage': 'Ked where it adds to a band. To change one, use Override on the Staff actions card.',
    '#org-recent-admin-actions': 'An organization already on a custom price shows it at the top of the card.',
    '#org-sites': 'Nership, handing the organization off and asking it to upgrade are here too; see Organization detail.',
    '#org-staff-actions': 'F page is for, top to bottom. The page itself is described under Organization detail.',
    '#organization-detail': 'Lter and search a list](../getting-started/console-tour.md#filter-and-search) for the toolbar itself.',
    '#organization-page-cards': 'Rvice\'s. It survives that vendor\'s own retention window, and it survives replacing the vendor.',
    '#organizations-admin': 'Toring a listing clears only what the takedown did, so a version stopped separately stays stopped.',
    '#password-help': 'Abeled guess, by name. It is recorded once, at account creation, and read-only.',
    '#platform-send-rate': 'Stripe\'s billing emails open the Stripe Dashboard, and a row Firebase sends opens the Firebase console.',
    '#platform-settings': 'Rows and not others. See Filter and search a list.',
    '#platform-suppressions': 'Change writes an audit row with the before, the after and the reason typed into the Why box.',
    '#plugin-reviews': 'By open/closed (across the whole queue, a page at a time), reply as Aglyn staff, close or reopen.',
    '#record-a-dnc-request': 'Program has something to check the day one starts, and so that an opt-out we receive now is not lost.',
    '#sign-one-device-out': 'Are audited; the password itself is never recorded. An account with no email address supports neither.',
    '#site-content': 'Site\'s cached pages are refreshed straight after the move, so it renders under the new organization\'s plan at once.',
    '#site-detail': 'Lters because a site does not store them: filter by Org ID, or open the organization, whose page lists its sites.',
    '#site-ownership': 'Usage, Custom domain, Settings snapshot and the site\'s Activity log.',
    '#site-settings-snapshot': 'Inst. To change a limit, override it on the organization\'s Staff actions card.',
    '#site-usage': 'S {#site-page-cards} Cards on a site\'s staff page that the Site detail list does not describe on their own.',
    '#sites-admin': 'Takes the no seat mark off their rows and pending invites, so they take a seat like anyone else from then on.',
    '#staff-automations': 'E is shown below, by that plugin, when it is installed on the platform — see Automations.',
    '#staff-media-library': 'N each member\'s staff page. An organization with more than thirty sites reads the first thirty and says so.',
    '#staff-notes': 'Product and collection templates. Change them from the site\'s own settings, as a member or by impersonating its owner.',
    '#staff-org-automations': 'Read-only view of the trigger and the steps. Nothing here runs, pauses or edits an automation.',
    '#staff-org-email': 'Itlements counts managers the way the seat gates do, never staff and never site collaborators.',
    '#staff-overview': 'Offering a reset email or a directly set password](/img/staff-console/admin-user-password.png)',
    '#staff-overview-newest-orgs': 'Equivalent, and the caption says how many organizations are billing and how many are comped.',
    '#staff-overview-organizations': 'Nd the organization resolves as Free. The tiles across the top of the overview, one heading each.',
    '#staff-overview-signups': 'Latform — one per customer workspace, whatever its plan. Open Organizations to list and manage them.',
    '#staff-overview-sites': 'Created in the last 30 days. It counts workspaces, not people: one account that opens two workspaces counts twice.',
    '#staff-overview-users': 'E across every organization, published and draft alike. Open Sites to list them and reach a site\'s staff page.',
    '#success-manager': 'N, who did it, when, and the reason they gave. The full, filterable record is on the Audit log.',
    '#suppressed-numbers': 'Or is marked Opted back in rather than removed, so the history of what was asked and when survives.',
    '#system-emails': 'A pinned warning banner with one-click exit shows for the entire session; staff accounts cannot be impersonated).',
    '#user-activity': 'Udit trail so a burst of views cannot bury an impersonation, and it filters and searches the same way.',
    '#user-audit-trail': 'Sites, or each site with its own role. Open an organization for its staff page.',
    '#user-data-access': 'To some entries (see Filter and search a list).',
    '#user-detail': 'By its exact email or uid. See Filter and search a list.',
    '#user-identity': 'Organizations and audit trail, with the support tools beside them: password help, sign-in history and email delivery.',
    '#user-organizations': 'Phone number with No opt-out recorded is not consent to market to it — check before calling or texting.',
    '#users-accounts': 'Ity/auth state, staff role, every organization membership with roles and per-site access, and its recent audit trail.',
    '#users-admin': 'It and each file are recorded in the audit log as data staff looked at (media.library-viewed, media.asset-viewed).',
    '#whats-there': 'Rd card on a user\'s staff detail page, offering a reset email or a directly set password](/img/staff-console/admin-user-password.png)',
  },
  taxServices: {
    '#connect': 'List the states where you collect tax (your nexus) in TaxJar: it charges no tax anywhere else.',
    '#how-sales-are-taxed': 'Tax service card says so while it is the case, with Go to Taxes to change the setting.',
  },
  webhooks: {
    '#outbound-webhooks': 'R feature. ::.',
  },
  zapier: {
    '#see-and-disconnect-your-zaps': 'Ng | bookings:read | | New Contact, Find Contact | contacts:read | | Create Contact, Update Contact | contacts:write | | New Form Submission | forms:read | | Choosing a site | sites:read |',
  },
}
