// GENERATED by tools/scripts/generate-mobile-theme-tokens.mjs — do not edit.
// Source: the console's resolved MUI theme (libs/shared/ui/theme), light and dark.

import SwiftUI

/// One theme intent: its fill, the text on that fill, its readable text
/// color on the page background, and its pressed fill.
public struct AglynIntent: Sendable {
  public let main: Color
  public let contrastText: Color
  public let text: Color
  public let pressed: Color
}

public struct AglynPalette: Sendable {
  public let primary: AglynIntent
  public let secondary: AglynIntent
  public let tertiary: AglynIntent
  public let error: AglynIntent
  public let warning: AglynIntent
  public let success: AglynIntent
  public let info: AglynIntent
  public let background: (default: Color, paper: Color)
  public let text: (primary: Color, secondary: Color, disabled: Color)
  public let divider: Color
  public let grey: [Int: Color]
}

/// One step of the console's type scale, in points at the default content
/// size. `font` scales with Dynamic Type relative to `relativeTo`.
public struct AglynTextStyle: Sendable {
  public let size: CGFloat
  public let weight: Font.Weight
  /// The line box height in points (the console's unitless line height × size).
  public let lineHeight: CGFloat
  /// Tracking in points.
  public let letterSpacing: CGFloat
  /// The console sets this variant in capitals.
  public let uppercase: Bool
  public let relativeTo: Font.TextStyle

  /// The brand face at this size and weight, scaled with Dynamic Type.
  /// SwiftUI draws the system font if the face is not registered.
  public var font: Font {
    .custom(AglynTokens.fontPostScriptName, size: size, relativeTo: relativeTo).weight(weight)
  }

  /// The spacing to add between lines so a line box is `lineHeight` tall.
  public var lineSpacing: CGFloat { max(0, lineHeight - size * 1.2) }
}

/// The console's resolved theme, light and dark.
public enum AglynTokens {
  /// The console's corner radius, in points.
  public static let radius: CGFloat = 4
  /// The console's spacing unit, in points.
  public static let spacing: CGFloat = 8
  /// The family the console's type stack asks for first; the app bundles it.
  public static let fontFamily = "Roboto Flex"
  /// The bundled variable face's PostScript name; weights are its `wght` axis.
  public static let fontPostScriptName = "RobotoFlex-Regular"
  /// The bundled face in AglynUI's resources, to register at launch.
  public static let fontResource = "Fonts/RobotoFlex-Variable.ttf"

  public static let light = AglynPalette(
    primary: AglynIntent(
      main: Color(.sRGB, red: 0 / 255, green: 176 / 255, blue: 255 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 0 / 255, green: 115 / 255, blue: 168 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 0 / 255, green: 119 / 255, blue: 173 / 255, opacity: 1)
    ),
    secondary: AglynIntent(
      main: Color(.sRGB, red: 224 / 255, green: 64 / 255, blue: 251 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 157 / 255, green: 45 / 255, blue: 176 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 157 / 255, green: 45 / 255, blue: 176 / 255, opacity: 1)
    ),
    tertiary: AglynIntent(
      main: Color(.sRGB, red: 64 / 255, green: 76 / 255, blue: 92 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 44 / 255, green: 53 / 255, blue: 64 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 44 / 255, green: 53 / 255, blue: 64 / 255, opacity: 1)
    ),
    error: AglynIntent(
      main: Color(.sRGB, red: 227 / 255, green: 44 / 255, blue: 39 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 158 / 255, green: 30 / 255, blue: 27 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 158 / 255, green: 30 / 255, blue: 27 / 255, opacity: 1)
    ),
    warning: AglynIntent(
      main: Color(.sRGB, red: 255 / 255, green: 171 / 255, blue: 64 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.8706),
      text: Color(.sRGB, red: 149 / 255, green: 100 / 255, blue: 37 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 255 / 255, green: 196 / 255, blue: 121 / 255, opacity: 1)
    ),
    success: AglynIntent(
      main: Color(.sRGB, red: 76 / 255, green: 175 / 255, blue: 80 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.8706),
      text: Color(.sRGB, red: 53 / 255, green: 122 / 255, blue: 56 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 129 / 255, green: 199 / 255, blue: 132 / 255, opacity: 1)
    ),
    info: AglynIntent(
      main: Color(.sRGB, red: 24 / 255, green: 120 / 255, blue: 205 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 16 / 255, green: 84 / 255, blue: 143 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 16 / 255, green: 84 / 255, blue: 143 / 255, opacity: 1)
    ),
    background: (default: Color(.sRGB, red: 245 / 255, green: 245 / 255, blue: 245 / 255, opacity: 1), paper: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1)),
    text: (
      primary: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.87),
      secondary: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.6),
      disabled: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.38)
    ),
    divider: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.12),
    grey: [
      50: Color(.sRGB, red: 250 / 255, green: 250 / 255, blue: 250 / 255, opacity: 1),
      100: Color(.sRGB, red: 245 / 255, green: 245 / 255, blue: 245 / 255, opacity: 1),
      200: Color(.sRGB, red: 238 / 255, green: 238 / 255, blue: 238 / 255, opacity: 1),
      300: Color(.sRGB, red: 224 / 255, green: 224 / 255, blue: 224 / 255, opacity: 1),
      400: Color(.sRGB, red: 189 / 255, green: 189 / 255, blue: 189 / 255, opacity: 1),
      500: Color(.sRGB, red: 158 / 255, green: 158 / 255, blue: 158 / 255, opacity: 1),
      600: Color(.sRGB, red: 117 / 255, green: 117 / 255, blue: 117 / 255, opacity: 1),
      700: Color(.sRGB, red: 97 / 255, green: 97 / 255, blue: 97 / 255, opacity: 1),
      800: Color(.sRGB, red: 66 / 255, green: 66 / 255, blue: 66 / 255, opacity: 1),
      900: Color(.sRGB, red: 33 / 255, green: 33 / 255, blue: 33 / 255, opacity: 1),
    ]
  )

  public static let dark = AglynPalette(
    primary: AglynIntent(
      main: Color(.sRGB, red: 0 / 255, green: 176 / 255, blue: 255 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 77 / 255, green: 200 / 255, blue: 255 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 0 / 255, green: 123 / 255, blue: 178 / 255, opacity: 1)
    ),
    secondary: AglynIntent(
      main: Color(.sRGB, red: 224 / 255, green: 64 / 255, blue: 251 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 233 / 255, green: 121 / 255, blue: 252 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 156 / 255, green: 44 / 255, blue: 175 / 255, opacity: 1)
    ),
    tertiary: AglynIntent(
      main: Color(.sRGB, red: 124 / 255, green: 140 / 255, blue: 163 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.8706),
      text: Color(.sRGB, red: 163 / 255, green: 175 / 255, blue: 191 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 163 / 255, green: 175 / 255, blue: 191 / 255, opacity: 1)
    ),
    error: AglynIntent(
      main: Color(.sRGB, red: 227 / 255, green: 44 / 255, blue: 39 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 238 / 255, green: 124 / 255, blue: 123 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 158 / 255, green: 30 / 255, blue: 27 / 255, opacity: 1)
    ),
    warning: AglynIntent(
      main: Color(.sRGB, red: 255 / 255, green: 171 / 255, blue: 64 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.8706),
      text: Color(.sRGB, red: 255 / 255, green: 196 / 255, blue: 121 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 255 / 255, green: 196 / 255, blue: 121 / 255, opacity: 1)
    ),
    success: AglynIntent(
      main: Color(.sRGB, red: 76 / 255, green: 175 / 255, blue: 80 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 0 / 255, green: 0 / 255, blue: 0 / 255, opacity: 0.8706),
      text: Color(.sRGB, red: 130 / 255, green: 199 / 255, blue: 133 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 130 / 255, green: 199 / 255, blue: 133 / 255, opacity: 1)
    ),
    info: AglynIntent(
      main: Color(.sRGB, red: 24 / 255, green: 120 / 255, blue: 205 / 255, opacity: 1),
      contrastText: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      text: Color(.sRGB, red: 101 / 255, green: 166 / 255, blue: 222 / 255, opacity: 1),
      pressed: Color(.sRGB, red: 16 / 255, green: 84 / 255, blue: 143 / 255, opacity: 1)
    ),
    background: (default: Color(.sRGB, red: 22 / 255, green: 28 / 255, blue: 33 / 255, opacity: 1), paper: Color(.sRGB, red: 42 / 255, green: 52 / 255, blue: 64 / 255, opacity: 1)),
    text: (
      primary: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 1),
      secondary: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.7),
      disabled: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.5)
    ),
    divider: Color(.sRGB, red: 255 / 255, green: 255 / 255, blue: 255 / 255, opacity: 0.12),
    grey: [
      50: Color(.sRGB, red: 250 / 255, green: 250 / 255, blue: 250 / 255, opacity: 1),
      100: Color(.sRGB, red: 245 / 255, green: 245 / 255, blue: 245 / 255, opacity: 1),
      200: Color(.sRGB, red: 238 / 255, green: 238 / 255, blue: 238 / 255, opacity: 1),
      300: Color(.sRGB, red: 224 / 255, green: 224 / 255, blue: 224 / 255, opacity: 1),
      400: Color(.sRGB, red: 189 / 255, green: 189 / 255, blue: 189 / 255, opacity: 1),
      500: Color(.sRGB, red: 158 / 255, green: 158 / 255, blue: 158 / 255, opacity: 1),
      600: Color(.sRGB, red: 117 / 255, green: 117 / 255, blue: 117 / 255, opacity: 1),
      700: Color(.sRGB, red: 97 / 255, green: 97 / 255, blue: 97 / 255, opacity: 1),
      800: Color(.sRGB, red: 66 / 255, green: 66 / 255, blue: 66 / 255, opacity: 1),
      900: Color(.sRGB, red: 33 / 255, green: 33 / 255, blue: 33 / 255, opacity: 1),
    ]
  )

  /// The console's type scale (MUI variants), at the phone size.
  public enum Typography {
    public static let h1 = AglynTextStyle(
      size: 34.29, weight: .black, lineHeight: 36, letterSpacing: -0.857, uppercase: false, relativeTo: .largeTitle)
    public static let h2 = AglynTextStyle(
      size: 27.83, weight: .heavy, lineHeight: 32, letterSpacing: -0.557, uppercase: false, relativeTo: .title)
    public static let h3 = AglynTextStyle(
      size: 26.67, weight: .bold, lineHeight: 32, letterSpacing: -0.4, uppercase: false, relativeTo: .title2)
    public static let h4 = AglynTextStyle(
      size: 25.91, weight: .regular, lineHeight: 32, letterSpacing: 0, uppercase: false, relativeTo: .title2)
    public static let h5 = AglynTextStyle(
      size: 20.99, weight: .regular, lineHeight: 28, letterSpacing: 0, uppercase: false, relativeTo: .title3)
    public static let h6 = AglynTextStyle(
      size: 17.5, weight: .medium, lineHeight: 28, letterSpacing: 0, uppercase: false, relativeTo: .headline)
    public static let subtitle1 = AglynTextStyle(
      size: 16, weight: .regular, lineHeight: 28, letterSpacing: 0, uppercase: false, relativeTo: .body)
    public static let subtitle2 = AglynTextStyle(
      size: 14, weight: .medium, lineHeight: 21.98, letterSpacing: 0, uppercase: false, relativeTo: .subheadline)
    public static let body1 = AglynTextStyle(
      size: 16, weight: .regular, lineHeight: 24, letterSpacing: 0, uppercase: false, relativeTo: .body)
    public static let body2 = AglynTextStyle(
      size: 14, weight: .regular, lineHeight: 20.02, letterSpacing: 0, uppercase: false, relativeTo: .callout)
    public static let caption = AglynTextStyle(
      size: 12, weight: .regular, lineHeight: 19.92, letterSpacing: 0, uppercase: false, relativeTo: .caption)
    public static let button = AglynTextStyle(
      size: 14, weight: .medium, lineHeight: 24.5, letterSpacing: 0, uppercase: true, relativeTo: .body)
    public static let overline = AglynTextStyle(
      size: 12, weight: .regular, lineHeight: 31.92, letterSpacing: 0, uppercase: true, relativeTo: .caption2)
  }
}
