// Aglyn and Aglyn POS on the JVM desktop (Compose Multiplatform). Windows
// ships from here (MSI/MSIX, packaged on Windows CI); macOS ships the SwiftUI
// app, so a Mac build of this is for development and screenshots.
//
// One module, two apps: -Paglyn.desktopApp=pos builds and runs Aglyn POS.
import org.jetbrains.compose.desktop.application.dsl.TargetFormat

plugins {
  alias(libs.plugins.kotlin.multiplatform)
  alias(libs.plugins.compose.compiler)
  alias(libs.plugins.compose.multiplatform)
}

val pos = (findProperty("aglyn.desktopApp") as String?) == "pos"
val isWindows = System.getProperty("os.name").orEmpty().startsWith("Windows")

// The WebView2 SDK package (a NuGet zip). Only its WebView2Loader.dll ships:
// the Besigner's embedded view on Windows talks to the Evergreen runtime
// Windows keeps updated, so no browser engine is bundled.
val webview2Sdk: Configuration by configurations.creating { isTransitive = false }
dependencies { webview2Sdk(libs.webview2.sdk) { artifact { type = "nupkg"; extension = "nupkg" } } }

// Compose packages `appResources/windows-x64` (and `windows-arm64`) beside
// the app; WebView2Host finds the loader through compose.application.resources.dir.
val webview2Loader by tasks.registering(Sync::class) {
  from({ zipTree(webview2Sdk.singleFile) }) {
    include("runtimes/win-x64/native/WebView2Loader.dll", "runtimes/win-arm64/native/WebView2Loader.dll", "LICENSE.txt")
    eachFile {
      path = when {
        path.contains("win-x64") -> "windows-x64/WebView2Loader.dll"
        path.contains("win-arm64") -> "windows-arm64/WebView2Loader.dll"
        else -> "common/licenses/WebView2-LICENSE.txt"
      }
    }
    includeEmptyDirs = false
  }
  into(layout.buildDirectory.dir("appResources"))
}

// The SDK's headers, for reading the COM layout (development only).
tasks.register<Sync>("webview2Headers") {
  from({ zipTree(webview2Sdk.singleFile) }) { include("build/native/include/*.h", "build/native/include/*.idl") }
  into(layout.buildDirectory.dir("webview2-sdk"))
}

kotlin {
  jvmToolchain(21)
  jvm("desktop")

  sourceSets {
    named("desktopMain") {
      dependencies {
        implementation(project(":native-shell"))
        implementation(project(":plugin-manifest"))
        implementation(compose.desktop.currentOs)
        implementation(libs.kotlinx.coroutines.swing)
      }
    }
    named("desktopTest") {
      dependencies {
        implementation(libs.compose.ui.test)
      }
    }
  }
}

compose.desktop {
  application {
    mainClass = if (pos) "com.aglyn.desktop.AglynPosDesktopKt" else "com.aglyn.desktop.AglynDesktopKt"
    // Run settings: the local emulator stack unless -Daglyn.* says otherwise.
    jvmArgs += (findProperty("aglyn.jvmArgs") as String?)?.split(' ')?.filter { it.isNotBlank() } ?: emptyList()

    // Packaging on Windows carries WebView2Loader.dll; a Mac or Linux build
    // never resolves the SDK.
    if (isWindows) nativeDistributions.appResourcesRootDir.set(layout.buildDirectory.dir("appResources"))
    nativeDistributions {
      targetFormats(TargetFormat.Msi, TargetFormat.Exe, TargetFormat.Dmg)
      packageName = if (pos) "Aglyn POS" else "Aglyn"
      packageVersion = "1.0.0"
      vendor = "Aglyn LLC"
      description = if (pos) "The Aglyn register" else "Manage your Aglyn workspace"
      windows {
        // Stable per app, so an install upgrades in place.
        upgradeUuid = if (pos) "5d3c8e2a-7f1b-4c4e-9a7e-2b6f0c9d1e42" else "9b1f4a6e-3c2d-4e8f-a1b7-6d5c0e9f2a13"
        menuGroup = "Aglyn"
        perUserInstall = true
        shortcut = true
        // Generated by tools/scripts/generate-native-brand-assets.mjs.
        iconFile.set(project.file(if (pos) "icons/aglyn-pos.ico" else "icons/aglyn.ico"))
      }
      macOS {
        bundleID = if (pos) "com.aglyn.pos.desktop" else "com.aglyn.app.desktop"
        iconFile.set(project.file(if (pos) "icons/aglyn-pos.icns" else "icons/aglyn.icns"))
      }
    }
  }
}

// Offscreen screenshots of every desktop screen against the emulator stack
// (a development tool; see DesktopSnapshots.kt).
tasks.register<JavaExec>("snapshots") {
  val test = kotlin.jvm("desktop").compilations.getByName("test")
  dependsOn(test.compileTaskProvider)
  classpath = files(test.output.allOutputs, test.runtimeDependencyFiles)
  mainClass.set("com.aglyn.desktop.DesktopSnapshotsKt")
  jvmArgs((findProperty("aglyn.jvmArgs") as String?)?.split(' ')?.filter { it.isNotBlank() } ?: emptyList<String>())
  (findProperty("aglyn.snapshotDir") as String?)?.let { systemProperty("aglyn.snapshotDir", it) }
}

// The register's screens on the desktop, driven like a cashier would (a
// development tool; see PosSnapshots.kt).
tasks.register<JavaExec>("posSnapshots") {
  val test = kotlin.jvm("desktop").compilations.getByName("test")
  dependsOn(test.compileTaskProvider)
  classpath = files(test.output.allOutputs, test.runtimeDependencyFiles)
  mainClass.set("com.aglyn.desktop.PosSnapshotsKt")
  jvmArgs((findProperty("aglyn.jvmArgs") as String?)?.split(' ')?.filter { it.isNotBlank() } ?: emptyList<String>())
  (findProperty("aglyn.snapshotDir") as String?)?.let { systemProperty("aglyn.snapshotDir", it) }
}

// The content areas (sites, pages, media, forms, submissions, data) at phone,
// tablet and desktop widths (a development tool; see ContentSnapshots.kt).
tasks.register<JavaExec>("contentSnapshots") {
  val test = kotlin.jvm("desktop").compilations.getByName("test")
  dependsOn(test.compileTaskProvider)
  classpath = files(test.output.allOutputs, test.runtimeDependencyFiles)
  mainClass.set("com.aglyn.desktop.ContentSnapshotsKt")
  jvmArgs((findProperty("aglyn.jvmArgs") as String?)?.split(' ')?.filter { it.isNotBlank() } ?: emptyList<String>())
  (findProperty("aglyn.snapshotDir") as String?)?.let { systemProperty("aglyn.snapshotDir", it) }
  (findProperty("aglyn.snapshotOnly") as String?)?.let { systemProperty("aglyn.snapshotOnly", it) }
}

// This module's test source set holds the snapshot tool, not tests; the
// shells' UI tests live in libs/native/kotlin/shell.
tasks.withType<Test>().configureEach { failOnNoDiscoveredTests.set(false) }

// Compose copies appResources into the package and the run; on Windows the
// loader is extracted first.
if (isWindows) {
  tasks.matching { it.name == "prepareAppResources" }.configureEach { dependsOn(webview2Loader) }
}
