// GENERATED by tools/scripts/generate-native-derived-values.mjs; do not edit.
// The console's checkEntitlement answers for each plan (plan-entitlements.ts).
package com.aglyn.core

/** Each plan's default for the plan features native screens gate on. */
object PlanFeatureDefaults {
  val byPlan: Map<String, Map<String, Boolean>> = mapOf(
    "free" to mapOf("marketingOverlays" to false, "abTesting" to false, "screenAnalytics" to false, "outreach" to false),
    "starter" to mapOf("marketingOverlays" to true, "abTesting" to false, "screenAnalytics" to false, "outreach" to false),
    "pro" to mapOf("marketingOverlays" to true, "abTesting" to false, "screenAnalytics" to true, "outreach" to false),
    "business" to mapOf("marketingOverlays" to true, "abTesting" to true, "screenAnalytics" to true, "outreach" to false),
    "scale" to mapOf("marketingOverlays" to true, "abTesting" to true, "screenAnalytics" to true, "outreach" to false),
    "advanced" to mapOf("marketingOverlays" to true, "abTesting" to true, "screenAnalytics" to true, "outreach" to false),
    "agency" to mapOf("marketingOverlays" to true, "abTesting" to true, "screenAnalytics" to true, "outreach" to false),
    "enterprise" to mapOf("marketingOverlays" to true, "abTesting" to true, "screenAnalytics" to true, "outreach" to false),
  )
}

/** The events an A/B test can count as its goal, in the console's picker order. */
object ExperimentGoalEvents {
  val all: List<String> = listOf("formSubmission", "pageView", "memberSignUp", "memberSignIn", "memberSignOut", "lead", "booking", "taskCompleted", "contactCreated", "contactStageChanged", "dealStageChanged", "dealWon", "dealLost", "orderPaid", "orderFulfilled", "orderDelivered", "orderRefunded", "orderCancelled", "returnRequested", "returnApproved", "returnDeclined", "returnReceived", "returnRefunded", "funnelLeft", "scrollDepth", "scrollToElement", "elementClick", "elementVisible", "elementHoverEnter", "elementHoverLeave", "exitIntent", "timeOnPage", "pageVisit")
}

/** Each release flag as the Remote Config template publishes it. */
object ReleaseFlagDefaults {
  val byKey: Map<String, ReleaseFlagValue> = mapOf(
    "release_member_accounts" to ReleaseFlagValue(true, 0, listOf()),
    "release_bookings" to ReleaseFlagValue(true, 0, listOf()),
    "release_commerce_v2" to ReleaseFlagValue(true, 0, listOf()),
    "release_marketplace" to ReleaseFlagValue(true, 0, listOf()),
    "release_crm" to ReleaseFlagValue(true, 0, listOf()),
    "release_outreach" to ReleaseFlagValue(false, 0, listOf()),
    "release_data_store" to ReleaseFlagValue(true, 0, listOf()),
    "release_email" to ReleaseFlagValue(true, 0, listOf()),
    "release_events" to ReleaseFlagValue(true, 0, listOf()),
    "release_inbox" to ReleaseFlagValue(true, 0, listOf()),
    "release_logic" to ReleaseFlagValue(true, 0, listOf()),
    "release_marketing" to ReleaseFlagValue(true, 0, listOf()),
    "release_redirects" to ReleaseFlagValue(true, 0, listOf()),
    "release_workflows" to ReleaseFlagValue(true, 0, listOf()),
    "release_accounting" to ReleaseFlagValue(false, 0, listOf()),
    "release_weglot" to ReleaseFlagValue(true, 0, listOf()),
    "release_addon_store" to ReleaseFlagValue(true, 0, listOf()),
    "release_native_checkout" to ReleaseFlagValue(true, 0, listOf()),
    "release_edit_bar" to ReleaseFlagValue(true, 0, listOf()),
    "release_assist" to ReleaseFlagValue(true, 0, listOf()),
    "release_video_uploads" to ReleaseFlagValue(false, 0, listOf()),
    "release_video_delivery" to ReleaseFlagValue(false, 0, listOf()),
    "release_ai_generative" to ReleaseFlagValue(true, 0, listOf()),
    "release_crm_assist_whole_record" to ReleaseFlagValue(true, 0, listOf()),
  )
}
