// GENERATED by tools/scripts/generate-native-derived-values.mjs; do not edit.
// The console's checkEntitlement answers for each plan (plan-entitlements.ts).

/// Each plan's default for the plan features native screens gate on.
public enum PlanFeatureDefaults {
  public static let byPlan: [String: [String: Bool]] = [
    "free": ["marketingOverlays": false, "abTesting": false, "screenAnalytics": false, "outreach": false],
    "starter": ["marketingOverlays": true, "abTesting": false, "screenAnalytics": false, "outreach": false],
    "pro": ["marketingOverlays": true, "abTesting": false, "screenAnalytics": true, "outreach": false],
    "business": ["marketingOverlays": true, "abTesting": true, "screenAnalytics": true, "outreach": false],
    "scale": ["marketingOverlays": true, "abTesting": true, "screenAnalytics": true, "outreach": false],
    "advanced": ["marketingOverlays": true, "abTesting": true, "screenAnalytics": true, "outreach": false],
    "agency": ["marketingOverlays": true, "abTesting": true, "screenAnalytics": true, "outreach": false],
    "enterprise": ["marketingOverlays": true, "abTesting": true, "screenAnalytics": true, "outreach": false],
  ]
}

/// The events an A/B test can count as its goal, in the console's picker order.
public enum ExperimentGoalEvents {
  public static let all: [String] = ["formSubmission", "pageView", "memberSignUp", "memberSignIn", "memberSignOut", "lead", "booking", "taskCompleted", "contactCreated", "contactStageChanged", "dealStageChanged", "dealWon", "dealLost", "orderPaid", "orderFulfilled", "orderDelivered", "orderRefunded", "orderCancelled", "returnRequested", "returnApproved", "returnDeclined", "returnReceived", "returnRefunded", "funnelLeft", "scrollDepth", "scrollToElement", "elementClick", "elementVisible", "elementHoverEnter", "elementHoverLeave", "exitIntent", "timeOnPage", "pageVisit"]
}

/// Each release flag as the Remote Config template publishes it.
public enum ReleaseFlagDefaults {
  public static let byKey: [String: ReleaseFlagValue] = [
    "release_member_accounts": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_bookings": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_commerce_v2": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_marketplace": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_crm": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_outreach": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_data_store": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_email": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_events": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_inbox": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_logic": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_marketing": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_redirects": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_workflows": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_accounting": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_addon_store": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_native_checkout": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_edit_bar": ReleaseFlagValue(enabled: true, rolloutPercent: 0, plans: []),
    "release_assist": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_video_uploads": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_video_delivery": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_ai_generative": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
    "release_crm_assist_whole_record": ReleaseFlagValue(enabled: false, rolloutPercent: 0, plans: []),
  ]
}
