/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import { pluginRequestFromWeb } from '@aglyn/aglyn/server'
import { signPluginTrust } from '@aglyn/aglyn/plugin-manager/plugin-trust-signing'
import {
  emailUnverifiedResponse,
  firebaseAdmin,
  isImpersonationSession,
} from '@aglyn/tenant-data-admin'
import { invalidIdTokenResponse } from '@aglyn/tenant-data-admin/server/id-token-refusal'
import { FieldValue } from 'firebase-admin/firestore'

/**
 * Staff trust-signing for realm plugins (AGL-420), served at
 * `/api/marketplace/admin/trust` for this plugin's review queue.
 *
 * It was `apps/console/app/api/admin/sign-plugin/route.ts` until AGL-3080.
 * What moved is everything that is the MARKETPLACE's: `marketplaceListings`
 * is its collection, "a version must have passed review" is its rule, and
 * the fields a grant writes are its documents.
 *
 * ⛔ WHAT DID NOT MOVE IS THE KEY. `PLUGIN_TRUST_PRIVATE_KEY` is deployed to
 * the console and nowhere else — never to a tenant runtime — and this
 * package is published to npm, where a self-hoster generates their own
 * pair. So the signature comes from the shell through
 * `signPluginTrust`, and this route refuses the grant outright when it
 * answers `signed: false`. A `trust: 'realm'` flag written without a
 * signature beside it is the one state the loaders cannot tell from
 * tampering.
 *
 * Granting writes
 * `{trust: 'realm', signature}` onto the listing's version doc, where the
 * signature is the platform Ed25519 key's signature over the version's
 * sha256 hex — the loaders (client blob-import + env-gated server import)
 * verify it against `PLUGIN_TRUST_PUBLIC_KEY` before a byte executes.
 * Super staff only: a realm grant lets marketplace code run in the app
 * realm of every workspace that installs it, the largest blast radius any
 * staff action has. Revoking removes the grant (already-loaded realms
 * pick it up on next load; use `revocations/{listingId}` for the hard
 * kill switch).
 *
 * `PLUGIN_TRUST_PRIVATE_KEY` is the base64 PKCS8 DER Ed25519 private key
 * (pair generated by `tools/scripts/generate-plugin-trust-key.mjs`) —
 * deployed ONLY to the console app, never to tenant runtimes.
 */
async function handler(request: Request): Promise<Response> {
  const { method, body, headers: rawHeaders } = await pluginRequestFromWeb(request)
  const headers = rawHeaders as Partial<Record<string, string>>
  if (method !== 'POST') {
    return Response.json({ error: 'Method not allowed' }, { status: 405 })
  }
  const authorization = headers.authorization ?? ''
  const idToken = authorization.startsWith('Bearer ')
    ? authorization.slice('Bearer '.length)
    : undefined
  if (!idToken) return Response.json({ error: 'Unauthenticated' }, { status: 401 })

  try {
    const decoded = await firebaseAdmin.app().auth().verifyIdToken(idToken)
    if (!decoded.email_verified && !isImpersonationSession(decoded)) {
      return emailUnverifiedResponse()
    }
    if (!decoded['staff']) {
      return Response.json({ error: 'Staff only' }, { status: 403 })
    }
    if (String(decoded['staffRole'] ?? 'support') !== 'super') {
      return Response.json({ error: 'Requires the super staff role' }, { status: 403 })
    }

    const listingId = String(body?.listingId ?? '')
    const version = String(body?.version ?? '')
    const action = body?.action === 'revoke' ? 'revoke' : 'grant'
    if (!listingId || !version) {
      return Response.json({ error: 'Missing listingId or version' }, { status: 400 })
    }

    const versionRef = firebaseAdmin
      .app()
      .firestore()
      .collection('marketplaceListings')
      .doc(listingId)
      .collection('pluginVersions')
      .doc(version)
    const snapshot = await versionRef.get()
    const sha256 = snapshot.get('sha256')
    if (typeof sha256 !== 'string' || !sha256) {
      return Response.json({ error: 'Unknown plugin version' }, { status: 404 })
    }

    // Realm trust is the strongest grant in the platform — it drops a
    // bundle into the app realm, where the sandbox iframe and the manifest
    // CSP no longer stand between it and user data. It cannot be granted to
    // bytes that have not passed review (AGL-966).
    if (action === 'grant' && snapshot.get('reviewState') !== 'approved') {
      return Response.json(
        {
          error:
            'That version has not passed review — approve it before granting realm trust',
          reviewState: snapshot.get('reviewState') ?? 'unknown',
        },
        { status: 409 },
      )
    }

    if (action === 'grant') {
      /*
       * The shell signs; this decides what is worth signing. A refusal here
       * is final — nothing is written, and the 501 is the same answer an
       * unconfigured deployment has always given, now reached through the
       * contract rather than by reading the key.
       */
      const { signed, signature, reason } = await signPluginTrust(sha256)
      if (!signed || !signature) {
        return Response.json(
          {
            error:
              reason ??
              'Trust signing is not configured (missing PLUGIN_TRUST_PRIVATE_KEY)',
          },
          { status: 501 },
        )
      }
      await versionRef.set(
        {
          trust: 'realm',
          signature,
          trustGrantedBy: decoded.uid,
          trustGrantedAt: FieldValue.serverTimestamp(),
        },
        { merge: true },
      )
    } else {
      await versionRef.set(
        {
          trust: FieldValue.delete(),
          signature: FieldValue.delete(),
          trustGrantedBy: FieldValue.delete(),
          trustGrantedAt: FieldValue.delete(),
        },
        { merge: true },
      )
    }

    await firebaseAdmin
      .app()
      .firestore()
      .collection('adminAudit')
      .add({
        actorUid: decoded.uid,
        action: `plugins.trust.${action}`,
        target: `marketplaceListings/${listingId}/pluginVersions/${version}`,
        after: action === 'grant' ? { trust: 'realm' } : { trust: null },
        at: FieldValue.serverTimestamp(),
      })

    return Response.json({ ok: true, action, listingId, version }, { status: 200 })
  } catch (error) {
    // An unverifiable credential is a 401, not a fault of ours
    // (AGL-1993). Null for anything else, so a real failure keeps its 500.
    const unauthenticated = invalidIdTokenResponse(error)
    if (unauthenticated) return unauthenticated
    console.error(error)
    return Response.json({ error: 'Trust signing failed' }, { status: 500 })
  }
}

export { handler as marketplaceAdminTrust }
