// GENERATED by tools/scripts/generate-native-contracts.mjs — do not edit.
// Source: tools/scripts/native-contracts.json over the pure TypeScript modules it names.

import Foundation

/// Any JSON value: a field the contract carries as-is.
public enum ContractJSON: Codable, Hashable, Sendable {
  case null
  case bool(Bool)
  case number(Double)
  case string(String)
  case array([ContractJSON])
  case object([String: ContractJSON])

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() {
      self = .null
    } else if let value = try? container.decode(Bool.self) {
      self = .bool(value)
    } else if let value = try? container.decode(Double.self) {
      self = .number(value)
    } else if let value = try? container.decode(String.self) {
      self = .string(value)
    } else if let value = try? container.decode([ContractJSON].self) {
      self = .array(value)
    } else {
      self = .object(try container.decode([String: ContractJSON].self))
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .null: try container.encodeNil()
    case .bool(let value): try container.encode(value)
    case .number(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    case .array(let value): try container.encode(value)
    case .object(let value): try container.encode(value)
    }
  }
}

public struct AccountPushSettings: Codable, Hashable, Sendable {
  public var account: [String: AccountPushSettingsAccountValue]?
  public var accountTypes: [String: AccountPushSettingsAccountTypesValue]?

  public init(account: [String: AccountPushSettingsAccountValue]? = nil, accountTypes: [String: AccountPushSettingsAccountTypesValue]? = nil) {
    self.account = account
    self.accountTypes = accountTypes
  }
}

public struct AccountPushSettingsAccountTypesValue: Codable, Hashable, Sendable {
  public var console: Bool?
  public var push: Bool?

  public init(console: Bool? = nil, push: Bool? = nil) {
    self.console = console
    self.push = push
  }
}

public struct AccountPushSettingsAccountValue: Codable, Hashable, Sendable {
  public var console: Bool?
  public var push: Bool?

  public init(console: Bool? = nil, push: Bool? = nil) {
    self.console = console
    self.push = push
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ApnsEnvironment: String, Codable, CaseIterable, Hashable, Sendable {
  case production = "production"
  case sandbox = "sandbox"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostOrder: Codable, Hashable, Sendable {
  public var amountCents: Double?
  public var billingAddress: OrderAddress?
  public var buyerNotifications: [String: HostOrderBuyerNotificationsValue]?
  public var cashierId: String?
  public var channel: OrderChannel?
  public var checkoutSessionId: String?
  public var couponCode: String?
  public var createdAtMs: Double?
  public var customerEmail: String?
  public var customerId: String?
  public var customerName: String?
  public var customerPhone: String?
  public var customerRecord: HostOrderCustomerRecord?
  public var discountBy: String?
  public var discountPct: Double?
  public var dispute: OrderDispute?
  public var feeCents: Double?
  public var fulfillments: [OrderFulfillment]?
  public var invoiceId: String?
  public var lineItems: [OrderLineItem]?
  public var locationId: String?
  public var note: String?
  public var number: Double?
  public var paymentIntentId: String?
  public var paymentLinkUrl: String?
  public var paymentRisk: PaymentRisk?
  public var payments: [OrderPayment]?
  public var productId: String?
  public var receiptRequest: HostOrderReceiptRequest?
  public var refundedCents: Double?
  public var refundedLineItemIds: [Double]?
  public var registerId: String?
  public var restockCheck: OrderRestockCheck?
  public var shiftId: String?
  public var shippingAddress: OrderAddress?
  public var status: OrderStatus
  public var subscriptionId: String?
  public var taxMode: HostOrderTaxMode?
  public var timeline: [OrderTimelineEvent]?
  public var totals: OrderTotals?
  public var unresolvedLines: [OrderUnresolvedLine]?

  public init(amountCents: Double? = nil, billingAddress: OrderAddress? = nil, buyerNotifications: [String: HostOrderBuyerNotificationsValue]? = nil, cashierId: String? = nil, channel: OrderChannel? = nil, checkoutSessionId: String? = nil, couponCode: String? = nil, createdAtMs: Double? = nil, customerEmail: String? = nil, customerId: String? = nil, customerName: String? = nil, customerPhone: String? = nil, customerRecord: HostOrderCustomerRecord? = nil, discountBy: String? = nil, discountPct: Double? = nil, dispute: OrderDispute? = nil, feeCents: Double? = nil, fulfillments: [OrderFulfillment]? = nil, invoiceId: String? = nil, lineItems: [OrderLineItem]? = nil, locationId: String? = nil, note: String? = nil, number: Double? = nil, paymentIntentId: String? = nil, paymentLinkUrl: String? = nil, paymentRisk: PaymentRisk? = nil, payments: [OrderPayment]? = nil, productId: String? = nil, receiptRequest: HostOrderReceiptRequest? = nil, refundedCents: Double? = nil, refundedLineItemIds: [Double]? = nil, registerId: String? = nil, restockCheck: OrderRestockCheck? = nil, shiftId: String? = nil, shippingAddress: OrderAddress? = nil, status: OrderStatus, subscriptionId: String? = nil, taxMode: HostOrderTaxMode? = nil, timeline: [OrderTimelineEvent]? = nil, totals: OrderTotals? = nil, unresolvedLines: [OrderUnresolvedLine]? = nil) {
    self.amountCents = amountCents
    self.billingAddress = billingAddress
    self.buyerNotifications = buyerNotifications
    self.cashierId = cashierId
    self.channel = channel
    self.checkoutSessionId = checkoutSessionId
    self.couponCode = couponCode
    self.createdAtMs = createdAtMs
    self.customerEmail = customerEmail
    self.customerId = customerId
    self.customerName = customerName
    self.customerPhone = customerPhone
    self.customerRecord = customerRecord
    self.discountBy = discountBy
    self.discountPct = discountPct
    self.dispute = dispute
    self.feeCents = feeCents
    self.fulfillments = fulfillments
    self.invoiceId = invoiceId
    self.lineItems = lineItems
    self.locationId = locationId
    self.note = note
    self.number = number
    self.paymentIntentId = paymentIntentId
    self.paymentLinkUrl = paymentLinkUrl
    self.paymentRisk = paymentRisk
    self.payments = payments
    self.productId = productId
    self.receiptRequest = receiptRequest
    self.refundedCents = refundedCents
    self.refundedLineItemIds = refundedLineItemIds
    self.registerId = registerId
    self.restockCheck = restockCheck
    self.shiftId = shiftId
    self.shippingAddress = shippingAddress
    self.status = status
    self.subscriptionId = subscriptionId
    self.taxMode = taxMode
    self.timeline = timeline
    self.totals = totals
    self.unresolvedLines = unresolvedLines
  }
}

public struct HostOrderBuyerNotificationsValue: Codable, Hashable, Sendable {
  public var atMs: Double
  public var channel: HostOrderBuyerNotificationsValueChannel
  public var state: HostOrderBuyerNotificationsValueState

  public init(atMs: Double, channel: HostOrderBuyerNotificationsValueChannel, state: HostOrderBuyerNotificationsValueState) {
    self.atMs = atMs
    self.channel = channel
    self.state = state
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderBuyerNotificationsValueChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case email = "email"
  case sms = "sms"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderBuyerNotificationsValueState: String, Codable, CaseIterable, Hashable, Sendable {
  case sending = "sending"
  case sent = "sent"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostOrderCustomerRecord: Codable, Hashable, Sendable {
  public var id: String
  public var kind: String

  public init(id: String, kind: String) {
    self.id = id
    self.kind = kind
  }
}

public struct HostOrderReceiptRequest: Codable, Hashable, Sendable {
  public var atMs: Double
  public var channel: PosReceiptChannel
  public var to: String?

  public init(atMs: Double, channel: PosReceiptChannel, to: String? = nil) {
    self.atMs = atMs
    self.channel = channel
    self.to = to
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderTaxMode: String, Codable, CaseIterable, Hashable, Sendable {
  case manual = "manual"
  case none = "none"
  case stripeAutomatic = "stripe-automatic"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostRedirect: Codable, Hashable, Sendable {
  public var destination: String
  public var enabled: Bool?
  public var externalDestinationApprovedBy: String?
  public var kind: HostRedirectKind?
  public var priority: Double?
  public var source: String
  public var statusCode: Int

  public init(destination: String, enabled: Bool? = nil, externalDestinationApprovedBy: String? = nil, kind: HostRedirectKind? = nil, priority: Double? = nil, source: String, statusCode: Int) {
    self.destination = destination
    self.enabled = enabled
    self.externalDestinationApprovedBy = externalDestinationApprovedBy
    self.kind = kind
    self.priority = priority
    self.source = source
    self.statusCode = statusCode
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostRedirectKind: String, Codable, CaseIterable, Hashable, Sendable {
  case exact = "exact"
  case prefix = "prefix"
  case regex = "regex"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListFilterField: Codable, Hashable, Sendable {
  public var column: String
  public var containsOrderBy: String?
  public var containsOrderDirection: ListFilterFieldContainsOrderDirection?
  public var keysOf: Bool?
  public var kind: ListFilterKind
  public var lowerPath: String?
  public var operators: [String]?
  public var path: String
  public var presence: ListFilterFieldPresence?
  public var reversedPath: String?
  public var rowPath: String?
  public var storedAs: ListFilterFieldStoredAs?
  public var tokensPath: String?
  public var verbatimTokens: Bool?
  public var windowOnly: Bool?

  public init(column: String, containsOrderBy: String? = nil, containsOrderDirection: ListFilterFieldContainsOrderDirection? = nil, keysOf: Bool? = nil, kind: ListFilterKind, lowerPath: String? = nil, operators: [String]? = nil, path: String, presence: ListFilterFieldPresence? = nil, reversedPath: String? = nil, rowPath: String? = nil, storedAs: ListFilterFieldStoredAs? = nil, tokensPath: String? = nil, verbatimTokens: Bool? = nil, windowOnly: Bool? = nil) {
    self.column = column
    self.containsOrderBy = containsOrderBy
    self.containsOrderDirection = containsOrderDirection
    self.keysOf = keysOf
    self.kind = kind
    self.lowerPath = lowerPath
    self.operators = operators
    self.path = path
    self.presence = presence
    self.reversedPath = reversedPath
    self.rowPath = rowPath
    self.storedAs = storedAs
    self.tokensPath = tokensPath
    self.verbatimTokens = verbatimTokens
    self.windowOnly = windowOnly
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldContainsOrderDirection: String, Codable, CaseIterable, Hashable, Sendable {
  case asc = "asc"
  case desc = "desc"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldPresence: String, Codable, CaseIterable, Hashable, Sendable {
  case always = "always"
  case nullable = "nullable"
  case sparse = "sparse"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldStoredAs: String, Codable, CaseIterable, Hashable, Sendable {
  case millis = "millis"
  case timestamp = "timestamp"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterKind: String, Codable, CaseIterable, Hashable, Sendable {
  case boolean = "boolean"
  case date = "date"
  case exact = "exact"
  case id = "id"
  case number = "number"
  case text = "text"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListFilterOption: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

public struct ListFilterRequest: Codable, Hashable, Sendable {
  public var field: String
  public var op: String
  public var value: String

  public init(field: String, op: String, value: String) {
    self.field = field
    self.op = op
    self.value = value
  }
}

public struct ListQueryDeclaration: Codable, Hashable, Sendable {
  public var fields: [ListFilterField]
  public var keys: [String: [String]]?
  public var search: ListQueryDeclarationSearch?
  public var sorts: [ListQuerySort]

  public init(fields: [ListFilterField], keys: [String: [String]]? = nil, search: ListQueryDeclarationSearch? = nil, sorts: [ListQuerySort]) {
    self.fields = fields
    self.keys = keys
    self.search = search
    self.sorts = sorts
  }
}

public struct ListQueryDeclarationSearch: Codable, Hashable, Sendable {
  public var scoped: ListQueryDeclarationSearchScoped?
  public var tokensPath: String

  public init(scoped: ListQueryDeclarationSearchScoped? = nil, tokensPath: String) {
    self.scoped = scoped
    self.tokensPath = tokensPath
  }
}

public struct ListQueryDeclarationSearchScoped: Codable, Hashable, Sendable {
  public var join: String
  public var tokensPath: String

  public init(join: String, tokensPath: String) {
    self.join = join
    self.tokensPath = tokensPath
  }
}

public struct ListQueryFilter: Codable, Hashable, Sendable {
  public var op: ListQueryOp
  public var path: String
  public var value: ContractJSON

  public init(op: ListQueryOp, path: String, value: ContractJSON) {
    self.op = op
    self.path = path
    self.value = value
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListQueryOp: String, Codable, CaseIterable, Hashable, Sendable {
  case notEqual = "!="
  case lessThan = "<"
  case lessThanOrEqual = "<="
  case equal = "=="
  case greaterThan = ">"
  case greaterThanOrEqual = ">="
  case arrayContains = "array-contains"
  case arrayContainsAny = "array-contains-any"
  case `in` = "in"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListQueryPlan: Codable, Hashable, Sendable {
  public var filters: [ListQueryFilter]
  public var notices: [String]
  public var orderBy: ListQuerySort
  public var refused: [ListQueryRefusal]
  public var searched: String?
  public var served: [ListFilterRequest]

  public init(filters: [ListQueryFilter], notices: [String], orderBy: ListQuerySort, refused: [ListQueryRefusal], searched: String? = nil, served: [ListFilterRequest]) {
    self.filters = filters
    self.notices = notices
    self.orderBy = orderBy
    self.refused = refused
    self.searched = searched
    self.served = served
  }
}

public struct ListQueryRefusal: Codable, Hashable, Sendable {
  public var clause: ContractJSON
  public var reason: String

  public init(clause: ContractJSON, reason: String) {
    self.clause = clause
    self.reason = reason
  }
}

public struct ListQueryRequest: Codable, Hashable, Sendable {
  public var base: [ListQueryFilter]?
  public var clauses: [ListFilterRequest]
  public var search: [String]?
  public var sort: ListQuerySort?

  public init(base: [ListQueryFilter]? = nil, clauses: [ListFilterRequest], search: [String]? = nil, sort: ListQuerySort? = nil) {
    self.base = base
    self.clauses = clauses
    self.search = search
    self.sort = sort
  }
}

public struct ListQuerySort: Codable, Hashable, Sendable {
  public var column: String?
  public var direction: ListQuerySortDirection
  public var path: String

  public init(column: String? = nil, direction: ListQuerySortDirection, path: String) {
    self.column = column
    self.direction = direction
    self.path = path
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListQuerySortDirection: String, Codable, CaseIterable, Hashable, Sendable {
  case asc = "asc"
  case desc = "desc"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct MobileDevice: Codable, Hashable, Sendable {
  public var apnsEnvironment: ApnsEnvironment?
  public var app: MobileDeviceApp
  public var appVersion: String?
  public var lastSeen: ContractJSON?
  public var platform: MobileDevicePlatform
  public var token: String
  public var transport: MobilePushTransport

  public init(apnsEnvironment: ApnsEnvironment? = nil, app: MobileDeviceApp, appVersion: String? = nil, lastSeen: ContractJSON? = nil, platform: MobileDevicePlatform, token: String, transport: MobilePushTransport) {
    self.apnsEnvironment = apnsEnvironment
    self.app = app
    self.appVersion = appVersion
    self.lastSeen = lastSeen
    self.platform = platform
    self.token = token
    self.transport = transport
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobileDeviceApp: String, Codable, CaseIterable, Hashable, Sendable {
  case aglyn = "aglyn"
  case aglynPos = "aglyn-pos"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobileDevicePlatform: String, Codable, CaseIterable, Hashable, Sendable {
  case android = "android"
  case ios = "ios"
  case macos = "macos"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct MobilePushData: Codable, Hashable, Sendable {
  public var hostId: String?
  public var link: String?
  public var orgId: String?
  public var type: String

  public init(hostId: String? = nil, link: String? = nil, orgId: String? = nil, type: String) {
    self.hostId = hostId
    self.link = link
    self.orgId = orgId
    self.type = type
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobilePushTransport: String, Codable, CaseIterable, Hashable, Sendable {
  case apns = "apns"
  case fcm = "fcm"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ModifierSelection: Codable, Hashable, Sendable {
  public var groupId: String
  public var optionId: String

  public init(groupId: String, optionId: String) {
    self.groupId = groupId
    self.optionId = optionId
  }
}

public struct OrderAddress: Codable, Hashable, Sendable {
  public var city: String?
  public var country: String?
  public var line1: String?
  public var line2: String?
  public var name: String?
  public var phone: String?
  public var postalCode: String?
  public var state: String?

  public init(city: String? = nil, country: String? = nil, line1: String? = nil, line2: String? = nil, name: String? = nil, phone: String? = nil, postalCode: String? = nil, state: String? = nil) {
    self.city = city
    self.country = country
    self.line1 = line1
    self.line2 = line2
    self.name = name
    self.phone = phone
    self.postalCode = postalCode
    self.state = state
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case draft = "draft"
  case online = "online"
  case pos = "pos"
  case subscription = "subscription"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderDispute: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var closedAtMs: Double?
  public var evidenceDueByMs: Double?
  public var id: String
  public var openedAtMs: Double
  public var outcome: String?
  public var reason: String?
  public var reversedCents: Double?
  public var reversedTransferCents: Double?
  public var status: String
  public var transferReversalId: String?

  public init(amountCents: Double, closedAtMs: Double? = nil, evidenceDueByMs: Double? = nil, id: String, openedAtMs: Double, outcome: String? = nil, reason: String? = nil, reversedCents: Double? = nil, reversedTransferCents: Double? = nil, status: String, transferReversalId: String? = nil) {
    self.amountCents = amountCents
    self.closedAtMs = closedAtMs
    self.evidenceDueByMs = evidenceDueByMs
    self.id = id
    self.openedAtMs = openedAtMs
    self.outcome = outcome
    self.reason = reason
    self.reversedCents = reversedCents
    self.reversedTransferCents = reversedTransferCents
    self.status = status
    self.transferReversalId = transferReversalId
  }
}

public struct OrderFulfillment: Codable, Hashable, Sendable {
  public var atMs: Double
  public var cancelledAtMs: Double?
  public var carrier: String?
  public var id: String
  public var labelRef: String?
  public var labelUrl: String?
  public var lineItemIds: [Double]
  public var lines: [OrderFulfillmentLinesItem]?
  public var notify: Bool?
  public var status: OrderFulfillmentStatus?
  public var trackingNumber: String?
  public var trackingStatus: String?
  public var trackingStatusAtMs: Double?
  public var trackingUrl: String?
  public var updatedAtMs: Double?

  public init(atMs: Double, cancelledAtMs: Double? = nil, carrier: String? = nil, id: String, labelRef: String? = nil, labelUrl: String? = nil, lineItemIds: [Double], lines: [OrderFulfillmentLinesItem]? = nil, notify: Bool? = nil, status: OrderFulfillmentStatus? = nil, trackingNumber: String? = nil, trackingStatus: String? = nil, trackingStatusAtMs: Double? = nil, trackingUrl: String? = nil, updatedAtMs: Double? = nil) {
    self.atMs = atMs
    self.cancelledAtMs = cancelledAtMs
    self.carrier = carrier
    self.id = id
    self.labelRef = labelRef
    self.labelUrl = labelUrl
    self.lineItemIds = lineItemIds
    self.lines = lines
    self.notify = notify
    self.status = status
    self.trackingNumber = trackingNumber
    self.trackingStatus = trackingStatus
    self.trackingStatusAtMs = trackingStatusAtMs
    self.trackingUrl = trackingUrl
    self.updatedAtMs = updatedAtMs
  }
}

public struct OrderFulfillmentLinesItem: Codable, Hashable, Sendable {
  public var lineItemId: Double
  public var quantity: Double

  public init(lineItemId: Double, quantity: Double) {
    self.lineItemId = lineItemId
    self.quantity = quantity
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderFulfillmentStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case active = "active"
  case cancelled = "cancelled"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderLineItem: Codable, Hashable, Sendable {
  public var fulfillmentId: String?
  public var modifiers: [OrderLineModifier]?
  public var name: String
  public var productId: String
  public var productType: ProductType?
  public var quantity: Double
  public var sku: String?
  public var supplierId: String?
  public var unitAmountCents: Double
  public var variantId: String?
  public var variantLabel: String?

  public init(fulfillmentId: String? = nil, modifiers: [OrderLineModifier]? = nil, name: String, productId: String, productType: ProductType? = nil, quantity: Double, sku: String? = nil, supplierId: String? = nil, unitAmountCents: Double, variantId: String? = nil, variantLabel: String? = nil) {
    self.fulfillmentId = fulfillmentId
    self.modifiers = modifiers
    self.name = name
    self.productId = productId
    self.productType = productType
    self.quantity = quantity
    self.sku = sku
    self.supplierId = supplierId
    self.unitAmountCents = unitAmountCents
    self.variantId = variantId
    self.variantLabel = variantLabel
  }
}

public struct OrderLineModifier: Codable, Hashable, Sendable {
  public var group: String
  public var groupId: String
  public var name: String
  public var optionId: String
  public var priceCents: Double

  public init(group: String, groupId: String, name: String, optionId: String, priceCents: Double) {
    self.group = group
    self.groupId = groupId
    self.name = name
    self.optionId = optionId
    self.priceCents = priceCents
  }
}

public struct OrderPayment: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var atMs: Double
  public var cardBrand: String?
  public var cashierId: String?
  public var cashTenderedCents: Double?
  public var changeCents: Double?
  public var checkoutSessionId: String?
  public var checkoutUrl: String?
  public var failureMessage: String?
  public var feeCents: Double?
  public var folioAtMs: Double?
  public var giftCardId: String?
  public var id: String
  public var last4: String?
  public var livemode: Bool?
  public var method: OrderPaymentMethod
  public var paymentIntentId: String?
  public var readerId: String?
  public var reservationId: String?
  public var settledAtMs: Double?
  public var status: OrderPaymentStatus
  public var takeFeeCents: Double?
  public var tipCents: Double?

  public init(amountCents: Double, atMs: Double, cardBrand: String? = nil, cashierId: String? = nil, cashTenderedCents: Double? = nil, changeCents: Double? = nil, checkoutSessionId: String? = nil, checkoutUrl: String? = nil, failureMessage: String? = nil, feeCents: Double? = nil, folioAtMs: Double? = nil, giftCardId: String? = nil, id: String, last4: String? = nil, livemode: Bool? = nil, method: OrderPaymentMethod, paymentIntentId: String? = nil, readerId: String? = nil, reservationId: String? = nil, settledAtMs: Double? = nil, status: OrderPaymentStatus, takeFeeCents: Double? = nil, tipCents: Double? = nil) {
    self.amountCents = amountCents
    self.atMs = atMs
    self.cardBrand = cardBrand
    self.cashierId = cashierId
    self.cashTenderedCents = cashTenderedCents
    self.changeCents = changeCents
    self.checkoutSessionId = checkoutSessionId
    self.checkoutUrl = checkoutUrl
    self.failureMessage = failureMessage
    self.feeCents = feeCents
    self.folioAtMs = folioAtMs
    self.giftCardId = giftCardId
    self.id = id
    self.last4 = last4
    self.livemode = livemode
    self.method = method
    self.paymentIntentId = paymentIntentId
    self.readerId = readerId
    self.reservationId = reservationId
    self.settledAtMs = settledAtMs
    self.status = status
    self.takeFeeCents = takeFeeCents
    self.tipCents = tipCents
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderPaymentMethod: String, Codable, CaseIterable, Hashable, Sendable {
  case cardKeyed = "card_keyed"
  case cardLink = "card_link"
  case cardPresent = "card_present"
  case cash = "cash"
  case folio = "folio"
  case giftCard = "gift_card"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderPaymentStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case canceled = "canceled"
  case failed = "failed"
  case pending = "pending"
  case reversed = "reversed"
  case succeeded = "succeeded"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderRestockCheck: Codable, Hashable, Sendable {
  public var flaggedAtMs: Double
  public var fullyReversed: Bool
  public var kind: OrderRestockCheckKind
  public var lines: [OrderRestockLine]
  public var resolution: OrderRestockCheckResolution?
  public var resolvedAtMs: Double?
  public var resolvedBy: String?
  public var units: Double

  public init(flaggedAtMs: Double, fullyReversed: Bool, kind: OrderRestockCheckKind, lines: [OrderRestockLine], resolution: OrderRestockCheckResolution? = nil, resolvedAtMs: Double? = nil, resolvedBy: String? = nil, units: Double) {
    self.flaggedAtMs = flaggedAtMs
    self.fullyReversed = fullyReversed
    self.kind = kind
    self.lines = lines
    self.resolution = resolution
    self.resolvedAtMs = resolvedAtMs
    self.resolvedBy = resolvedBy
    self.units = units
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderRestockCheckKind: String, Codable, CaseIterable, Hashable, Sendable {
  case chargeback = "chargeback"
  case refund = "refund"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderRestockCheckResolution: String, Codable, CaseIterable, Hashable, Sendable {
  case dismissed = "dismissed"
  case restocked = "restocked"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderRestockLine: Codable, Hashable, Sendable {
  public var lineIndex: Double?
  public var name: String?
  public var productId: String
  public var quantity: Double
  public var variantId: String
  public var variantLabel: String?

  public init(lineIndex: Double? = nil, name: String? = nil, productId: String, quantity: Double, variantId: String, variantLabel: String? = nil) {
    self.lineIndex = lineIndex
    self.name = name
    self.productId = productId
    self.quantity = quantity
    self.variantId = variantId
    self.variantLabel = variantLabel
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case cancelled = "cancelled"
  case delivered = "delivered"
  case fulfilled = "fulfilled"
  case paid = "paid"
  case partiallyFulfilled = "partially_fulfilled"
  case pending = "pending"
  case refunded = "refunded"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderTimelineEvent: Codable, Hashable, Sendable {
  public var atMs: Double
  public var detail: String?
  public var event: String

  public init(atMs: Double, detail: String? = nil, event: String) {
    self.atMs = atMs
    self.detail = detail
    self.event = event
  }
}

public struct OrderTotals: Codable, Hashable, Sendable {
  public var discountCents: Double
  public var feeCents: Double
  public var itemsCents: Double
  public var shippingCents: Double
  public var taxCents: Double
  public var tipCents: Double?
  public var totalCents: Double

  public init(discountCents: Double, feeCents: Double, itemsCents: Double, shippingCents: Double, taxCents: Double, tipCents: Double? = nil, totalCents: Double) {
    self.discountCents = discountCents
    self.feeCents = feeCents
    self.itemsCents = itemsCents
    self.shippingCents = shippingCents
    self.taxCents = taxCents
    self.tipCents = tipCents
    self.totalCents = totalCents
  }
}

public struct OrderUnresolvedLine: Codable, Hashable, Sendable {
  public var productId: String
  public var quantity: Double
  public var variantId: String?

  public init(productId: String, quantity: Double, variantId: String? = nil) {
    self.productId = productId
    self.quantity = quantity
    self.variantId = variantId
  }
}

public struct PaymentRisk: Codable, Hashable, Sendable {
  public var latestAtMs: Double
  public var latestKind: PaymentRiskSignalKind
  public var signals: [PaymentRiskSignal]

  public init(latestAtMs: Double, latestKind: PaymentRiskSignalKind, signals: [PaymentRiskSignal]) {
    self.latestAtMs = latestAtMs
    self.latestKind = latestKind
    self.signals = signals
  }
}

public struct PaymentRiskSignal: Codable, Hashable, Sendable {
  public var atMs: Double
  public var detail: String?
  public var kind: PaymentRiskSignalKind
  public var outcome: String?
  public var stripeObjectId: String

  public init(atMs: Double, detail: String? = nil, kind: PaymentRiskSignalKind, outcome: String? = nil, stripeObjectId: String) {
    self.atMs = atMs
    self.detail = detail
    self.kind = kind
    self.outcome = outcome
    self.stripeObjectId = stripeObjectId
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum PaymentRiskSignalKind: String, Codable, CaseIterable, Hashable, Sendable {
  case dispute = "dispute"
  case earlyFraudWarning = "early-fraud-warning"
  case radarReview = "radar-review"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum PosReceiptChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case email = "email"
  case none = "none"
  case print = "print"
  case sms = "sms"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ProductModifierGroup: Codable, Hashable, Sendable {
  public var id: String
  public var max: Double
  public var min: Double
  public var name: String
  public var options: [ProductModifierOption]

  public init(id: String, max: Double, min: Double, name: String, options: [ProductModifierOption]) {
    self.id = id
    self.max = max
    self.min = min
    self.name = name
    self.options = options
  }
}

public struct ProductModifierOption: Codable, Hashable, Sendable {
  public var id: String
  public var name: String
  public var priceCents: Double

  public init(id: String, name: String, priceCents: Double) {
    self.id = id
    self.name = name
    self.priceCents = priceCents
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ProductType: String, Codable, CaseIterable, Hashable, Sendable {
  case digital = "digital"
  case physical = "physical"
  case service = "service"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ReceiptData: Codable, Hashable, Sendable {
  public var banner: String?
  public var barcode: String?
  public var cashierName: String?
  public var changeCents: Double?
  public var createdAtMs: Double
  public var currency: String
  public var discountCents: Double?
  public var footer: String?
  public var lines: [ReceiptLine]
  public var orderId: String?
  public var orderNumber: String
  public var refundedCents: Double?
  public var registerName: String?
  public var shippingCents: Double?
  public var storeLines: [String]?
  public var storeName: String
  public var subtotalCents: Double
  public var taxCents: Double?
  public var tenders: [ReceiptTender]?
  public var timeZone: String?
  public var tipCents: Double?
  public var totalCents: Double

  public init(banner: String? = nil, barcode: String? = nil, cashierName: String? = nil, changeCents: Double? = nil, createdAtMs: Double, currency: String, discountCents: Double? = nil, footer: String? = nil, lines: [ReceiptLine], orderId: String? = nil, orderNumber: String, refundedCents: Double? = nil, registerName: String? = nil, shippingCents: Double? = nil, storeLines: [String]? = nil, storeName: String, subtotalCents: Double, taxCents: Double? = nil, tenders: [ReceiptTender]? = nil, timeZone: String? = nil, tipCents: Double? = nil, totalCents: Double) {
    self.banner = banner
    self.barcode = barcode
    self.cashierName = cashierName
    self.changeCents = changeCents
    self.createdAtMs = createdAtMs
    self.currency = currency
    self.discountCents = discountCents
    self.footer = footer
    self.lines = lines
    self.orderId = orderId
    self.orderNumber = orderNumber
    self.refundedCents = refundedCents
    self.registerName = registerName
    self.shippingCents = shippingCents
    self.storeLines = storeLines
    self.storeName = storeName
    self.subtotalCents = subtotalCents
    self.taxCents = taxCents
    self.tenders = tenders
    self.timeZone = timeZone
    self.tipCents = tipCents
    self.totalCents = totalCents
  }
}

public struct ReceiptLine: Codable, Hashable, Sendable {
  public var detail: String?
  public var name: String
  public var quantity: Double
  public var totalCents: Double
  public var unitCents: Double

  public init(detail: String? = nil, name: String, quantity: Double, totalCents: Double, unitCents: Double) {
    self.detail = detail
    self.name = name
    self.quantity = quantity
    self.totalCents = totalCents
    self.unitCents = unitCents
  }
}

public struct ReceiptTender: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var label: String

  public init(amountCents: Double, label: String) {
    self.amountCents = amountCents
    self.label = label
  }
}

/// The values in contracts.generated.json, keyed as the TypeScript exports are.
public struct ContractValues: Codable, Hashable, Sendable {
  public let listQueryDisjunctions: Int
  public let listQueryIdPath: String
  public let nameTokenLimit: Int
  public let nameTokenMaxPrefix: Int
  public let orderChannelLabels: [String: String]
  public let orderChannelOptions: [ListFilterOption]
  public let orderDisputeOptions: [ListFilterOption]
  public let orderListHeaders: [String: String]
  public let orderListQuery: ListQueryDeclaration
  public let orderListSelectFields: [String]
  public let orderStatusLabels: [String: String]
  public let orderStatusOptions: [ListFilterOption]
  public let productListBase: [ListQueryFilter]
  public let productListHeaders: [String: String]
  public let productListOptions: [String: [ListFilterOption]]
  public let productListQuery: ListQueryDeclaration
  public let productListSelectFields: [String]
  public let scopedSearchJoin: String

  enum CodingKeys: String, CodingKey {
    case listQueryDisjunctions = "LIST_QUERY_DISJUNCTIONS"
    case listQueryIdPath = "LIST_QUERY_ID_PATH"
    case nameTokenLimit = "NAME_TOKEN_LIMIT"
    case nameTokenMaxPrefix = "NAME_TOKEN_MAX_PREFIX"
    case orderChannelLabels = "ORDER_CHANNEL_LABELS"
    case orderChannelOptions = "ORDER_CHANNEL_OPTIONS"
    case orderDisputeOptions = "ORDER_DISPUTE_OPTIONS"
    case orderListHeaders = "ORDER_LIST_HEADERS"
    case orderListQuery = "ORDER_LIST_QUERY"
    case orderListSelectFields = "ORDER_LIST_SELECT_FIELDS"
    case orderStatusLabels = "ORDER_STATUS_LABELS"
    case orderStatusOptions = "ORDER_STATUS_OPTIONS"
    case productListBase = "PRODUCT_LIST_BASE"
    case productListHeaders = "PRODUCT_LIST_HEADERS"
    case productListOptions = "PRODUCT_LIST_OPTIONS"
    case productListQuery = "PRODUCT_LIST_QUERY"
    case productListSelectFields = "PRODUCT_LIST_SELECT_FIELDS"
    case scopedSearchJoin = "SCOPED_SEARCH_JOIN"
  }
}
