// GENERATED by tools/scripts/generate-native-contracts.mjs — do not edit.
// Source: tools/scripts/native-contracts.json over the pure TypeScript modules it names.

import Foundation

/// Any JSON value: a field the contract carries as-is.
public enum ContractJSON: Codable, Hashable, Sendable {
  case null
  case bool(Bool)
  case number(Double)
  case string(String)
  case array([ContractJSON])
  case object([String: ContractJSON])

  public init(from decoder: Decoder) throws {
    let container = try decoder.singleValueContainer()
    if container.decodeNil() {
      self = .null
    } else if let value = try? container.decode(Bool.self) {
      self = .bool(value)
    } else if let value = try? container.decode(Double.self) {
      self = .number(value)
    } else if let value = try? container.decode(String.self) {
      self = .string(value)
    } else if let value = try? container.decode([ContractJSON].self) {
      self = .array(value)
    } else {
      self = .object(try container.decode([String: ContractJSON].self))
    }
  }

  public func encode(to encoder: Encoder) throws {
    var container = encoder.singleValueContainer()
    switch self {
    case .null: try container.encodeNil()
    case .bool(let value): try container.encode(value)
    case .number(let value): try container.encode(value)
    case .string(let value): try container.encode(value)
    case .array(let value): try container.encode(value)
    case .object(let value): try container.encode(value)
    }
  }
}

public struct AccountPushSettings: Codable, Hashable, Sendable {
  public var account: [String: AccountPushSettingsAccountValue]?
  public var accountTypes: [String: AccountPushSettingsAccountTypesValue]?

  public init(account: [String: AccountPushSettingsAccountValue]? = nil, accountTypes: [String: AccountPushSettingsAccountTypesValue]? = nil) {
    self.account = account
    self.accountTypes = accountTypes
  }
}

public struct AccountPushSettingsAccountTypesValue: Codable, Hashable, Sendable {
  public var console: Bool?
  public var push: Bool?

  public init(console: Bool? = nil, push: Bool? = nil) {
    self.console = console
    self.push = push
  }
}

public struct AccountPushSettingsAccountValue: Codable, Hashable, Sendable {
  public var console: Bool?
  public var push: Bool?

  public init(console: Bool? = nil, push: Bool? = nil) {
    self.console = console
    self.push = push
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ApnsEnvironment: String, Codable, CaseIterable, Hashable, Sendable {
  case production = "production"
  case sandbox = "sandbox"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BindingRefVia: String, Codable, CaseIterable, Hashable, Sendable {
  case id = "id"
  case name = "name"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct BookingActions: Codable, Hashable, Sendable {
  public var cancel: Bool
  public var checkIn: Bool
  public var refundCents: Int
  public var reschedule: Bool
  public var undoCheckIn: Bool

  public init(cancel: Bool, checkIn: Bool, refundCents: Int, reschedule: Bool, undoCheckIn: Bool) {
    self.cancel = cancel
    self.checkIn = checkIn
    self.refundCents = refundCents
    self.reschedule = reschedule
    self.undoCheckIn = undoCheckIn
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BookingFieldAsk: String, Codable, CaseIterable, Hashable, Sendable {
  case off = "off"
  case optional = "optional"
  case required = "required"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct BookingInPersonPayment: Codable, Hashable, Sendable {
  public var amountCents: Int
  public var attempt: String?
  public var feeCents: Int
  public var paidAtMs: Int?
  public var paymentIntentId: String
  public var serviceCents: Int
  public var startedAtMs: Int
  public var startedBy: String
  public var status: BookingInPersonPaymentStatus
  public var taxCents: Int

  public init(amountCents: Int, attempt: String? = nil, feeCents: Int, paidAtMs: Int? = nil, paymentIntentId: String, serviceCents: Int, startedAtMs: Int, startedBy: String, status: BookingInPersonPaymentStatus, taxCents: Int) {
    self.amountCents = amountCents
    self.attempt = attempt
    self.feeCents = feeCents
    self.paidAtMs = paidAtMs
    self.paymentIntentId = paymentIntentId
    self.serviceCents = serviceCents
    self.startedAtMs = startedAtMs
    self.startedBy = startedBy
    self.status = status
    self.taxCents = taxCents
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BookingInPersonPaymentStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case canceled = "canceled"
  case paid = "paid"
  case pending = "pending"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BookingInPersonState: String, Codable, CaseIterable, Hashable, Sendable {
  case awaitingOnline = "awaiting-online"
  case canceled = "canceled"
  case collecting = "collecting"
  case paid = "paid"
  case payable = "payable"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BookingPriceDisplay: String, Codable, CaseIterable, Hashable, Sendable {
  case contact = "contact"
  case estimate = "estimate"
  case fixed = "fixed"
  case varies = "varies"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct BookingServiceDraft: Codable, Hashable, Sendable {
  public var askAddress: BookingFieldAsk
  public var askPhone: BookingFieldAsk
  public var crmFollowUpTask: Bool
  public var crmMeetingActivity: Bool
  public var description: String
  public var durationMinutes: String
  public var name: String
  public var priceDisplay: BookingPriceDisplay
  public var priceUsd: String
  public var timezone: String
  public var windowText: [String]

  public init(askAddress: BookingFieldAsk, askPhone: BookingFieldAsk, crmFollowUpTask: Bool, crmMeetingActivity: Bool, description: String, durationMinutes: String, name: String, priceDisplay: BookingPriceDisplay, priceUsd: String, timezone: String, windowText: [String]) {
    self.askAddress = askAddress
    self.askPhone = askPhone
    self.crmFollowUpTask = crmFollowUpTask
    self.crmMeetingActivity = crmMeetingActivity
    self.description = description
    self.durationMinutes = durationMinutes
    self.name = name
    self.priceDisplay = priceDisplay
    self.priceUsd = priceUsd
    self.timezone = timezone
    self.windowText = windowText
  }
}

public struct BookingServiceFields: Codable, Hashable, Sendable {
  public var askAddress: BookingFieldAsk
  public var askPhone: BookingFieldAsk
  public var crmFollowUpTask: Bool
  public var crmMeetingActivity: Bool
  public var description: String
  public var durationMinutes: Int
  public var name: String
  public var priceDisplay: BookingPriceDisplay
  public var priceUsd: Int
  public var timezone: String
  public var windows: [String: [BookingWindow]]

  public init(askAddress: BookingFieldAsk, askPhone: BookingFieldAsk, crmFollowUpTask: Bool, crmMeetingActivity: Bool, description: String, durationMinutes: Int, name: String, priceDisplay: BookingPriceDisplay, priceUsd: Int, timezone: String, windows: [String: [BookingWindow]]) {
    self.askAddress = askAddress
    self.askPhone = askPhone
    self.crmFollowUpTask = crmFollowUpTask
    self.crmMeetingActivity = crmMeetingActivity
    self.description = description
    self.durationMinutes = durationMinutes
    self.name = name
    self.priceDisplay = priceDisplay
    self.priceUsd = priceUsd
    self.timezone = timezone
    self.windows = windows
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum BookingState: String, Codable, CaseIterable, Hashable, Sendable {
  case canceled = "canceled"
  case confirmed = "confirmed"
  case expired = "expired"
  case pendingPayment = "pendingPayment"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct BookingWindow: Codable, Hashable, Sendable {
  public var end: Int
  public var start: Int

  public init(end: Int, start: Int) {
    self.end = end
    self.start = start
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ContentSchemaType: String, Codable, CaseIterable, Hashable, Sendable {
  case article = "Article"
  case blogPosting = "BlogPosting"
  case newsArticle = "NewsArticle"
  case techArticle = "TechArticle"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ContentSchemaTypeOptionsItem: Codable, Hashable, Sendable {
  public var description: String
  public var label: String
  public var value: String

  public init(description: String, label: String, value: String) {
    self.description = description
    self.label = label
    self.value = value
  }
}

public struct DatasetFieldDefinition: Codable, Hashable, Sendable {
  public var customType: String?
  public var `default`: ContractJSON?
  public var description: String?
  public var name: String?
  public var reference: DatasetFieldDefinitionReference?
  public var required: Bool?
  public var slugFrom: String?
  public var type: DatasetFieldType?
  public var validation: DatasetFieldValidation?

  public init(customType: String? = nil, `default`: ContractJSON? = nil, description: String? = nil, name: String? = nil, reference: DatasetFieldDefinitionReference? = nil, required: Bool? = nil, slugFrom: String? = nil, type: DatasetFieldType? = nil, validation: DatasetFieldValidation? = nil) {
    self.customType = customType
    self.default = `default`
    self.description = description
    self.name = name
    self.reference = reference
    self.required = required
    self.slugFrom = slugFrom
    self.type = type
    self.validation = validation
  }
}

public struct DatasetFieldDefinitionReference: Codable, Hashable, Sendable {
  public var datasetId: String
  public var displayFieldId: String?
  public var multiple: Bool?
  public var onDelete: DatasetFieldDefinitionReferenceOnDelete?

  public init(datasetId: String, displayFieldId: String? = nil, multiple: Bool? = nil, onDelete: DatasetFieldDefinitionReferenceOnDelete? = nil) {
    self.datasetId = datasetId
    self.displayFieldId = displayFieldId
    self.multiple = multiple
    self.onDelete = onDelete
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum DatasetFieldDefinitionReferenceOnDelete: String, Codable, CaseIterable, Hashable, Sendable {
  case restrict = "restrict"
  case setNull = "setNull"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct DatasetFieldEntry: Codable, Hashable, Sendable {
  public var id: String
  public var name: String

  public init(id: String, name: String) {
    self.id = id
    self.name = name
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum DatasetFieldType: String, Codable, CaseIterable, Hashable, Sendable {
  case bool = "bool"
  case bytes = "bytes"
  case coordinates = "coordinates"
  case float = "float"
  case int32 = "int32"
  case int64 = "int64"
  case map = "map"
  case `nil` = "nil"
  case reference = "reference"
  case sorted = "sorted"
  case text = "text"
  case timestamp = "timestamp"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct DatasetFieldValidation: Codable, Hashable, Sendable {
  public var max: Double?
  public var min: Double?
  public var options: [String]?
  public var regex: String?
  public var required: Bool?

  public init(max: Double? = nil, min: Double? = nil, options: [String]? = nil, regex: String? = nil, required: Bool? = nil) {
    self.max = max
    self.min = min
    self.options = options
    self.regex = regex
    self.required = required
  }
}

public struct DatasetModel: Codable, Hashable, Sendable {
  public var fields: [String: DatasetFieldDefinition]?
  public var order: [String]?

  public init(fields: [String: DatasetFieldDefinition]? = nil, order: [String]? = nil) {
    self.fields = fields
    self.order = order
  }
}

public struct DeviceSplitEntry: Codable, Hashable, Sendable {
  public var count: Int
  public var device: String
  public var percent: Int

  public init(count: Int, device: String, percent: Int) {
    self.count = count
    self.device = device
    self.percent = percent
  }
}

public struct EntryStatusOptionsItem: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum EventRemovableField: String, Codable, CaseIterable, Hashable, Sendable {
  case coverImage = "coverImage"
  case coverImageAlt = "coverImageAlt"
  case description = "description"
  case location = "location"
  case organizer = "organizer"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum EventStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case draft = "draft"
  case published = "published"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct EventStoredFields: Codable, Hashable, Sendable {
  public var coverImage: String?
  public var coverImageAlt: String?
  public var description: String?
  public var endsAtMs: Int
  public var location: String?
  public var organizer: String?
  public var startsAtMs: Int
  public var status: EventStatus
  public var title: String

  public init(coverImage: String? = nil, coverImageAlt: String? = nil, description: String? = nil, endsAtMs: Int, location: String? = nil, organizer: String? = nil, startsAtMs: Int, status: EventStatus, title: String) {
    self.coverImage = coverImage
    self.coverImageAlt = coverImageAlt
    self.description = description
    self.endsAtMs = endsAtMs
    self.location = location
    self.organizer = organizer
    self.startsAtMs = startsAtMs
    self.status = status
    self.title = title
  }
}

public struct EventWrite: Codable, Hashable, Sendable {
  public var fields: EventStoredFields
  public var remove: [EventRemovableField]

  public init(fields: EventStoredFields, remove: [EventRemovableField]) {
    self.fields = fields
    self.remove = remove
  }
}

public struct EventWriteInput: Codable, Hashable, Sendable {
  public var coverImage: String?
  public var coverImageAlt: String?
  public var description: String?
  public var endsAtMs: Int?
  public var location: String?
  public var organizer: String?
  public var startsAtMs: Int
  public var status: EventStatus
  public var title: String

  public init(coverImage: String? = nil, coverImageAlt: String? = nil, description: String? = nil, endsAtMs: Int? = nil, location: String? = nil, organizer: String? = nil, startsAtMs: Int, status: EventStatus, title: String) {
    self.coverImage = coverImage
    self.coverImageAlt = coverImageAlt
    self.description = description
    self.endsAtMs = endsAtMs
    self.location = location
    self.organizer = organizer
    self.startsAtMs = startsAtMs
    self.status = status
    self.title = title
  }
}

public struct FormLeadRoutingOptionsItem: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

public struct FormStatusOptionsItem: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum FunctionComparator: String, Codable, CaseIterable, Hashable, Sendable {
  case notEqual = "!="
  case lessThan = "<"
  case lessThanOrEqual = "<="
  case equal = "=="
  case greaterThan = ">"
  case greaterThanOrEqual = ">="
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct FunctionConditionalOperation: Codable, Hashable, Sendable {
  public var `if`: FunctionConditionalOperationIf?
  public var otherwise: [FunctionSetOperation]?
  public var then: [FunctionSetOperation]?

  public init(`if`: FunctionConditionalOperationIf? = nil, otherwise: [FunctionSetOperation]? = nil, then: [FunctionSetOperation]? = nil) {
    self.if = `if`
    self.otherwise = otherwise
    self.then = then
  }
}

public struct FunctionConditionalOperationIf: Codable, Hashable, Sendable {
  public var comparator: FunctionComparator
  public var left: String
  public var right: String

  public init(comparator: FunctionComparator, left: String, right: String) {
    self.comparator = comparator
    self.left = left
    self.right = right
  }
}

public struct FunctionSetOperation: Codable, Hashable, Sendable {
  public var expression: String?
  public var set: String?
  public var workflow: String?

  public init(expression: String? = nil, set: String? = nil, workflow: String? = nil) {
    self.expression = expression
    self.set = set
    self.workflow = workflow
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum FunctionValueType: String, Codable, CaseIterable, Hashable, Sendable {
  case boolean = "boolean"
  case number = "number"
  case text = "text"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostEventDeclaration: Codable, Hashable, Sendable {
  public var label: String
  public var order: Double
  public var payloadKeys: [String]?
  public var pluginId: String?
  public var recipientActed: Bool?
  public var type: String

  public init(label: String, order: Double, payloadKeys: [String]? = nil, pluginId: String? = nil, recipientActed: Bool? = nil, type: String) {
    self.label = label
    self.order = order
    self.payloadKeys = payloadKeys
    self.pluginId = pluginId
    self.recipientActed = recipientActed
    self.type = type
  }
}

public struct HostFunction: Codable, Hashable, Sendable {
  public var name: String?
  public var operations: [FunctionConditionalOperation]?
  public var parameters: [HostFunctionParameter]?
  public var returnValue: String?
  public var variables: [HostFunctionVariable]?

  public init(name: String? = nil, operations: [FunctionConditionalOperation]? = nil, parameters: [HostFunctionParameter]? = nil, returnValue: String? = nil, variables: [HostFunctionVariable]? = nil) {
    self.name = name
    self.operations = operations
    self.parameters = parameters
    self.returnValue = returnValue
    self.variables = variables
  }
}

public struct HostFunctionParameter: Codable, Hashable, Sendable {
  public var defaultValue: String?
  public var label: String?
  public var name: String?
  public var options: [HostFunctionParameterOption]?
  public var required: Bool?
  public var type: FunctionValueType?

  public init(defaultValue: String? = nil, label: String? = nil, name: String? = nil, options: [HostFunctionParameterOption]? = nil, required: Bool? = nil, type: FunctionValueType? = nil) {
    self.defaultValue = defaultValue
    self.label = label
    self.name = name
    self.options = options
    self.required = required
    self.type = type
  }
}

public struct HostFunctionParameterOption: Codable, Hashable, Sendable {
  public var label: String?
  public var value: String

  public init(label: String? = nil, value: String) {
    self.label = label
    self.value = value
  }
}

public struct HostFunctionVariable: Codable, Hashable, Sendable {
  public var name: String?
  public var type: FunctionValueType?

  public init(name: String? = nil, type: FunctionValueType? = nil) {
    self.name = name
    self.type = type
  }
}

public struct HostOrder: Codable, Hashable, Sendable {
  public var amountCents: Double?
  public var billingAddress: OrderAddress?
  public var buyerNotifications: [String: HostOrderBuyerNotificationsValue]?
  public var cashierId: String?
  public var channel: OrderChannel?
  public var channelSource: OrderChannelSource?
  public var checkoutSessionId: String?
  public var couponCode: String?
  public var createdAtMs: Double?
  public var credits: [OrderCredit]?
  public var customerEmail: String?
  public var customerId: String?
  public var customerName: String?
  public var customerPhone: String?
  public var customerRecord: HostOrderCustomerRecord?
  public var discountBy: String?
  public var discountPct: Double?
  public var dispute: OrderDispute?
  public var extras: [OrderExtra]?
  public var feeCents: Double?
  public var fulfillments: [OrderFulfillment]?
  public var invoiceId: String?
  public var lineItems: [OrderLineItem]?
  public var locationId: String?
  public var note: String?
  public var number: Double?
  public var paymentIntentId: String?
  public var paymentLinkUrl: String?
  public var paymentRisk: PaymentRisk?
  public var payments: [OrderPayment]?
  public var productId: String?
  public var receiptRequest: HostOrderReceiptRequest?
  public var refundedCents: Double?
  public var refundedLineItemIds: [Double]?
  public var registerId: String?
  public var restockCheck: OrderRestockCheck?
  public var shiftId: String?
  public var shippingAddress: OrderAddress?
  public var status: OrderStatus?
  public var subscriptionId: String?
  public var taxMode: HostOrderTaxMode?
  public var timeline: [OrderTimelineEvent]?
  public var totals: OrderTotals?
  public var unresolvedLines: [OrderUnresolvedLine]?

  public init(amountCents: Double? = nil, billingAddress: OrderAddress? = nil, buyerNotifications: [String: HostOrderBuyerNotificationsValue]? = nil, cashierId: String? = nil, channel: OrderChannel? = nil, channelSource: OrderChannelSource? = nil, checkoutSessionId: String? = nil, couponCode: String? = nil, createdAtMs: Double? = nil, credits: [OrderCredit]? = nil, customerEmail: String? = nil, customerId: String? = nil, customerName: String? = nil, customerPhone: String? = nil, customerRecord: HostOrderCustomerRecord? = nil, discountBy: String? = nil, discountPct: Double? = nil, dispute: OrderDispute? = nil, extras: [OrderExtra]? = nil, feeCents: Double? = nil, fulfillments: [OrderFulfillment]? = nil, invoiceId: String? = nil, lineItems: [OrderLineItem]? = nil, locationId: String? = nil, note: String? = nil, number: Double? = nil, paymentIntentId: String? = nil, paymentLinkUrl: String? = nil, paymentRisk: PaymentRisk? = nil, payments: [OrderPayment]? = nil, productId: String? = nil, receiptRequest: HostOrderReceiptRequest? = nil, refundedCents: Double? = nil, refundedLineItemIds: [Double]? = nil, registerId: String? = nil, restockCheck: OrderRestockCheck? = nil, shiftId: String? = nil, shippingAddress: OrderAddress? = nil, status: OrderStatus? = nil, subscriptionId: String? = nil, taxMode: HostOrderTaxMode? = nil, timeline: [OrderTimelineEvent]? = nil, totals: OrderTotals? = nil, unresolvedLines: [OrderUnresolvedLine]? = nil) {
    self.amountCents = amountCents
    self.billingAddress = billingAddress
    self.buyerNotifications = buyerNotifications
    self.cashierId = cashierId
    self.channel = channel
    self.channelSource = channelSource
    self.checkoutSessionId = checkoutSessionId
    self.couponCode = couponCode
    self.createdAtMs = createdAtMs
    self.credits = credits
    self.customerEmail = customerEmail
    self.customerId = customerId
    self.customerName = customerName
    self.customerPhone = customerPhone
    self.customerRecord = customerRecord
    self.discountBy = discountBy
    self.discountPct = discountPct
    self.dispute = dispute
    self.extras = extras
    self.feeCents = feeCents
    self.fulfillments = fulfillments
    self.invoiceId = invoiceId
    self.lineItems = lineItems
    self.locationId = locationId
    self.note = note
    self.number = number
    self.paymentIntentId = paymentIntentId
    self.paymentLinkUrl = paymentLinkUrl
    self.paymentRisk = paymentRisk
    self.payments = payments
    self.productId = productId
    self.receiptRequest = receiptRequest
    self.refundedCents = refundedCents
    self.refundedLineItemIds = refundedLineItemIds
    self.registerId = registerId
    self.restockCheck = restockCheck
    self.shiftId = shiftId
    self.shippingAddress = shippingAddress
    self.status = status
    self.subscriptionId = subscriptionId
    self.taxMode = taxMode
    self.timeline = timeline
    self.totals = totals
    self.unresolvedLines = unresolvedLines
  }
}

public struct HostOrderBuyerNotificationsValue: Codable, Hashable, Sendable {
  public var atMs: Double
  public var channel: HostOrderBuyerNotificationsValueChannel
  public var state: HostOrderBuyerNotificationsValueState

  public init(atMs: Double, channel: HostOrderBuyerNotificationsValueChannel, state: HostOrderBuyerNotificationsValueState) {
    self.atMs = atMs
    self.channel = channel
    self.state = state
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderBuyerNotificationsValueChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case email = "email"
  case sms = "sms"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderBuyerNotificationsValueState: String, Codable, CaseIterable, Hashable, Sendable {
  case sending = "sending"
  case sent = "sent"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostOrderCustomerRecord: Codable, Hashable, Sendable {
  public var id: String
  public var kind: String

  public init(id: String, kind: String) {
    self.id = id
    self.kind = kind
  }
}

public struct HostOrderReceiptRequest: Codable, Hashable, Sendable {
  public var atMs: Double
  public var channel: PosReceiptChannel
  public var to: String?

  public init(atMs: Double, channel: PosReceiptChannel, to: String? = nil) {
    self.atMs = atMs
    self.channel = channel
    self.to = to
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostOrderTaxMode: String, Codable, CaseIterable, Hashable, Sendable {
  case manual = "manual"
  case none = "none"
  case stripeAutomatic = "stripe-automatic"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostProduct: Codable, Hashable, Sendable {
  public var categoryIds: [String]?
  public var channel: ProductChannelFacts?
  public var collectionIds: [String]?
  public var createdAtMs: Double?
  public var description: String?
  public var digitalFiles: [HostProductDigitalFilesItem]?
  public var downloadLimit: Double?
  public var gatedVideos: [HostProductGatedVideosItem]?
  public var giftCard: Bool?
  public var imageUrl: String?
  public var inventory: Double?
  public var lowStockThreshold: Double?
  public var mediaUrls: [String]?
  public var modifierGroups: [ProductModifierGroup]?
  public var name: String?
  public var options: [ProductOption]?
  public var oversellPolicy: HostProductOversellPolicy?
  public var posQuickKey: Bool?
  public var priceUsd: Double?
  public var relatedProductIds: [String]?
  public var seo: HostProductSeo?
  public var shipping: ProductShippingFacts?
  public var slug: String?
  public var status: ProductStatus?
  public var subscription: HostProductSubscription?
  public var subscriptionOptional: Bool?
  public var supplierId: String?
  public var tags: [String]?
  public var taxExempt: Bool?
  public var type: ProductType?
  public var updatedAtMs: Double?
  public var variants: [ProductVariant]?

  public init(categoryIds: [String]? = nil, channel: ProductChannelFacts? = nil, collectionIds: [String]? = nil, createdAtMs: Double? = nil, description: String? = nil, digitalFiles: [HostProductDigitalFilesItem]? = nil, downloadLimit: Double? = nil, gatedVideos: [HostProductGatedVideosItem]? = nil, giftCard: Bool? = nil, imageUrl: String? = nil, inventory: Double? = nil, lowStockThreshold: Double? = nil, mediaUrls: [String]? = nil, modifierGroups: [ProductModifierGroup]? = nil, name: String? = nil, options: [ProductOption]? = nil, oversellPolicy: HostProductOversellPolicy? = nil, posQuickKey: Bool? = nil, priceUsd: Double? = nil, relatedProductIds: [String]? = nil, seo: HostProductSeo? = nil, shipping: ProductShippingFacts? = nil, slug: String? = nil, status: ProductStatus? = nil, subscription: HostProductSubscription? = nil, subscriptionOptional: Bool? = nil, supplierId: String? = nil, tags: [String]? = nil, taxExempt: Bool? = nil, type: ProductType? = nil, updatedAtMs: Double? = nil, variants: [ProductVariant]? = nil) {
    self.categoryIds = categoryIds
    self.channel = channel
    self.collectionIds = collectionIds
    self.createdAtMs = createdAtMs
    self.description = description
    self.digitalFiles = digitalFiles
    self.downloadLimit = downloadLimit
    self.gatedVideos = gatedVideos
    self.giftCard = giftCard
    self.imageUrl = imageUrl
    self.inventory = inventory
    self.lowStockThreshold = lowStockThreshold
    self.mediaUrls = mediaUrls
    self.modifierGroups = modifierGroups
    self.name = name
    self.options = options
    self.oversellPolicy = oversellPolicy
    self.posQuickKey = posQuickKey
    self.priceUsd = priceUsd
    self.relatedProductIds = relatedProductIds
    self.seo = seo
    self.shipping = shipping
    self.slug = slug
    self.status = status
    self.subscription = subscription
    self.subscriptionOptional = subscriptionOptional
    self.supplierId = supplierId
    self.tags = tags
    self.taxExempt = taxExempt
    self.type = type
    self.updatedAtMs = updatedAtMs
    self.variants = variants
  }
}

public struct HostProductDigitalFilesItem: Codable, Hashable, Sendable {
  public var fileName: String
  public var url: String
  public var version: String?

  public init(fileName: String, url: String, version: String? = nil) {
    self.fileName = fileName
    self.url = url
    self.version = version
  }
}

public struct HostProductGatedVideosItem: Codable, Hashable, Sendable {
  public var title: String?
  public var url: String

  public init(title: String? = nil, url: String) {
    self.title = title
    self.url = url
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostProductOversellPolicy: String, Codable, CaseIterable, Hashable, Sendable {
  case backorder = "backorder"
  case deny = "deny"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostProductSeo: Codable, Hashable, Sendable {
  public var description: String?
  public var imageUrl: String?
  public var title: String?

  public init(description: String? = nil, imageUrl: String? = nil, title: String? = nil) {
    self.description = description
    self.imageUrl = imageUrl
    self.title = title
  }
}

public struct HostProductSubscription: Codable, Hashable, Sendable {
  public var interval: HostProductSubscriptionInterval
  public var trialDays: Double?

  public init(interval: HostProductSubscriptionInterval, trialDays: Double? = nil) {
    self.interval = interval
    self.trialDays = trialDays
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostProductSubscriptionInterval: String, Codable, CaseIterable, Hashable, Sendable {
  case month = "month"
  case year = "year"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct HostRedirect: Codable, Hashable, Sendable {
  public var destination: String
  public var enabled: Bool?
  public var externalDestinationApprovedBy: String?
  public var kind: HostRedirectKind?
  public var priority: Double?
  public var source: String
  public var statusCode: Int

  public init(destination: String, enabled: Bool? = nil, externalDestinationApprovedBy: String? = nil, kind: HostRedirectKind? = nil, priority: Double? = nil, source: String, statusCode: Int) {
    self.destination = destination
    self.enabled = enabled
    self.externalDestinationApprovedBy = externalDestinationApprovedBy
    self.kind = kind
    self.priority = priority
    self.source = source
    self.statusCode = statusCode
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostRedirectKind: String, Codable, CaseIterable, Hashable, Sendable {
  case exact = "exact"
  case prefix = "prefix"
  case regex = "regex"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum HostVariableType: String, Codable, CaseIterable, Hashable, Sendable {
  case boolean = "boolean"
  case collection = "collection"
  case date = "date"
  case dictionary = "dictionary"
  case number = "number"
  case text = "text"
  case time = "time"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum InstallTarget: String, Codable, CaseIterable, Hashable, Sendable {
  case host = "host"
  case org = "org"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListFilterClause: Codable, Hashable, Sendable {
  public var field: String
  public var label: String?
  public var op: String
  public var value: String

  public init(field: String, label: String? = nil, op: String, value: String) {
    self.field = field
    self.label = label
    self.op = op
    self.value = value
  }
}

public struct ListFilterField: Codable, Hashable, Sendable {
  public var column: String
  public var containsOrderBy: String?
  public var containsOrderDirection: ListFilterFieldContainsOrderDirection?
  public var keysOf: Bool?
  public var kind: ListFilterKind
  public var lowerPath: String?
  public var operators: [String]?
  public var path: String
  public var presence: ListFilterFieldPresence?
  public var reversedPath: String?
  public var rowPath: String?
  public var storedAs: ListFilterFieldStoredAs?
  public var tokensPath: String?
  public var verbatimTokens: Bool?
  public var windowOnly: Bool?

  public init(column: String, containsOrderBy: String? = nil, containsOrderDirection: ListFilterFieldContainsOrderDirection? = nil, keysOf: Bool? = nil, kind: ListFilterKind, lowerPath: String? = nil, operators: [String]? = nil, path: String, presence: ListFilterFieldPresence? = nil, reversedPath: String? = nil, rowPath: String? = nil, storedAs: ListFilterFieldStoredAs? = nil, tokensPath: String? = nil, verbatimTokens: Bool? = nil, windowOnly: Bool? = nil) {
    self.column = column
    self.containsOrderBy = containsOrderBy
    self.containsOrderDirection = containsOrderDirection
    self.keysOf = keysOf
    self.kind = kind
    self.lowerPath = lowerPath
    self.operators = operators
    self.path = path
    self.presence = presence
    self.reversedPath = reversedPath
    self.rowPath = rowPath
    self.storedAs = storedAs
    self.tokensPath = tokensPath
    self.verbatimTokens = verbatimTokens
    self.windowOnly = windowOnly
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldContainsOrderDirection: String, Codable, CaseIterable, Hashable, Sendable {
  case asc = "asc"
  case desc = "desc"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldPresence: String, Codable, CaseIterable, Hashable, Sendable {
  case always = "always"
  case nullable = "nullable"
  case sparse = "sparse"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterFieldStoredAs: String, Codable, CaseIterable, Hashable, Sendable {
  case millis = "millis"
  case timestamp = "timestamp"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListFilterKind: String, Codable, CaseIterable, Hashable, Sendable {
  case boolean = "boolean"
  case date = "date"
  case exact = "exact"
  case id = "id"
  case number = "number"
  case text = "text"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListFilterOption: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

public struct ListFilterRequest: Codable, Hashable, Sendable {
  public var field: String
  public var op: String
  public var value: String

  public init(field: String, op: String, value: String) {
    self.field = field
    self.op = op
    self.value = value
  }
}

public struct ListQueryDeclaration: Codable, Hashable, Sendable {
  public var fields: [ListFilterField]
  public var keys: [String: [String]]?
  public var search: ListQueryDeclarationSearch?
  public var sorts: [ListQuerySort]

  public init(fields: [ListFilterField], keys: [String: [String]]? = nil, search: ListQueryDeclarationSearch? = nil, sorts: [ListQuerySort]) {
    self.fields = fields
    self.keys = keys
    self.search = search
    self.sorts = sorts
  }
}

public struct ListQueryDeclarationSearch: Codable, Hashable, Sendable {
  public var scoped: ListQueryDeclarationSearchScoped?
  public var tokensPath: String

  public init(scoped: ListQueryDeclarationSearchScoped? = nil, tokensPath: String) {
    self.scoped = scoped
    self.tokensPath = tokensPath
  }
}

public struct ListQueryDeclarationSearchScoped: Codable, Hashable, Sendable {
  public var join: String
  public var tokensPath: String

  public init(join: String, tokensPath: String) {
    self.join = join
    self.tokensPath = tokensPath
  }
}

public struct ListQueryFilter: Codable, Hashable, Sendable {
  public var op: ListQueryOp
  public var path: String
  public var value: ContractJSON

  public init(op: ListQueryOp, path: String, value: ContractJSON) {
    self.op = op
    self.path = path
    self.value = value
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListQueryOp: String, Codable, CaseIterable, Hashable, Sendable {
  case notEqual = "!="
  case lessThan = "<"
  case lessThanOrEqual = "<="
  case equal = "=="
  case greaterThan = ">"
  case greaterThanOrEqual = ">="
  case arrayContains = "array-contains"
  case arrayContainsAny = "array-contains-any"
  case `in` = "in"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListQueryPlan: Codable, Hashable, Sendable {
  public var filters: [ListQueryFilter]
  public var notices: [String]
  public var orderBy: ListQuerySort
  public var refused: [ListQueryRefusal]
  public var searched: String?
  public var served: [ListFilterRequest]
  public var sortFallback: ListQueryPlanSortFallback?

  public init(filters: [ListQueryFilter], notices: [String], orderBy: ListQuerySort, refused: [ListQueryRefusal], searched: String? = nil, served: [ListFilterRequest], sortFallback: ListQueryPlanSortFallback? = nil) {
    self.filters = filters
    self.notices = notices
    self.orderBy = orderBy
    self.refused = refused
    self.searched = searched
    self.served = served
    self.sortFallback = sortFallback
  }
}

public struct ListQueryPlanSortFallback: Codable, Hashable, Sendable {
  public var asked: ListQuerySort
  public var reason: ListQueryPlanSortFallbackReason

  public init(asked: ListQuerySort, reason: ListQueryPlanSortFallbackReason) {
    self.asked = asked
    self.reason = reason
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListQueryPlanSortFallbackReason: String, Codable, CaseIterable, Hashable, Sendable {
  case alone = "alone"
  case range = "range"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ListQueryRefusal: Codable, Hashable, Sendable {
  public var clause: ContractJSON
  public var reason: String

  public init(clause: ContractJSON, reason: String) {
    self.clause = clause
    self.reason = reason
  }
}

public struct ListQueryRequest: Codable, Hashable, Sendable {
  public var base: [ListQueryFilter]?
  public var clauses: [ListFilterRequest]
  public var search: [String]?
  public var sort: ListQuerySort?

  public init(base: [ListQueryFilter]? = nil, clauses: [ListFilterRequest], search: [String]? = nil, sort: ListQuerySort? = nil) {
    self.base = base
    self.clauses = clauses
    self.search = search
    self.sort = sort
  }
}

public struct ListQuerySort: Codable, Hashable, Sendable {
  public var alone: Bool?
  public var column: String?
  public var direction: ListQuerySortDirection
  public var label: String?
  public var path: String

  public init(alone: Bool? = nil, column: String? = nil, direction: ListQuerySortDirection, label: String? = nil, path: String) {
    self.alone = alone
    self.column = column
    self.direction = direction
    self.label = label
    self.path = path
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ListQuerySortDirection: String, Codable, CaseIterable, Hashable, Sendable {
  case asc = "asc"
  case desc = "desc"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct LocalBusinessTypeOptionsItem: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

public struct ManagedBooking: Codable, Hashable, Sendable {
  public var checkedInAtMs: Double?
  public var endsAtMs: Double?
  public var expiresAtMs: Double?
  public var paidAmountCents: Double?
  public var refundedCents: Double?
  public var startsAtMs: Double?
  public var status: String?

  public init(checkedInAtMs: Double? = nil, endsAtMs: Double? = nil, expiresAtMs: Double? = nil, paidAmountCents: Double? = nil, refundedCents: Double? = nil, startsAtMs: Double? = nil, status: String? = nil) {
    self.checkedInAtMs = checkedInAtMs
    self.endsAtMs = endsAtMs
    self.expiresAtMs = expiresAtMs
    self.paidAmountCents = paidAmountCents
    self.refundedCents = refundedCents
    self.startsAtMs = startsAtMs
    self.status = status
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MediaKind: String, Codable, CaseIterable, Hashable, Sendable {
  case document = "document"
  case image = "image"
  case pdf = "pdf"
  case video = "video"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MediaSort: String, Codable, CaseIterable, Hashable, Sendable {
  case name = "name"
  case newest = "newest"
  case oldest = "oldest"
  case size = "size"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct MobileDevice: Codable, Hashable, Sendable {
  public var apnsEnvironment: ApnsEnvironment?
  public var app: MobileDeviceApp
  public var appVersion: String?
  public var lastSeen: ContractJSON?
  public var platform: MobileDevicePlatform
  public var token: String
  public var transport: MobilePushTransport

  public init(apnsEnvironment: ApnsEnvironment? = nil, app: MobileDeviceApp, appVersion: String? = nil, lastSeen: ContractJSON? = nil, platform: MobileDevicePlatform, token: String, transport: MobilePushTransport) {
    self.apnsEnvironment = apnsEnvironment
    self.app = app
    self.appVersion = appVersion
    self.lastSeen = lastSeen
    self.platform = platform
    self.token = token
    self.transport = transport
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobileDeviceApp: String, Codable, CaseIterable, Hashable, Sendable {
  case aglyn = "aglyn"
  case aglynPos = "aglyn-pos"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobileDevicePlatform: String, Codable, CaseIterable, Hashable, Sendable {
  case android = "android"
  case ios = "ios"
  case macos = "macos"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct MobilePushData: Codable, Hashable, Sendable {
  public var hostId: String?
  public var link: String?
  public var orgId: String?
  public var type: String

  public init(hostId: String? = nil, link: String? = nil, orgId: String? = nil, type: String) {
    self.hostId = hostId
    self.link = link
    self.orgId = orgId
    self.type = type
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum MobilePushTransport: String, Codable, CaseIterable, Hashable, Sendable {
  case apns = "apns"
  case fcm = "fcm"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ModifierSelection: Codable, Hashable, Sendable {
  public var groupId: String
  public var optionId: String

  public init(groupId: String, optionId: String) {
    self.groupId = groupId
    self.optionId = optionId
  }
}

public struct OrderAddress: Codable, Hashable, Sendable {
  public var city: String?
  public var country: String?
  public var line1: String?
  public var line2: String?
  public var name: String?
  public var phone: String?
  public var postalCode: String?
  public var state: String?

  public init(city: String? = nil, country: String? = nil, line1: String? = nil, line2: String? = nil, name: String? = nil, phone: String? = nil, postalCode: String? = nil, state: String? = nil) {
    self.city = city
    self.country = country
    self.line1 = line1
    self.line2 = line2
    self.name = name
    self.phone = phone
    self.postalCode = postalCode
    self.state = state
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case draft = "draft"
  case marketplace = "marketplace"
  case online = "online"
  case pos = "pos"
  case subscription = "subscription"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderChannelSource: Codable, Hashable, Sendable {
  public var channelId: String
  public var channelLabel: String
  public var currency: String
  public var externalOrderId: String
  public var externalRef: String
  public var fees: [OrderChannelSourceFeesItem]?
  public var feesTotalCents: Double?
  public var handoff: OrderChannelSourceHandoff?
  public var lines: [OrderChannelSourceLinesItem]
  public var refundIds: [String]?
  public var taxRemittedByChannel: Bool

  public init(channelId: String, channelLabel: String, currency: String, externalOrderId: String, externalRef: String, fees: [OrderChannelSourceFeesItem]? = nil, feesTotalCents: Double? = nil, handoff: OrderChannelSourceHandoff? = nil, lines: [OrderChannelSourceLinesItem], refundIds: [String]? = nil, taxRemittedByChannel: Bool) {
    self.channelId = channelId
    self.channelLabel = channelLabel
    self.currency = currency
    self.externalOrderId = externalOrderId
    self.externalRef = externalRef
    self.fees = fees
    self.feesTotalCents = feesTotalCents
    self.handoff = handoff
    self.lines = lines
    self.refundIds = refundIds
    self.taxRemittedByChannel = taxRemittedByChannel
  }
}

public struct OrderChannelSourceFeesItem: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var label: String

  public init(amountCents: Double, label: String) {
    self.amountCents = amountCents
    self.label = label
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderChannelSourceHandoff: String, Codable, CaseIterable, Hashable, Sendable {
  case courier = "courier"
  case ship = "ship"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderChannelSourceLinesItem: Codable, Hashable, Sendable {
  public var externalLineId: String
  public var lineIndex: Double

  public init(externalLineId: String, lineIndex: Double) {
    self.externalLineId = externalLineId
    self.lineIndex = lineIndex
  }
}

public struct OrderCredit: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var appliedAs: OrderCreditAppliedAs
  public var key: String
  public var label: String
  public var last4: String
  public var pluginId: String
  public var providerId: String
  public var reference: String

  public init(amountCents: Double, appliedAs: OrderCreditAppliedAs, key: String, label: String, last4: String, pluginId: String, providerId: String, reference: String) {
    self.amountCents = amountCents
    self.appliedAs = appliedAs
    self.key = key
    self.label = label
    self.last4 = last4
    self.pluginId = pluginId
    self.providerId = providerId
    self.reference = reference
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderCreditAppliedAs: String, Codable, CaseIterable, Hashable, Sendable {
  case discount = "discount"
  case tender = "tender"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderDispute: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var closedAtMs: Double?
  public var evidenceDueByMs: Double?
  public var id: String
  public var openedAtMs: Double
  public var outcome: String?
  public var reason: String?
  public var reversedCents: Double?
  public var reversedTransferCents: Double?
  public var status: String
  public var transferReversalId: String?

  public init(amountCents: Double, closedAtMs: Double? = nil, evidenceDueByMs: Double? = nil, id: String, openedAtMs: Double, outcome: String? = nil, reason: String? = nil, reversedCents: Double? = nil, reversedTransferCents: Double? = nil, status: String, transferReversalId: String? = nil) {
    self.amountCents = amountCents
    self.closedAtMs = closedAtMs
    self.evidenceDueByMs = evidenceDueByMs
    self.id = id
    self.openedAtMs = openedAtMs
    self.outcome = outcome
    self.reason = reason
    self.reversedCents = reversedCents
    self.reversedTransferCents = reversedTransferCents
    self.status = status
    self.transferReversalId = transferReversalId
  }
}

public struct OrderExtra: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var id: String
  public var key: String
  public var label: String
  public var pluginId: String
  public var quoteRef: String?

  public init(amountCents: Double, id: String, key: String, label: String, pluginId: String, quoteRef: String? = nil) {
    self.amountCents = amountCents
    self.id = id
    self.key = key
    self.label = label
    self.pluginId = pluginId
    self.quoteRef = quoteRef
  }
}

public struct OrderFulfillment: Codable, Hashable, Sendable {
  public var atMs: Double
  public var cancelledAtMs: Double?
  public var carrier: String?
  public var id: String
  public var labelRef: String?
  public var labelUrl: String?
  public var lineItemIds: [Double]
  public var lines: [OrderFulfillmentLinesItem]?
  public var notify: Bool?
  public var status: OrderFulfillmentStatus?
  public var trackingNumber: String?
  public var trackingStatus: String?
  public var trackingStatusAtMs: Double?
  public var trackingUrl: String?
  public var updatedAtMs: Double?

  public init(atMs: Double, cancelledAtMs: Double? = nil, carrier: String? = nil, id: String, labelRef: String? = nil, labelUrl: String? = nil, lineItemIds: [Double], lines: [OrderFulfillmentLinesItem]? = nil, notify: Bool? = nil, status: OrderFulfillmentStatus? = nil, trackingNumber: String? = nil, trackingStatus: String? = nil, trackingStatusAtMs: Double? = nil, trackingUrl: String? = nil, updatedAtMs: Double? = nil) {
    self.atMs = atMs
    self.cancelledAtMs = cancelledAtMs
    self.carrier = carrier
    self.id = id
    self.labelRef = labelRef
    self.labelUrl = labelUrl
    self.lineItemIds = lineItemIds
    self.lines = lines
    self.notify = notify
    self.status = status
    self.trackingNumber = trackingNumber
    self.trackingStatus = trackingStatus
    self.trackingStatusAtMs = trackingStatusAtMs
    self.trackingUrl = trackingUrl
    self.updatedAtMs = updatedAtMs
  }
}

public struct OrderFulfillmentLinesItem: Codable, Hashable, Sendable {
  public var lineItemId: Double
  public var quantity: Double

  public init(lineItemId: Double, quantity: Double) {
    self.lineItemId = lineItemId
    self.quantity = quantity
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderFulfillmentStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case active = "active"
  case cancelled = "cancelled"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderLineItem: Codable, Hashable, Sendable {
  public var fulfillmentId: String?
  public var modifiers: [OrderLineModifier]?
  public var name: String
  public var productId: String
  public var productType: ProductType?
  public var quantity: Double
  public var sku: String?
  public var supplierId: String?
  public var unitAmountCents: Double
  public var variantId: String?
  public var variantLabel: String?

  public init(fulfillmentId: String? = nil, modifiers: [OrderLineModifier]? = nil, name: String, productId: String, productType: ProductType? = nil, quantity: Double, sku: String? = nil, supplierId: String? = nil, unitAmountCents: Double, variantId: String? = nil, variantLabel: String? = nil) {
    self.fulfillmentId = fulfillmentId
    self.modifiers = modifiers
    self.name = name
    self.productId = productId
    self.productType = productType
    self.quantity = quantity
    self.sku = sku
    self.supplierId = supplierId
    self.unitAmountCents = unitAmountCents
    self.variantId = variantId
    self.variantLabel = variantLabel
  }
}

public struct OrderLineModifier: Codable, Hashable, Sendable {
  public var group: String
  public var groupId: String
  public var name: String
  public var optionId: String
  public var priceCents: Double

  public init(group: String, groupId: String, name: String, optionId: String, priceCents: Double) {
    self.group = group
    self.groupId = groupId
    self.name = name
    self.optionId = optionId
    self.priceCents = priceCents
  }
}

public struct OrderPayment: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var atMs: Double
  public var cardBrand: String?
  public var cashierId: String?
  public var cashTenderedCents: Double?
  public var changeCents: Double?
  public var checkoutSessionId: String?
  public var checkoutUrl: String?
  public var creditLabel: String?
  public var creditProviderId: String?
  public var creditReference: String?
  public var failureMessage: String?
  public var feeCents: Double?
  public var folioAtMs: Double?
  public var giftCardId: String?
  public var id: String
  public var last4: String?
  public var livemode: Bool?
  public var method: OrderPaymentMethod
  public var paymentIntentId: String?
  public var readerId: String?
  public var reservationId: String?
  public var settledAtMs: Double?
  public var status: OrderPaymentStatus
  public var takeFeeCents: Double?
  public var tipCents: Double?

  public init(amountCents: Double, atMs: Double, cardBrand: String? = nil, cashierId: String? = nil, cashTenderedCents: Double? = nil, changeCents: Double? = nil, checkoutSessionId: String? = nil, checkoutUrl: String? = nil, creditLabel: String? = nil, creditProviderId: String? = nil, creditReference: String? = nil, failureMessage: String? = nil, feeCents: Double? = nil, folioAtMs: Double? = nil, giftCardId: String? = nil, id: String, last4: String? = nil, livemode: Bool? = nil, method: OrderPaymentMethod, paymentIntentId: String? = nil, readerId: String? = nil, reservationId: String? = nil, settledAtMs: Double? = nil, status: OrderPaymentStatus, takeFeeCents: Double? = nil, tipCents: Double? = nil) {
    self.amountCents = amountCents
    self.atMs = atMs
    self.cardBrand = cardBrand
    self.cashierId = cashierId
    self.cashTenderedCents = cashTenderedCents
    self.changeCents = changeCents
    self.checkoutSessionId = checkoutSessionId
    self.checkoutUrl = checkoutUrl
    self.creditLabel = creditLabel
    self.creditProviderId = creditProviderId
    self.creditReference = creditReference
    self.failureMessage = failureMessage
    self.feeCents = feeCents
    self.folioAtMs = folioAtMs
    self.giftCardId = giftCardId
    self.id = id
    self.last4 = last4
    self.livemode = livemode
    self.method = method
    self.paymentIntentId = paymentIntentId
    self.readerId = readerId
    self.reservationId = reservationId
    self.settledAtMs = settledAtMs
    self.status = status
    self.takeFeeCents = takeFeeCents
    self.tipCents = tipCents
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderPaymentMethod: String, Codable, CaseIterable, Hashable, Sendable {
  case cardKeyed = "card_keyed"
  case cardLink = "card_link"
  case cardPresent = "card_present"
  case cash = "cash"
  case credit = "credit"
  case folio = "folio"
  case giftCard = "gift_card"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderPaymentStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case canceled = "canceled"
  case failed = "failed"
  case pending = "pending"
  case reversed = "reversed"
  case succeeded = "succeeded"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderRestockCheck: Codable, Hashable, Sendable {
  public var flaggedAtMs: Double
  public var fullyReversed: Bool
  public var kind: OrderRestockCheckKind
  public var lines: [OrderRestockLine]
  public var resolution: OrderRestockCheckResolution?
  public var resolvedAtMs: Double?
  public var resolvedBy: String?
  public var units: Double

  public init(flaggedAtMs: Double, fullyReversed: Bool, kind: OrderRestockCheckKind, lines: [OrderRestockLine], resolution: OrderRestockCheckResolution? = nil, resolvedAtMs: Double? = nil, resolvedBy: String? = nil, units: Double) {
    self.flaggedAtMs = flaggedAtMs
    self.fullyReversed = fullyReversed
    self.kind = kind
    self.lines = lines
    self.resolution = resolution
    self.resolvedAtMs = resolvedAtMs
    self.resolvedBy = resolvedBy
    self.units = units
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderRestockCheckKind: String, Codable, CaseIterable, Hashable, Sendable {
  case chargeback = "chargeback"
  case refund = "refund"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderRestockCheckResolution: String, Codable, CaseIterable, Hashable, Sendable {
  case dismissed = "dismissed"
  case restocked = "restocked"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderRestockLine: Codable, Hashable, Sendable {
  public var lineIndex: Double?
  public var name: String?
  public var productId: String
  public var quantity: Double
  public var variantId: String
  public var variantLabel: String?

  public init(lineIndex: Double? = nil, name: String? = nil, productId: String, quantity: Double, variantId: String, variantLabel: String? = nil) {
    self.lineIndex = lineIndex
    self.name = name
    self.productId = productId
    self.quantity = quantity
    self.variantId = variantId
    self.variantLabel = variantLabel
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case cancelled = "cancelled"
  case delivered = "delivered"
  case fulfilled = "fulfilled"
  case paid = "paid"
  case partiallyFulfilled = "partially_fulfilled"
  case pending = "pending"
  case refunded = "refunded"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum OrderStatusColorValue: String, Codable, CaseIterable, Hashable, Sendable {
  case `default` = "default"
  case error = "error"
  case info = "info"
  case success = "success"
  case warning = "warning"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct OrderTimelineEvent: Codable, Hashable, Sendable {
  public var atMs: Double
  public var detail: String?
  public var event: String

  public init(atMs: Double, detail: String? = nil, event: String) {
    self.atMs = atMs
    self.detail = detail
    self.event = event
  }
}

public struct OrderTotals: Codable, Hashable, Sendable {
  public var discountCents: Double?
  public var extrasCents: Double?
  public var feeCents: Double?
  public var itemsCents: Double?
  public var shippingCents: Double?
  public var taxCents: Double?
  public var tipCents: Double?
  public var totalCents: Double?

  public init(discountCents: Double? = nil, extrasCents: Double? = nil, feeCents: Double? = nil, itemsCents: Double? = nil, shippingCents: Double? = nil, taxCents: Double? = nil, tipCents: Double? = nil, totalCents: Double? = nil) {
    self.discountCents = discountCents
    self.extrasCents = extrasCents
    self.feeCents = feeCents
    self.itemsCents = itemsCents
    self.shippingCents = shippingCents
    self.taxCents = taxCents
    self.tipCents = tipCents
    self.totalCents = totalCents
  }
}

public struct OrderUnresolvedLine: Codable, Hashable, Sendable {
  public var productId: String
  public var quantity: Double
  public var variantId: String?

  public init(productId: String, quantity: Double, variantId: String? = nil) {
    self.productId = productId
    self.quantity = quantity
    self.variantId = variantId
  }
}

public struct PaymentRisk: Codable, Hashable, Sendable {
  public var latestAtMs: Double
  public var latestKind: PaymentRiskSignalKind
  public var signals: [PaymentRiskSignal]

  public init(latestAtMs: Double, latestKind: PaymentRiskSignalKind, signals: [PaymentRiskSignal]) {
    self.latestAtMs = latestAtMs
    self.latestKind = latestKind
    self.signals = signals
  }
}

public struct PaymentRiskSignal: Codable, Hashable, Sendable {
  public var atMs: Double
  public var detail: String?
  public var kind: PaymentRiskSignalKind
  public var outcome: String?
  public var stripeObjectId: String

  public init(atMs: Double, detail: String? = nil, kind: PaymentRiskSignalKind, outcome: String? = nil, stripeObjectId: String) {
    self.atMs = atMs
    self.detail = detail
    self.kind = kind
    self.outcome = outcome
    self.stripeObjectId = stripeObjectId
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum PaymentRiskSignalKind: String, Codable, CaseIterable, Hashable, Sendable {
  case dispute = "dispute"
  case earlyFraudWarning = "early-fraud-warning"
  case radarReview = "radar-review"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum PosReceiptChannel: String, Codable, CaseIterable, Hashable, Sendable {
  case email = "email"
  case none = "none"
  case print = "print"
  case sms = "sms"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ProductChannelFacts: Codable, Hashable, Sendable {
  public var brand: String?
  public var condition: ProductChannelFactsCondition?
  public var googleProductCategory: String?
  public var gtin: String?
  public var mpn: String?

  public init(brand: String? = nil, condition: ProductChannelFactsCondition? = nil, googleProductCategory: String? = nil, gtin: String? = nil, mpn: String? = nil) {
    self.brand = brand
    self.condition = condition
    self.googleProductCategory = googleProductCategory
    self.gtin = gtin
    self.mpn = mpn
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ProductChannelFactsCondition: String, Codable, CaseIterable, Hashable, Sendable {
  case new = "new"
  case refurbished = "refurbished"
  case used = "used"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ProductModifierGroup: Codable, Hashable, Sendable {
  public var id: String
  public var max: Double
  public var min: Double
  public var name: String
  public var options: [ProductModifierOption]

  public init(id: String, max: Double, min: Double, name: String, options: [ProductModifierOption]) {
    self.id = id
    self.max = max
    self.min = min
    self.name = name
    self.options = options
  }
}

public struct ProductModifierOption: Codable, Hashable, Sendable {
  public var id: String
  public var name: String
  public var priceCents: Double

  public init(id: String, name: String, priceCents: Double) {
    self.id = id
    self.name = name
    self.priceCents = priceCents
  }
}

public struct ProductOption: Codable, Hashable, Sendable {
  public var name: String
  public var values: [String]

  public init(name: String, values: [String]) {
    self.name = name
    self.values = values
  }
}

public struct ProductShippingFacts: Codable, Hashable, Sendable {
  public var heightCm: Double?
  public var hsCode: String?
  public var lengthCm: Double?
  public var originCountry: String?
  public var widthCm: Double?

  public init(heightCm: Double? = nil, hsCode: String? = nil, lengthCm: Double? = nil, originCountry: String? = nil, widthCm: Double? = nil) {
    self.heightCm = heightCm
    self.hsCode = hsCode
    self.lengthCm = lengthCm
    self.originCountry = originCountry
    self.widthCm = widthCm
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ProductStatus: String, Codable, CaseIterable, Hashable, Sendable {
  case active = "active"
  case archived = "archived"
  case draft = "draft"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum ProductType: String, Codable, CaseIterable, Hashable, Sendable {
  case digital = "digital"
  case physical = "physical"
  case service = "service"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct ProductVariant: Codable, Hashable, Sendable {
  public var barcode: String?
  public var compareAtPriceUsd: Double?
  public var id: String?
  public var imageUrl: String?
  public var inventory: Double?
  public var inventoryByLocation: [String: Double]?
  public var options: [String: String]?
  public var priceUsd: Double?
  public var sku: String?
  public var weightGrams: Double?

  public init(barcode: String? = nil, compareAtPriceUsd: Double? = nil, id: String? = nil, imageUrl: String? = nil, inventory: Double? = nil, inventoryByLocation: [String: Double]? = nil, options: [String: String]? = nil, priceUsd: Double? = nil, sku: String? = nil, weightGrams: Double? = nil) {
    self.barcode = barcode
    self.compareAtPriceUsd = compareAtPriceUsd
    self.id = id
    self.imageUrl = imageUrl
    self.inventory = inventory
    self.inventoryByLocation = inventoryByLocation
    self.options = options
    self.priceUsd = priceUsd
    self.sku = sku
    self.weightGrams = weightGrams
  }
}

public struct ReceiptData: Codable, Hashable, Sendable {
  public var banner: String?
  public var barcode: String?
  public var cashierName: String?
  public var changeCents: Double?
  public var createdAtMs: Double
  public var currency: String
  public var discountCents: Double?
  public var footer: String?
  public var lines: [ReceiptLine]
  public var orderId: String?
  public var orderNumber: String
  public var refundedCents: Double?
  public var registerName: String?
  public var shippingCents: Double?
  public var storeLines: [String]?
  public var storeName: String
  public var subtotalCents: Double
  public var taxCents: Double?
  public var tenders: [ReceiptTender]?
  public var timeZone: String?
  public var tipCents: Double?
  public var totalCents: Double

  public init(banner: String? = nil, barcode: String? = nil, cashierName: String? = nil, changeCents: Double? = nil, createdAtMs: Double, currency: String, discountCents: Double? = nil, footer: String? = nil, lines: [ReceiptLine], orderId: String? = nil, orderNumber: String, refundedCents: Double? = nil, registerName: String? = nil, shippingCents: Double? = nil, storeLines: [String]? = nil, storeName: String, subtotalCents: Double, taxCents: Double? = nil, tenders: [ReceiptTender]? = nil, timeZone: String? = nil, tipCents: Double? = nil, totalCents: Double) {
    self.banner = banner
    self.barcode = barcode
    self.cashierName = cashierName
    self.changeCents = changeCents
    self.createdAtMs = createdAtMs
    self.currency = currency
    self.discountCents = discountCents
    self.footer = footer
    self.lines = lines
    self.orderId = orderId
    self.orderNumber = orderNumber
    self.refundedCents = refundedCents
    self.registerName = registerName
    self.shippingCents = shippingCents
    self.storeLines = storeLines
    self.storeName = storeName
    self.subtotalCents = subtotalCents
    self.taxCents = taxCents
    self.tenders = tenders
    self.timeZone = timeZone
    self.tipCents = tipCents
    self.totalCents = totalCents
  }
}

public struct ReceiptLine: Codable, Hashable, Sendable {
  public var detail: String?
  public var name: String
  public var quantity: Double
  public var totalCents: Double
  public var unitCents: Double

  public init(detail: String? = nil, name: String, quantity: Double, totalCents: Double, unitCents: Double) {
    self.detail = detail
    self.name = name
    self.quantity = quantity
    self.totalCents = totalCents
    self.unitCents = unitCents
  }
}

public struct ReceiptTender: Codable, Hashable, Sendable {
  public var amountCents: Double
  public var label: String

  public init(amountCents: Double, label: String) {
    self.amountCents = amountCents
    self.label = label
  }
}

public struct ScreenTrafficRow: Codable, Hashable, Sendable {
  public var devices: [String: Double]
  public var referrers: [String: Double]
  public var screenId: String
  public var total: Int

  public init(devices: [String: Double], referrers: [String: Double], screenId: String, total: Int) {
    self.devices = devices
    self.referrers = referrers
    self.screenId = screenId
    self.total = total
  }
}

public struct SiteFilterOptions: Codable, Hashable, Sendable {
  public var hasCustomDomain: [SiteFilterOptionsHasCustomDomainItem]

  public init(hasCustomDomain: [SiteFilterOptionsHasCustomDomainItem]) {
    self.hasCustomDomain = hasCustomDomain
  }
}

public struct SiteFilterOptionsHasCustomDomainItem: Codable, Hashable, Sendable {
  public var label: String
  public var value: String

  public init(label: String, value: String) {
    self.label = label
    self.value = value
  }
}

/// A newer server value decodes as `.unknown`, so an older app never fails on it.
public enum TenantEmailControl: String, Codable, CaseIterable, Hashable, Sendable {
  case besigner = "besigner"
  case external = "external"
  case fixed = "fixed"
  case unknown = ""

  public init(from decoder: Decoder) throws {
    let raw = try decoder.singleValueContainer().decode(String.self)
    self = Self(rawValue: raw) ?? .unknown
  }
}

public struct TenantEmailEntry: Codable, Hashable, Sendable {
  public var authoredIn: String?
  public var control: TenantEmailControl?
  public var defaultSubject: String?
  public var description: String?
  public var footerReason: String?
  public var key: String?
  public var name: String?
  public var plugin: String?
  public var pluginId: String?
  public var requiresFeature: String?

  public init(authoredIn: String? = nil, control: TenantEmailControl? = nil, defaultSubject: String? = nil, description: String? = nil, footerReason: String? = nil, key: String? = nil, name: String? = nil, plugin: String? = nil, pluginId: String? = nil, requiresFeature: String? = nil) {
    self.authoredIn = authoredIn
    self.control = control
    self.defaultSubject = defaultSubject
    self.description = description
    self.footerReason = footerReason
    self.key = key
    self.name = name
    self.plugin = plugin
    self.pluginId = pluginId
    self.requiresFeature = requiresFeature
  }
}

public struct WhereUsedDependent: Codable, Hashable, Sendable {
  public var id: String?
  public var name: String?
  public var type: String?
  public var versionId: String?
  public var via: [BindingRefVia]?

  public init(id: String? = nil, name: String? = nil, type: String? = nil, versionId: String? = nil, via: [BindingRefVia]? = nil) {
    self.id = id
    self.name = name
    self.type = type
    self.versionId = versionId
    self.via = via
  }
}

public struct WhereUsedResult: Codable, Hashable, Sendable {
  public var dependents: [WhereUsedDependent]?
  public var legacyCount: Int?
  public var total: Int?

  public init(dependents: [WhereUsedDependent]? = nil, legacyCount: Int? = nil, total: Int? = nil) {
    self.dependents = dependents
    self.legacyCount = legacyCount
    self.total = total
  }
}

/// The values in contracts.generated.json, keyed as the TypeScript exports are.
public struct ContractValues: Codable, Hashable, Sendable {
  public let areaServedMax: Int
  public let artifactTypeLabels: [String: String]
  public let bookingFieldAsks: [BookingFieldAsk]
  public let bookingInPersonMaxCents: Int
  public let bookingInPersonMinCents: Int
  public let bookingMaxDaysAhead: Int
  public let bookingPriceDisplays: [BookingPriceDisplay]
  public let bookingPriceLabels: [String: String]
  public let bookingServiceDescriptionMax: Int
  public let bookingServiceNameMax: Int
  public let bookingStateLabels: [String: String]
  public let bookingWeekdays: [String]
  public let browseSorts: [String: ListQuerySort]
  public let componentListQuery: ListQueryDeclaration
  public let contentSchemaTypeDefault: ContentSchemaType
  public let contentSchemaTypeOptions: [ContentSchemaTypeOptionsItem]
  public let crossMaxDepth: Int
  public let datasetAuthorableFieldTypes: [DatasetFieldType]
  public let datasetFieldTypeLabels: [String: String]
  public let datasetFieldTypes: [DatasetFieldType]
  public let datasetFilterPrefixMax: Int
  public let defaultTitlePattern: String
  public let entryListFilterHeaders: [String: String]
  public let entryListQuery: ListQueryDeclaration
  public let entryStatusOptions: [EntryStatusOptionsItem]
  public let eventCoverAltMaxLength: Int
  public let eventDefaultDurationMs: Double
  public let eventDescriptionMaxLength: Int
  public let eventLocationMaxLength: Int
  public let eventOrganizerMaxLength: Int
  public let eventTitleMaxLength: Int
  public let formInUse: ListQueryFilter
  public let formLeadRoutingOptions: [FormLeadRoutingOptionsItem]
  public let formListFilterHeaders: [String: String]
  public let formListQuery: ListQueryDeclaration
  public let formScopedSubmissionListQuery: ListQueryDeclaration
  public let formStatusOptions: [FormStatusOptionsItem]
  public let functionBuiltinNames: [String]
  public let functionMaxOperations: Int
  public let heldLicenceQuery: ListQueryDeclaration
  public let hostEvents: [HostEventDeclaration]
  public let hostVariableTypeLabels: [String: String]
  public let installTargets: [String: [InstallTarget]]
  public let layoutListQuery: ListQueryDeclaration
  public let listQueryDisjunctions: Int
  public let listQueryIdPath: String
  public let listingCategories: [String]
  public let localBusinessTypeOptions: [LocalBusinessTypeOptionsItem]
  public let marketplaceBrowseQuery: ListQueryDeclaration
  public let mediaAltMaxLength: Int
  public let mediaAltOptions: [ListFilterOption]
  public let mediaDisjunctionLimit: Int
  public let mediaFilterHeaders: [String: String]
  public let mediaFolderMaxDepth: Int
  public let mediaFolderNameMaxLength: Int
  public let mediaKinds: [MediaKind]
  public let mediaListQuery: ListQueryDeclaration
  public let mediaOrientationOptions: [ListFilterOption]
  public let mediaScopedSearchNotice: String
  public let mediaSortLabels: [String: String]
  public let mediaSortOrder: [String: ListQuerySort]
  public let mediaSorts: [MediaSort]
  public let mediaTagMaxCount: Int
  public let mediaTagMaxLength: Int
  public let mediaTypeOptions: [ListFilterOption]
  public let nameTokenLimit: Int
  public let nameTokenMaxPrefix: Int
  public let openDisputeClause: ListFilterClause
  public let orderChannelLabels: [String: String]
  public let orderChannelOptions: [ListFilterOption]
  public let orderDisputeOptions: [ListFilterOption]
  public let orderListHeaders: [String: String]
  public let orderListQuery: ListQueryDeclaration
  public let orderListSelectFields: [String]
  public let orderStatusColor: [String: OrderStatusColorValue]
  public let orderStatusLabels: [String: String]
  public let orderStatusOptions: [ListFilterOption]
  public let orgSubmissionListQuery: ListQueryDeclaration
  public let paymentAcceptedMaxLength: Int
  public let priceRangeMaxLength: Int
  public let productListBase: [ListQueryFilter]
  public let productListHeaders: [String: String]
  public let productListOptions: [String: [ListFilterOption]]
  public let productListQuery: ListQueryDeclaration
  public let productListSelectFields: [String]
  public let reminderWindowEndHours: Int
  public let reminderWindowStartHours: Int
  public let scopedSearchJoin: String
  public let searchEngineVerificationLabels: [String: String]
  public let searchEngineVerificationMetaNames: [String: String]
  public let siteCardsPageSize: Int
  public let siteFilterHeaders: [String: String]
  public let siteFilterOptions: SiteFilterOptions
  public let siteListDeclaration: ListQueryDeclaration
  public let submissionFilterHeaders: [String: String]
  public let submissionListQuery: ListQueryDeclaration
  public let submissionReadOptions: [ListFilterOption]
  public let templateKindOptions: [ListFilterOption]
  public let templateListBase: [ListQueryFilter]
  public let templateListQuery: ListQueryDeclaration
  public let tenantEmailCollection: String
  public let tenantEmails: [TenantEmailEntry]
  public let workflowMaxSteps: Int

  enum CodingKeys: String, CodingKey {
    case areaServedMax = "AREA_SERVED_MAX"
    case artifactTypeLabels = "ARTIFACT_TYPE_LABELS"
    case bookingFieldAsks = "BOOKING_FIELD_ASKS"
    case bookingInPersonMaxCents = "BOOKING_IN_PERSON_MAX_CENTS"
    case bookingInPersonMinCents = "BOOKING_IN_PERSON_MIN_CENTS"
    case bookingMaxDaysAhead = "BOOKING_MAX_DAYS_AHEAD"
    case bookingPriceDisplays = "BOOKING_PRICE_DISPLAYS"
    case bookingPriceLabels = "BOOKING_PRICE_LABELS"
    case bookingServiceDescriptionMax = "BOOKING_SERVICE_DESCRIPTION_MAX"
    case bookingServiceNameMax = "BOOKING_SERVICE_NAME_MAX"
    case bookingStateLabels = "BOOKING_STATE_LABELS"
    case bookingWeekdays = "BOOKING_WEEKDAYS"
    case browseSorts = "BROWSE_SORTS"
    case componentListQuery = "COMPONENT_LIST_QUERY"
    case contentSchemaTypeDefault = "CONTENT_SCHEMA_TYPE_DEFAULT"
    case contentSchemaTypeOptions = "CONTENT_SCHEMA_TYPE_OPTIONS"
    case crossMaxDepth = "CROSS_MAX_DEPTH"
    case datasetAuthorableFieldTypes = "DATASET_AUTHORABLE_FIELD_TYPES"
    case datasetFieldTypeLabels = "DATASET_FIELD_TYPE_LABELS"
    case datasetFieldTypes = "DATASET_FIELD_TYPES"
    case datasetFilterPrefixMax = "DATASET_FILTER_PREFIX_MAX"
    case defaultTitlePattern = "DEFAULT_TITLE_PATTERN"
    case entryListFilterHeaders = "ENTRY_LIST_FILTER_HEADERS"
    case entryListQuery = "ENTRY_LIST_QUERY"
    case entryStatusOptions = "ENTRY_STATUS_OPTIONS"
    case eventCoverAltMaxLength = "EVENT_COVER_ALT_MAX_LENGTH"
    case eventDefaultDurationMs = "EVENT_DEFAULT_DURATION_MS"
    case eventDescriptionMaxLength = "EVENT_DESCRIPTION_MAX_LENGTH"
    case eventLocationMaxLength = "EVENT_LOCATION_MAX_LENGTH"
    case eventOrganizerMaxLength = "EVENT_ORGANIZER_MAX_LENGTH"
    case eventTitleMaxLength = "EVENT_TITLE_MAX_LENGTH"
    case formInUse = "FORM_IN_USE"
    case formLeadRoutingOptions = "FORM_LEAD_ROUTING_OPTIONS"
    case formListFilterHeaders = "FORM_LIST_FILTER_HEADERS"
    case formListQuery = "FORM_LIST_QUERY"
    case formScopedSubmissionListQuery = "FORM_SCOPED_SUBMISSION_LIST_QUERY"
    case formStatusOptions = "FORM_STATUS_OPTIONS"
    case functionBuiltinNames = "FUNCTION_BUILTIN_NAMES"
    case functionMaxOperations = "FUNCTION_MAX_OPERATIONS"
    case heldLicenceQuery = "HELD_LICENCE_QUERY"
    case hostEvents = "HOST_EVENTS"
    case hostVariableTypeLabels = "HOST_VARIABLE_TYPE_LABELS"
    case installTargets = "INSTALL_TARGETS"
    case layoutListQuery = "LAYOUT_LIST_QUERY"
    case listQueryDisjunctions = "LIST_QUERY_DISJUNCTIONS"
    case listQueryIdPath = "LIST_QUERY_ID_PATH"
    case listingCategories = "LISTING_CATEGORIES"
    case localBusinessTypeOptions = "LOCAL_BUSINESS_TYPE_OPTIONS"
    case marketplaceBrowseQuery = "MARKETPLACE_BROWSE_QUERY"
    case mediaAltMaxLength = "MEDIA_ALT_MAX_LENGTH"
    case mediaAltOptions = "MEDIA_ALT_OPTIONS"
    case mediaDisjunctionLimit = "MEDIA_DISJUNCTION_LIMIT"
    case mediaFilterHeaders = "MEDIA_FILTER_HEADERS"
    case mediaFolderMaxDepth = "MEDIA_FOLDER_MAX_DEPTH"
    case mediaFolderNameMaxLength = "MEDIA_FOLDER_NAME_MAX_LENGTH"
    case mediaKinds = "MEDIA_KINDS"
    case mediaListQuery = "MEDIA_LIST_QUERY"
    case mediaOrientationOptions = "MEDIA_ORIENTATION_OPTIONS"
    case mediaScopedSearchNotice = "MEDIA_SCOPED_SEARCH_NOTICE"
    case mediaSortLabels = "MEDIA_SORT_LABELS"
    case mediaSortOrder = "MEDIA_SORT_ORDER"
    case mediaSorts = "MEDIA_SORTS"
    case mediaTagMaxCount = "MEDIA_TAG_MAX_COUNT"
    case mediaTagMaxLength = "MEDIA_TAG_MAX_LENGTH"
    case mediaTypeOptions = "MEDIA_TYPE_OPTIONS"
    case nameTokenLimit = "NAME_TOKEN_LIMIT"
    case nameTokenMaxPrefix = "NAME_TOKEN_MAX_PREFIX"
    case openDisputeClause = "OPEN_DISPUTE_CLAUSE"
    case orderChannelLabels = "ORDER_CHANNEL_LABELS"
    case orderChannelOptions = "ORDER_CHANNEL_OPTIONS"
    case orderDisputeOptions = "ORDER_DISPUTE_OPTIONS"
    case orderListHeaders = "ORDER_LIST_HEADERS"
    case orderListQuery = "ORDER_LIST_QUERY"
    case orderListSelectFields = "ORDER_LIST_SELECT_FIELDS"
    case orderStatusColor = "ORDER_STATUS_COLOR"
    case orderStatusLabels = "ORDER_STATUS_LABELS"
    case orderStatusOptions = "ORDER_STATUS_OPTIONS"
    case orgSubmissionListQuery = "ORG_SUBMISSION_LIST_QUERY"
    case paymentAcceptedMaxLength = "PAYMENT_ACCEPTED_MAX_LENGTH"
    case priceRangeMaxLength = "PRICE_RANGE_MAX_LENGTH"
    case productListBase = "PRODUCT_LIST_BASE"
    case productListHeaders = "PRODUCT_LIST_HEADERS"
    case productListOptions = "PRODUCT_LIST_OPTIONS"
    case productListQuery = "PRODUCT_LIST_QUERY"
    case productListSelectFields = "PRODUCT_LIST_SELECT_FIELDS"
    case reminderWindowEndHours = "REMINDER_WINDOW_END_HOURS"
    case reminderWindowStartHours = "REMINDER_WINDOW_START_HOURS"
    case scopedSearchJoin = "SCOPED_SEARCH_JOIN"
    case searchEngineVerificationLabels = "SEARCH_ENGINE_VERIFICATION_LABELS"
    case searchEngineVerificationMetaNames = "SEARCH_ENGINE_VERIFICATION_META_NAMES"
    case siteCardsPageSize = "SITE_CARDS_PAGE_SIZE"
    case siteFilterHeaders = "SITE_FILTER_HEADERS"
    case siteFilterOptions = "SITE_FILTER_OPTIONS"
    case siteListDeclaration = "SITE_LIST_DECLARATION"
    case submissionFilterHeaders = "SUBMISSION_FILTER_HEADERS"
    case submissionListQuery = "SUBMISSION_LIST_QUERY"
    case submissionReadOptions = "SUBMISSION_READ_OPTIONS"
    case templateKindOptions = "TEMPLATE_KIND_OPTIONS"
    case templateListBase = "TEMPLATE_LIST_BASE"
    case templateListQuery = "TEMPLATE_LIST_QUERY"
    case tenantEmailCollection = "TENANT_EMAIL_COLLECTION"
    case tenantEmails = "TENANT_EMAILS"
    case workflowMaxSteps = "WORKFLOW_MAX_STEPS"
  }
}
