// GENERATED by tools/scripts/generate-native-contracts.mjs — do not edit.
// Source: tools/scripts/native-contracts.json over the pure TypeScript modules it names.

package com.aglyn.contracts

import kotlinx.serialization.KSerializer
import kotlinx.serialization.SerialName
import kotlinx.serialization.Serializable
import kotlinx.serialization.descriptors.PrimitiveKind
import kotlinx.serialization.descriptors.PrimitiveSerialDescriptor
import kotlinx.serialization.descriptors.SerialDescriptor
import kotlinx.serialization.encoding.Decoder
import kotlinx.serialization.encoding.Encoder
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonElement

/** Encodes an enum as its raw string, and decodes an unknown one as [fallback]. */
open class RawEnumSerializer<E : Enum<E>>(
    name: String,
    private val values: List<E>,
    private val fallback: E,
    private val raw: (E) -> String,
) : KSerializer<E> {
    override val descriptor: SerialDescriptor = PrimitiveSerialDescriptor(name, PrimitiveKind.STRING)
    override fun serialize(encoder: Encoder, value: E) = encoder.encodeString(raw(value))
    override fun deserialize(decoder: Decoder): E {
        val value = decoder.decodeString()
        return values.firstOrNull { it != fallback && raw(it) == value } ?: fallback
    }
}

@Serializable
data class AccountPushSettings(
    val account: Map<String, AccountPushSettingsAccountValue>? = null,
    val accountTypes: Map<String, AccountPushSettingsAccountTypesValue>? = null,
)

@Serializable
data class AccountPushSettingsAccountTypesValue(
    val console: Boolean? = null,
    val push: Boolean? = null,
)

@Serializable
data class AccountPushSettingsAccountValue(
    val console: Boolean? = null,
    val push: Boolean? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ApnsEnvironmentSerializer::class)
enum class ApnsEnvironment(val raw: String) {
    PRODUCTION("production"),
    SANDBOX("sandbox"),
    UNKNOWN(""),
}

internal object ApnsEnvironmentSerializer :
    RawEnumSerializer<ApnsEnvironment>("com.aglyn.contracts.ApnsEnvironment", ApnsEnvironment.entries, ApnsEnvironment.UNKNOWN, { it.raw })

@Serializable
data class BookingActions(
    val cancel: Boolean,
    val checkIn: Boolean,
    val refundCents: Long,
    val reschedule: Boolean,
    val undoCheckIn: Boolean,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = BookingFieldAskSerializer::class)
enum class BookingFieldAsk(val raw: String) {
    OFF("off"),
    OPTIONAL("optional"),
    REQUIRED("required"),
    UNKNOWN(""),
}

internal object BookingFieldAskSerializer :
    RawEnumSerializer<BookingFieldAsk>("com.aglyn.contracts.BookingFieldAsk", BookingFieldAsk.entries, BookingFieldAsk.UNKNOWN, { it.raw })

@Serializable
data class BookingInPersonPayment(
    val amountCents: Long,
    val attempt: String? = null,
    val feeCents: Long,
    val paidAtMs: Long? = null,
    val paymentIntentId: String,
    val serviceCents: Long,
    val startedAtMs: Long,
    val startedBy: String,
    val status: BookingInPersonPaymentStatus,
    val taxCents: Long,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = BookingInPersonPaymentStatusSerializer::class)
enum class BookingInPersonPaymentStatus(val raw: String) {
    CANCELED("canceled"),
    PAID("paid"),
    PENDING("pending"),
    UNKNOWN(""),
}

internal object BookingInPersonPaymentStatusSerializer :
    RawEnumSerializer<BookingInPersonPaymentStatus>("com.aglyn.contracts.BookingInPersonPaymentStatus", BookingInPersonPaymentStatus.entries, BookingInPersonPaymentStatus.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = BookingInPersonStateSerializer::class)
enum class BookingInPersonState(val raw: String) {
    AWAITING_ONLINE("awaiting-online"),
    CANCELED("canceled"),
    COLLECTING("collecting"),
    PAID("paid"),
    PAYABLE("payable"),
    UNKNOWN(""),
}

internal object BookingInPersonStateSerializer :
    RawEnumSerializer<BookingInPersonState>("com.aglyn.contracts.BookingInPersonState", BookingInPersonState.entries, BookingInPersonState.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = BookingPriceDisplaySerializer::class)
enum class BookingPriceDisplay(val raw: String) {
    CONTACT("contact"),
    ESTIMATE("estimate"),
    FIXED("fixed"),
    VARIES("varies"),
    UNKNOWN(""),
}

internal object BookingPriceDisplaySerializer :
    RawEnumSerializer<BookingPriceDisplay>("com.aglyn.contracts.BookingPriceDisplay", BookingPriceDisplay.entries, BookingPriceDisplay.UNKNOWN, { it.raw })

@Serializable
data class BookingServiceDraft(
    val askAddress: BookingFieldAsk,
    val askPhone: BookingFieldAsk,
    val crmFollowUpTask: Boolean,
    val crmMeetingActivity: Boolean,
    val description: String,
    val durationMinutes: String,
    val name: String,
    val priceDisplay: BookingPriceDisplay,
    val priceUsd: String,
    val timezone: String,
    val windowText: List<String>,
)

@Serializable
data class BookingServiceFields(
    val askAddress: BookingFieldAsk,
    val askPhone: BookingFieldAsk,
    val crmFollowUpTask: Boolean,
    val crmMeetingActivity: Boolean,
    val description: String,
    val durationMinutes: Long,
    val name: String,
    val priceDisplay: BookingPriceDisplay,
    val priceUsd: Long,
    val timezone: String,
    val windows: Map<String, List<BookingWindow>>,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = BookingStateSerializer::class)
enum class BookingState(val raw: String) {
    CANCELED("canceled"),
    CONFIRMED("confirmed"),
    EXPIRED("expired"),
    PENDING_PAYMENT("pendingPayment"),
    UNKNOWN(""),
}

internal object BookingStateSerializer :
    RawEnumSerializer<BookingState>("com.aglyn.contracts.BookingState", BookingState.entries, BookingState.UNKNOWN, { it.raw })

@Serializable
data class BookingWindow(
    val end: Long,
    val start: Long,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ContentSchemaTypeSerializer::class)
enum class ContentSchemaType(val raw: String) {
    ARTICLE("Article"),
    BLOG_POSTING("BlogPosting"),
    NEWS_ARTICLE("NewsArticle"),
    TECH_ARTICLE("TechArticle"),
    UNKNOWN(""),
}

internal object ContentSchemaTypeSerializer :
    RawEnumSerializer<ContentSchemaType>("com.aglyn.contracts.ContentSchemaType", ContentSchemaType.entries, ContentSchemaType.UNKNOWN, { it.raw })

@Serializable
data class ContentSchemaTypeOptionsItem(
    val description: String,
    val label: String,
    val value: String,
)

@Serializable
data class CrmDealStage(
    val forecastCategory: CrmForecastCategory? = null,
    val id: String,
    val kind: CrmDealStatus,
    val name: String,
    val order: Double,
    val probability: Double,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = CrmDealStatusSerializer::class)
enum class CrmDealStatus(val raw: String) {
    LOST("lost"),
    OPEN("open"),
    WON("won"),
    UNKNOWN(""),
}

internal object CrmDealStatusSerializer :
    RawEnumSerializer<CrmDealStatus>("com.aglyn.contracts.CrmDealStatus", CrmDealStatus.entries, CrmDealStatus.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = CrmForecastCategorySerializer::class)
enum class CrmForecastCategory(val raw: String) {
    BEST_CASE("bestCase"),
    CLOSED("closed"),
    COMMIT("commit"),
    OMITTED("omitted"),
    PIPELINE("pipeline"),
    UNKNOWN(""),
}

internal object CrmForecastCategorySerializer :
    RawEnumSerializer<CrmForecastCategory>("com.aglyn.contracts.CrmForecastCategory", CrmForecastCategory.entries, CrmForecastCategory.UNKNOWN, { it.raw })

@Serializable
data class DeviceSplitEntry(
    val count: Long,
    val device: String,
    val percent: Long,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = DropOffActionSerializer::class)
enum class DropOffAction(val raw: String) {
    EMAIL("email"),
    TASK("task"),
    UNKNOWN(""),
}

internal object DropOffActionSerializer :
    RawEnumSerializer<DropOffAction>("com.aglyn.contracts.DropOffAction", DropOffAction.entries, DropOffAction.UNKNOWN, { it.raw })

@Serializable
data class EntryStatusOptionsItem(
    val label: String,
    val value: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = EventRemovableFieldSerializer::class)
enum class EventRemovableField(val raw: String) {
    COVER_IMAGE("coverImage"),
    COVER_IMAGE_ALT("coverImageAlt"),
    DESCRIPTION("description"),
    LOCATION("location"),
    ORGANIZER("organizer"),
    UNKNOWN(""),
}

internal object EventRemovableFieldSerializer :
    RawEnumSerializer<EventRemovableField>("com.aglyn.contracts.EventRemovableField", EventRemovableField.entries, EventRemovableField.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = EventStatusSerializer::class)
enum class EventStatus(val raw: String) {
    DRAFT("draft"),
    PUBLISHED("published"),
    UNKNOWN(""),
}

internal object EventStatusSerializer :
    RawEnumSerializer<EventStatus>("com.aglyn.contracts.EventStatus", EventStatus.entries, EventStatus.UNKNOWN, { it.raw })

@Serializable
data class EventStoredFields(
    val coverImage: String? = null,
    val coverImageAlt: String? = null,
    val description: String? = null,
    val endsAtMs: Long,
    val location: String? = null,
    val organizer: String? = null,
    val startsAtMs: Long,
    val status: EventStatus,
    val title: String,
)

@Serializable
data class EventWrite(
    val fields: EventStoredFields,
    val remove: List<EventRemovableField>,
)

@Serializable
data class EventWriteInput(
    val coverImage: String? = null,
    val coverImageAlt: String? = null,
    val description: String? = null,
    val endsAtMs: Long? = null,
    val location: String? = null,
    val organizer: String? = null,
    val startsAtMs: Long,
    val status: EventStatus,
    val title: String,
)

@Serializable
data class FormLeadRoutingOptionsItem(
    val label: String,
    val value: String,
)

@Serializable
data class FormStatusOptionsItem(
    val label: String,
    val value: String,
)

@Serializable
data class FunnelDefinition(
    val name: String,
    val steps: List<FunnelStep>,
)

@Serializable
data class FunnelInventory(
    val forms: List<FunnelInventoryItem>,
    val overlays: List<FunnelInventoryItem>,
    val pages: List<String>,
    val products: List<FunnelInventoryItem>,
    val services: List<FunnelInventoryItem>,
)

@Serializable
data class FunnelInventoryItem(
    val id: String,
    val name: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = FunnelPageMatchSerializer::class)
enum class FunnelPageMatch(val raw: String) {
    EXACT("exact"),
    PREFIX("prefix"),
    UNKNOWN(""),
}

internal object FunnelPageMatchSerializer :
    RawEnumSerializer<FunnelPageMatch>("com.aglyn.contracts.FunnelPageMatch", FunnelPageMatch.entries, FunnelPageMatch.UNKNOWN, { it.raw })

@Serializable
data class FunnelResult(
    val capped: Boolean,
    val completed: Long,
    val computedAt: Long,
    val entered: Long,
    val from: String,
    val funnelId: String,
    val journeysRead: Long,
    val overall: Double? = null,
    val sources: List<FunnelSourceResult>,
    val steps: List<FunnelStepResult>,
    val to: String,
)

@Serializable
data class FunnelSourceResult(
    val completed: Long,
    val conversion: Double? = null,
    val entered: Long,
    val source: String,
)

@Serializable
data class FunnelStep(
    val key: String,
    val label: String? = null,
    val match: FunnelPageMatch? = null,
    val type: SiteJourneyStepType,
)

@Serializable
data class FunnelStepResult(
    val dropOff: Long,
    val fromPrevious: Double? = null,
    val fromStart: Double? = null,
    val index: Long,
    val label: String,
    val medianMsFromPrevious: Double? = null,
    val visitors: Long,
)

@Serializable
data class HostEventDeclaration(
    val label: String,
    val order: Double,
    val payloadKeys: List<String>? = null,
    val pluginId: String? = null,
    val recipientActed: Boolean? = null,
    val type: String,
)

@Serializable
data class HostOrder(
    val amountCents: Double? = null,
    val billingAddress: OrderAddress? = null,
    val buyerNotifications: Map<String, HostOrderBuyerNotificationsValue>? = null,
    val cashierId: String? = null,
    val channel: OrderChannel? = null,
    val channelSource: OrderChannelSource? = null,
    val checkoutSessionId: String? = null,
    val couponCode: String? = null,
    val createdAtMs: Double? = null,
    val credits: List<OrderCredit>? = null,
    val customerEmail: String? = null,
    val customerId: String? = null,
    val customerName: String? = null,
    val customerPhone: String? = null,
    val customerRecord: HostOrderCustomerRecord? = null,
    val discountBy: String? = null,
    val discountPct: Double? = null,
    val dispute: OrderDispute? = null,
    val extras: List<OrderExtra>? = null,
    val feeCents: Double? = null,
    val fulfillmentMethod: OrderFulfillmentMethod? = null,
    val fulfillments: List<OrderFulfillment>? = null,
    val invoiceId: String? = null,
    val kioskDeviceId: String? = null,
    val kioskQueuedAtMs: Double? = null,
    val kioskQueueRegisterId: String? = null,
    val lineItems: List<OrderLineItem>? = null,
    val localDelivery: OrderLocalDelivery? = null,
    val locationId: String? = null,
    val note: String? = null,
    val number: Double? = null,
    val offline: PosOfflineOrderStamp? = null,
    val paymentIntentId: String? = null,
    val paymentLinkUrl: String? = null,
    val paymentRisk: PaymentRisk? = null,
    val payments: List<OrderPayment>? = null,
    val pickup: OrderPickup? = null,
    val posSource: String? = null,
    val productId: String? = null,
    val receiptRequest: HostOrderReceiptRequest? = null,
    val refundedCents: Double? = null,
    val refundedLineItemIds: List<Double>? = null,
    val registerId: String? = null,
    val restockCheck: OrderRestockCheck? = null,
    val shiftId: String? = null,
    val shippingAddress: OrderAddress? = null,
    val status: OrderStatus? = null,
    val subscriptionId: String? = null,
    val taxMode: HostOrderTaxMode? = null,
    val timeline: List<OrderTimelineEvent>? = null,
    val totals: OrderTotals? = null,
    val unresolvedLines: List<OrderUnresolvedLine>? = null,
)

@Serializable
data class HostOrderBuyerNotificationsValue(
    val atMs: Double,
    val channel: HostOrderBuyerNotificationsValueChannel,
    val state: HostOrderBuyerNotificationsValueState,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostOrderBuyerNotificationsValueChannelSerializer::class)
enum class HostOrderBuyerNotificationsValueChannel(val raw: String) {
    EMAIL("email"),
    SMS("sms"),
    UNKNOWN(""),
}

internal object HostOrderBuyerNotificationsValueChannelSerializer :
    RawEnumSerializer<HostOrderBuyerNotificationsValueChannel>("com.aglyn.contracts.HostOrderBuyerNotificationsValueChannel", HostOrderBuyerNotificationsValueChannel.entries, HostOrderBuyerNotificationsValueChannel.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostOrderBuyerNotificationsValueStateSerializer::class)
enum class HostOrderBuyerNotificationsValueState(val raw: String) {
    SENDING("sending"),
    SENT("sent"),
    UNKNOWN(""),
}

internal object HostOrderBuyerNotificationsValueStateSerializer :
    RawEnumSerializer<HostOrderBuyerNotificationsValueState>("com.aglyn.contracts.HostOrderBuyerNotificationsValueState", HostOrderBuyerNotificationsValueState.entries, HostOrderBuyerNotificationsValueState.UNKNOWN, { it.raw })

@Serializable
data class HostOrderCustomerRecord(
    val id: String,
    val kind: String,
)

@Serializable
data class HostOrderReceiptRequest(
    val atMs: Double,
    val channel: PosReceiptChannel,
    val to: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostOrderTaxModeSerializer::class)
enum class HostOrderTaxMode(val raw: String) {
    MANUAL("manual"),
    NONE("none"),
    STRIPE_AUTOMATIC("stripe-automatic"),
    UNKNOWN(""),
}

internal object HostOrderTaxModeSerializer :
    RawEnumSerializer<HostOrderTaxMode>("com.aglyn.contracts.HostOrderTaxMode", HostOrderTaxMode.entries, HostOrderTaxMode.UNKNOWN, { it.raw })

@Serializable
data class HostProduct(
    val categoryIds: List<String>? = null,
    val channel: ProductChannelFacts? = null,
    val collectionIds: List<String>? = null,
    val createdAtMs: Double? = null,
    val description: String? = null,
    val digitalFiles: List<HostProductDigitalFilesItem>? = null,
    val downloadLimit: Double? = null,
    val gatedVideos: List<HostProductGatedVideosItem>? = null,
    val giftCard: Boolean? = null,
    val imageUrl: String? = null,
    val inventory: Double? = null,
    val lowStockThreshold: Double? = null,
    val mediaUrls: List<String>? = null,
    val modifierGroups: List<ProductModifierGroup>? = null,
    val name: String? = null,
    val options: List<ProductOption>? = null,
    val oversellPolicy: HostProductOversellPolicy? = null,
    val posQuickKey: Boolean? = null,
    val priceUsd: Double? = null,
    val relatedProductIds: List<String>? = null,
    val seo: HostProductSeo? = null,
    val shipping: ProductShippingFacts? = null,
    val slug: String? = null,
    val status: ProductStatus? = null,
    val subscription: HostProductSubscription? = null,
    val subscriptionOptional: Boolean? = null,
    val supplierId: String? = null,
    val tags: List<String>? = null,
    val taxExempt: Boolean? = null,
    val type: ProductType? = null,
    val updatedAtMs: Double? = null,
    val variants: List<ProductVariant>? = null,
)

@Serializable
data class HostProductDigitalFilesItem(
    val fileName: String,
    val url: String,
    val version: String? = null,
)

@Serializable
data class HostProductGatedVideosItem(
    val title: String? = null,
    val url: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostProductOversellPolicySerializer::class)
enum class HostProductOversellPolicy(val raw: String) {
    BACKORDER("backorder"),
    DENY("deny"),
    UNKNOWN(""),
}

internal object HostProductOversellPolicySerializer :
    RawEnumSerializer<HostProductOversellPolicy>("com.aglyn.contracts.HostProductOversellPolicy", HostProductOversellPolicy.entries, HostProductOversellPolicy.UNKNOWN, { it.raw })

@Serializable
data class HostProductSeo(
    val description: String? = null,
    val imageUrl: String? = null,
    val title: String? = null,
)

@Serializable
data class HostProductSubscription(
    val interval: HostProductSubscriptionInterval,
    val trialDays: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostProductSubscriptionIntervalSerializer::class)
enum class HostProductSubscriptionInterval(val raw: String) {
    MONTH("month"),
    YEAR("year"),
    UNKNOWN(""),
}

internal object HostProductSubscriptionIntervalSerializer :
    RawEnumSerializer<HostProductSubscriptionInterval>("com.aglyn.contracts.HostProductSubscriptionInterval", HostProductSubscriptionInterval.entries, HostProductSubscriptionInterval.UNKNOWN, { it.raw })

@Serializable
data class HostRedirect(
    val destination: String,
    val enabled: Boolean? = null,
    val externalDestinationApprovedBy: String? = null,
    val kind: HostRedirectKind? = null,
    val priority: Double? = null,
    val source: String,
    val statusCode: Long,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = HostRedirectKindSerializer::class)
enum class HostRedirectKind(val raw: String) {
    EXACT("exact"),
    PREFIX("prefix"),
    REGEX("regex"),
    UNKNOWN(""),
}

internal object HostRedirectKindSerializer :
    RawEnumSerializer<HostRedirectKind>("com.aglyn.contracts.HostRedirectKind", HostRedirectKind.entries, HostRedirectKind.UNKNOWN, { it.raw })

@Serializable
data class ListFilterClause(
    val field: String,
    val label: String? = null,
    val op: String,
    val value: String,
)

@Serializable
data class ListFilterField(
    val column: String,
    val containsOrderBy: String? = null,
    val containsOrderDirection: ListFilterFieldContainsOrderDirection? = null,
    val keysOf: Boolean? = null,
    val kind: ListFilterKind,
    val lowerPath: String? = null,
    val operators: List<String>? = null,
    val path: String,
    val presence: ListFilterFieldPresence? = null,
    val reversedPath: String? = null,
    val rowPath: String? = null,
    val storedAs: ListFilterFieldStoredAs? = null,
    val tokensPath: String? = null,
    val verbatimTokens: Boolean? = null,
    val windowOnly: Boolean? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListFilterFieldContainsOrderDirectionSerializer::class)
enum class ListFilterFieldContainsOrderDirection(val raw: String) {
    ASC("asc"),
    DESC("desc"),
    UNKNOWN(""),
}

internal object ListFilterFieldContainsOrderDirectionSerializer :
    RawEnumSerializer<ListFilterFieldContainsOrderDirection>("com.aglyn.contracts.ListFilterFieldContainsOrderDirection", ListFilterFieldContainsOrderDirection.entries, ListFilterFieldContainsOrderDirection.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListFilterFieldPresenceSerializer::class)
enum class ListFilterFieldPresence(val raw: String) {
    ALWAYS("always"),
    NULLABLE("nullable"),
    SPARSE("sparse"),
    UNKNOWN(""),
}

internal object ListFilterFieldPresenceSerializer :
    RawEnumSerializer<ListFilterFieldPresence>("com.aglyn.contracts.ListFilterFieldPresence", ListFilterFieldPresence.entries, ListFilterFieldPresence.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListFilterFieldStoredAsSerializer::class)
enum class ListFilterFieldStoredAs(val raw: String) {
    MILLIS("millis"),
    TIMESTAMP("timestamp"),
    UNKNOWN(""),
}

internal object ListFilterFieldStoredAsSerializer :
    RawEnumSerializer<ListFilterFieldStoredAs>("com.aglyn.contracts.ListFilterFieldStoredAs", ListFilterFieldStoredAs.entries, ListFilterFieldStoredAs.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListFilterKindSerializer::class)
enum class ListFilterKind(val raw: String) {
    BOOLEAN("boolean"),
    DATE("date"),
    EXACT("exact"),
    ID("id"),
    NUMBER("number"),
    TEXT("text"),
    UNKNOWN(""),
}

internal object ListFilterKindSerializer :
    RawEnumSerializer<ListFilterKind>("com.aglyn.contracts.ListFilterKind", ListFilterKind.entries, ListFilterKind.UNKNOWN, { it.raw })

@Serializable
data class ListFilterOption(
    val label: String,
    val value: String,
)

@Serializable
data class ListFilterRequest(
    val field: String,
    val op: String,
    val value: String,
)

@Serializable
data class ListQueryDeclaration(
    val fields: List<ListFilterField>,
    val keys: Map<String, List<String>>? = null,
    val search: ListQueryDeclarationSearch? = null,
    val sorts: List<ListQuerySort>,
)

@Serializable
data class ListQueryDeclarationSearch(
    val scoped: ListQueryDeclarationSearchScoped? = null,
    val tokensPath: String,
)

@Serializable
data class ListQueryDeclarationSearchScoped(
    val join: String,
    val tokensPath: String,
)

@Serializable
data class ListQueryFilter(
    val op: ListQueryOp,
    val path: String,
    val value: JsonElement,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListQueryOpSerializer::class)
enum class ListQueryOp(val raw: String) {
    NOT_EQUAL("!="),
    LESS_THAN("<"),
    LESS_THAN_OR_EQUAL("<="),
    EQUAL("=="),
    GREATER_THAN(">"),
    GREATER_THAN_OR_EQUAL(">="),
    ARRAY_CONTAINS("array-contains"),
    ARRAY_CONTAINS_ANY("array-contains-any"),
    IN("in"),
    UNKNOWN(""),
}

internal object ListQueryOpSerializer :
    RawEnumSerializer<ListQueryOp>("com.aglyn.contracts.ListQueryOp", ListQueryOp.entries, ListQueryOp.UNKNOWN, { it.raw })

@Serializable
data class ListQueryPlan(
    val filters: List<ListQueryFilter>,
    val notices: List<String>,
    val orderBy: ListQuerySort,
    val refused: List<ListQueryRefusal>,
    val searched: String? = null,
    val served: List<ListFilterRequest>,
    val sortFallback: ListQueryPlanSortFallback? = null,
)

@Serializable
data class ListQueryPlanSortFallback(
    val asked: ListQuerySort,
    val reason: ListQueryPlanSortFallbackReason,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListQueryPlanSortFallbackReasonSerializer::class)
enum class ListQueryPlanSortFallbackReason(val raw: String) {
    ALONE("alone"),
    RANGE("range"),
    UNKNOWN(""),
}

internal object ListQueryPlanSortFallbackReasonSerializer :
    RawEnumSerializer<ListQueryPlanSortFallbackReason>("com.aglyn.contracts.ListQueryPlanSortFallbackReason", ListQueryPlanSortFallbackReason.entries, ListQueryPlanSortFallbackReason.UNKNOWN, { it.raw })

@Serializable
data class ListQueryRefusal(
    val clause: JsonElement,
    val reason: String,
)

@Serializable
data class ListQueryRequest(
    val base: List<ListQueryFilter>? = null,
    val clauses: List<ListFilterRequest>,
    val search: List<String>? = null,
    val sort: ListQuerySort? = null,
)

@Serializable
data class ListQuerySort(
    val alone: Boolean? = null,
    val column: String? = null,
    val direction: ListQuerySortDirection,
    val label: String? = null,
    val path: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ListQuerySortDirectionSerializer::class)
enum class ListQuerySortDirection(val raw: String) {
    ASC("asc"),
    DESC("desc"),
    UNKNOWN(""),
}

internal object ListQuerySortDirectionSerializer :
    RawEnumSerializer<ListQuerySortDirection>("com.aglyn.contracts.ListQuerySortDirection", ListQuerySortDirection.entries, ListQuerySortDirection.UNKNOWN, { it.raw })

@Serializable
data class LocalBusinessTypeOptionsItem(
    val label: String,
    val value: String,
)

@Serializable
data class LocalFulfillmentQueueFields(
    val due: String,
    val key: String,
    val location: String,
    val status: String,
)

@Serializable
data class LocalFulfillmentQueueTab(
    val key: OrderFulfillmentKey,
    val label: String,
    val method: LocalFulfillmentQueueTabMethod,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = LocalFulfillmentQueueTabMethodSerializer::class)
enum class LocalFulfillmentQueueTabMethod(val raw: String) {
    LOCAL_DELIVERY("local_delivery"),
    PICKUP("pickup"),
    UNKNOWN(""),
}

internal object LocalFulfillmentQueueTabMethodSerializer :
    RawEnumSerializer<LocalFulfillmentQueueTabMethod>("com.aglyn.contracts.LocalFulfillmentQueueTabMethod", LocalFulfillmentQueueTabMethod.entries, LocalFulfillmentQueueTabMethod.UNKNOWN, { it.raw })

@Serializable
data class ManagedBooking(
    val checkedInAtMs: Double? = null,
    val endsAtMs: Double? = null,
    val expiresAtMs: Double? = null,
    val paidAmountCents: Double? = null,
    val refundedCents: Double? = null,
    val startsAtMs: Double? = null,
    val status: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = MediaKindSerializer::class)
enum class MediaKind(val raw: String) {
    DOCUMENT("document"),
    IMAGE("image"),
    PDF("pdf"),
    VIDEO("video"),
    UNKNOWN(""),
}

internal object MediaKindSerializer :
    RawEnumSerializer<MediaKind>("com.aglyn.contracts.MediaKind", MediaKind.entries, MediaKind.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = MediaSortSerializer::class)
enum class MediaSort(val raw: String) {
    NAME("name"),
    NEWEST("newest"),
    OLDEST("oldest"),
    SIZE("size"),
    UNKNOWN(""),
}

internal object MediaSortSerializer :
    RawEnumSerializer<MediaSort>("com.aglyn.contracts.MediaSort", MediaSort.entries, MediaSort.UNKNOWN, { it.raw })

@Serializable
data class MobileDevice(
    val apnsEnvironment: ApnsEnvironment? = null,
    val app: MobileDeviceApp,
    val appVersion: String? = null,
    val lastSeen: JsonElement? = null,
    val platform: MobileDevicePlatform,
    val token: String,
    val transport: MobilePushTransport,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = MobileDeviceAppSerializer::class)
enum class MobileDeviceApp(val raw: String) {
    AGLYN("aglyn"),
    AGLYN_POS("aglyn-pos"),
    UNKNOWN(""),
}

internal object MobileDeviceAppSerializer :
    RawEnumSerializer<MobileDeviceApp>("com.aglyn.contracts.MobileDeviceApp", MobileDeviceApp.entries, MobileDeviceApp.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = MobileDevicePlatformSerializer::class)
enum class MobileDevicePlatform(val raw: String) {
    ANDROID("android"),
    IOS("ios"),
    MACOS("macos"),
    UNKNOWN(""),
}

internal object MobileDevicePlatformSerializer :
    RawEnumSerializer<MobileDevicePlatform>("com.aglyn.contracts.MobileDevicePlatform", MobileDevicePlatform.entries, MobileDevicePlatform.UNKNOWN, { it.raw })

@Serializable
data class MobilePushData(
    val hostId: String? = null,
    val link: String? = null,
    val orgId: String? = null,
    val type: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = MobilePushTransportSerializer::class)
enum class MobilePushTransport(val raw: String) {
    APNS("apns"),
    FCM("fcm"),
    UNKNOWN(""),
}

internal object MobilePushTransportSerializer :
    RawEnumSerializer<MobilePushTransport>("com.aglyn.contracts.MobilePushTransport", MobilePushTransport.entries, MobilePushTransport.UNKNOWN, { it.raw })

@Serializable
data class ModifierSelection(
    val groupId: String,
    val optionId: String,
)

@Serializable
data class NativeCampaignSendStatusesItem(
    val label: String,
    val value: String,
)

@Serializable
data class NativeCrmPicklist(
    val id: String,
    val label: String,
    val `object`: String,
    val standardLabels: List<String>,
)

@Serializable
data class OrderAddress(
    val city: String? = null,
    val country: String? = null,
    val line1: String? = null,
    val line2: String? = null,
    val name: String? = null,
    val phone: String? = null,
    val postalCode: String? = null,
    val state: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderChannelSerializer::class)
enum class OrderChannel(val raw: String) {
    DRAFT("draft"),
    MARKETPLACE("marketplace"),
    ONLINE("online"),
    POS("pos"),
    SUBSCRIPTION("subscription"),
    UNKNOWN(""),
}

internal object OrderChannelSerializer :
    RawEnumSerializer<OrderChannel>("com.aglyn.contracts.OrderChannel", OrderChannel.entries, OrderChannel.UNKNOWN, { it.raw })

@Serializable
data class OrderChannelSource(
    val channelId: String,
    val channelLabel: String,
    val currency: String,
    val externalOrderId: String,
    val externalRef: String,
    val fees: List<OrderChannelSourceFeesItem>? = null,
    val feesTotalCents: Double? = null,
    val handoff: OrderChannelSourceHandoff? = null,
    val lines: List<OrderChannelSourceLinesItem>,
    val refundIds: List<String>? = null,
    val taxRemittedByChannel: Boolean,
)

@Serializable
data class OrderChannelSourceFeesItem(
    val amountCents: Double,
    val label: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderChannelSourceHandoffSerializer::class)
enum class OrderChannelSourceHandoff(val raw: String) {
    COURIER("courier"),
    SHIP("ship"),
    UNKNOWN(""),
}

internal object OrderChannelSourceHandoffSerializer :
    RawEnumSerializer<OrderChannelSourceHandoff>("com.aglyn.contracts.OrderChannelSourceHandoff", OrderChannelSourceHandoff.entries, OrderChannelSourceHandoff.UNKNOWN, { it.raw })

@Serializable
data class OrderChannelSourceLinesItem(
    val externalLineId: String,
    val lineIndex: Double,
)

@Serializable
data class OrderCredit(
    val amountCents: Double,
    val appliedAs: OrderCreditAppliedAs,
    val key: String,
    val label: String,
    val last4: String,
    val pluginId: String,
    val providerId: String,
    val reference: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderCreditAppliedAsSerializer::class)
enum class OrderCreditAppliedAs(val raw: String) {
    DISCOUNT("discount"),
    TENDER("tender"),
    UNKNOWN(""),
}

internal object OrderCreditAppliedAsSerializer :
    RawEnumSerializer<OrderCreditAppliedAs>("com.aglyn.contracts.OrderCreditAppliedAs", OrderCreditAppliedAs.entries, OrderCreditAppliedAs.UNKNOWN, { it.raw })

@Serializable
data class OrderDispute(
    val amountCents: Double,
    val closedAtMs: Double? = null,
    val evidenceDueByMs: Double? = null,
    val id: String,
    val openedAtMs: Double,
    val outcome: String? = null,
    val reason: String? = null,
    val reversedCents: Double? = null,
    val reversedTransferCents: Double? = null,
    val status: String,
    val transferReversalId: String? = null,
)

@Serializable
data class OrderExtra(
    val amountCents: Double,
    val id: String,
    val key: String,
    val label: String,
    val pluginId: String,
    val quoteRef: String? = null,
)

@Serializable
data class OrderFulfillment(
    val atMs: Double,
    val cancelledAtMs: Double? = null,
    val carrier: String? = null,
    val handover: OrderFulfillmentHandover? = null,
    val id: String,
    val labelRef: String? = null,
    val labelUrl: String? = null,
    val lineItemIds: List<Double>,
    val lines: List<OrderFulfillmentLinesItem>? = null,
    val notify: Boolean? = null,
    val status: OrderFulfillmentStatus? = null,
    val trackingNumber: String? = null,
    val trackingStatus: String? = null,
    val trackingStatusAtMs: Double? = null,
    val trackingUrl: String? = null,
    val updatedAtMs: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderFulfillmentHandoverSerializer::class)
enum class OrderFulfillmentHandover(val raw: String) {
    LOCAL_DELIVERY("local_delivery"),
    PICKUP("pickup"),
    UNKNOWN(""),
}

internal object OrderFulfillmentHandoverSerializer :
    RawEnumSerializer<OrderFulfillmentHandover>("com.aglyn.contracts.OrderFulfillmentHandover", OrderFulfillmentHandover.entries, OrderFulfillmentHandover.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderFulfillmentKeySerializer::class)
enum class OrderFulfillmentKey(val raw: String) {
    DELIVERY_DELIVERED("delivery_delivered"),
    DELIVERY_FAILED("delivery_failed"),
    DELIVERY_OUT_FOR_DELIVERY("delivery_out_for_delivery"),
    DELIVERY_SCHEDULED("delivery_scheduled"),
    PICKUP_PICKED_UP("pickup_picked_up"),
    PICKUP_PREPARING("pickup_preparing"),
    PICKUP_READY("pickup_ready"),
    UNKNOWN(""),
}

internal object OrderFulfillmentKeySerializer :
    RawEnumSerializer<OrderFulfillmentKey>("com.aglyn.contracts.OrderFulfillmentKey", OrderFulfillmentKey.entries, OrderFulfillmentKey.UNKNOWN, { it.raw })

@Serializable
data class OrderFulfillmentLinesItem(
    val lineItemId: Double,
    val quantity: Double,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderFulfillmentMethodSerializer::class)
enum class OrderFulfillmentMethod(val raw: String) {
    LOCAL_DELIVERY("local_delivery"),
    PICKUP("pickup"),
    SHIPPING("shipping"),
    UNKNOWN(""),
}

internal object OrderFulfillmentMethodSerializer :
    RawEnumSerializer<OrderFulfillmentMethod>("com.aglyn.contracts.OrderFulfillmentMethod", OrderFulfillmentMethod.entries, OrderFulfillmentMethod.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderFulfillmentStatusSerializer::class)
enum class OrderFulfillmentStatus(val raw: String) {
    ACTIVE("active"),
    CANCELLED("cancelled"),
    UNKNOWN(""),
}

internal object OrderFulfillmentStatusSerializer :
    RawEnumSerializer<OrderFulfillmentStatus>("com.aglyn.contracts.OrderFulfillmentStatus", OrderFulfillmentStatus.entries, OrderFulfillmentStatus.UNKNOWN, { it.raw })

@Serializable
data class OrderLineItem(
    val fulfillmentId: String? = null,
    val modifiers: List<OrderLineModifier>? = null,
    val name: String,
    val productId: String,
    val productType: ProductType? = null,
    val quantity: Double,
    val sku: String? = null,
    val supplierId: String? = null,
    val unitAmountCents: Double,
    val variantId: String? = null,
    val variantLabel: String? = null,
)

@Serializable
data class OrderLineModifier(
    val group: String,
    val groupId: String,
    val name: String,
    val optionId: String,
    val priceCents: Double,
)

@Serializable
data class OrderLocalDelivery(
    val addressOutsideZone: Boolean? = null,
    val deliveredAtMs: Double? = null,
    val failedAtMs: Double? = null,
    val failedReason: String? = null,
    val feeCents: Double? = null,
    val locationId: String? = null,
    val outForDeliveryAtMs: Double? = null,
    val postalCode: String? = null,
    val status: OrderLocalDeliveryStatus? = null,
    val updatedAtMs: Double? = null,
    val windowEndMs: Double? = null,
    val windowLabel: String? = null,
    val windowStartMs: Double? = null,
    val zoneId: String? = null,
    val zoneName: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderLocalDeliveryStatusSerializer::class)
enum class OrderLocalDeliveryStatus(val raw: String) {
    DELIVERED("delivered"),
    FAILED("failed"),
    OUT_FOR_DELIVERY("out_for_delivery"),
    SCHEDULED("scheduled"),
    UNKNOWN(""),
}

internal object OrderLocalDeliveryStatusSerializer :
    RawEnumSerializer<OrderLocalDeliveryStatus>("com.aglyn.contracts.OrderLocalDeliveryStatus", OrderLocalDeliveryStatus.entries, OrderLocalDeliveryStatus.UNKNOWN, { it.raw })

@Serializable
data class OrderPayment(
    val amountCents: Double,
    val atMs: Double,
    val cardBrand: String? = null,
    val cashierId: String? = null,
    val cashTenderedCents: Double? = null,
    val changeCents: Double? = null,
    val checkoutSessionId: String? = null,
    val checkoutUrl: String? = null,
    val creditLabel: String? = null,
    val creditProviderId: String? = null,
    val creditReference: String? = null,
    val failureMessage: String? = null,
    val feeCents: Double? = null,
    val folioAtMs: Double? = null,
    val giftCardId: String? = null,
    val id: String,
    val last4: String? = null,
    val livemode: Boolean? = null,
    val method: OrderPaymentMethod,
    val paymentIntentId: String? = null,
    val readerId: String? = null,
    val reservationId: String? = null,
    val settledAtMs: Double? = null,
    val status: OrderPaymentStatus,
    val takeFeeCents: Double? = null,
    val tipCents: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderPaymentMethodSerializer::class)
enum class OrderPaymentMethod(val raw: String) {
    CARD_KEYED("card_keyed"),
    CARD_LINK("card_link"),
    CARD_PRESENT("card_present"),
    CASH("cash"),
    CREDIT("credit"),
    FOLIO("folio"),
    GIFT_CARD("gift_card"),
    UNKNOWN(""),
}

internal object OrderPaymentMethodSerializer :
    RawEnumSerializer<OrderPaymentMethod>("com.aglyn.contracts.OrderPaymentMethod", OrderPaymentMethod.entries, OrderPaymentMethod.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderPaymentStatusSerializer::class)
enum class OrderPaymentStatus(val raw: String) {
    CANCELED("canceled"),
    FAILED("failed"),
    PENDING("pending"),
    REVERSED("reversed"),
    SUCCEEDED("succeeded"),
    UNKNOWN(""),
}

internal object OrderPaymentStatusSerializer :
    RawEnumSerializer<OrderPaymentStatus>("com.aglyn.contracts.OrderPaymentStatus", OrderPaymentStatus.entries, OrderPaymentStatus.UNKNOWN, { it.raw })

@Serializable
data class OrderPickup(
    val address: String? = null,
    val hours: String? = null,
    val instructions: String? = null,
    val locationId: String? = null,
    val locationName: String? = null,
    val pickedUpAtMs: Double? = null,
    val pickedUpBy: String? = null,
    val readyAtMs: Double? = null,
    val status: OrderPickupStatus? = null,
    val updatedAtMs: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderPickupStatusSerializer::class)
enum class OrderPickupStatus(val raw: String) {
    PICKED_UP("picked_up"),
    PREPARING("preparing"),
    READY("ready"),
    UNKNOWN(""),
}

internal object OrderPickupStatusSerializer :
    RawEnumSerializer<OrderPickupStatus>("com.aglyn.contracts.OrderPickupStatus", OrderPickupStatus.entries, OrderPickupStatus.UNKNOWN, { it.raw })

@Serializable
data class OrderRestockCheck(
    val flaggedAtMs: Double,
    val fullyReversed: Boolean,
    val kind: OrderRestockCheckKind,
    val lines: List<OrderRestockLine>,
    val resolution: OrderRestockCheckResolution? = null,
    val resolvedAtMs: Double? = null,
    val resolvedBy: String? = null,
    val units: Double,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderRestockCheckKindSerializer::class)
enum class OrderRestockCheckKind(val raw: String) {
    CHARGEBACK("chargeback"),
    REFUND("refund"),
    UNKNOWN(""),
}

internal object OrderRestockCheckKindSerializer :
    RawEnumSerializer<OrderRestockCheckKind>("com.aglyn.contracts.OrderRestockCheckKind", OrderRestockCheckKind.entries, OrderRestockCheckKind.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderRestockCheckResolutionSerializer::class)
enum class OrderRestockCheckResolution(val raw: String) {
    DISMISSED("dismissed"),
    RESTOCKED("restocked"),
    UNKNOWN(""),
}

internal object OrderRestockCheckResolutionSerializer :
    RawEnumSerializer<OrderRestockCheckResolution>("com.aglyn.contracts.OrderRestockCheckResolution", OrderRestockCheckResolution.entries, OrderRestockCheckResolution.UNKNOWN, { it.raw })

@Serializable
data class OrderRestockLine(
    val lineIndex: Double? = null,
    val name: String? = null,
    val productId: String,
    val quantity: Double,
    val variantId: String,
    val variantLabel: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderStatusSerializer::class)
enum class OrderStatus(val raw: String) {
    CANCELLED("cancelled"),
    DELIVERED("delivered"),
    FULFILLED("fulfilled"),
    PAID("paid"),
    PARTIALLY_FULFILLED("partially_fulfilled"),
    PENDING("pending"),
    REFUNDED("refunded"),
    UNKNOWN(""),
}

internal object OrderStatusSerializer :
    RawEnumSerializer<OrderStatus>("com.aglyn.contracts.OrderStatus", OrderStatus.entries, OrderStatus.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = OrderStatusColorValueSerializer::class)
enum class OrderStatusColorValue(val raw: String) {
    DEFAULT("default"),
    ERROR("error"),
    INFO("info"),
    SUCCESS("success"),
    WARNING("warning"),
    UNKNOWN(""),
}

internal object OrderStatusColorValueSerializer :
    RawEnumSerializer<OrderStatusColorValue>("com.aglyn.contracts.OrderStatusColorValue", OrderStatusColorValue.entries, OrderStatusColorValue.UNKNOWN, { it.raw })

@Serializable
data class OrderTimelineEvent(
    val atMs: Double,
    val detail: String? = null,
    val event: String,
)

@Serializable
data class OrderTotals(
    val discountCents: Double? = null,
    val extrasCents: Double? = null,
    val feeCents: Double? = null,
    val itemsCents: Double? = null,
    val shippingCents: Double? = null,
    val taxCents: Double? = null,
    val tipCents: Double? = null,
    val totalCents: Double? = null,
)

@Serializable
data class OrderUnresolvedLine(
    val productId: String,
    val quantity: Double,
    val variantId: String? = null,
)

@Serializable
data class PaymentRisk(
    val latestAtMs: Double,
    val latestKind: PaymentRiskSignalKind,
    val signals: List<PaymentRiskSignal>,
)

@Serializable
data class PaymentRiskSignal(
    val atMs: Double,
    val detail: String? = null,
    val kind: PaymentRiskSignalKind,
    val outcome: String? = null,
    val stripeObjectId: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PaymentRiskSignalKindSerializer::class)
enum class PaymentRiskSignalKind(val raw: String) {
    DISPUTE("dispute"),
    EARLY_FRAUD_WARNING("early-fraud-warning"),
    RADAR_REVIEW("radar-review"),
    UNKNOWN(""),
}

internal object PaymentRiskSignalKindSerializer :
    RawEnumSerializer<PaymentRiskSignalKind>("com.aglyn.contracts.PaymentRiskSignalKind", PaymentRiskSignalKind.entries, PaymentRiskSignalKind.UNKNOWN, { it.raw })

@Serializable
data class PickupLocationSettings(
    val enabled: Boolean? = null,
    val hours: String? = null,
    val instructions: String? = null,
    val readyWithinMinutes: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosDeviceModeSerializer::class)
enum class PosDeviceMode(val raw: String) {
    DISPLAY("display"),
    KIOSK("kiosk"),
    UNKNOWN(""),
}

internal object PosDeviceModeSerializer :
    RawEnumSerializer<PosDeviceMode>("com.aglyn.contracts.PosDeviceMode", PosDeviceMode.entries, PosDeviceMode.UNKNOWN, { it.raw })

@Serializable
data class PosKioskCatalog(
    val categories: List<PosKioskCategory>,
    val currency: String,
    val products: List<PosKioskProduct>,
)

@Serializable
data class PosKioskCategory(
    val id: String,
    val name: String,
)

@Serializable
data class PosKioskContext(
    val branding: PosKioskContextBranding,
    val currency: String,
    val idleSeconds: Long,
    val offerMarketing: Boolean,
    val payments: PosKioskContextPayments,
    val receipts: List<PosReceiptChannel>,
    val testMode: Boolean,
    val tipping: PosKioskContextTipping,
)

@Serializable
data class PosKioskContextBranding(
    val logoDarkUrl: String? = null,
    val logoUrl: String? = null,
    val message: String,
    val name: String,
)

@Serializable
data class PosKioskContextPayments(
    val cardPresent: Boolean,
    val payAtCounter: Boolean,
    val reader: Boolean,
)

@Serializable
data class PosKioskContextTipping(
    val enabled: Boolean,
    val percentages: List<Double>,
)

@Serializable
data class PosKioskLine(
    val modifiers: List<ModifierSelection>? = null,
    val productId: String,
    val quantity: Long,
    val variantId: String? = null,
)

@Serializable
data class PosKioskProduct(
    val categoryIds: List<String>,
    val description: String? = null,
    val id: String,
    val imageUrl: String? = null,
    val modifierGroups: List<ProductModifierGroup>,
    val name: String,
    val options: List<PosKioskProductOptionsItem>,
    val variants: List<PosKioskVariant>,
)

@Serializable
data class PosKioskProductOptionsItem(
    val name: String,
    val values: List<String>,
)

@Serializable
data class PosKioskSale(
    val discountCents: Long,
    val dueCents: Long,
    val itemsCents: Long,
    val lines: List<PosKioskSaleLine>,
    val number: Long,
    val orderId: String,
    val paidCents: Long,
    val payment: PosKioskSalePayment? = null,
    val status: PosKioskSaleStatus,
    val taxCents: Long,
    val tipCents: Long,
    val totalCents: Long,
)

@Serializable
data class PosKioskSaleLine(
    val amountCents: Long,
    val name: String,
    val quantity: Long,
    val variantLabel: String? = null,
)

@Serializable
data class PosKioskSalePayment(
    val failureMessage: String? = null,
    val id: String,
    val status: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosKioskSaleStatusSerializer::class)
enum class PosKioskSaleStatus(val raw: String) {
    OPEN("open"),
    PAID("paid"),
    QUEUED("queued"),
    VOIDED("voided"),
    UNKNOWN(""),
}

internal object PosKioskSaleStatusSerializer :
    RawEnumSerializer<PosKioskSaleStatus>("com.aglyn.contracts.PosKioskSaleStatus", PosKioskSaleStatus.entries, PosKioskSaleStatus.UNKNOWN, { it.raw })

@Serializable
data class PosKioskVariant(
    val id: String,
    val options: Map<String, String>,
    val priceCents: Long,
    val soldOut: Boolean,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosOfflineFlagSerializer::class)
enum class PosOfflineFlag(val raw: String) {
    CASH_SHORT("cash-short"),
    CASHIER_UNVERIFIED("cashier-unverified"),
    CLOCK_ADJUSTED("clock-adjusted"),
    DISCOUNT_OVER_LIMIT("discount-over-limit"),
    LATE_SYNC("late-sync"),
    NO_SHIFT("no-shift"),
    PRICE_CHANGED("price-changed"),
    REGISTER_OVER_CAP("register-over-cap"),
    SHIFT_CLOSED("shift-closed"),
    STOCK_SHORT("stock-short"),
    TAX_DIFFERS("tax-differs"),
    TOTALS_RESTATED("totals-restated"),
    UNKNOWN_PRODUCT("unknown-product"),
    UNKNOWN_REGISTER("unknown-register"),
    UNKNOWN(""),
}

internal object PosOfflineFlagSerializer :
    RawEnumSerializer<PosOfflineFlag>("com.aglyn.contracts.PosOfflineFlag", PosOfflineFlag.entries, PosOfflineFlag.UNKNOWN, { it.raw })

@Serializable
data class PosOfflineKit(
    val available: Boolean,
    val hostId: String,
    val issuedAtMs: Double,
    val maxDiscountPct: Double,
    val orgId: String,
    val receipt: PosOfflineKitReceipt,
    val registers: List<PosOfflineKitRegister>,
    val requireOpenShift: Boolean,
    val tax: PosOfflineKitTax,
    val unavailableReason: String? = null,
    val v: Long,
)

@Serializable
data class PosOfflineKitReceipt(
    val address: String? = null,
    val footer: String? = null,
    val logo: String? = null,
    val name: String,
    val returnPolicy: String? = null,
)

@Serializable
data class PosOfflineKitRegister(
    val id: String,
    val locationId: String? = null,
    val name: String,
    val openShiftId: String? = null,
)

@Serializable
data class PosOfflineKitTax(
    val pct: Double? = null,
    val pricesIncludeTax: Boolean,
)

@Serializable
data class PosOfflineOrderStamp(
    val flags: List<PosOfflineFlag>,
    val priceDrift: List<PosOfflineOrderStampPriceDriftItem>? = null,
    val saleKey: String,
    val soldAtMs: Double,
    val stockConflicts: List<PosOfflineStockConflict>? = null,
    val syncedAtMs: Double,
    val syncedBy: String,
)

@Serializable
data class PosOfflineOrderStampPriceDriftItem(
    val currentCents: Double,
    val index: Double,
    val rungCents: Double,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosOfflineOutcomeStatusSerializer::class)
enum class PosOfflineOutcomeStatus(val raw: String) {
    RECORDED("recorded"),
    REFUSED("refused"),
    REPLAYED("replayed"),
    UNKNOWN(""),
}

internal object PosOfflineOutcomeStatusSerializer :
    RawEnumSerializer<PosOfflineOutcomeStatus>("com.aglyn.contracts.PosOfflineOutcomeStatus", PosOfflineOutcomeStatus.entries, PosOfflineOutcomeStatus.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosOfflineRefusalSerializer::class)
enum class PosOfflineRefusal(val raw: String) {
    CONFLICT("conflict"),
    FAILED("failed"),
    INVALID("invalid"),
    WRONG_SITE("wrong-site"),
    WRONG_STAFF("wrong-staff"),
    WRONG_WORKSPACE("wrong-workspace"),
    UNKNOWN(""),
}

internal object PosOfflineRefusalSerializer :
    RawEnumSerializer<PosOfflineRefusal>("com.aglyn.contracts.PosOfflineRefusal", PosOfflineRefusal.entries, PosOfflineRefusal.UNKNOWN, { it.raw })

@Serializable
data class PosOfflineSale(
    val cashierAssertion: String? = null,
    val cashTenderedCents: Double,
    val changeCents: Double,
    val customer: PosOfflineSaleCustomer? = null,
    val discountPct: Double,
    val hostId: String,
    val lines: List<PosOfflineSaleLine>,
    val locationId: String? = null,
    val orgId: String,
    val registerId: String,
    val saleKey: String,
    val shiftId: String? = null,
    val signedInUid: String,
    val soldAtMs: Double,
    val totals: OrderTotals,
    val v: Long,
)

@Serializable
data class PosOfflineSaleCustomer(
    val email: String? = null,
    val id: String? = null,
    val kind: String? = null,
    val name: String? = null,
)

@Serializable
data class PosOfflineSaleLine(
    val modifiers: List<ModifierSelection>? = null,
    val name: String,
    val productId: String,
    val productType: ProductType? = null,
    val quantity: Double,
    val sku: String? = null,
    val unitAmountCents: Double,
    val variantId: String? = null,
    val variantLabel: String? = null,
)

@Serializable
data class PosOfflineSaleOutcome(
    val error: String? = null,
    val flags: List<PosOfflineFlag>? = null,
    val number: Double? = null,
    val orderId: String? = null,
    val reason: PosOfflineRefusal? = null,
    val retry: Boolean? = null,
    val saleKey: String,
    val status: PosOfflineOutcomeStatus,
    val stockConflicts: List<PosOfflineStockConflict>? = null,
)

@Serializable
data class PosOfflineStockConflict(
    val applied: Double,
    val name: String,
    val productId: String,
    val requested: Double,
    val shortUnits: Double,
    val variantId: String? = null,
)

@Serializable
data class PosOfflineSyncRequest(
    val hostId: String,
    val sales: List<PosOfflineSale>,
)

@Serializable
data class PosOfflineSyncResponse(
    val results: List<PosOfflineSaleOutcome>,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = PosReceiptChannelSerializer::class)
enum class PosReceiptChannel(val raw: String) {
    EMAIL("email"),
    NONE("none"),
    PRINT("print"),
    SMS("sms"),
    UNKNOWN(""),
}

internal object PosReceiptChannelSerializer :
    RawEnumSerializer<PosReceiptChannel>("com.aglyn.contracts.PosReceiptChannel", PosReceiptChannel.entries, PosReceiptChannel.UNKNOWN, { it.raw })

@Serializable
data class ProductChannelFacts(
    val brand: String? = null,
    val condition: ProductChannelFactsCondition? = null,
    val googleProductCategory: String? = null,
    val gtin: String? = null,
    val mpn: String? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ProductChannelFactsConditionSerializer::class)
enum class ProductChannelFactsCondition(val raw: String) {
    NEW("new"),
    REFURBISHED("refurbished"),
    USED("used"),
    UNKNOWN(""),
}

internal object ProductChannelFactsConditionSerializer :
    RawEnumSerializer<ProductChannelFactsCondition>("com.aglyn.contracts.ProductChannelFactsCondition", ProductChannelFactsCondition.entries, ProductChannelFactsCondition.UNKNOWN, { it.raw })

@Serializable
data class ProductModifierGroup(
    val id: String,
    val max: Double,
    val min: Double,
    val name: String,
    val options: List<ProductModifierOption>,
)

@Serializable
data class ProductModifierOption(
    val id: String,
    val name: String,
    val priceCents: Double,
)

@Serializable
data class ProductOption(
    val name: String,
    val values: List<String>,
)

@Serializable
data class ProductShippingFacts(
    val heightCm: Double? = null,
    val hsCode: String? = null,
    val lengthCm: Double? = null,
    val originCountry: String? = null,
    val widthCm: Double? = null,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ProductStatusSerializer::class)
enum class ProductStatus(val raw: String) {
    ACTIVE("active"),
    ARCHIVED("archived"),
    DRAFT("draft"),
    UNKNOWN(""),
}

internal object ProductStatusSerializer :
    RawEnumSerializer<ProductStatus>("com.aglyn.contracts.ProductStatus", ProductStatus.entries, ProductStatus.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = ProductTypeSerializer::class)
enum class ProductType(val raw: String) {
    DIGITAL("digital"),
    PHYSICAL("physical"),
    SERVICE("service"),
    UNKNOWN(""),
}

internal object ProductTypeSerializer :
    RawEnumSerializer<ProductType>("com.aglyn.contracts.ProductType", ProductType.entries, ProductType.UNKNOWN, { it.raw })

@Serializable
data class ProductVariant(
    val barcode: String? = null,
    val compareAtPriceUsd: Double? = null,
    val id: String? = null,
    val imageUrl: String? = null,
    val inventory: Double? = null,
    val inventoryByLocation: Map<String, Double>? = null,
    val options: Map<String, String>? = null,
    val priceUsd: Double? = null,
    val sku: String? = null,
    val weightGrams: Double? = null,
)

@Serializable
data class ReceiptData(
    val banner: String? = null,
    val barcode: String? = null,
    val cashierName: String? = null,
    val changeCents: Double? = null,
    val createdAtMs: Double,
    val currency: String,
    val discountCents: Double? = null,
    val footer: String? = null,
    val lines: List<ReceiptLine>,
    val orderId: String? = null,
    val orderNumber: String,
    val refundedCents: Double? = null,
    val registerName: String? = null,
    val shippingCents: Double? = null,
    val storeLines: List<String>? = null,
    val storeName: String,
    val subtotalCents: Double,
    val taxCents: Double? = null,
    val tenders: List<ReceiptTender>? = null,
    val timeZone: String? = null,
    val tipCents: Double? = null,
    val totalCents: Double,
)

@Serializable
data class ReceiptLine(
    val detail: String? = null,
    val name: String,
    val quantity: Double,
    val totalCents: Double,
    val unitCents: Double,
)

@Serializable
data class ReceiptTender(
    val amountCents: Double,
    val label: String,
)

@Serializable
data class ScreenTrafficRow(
    val devices: Map<String, Double>,
    val referrers: Map<String, Double>,
    val screenId: String,
    val total: Long,
)

@Serializable
data class SiteFilterOptions(
    val hasCustomDomain: List<SiteFilterOptionsHasCustomDomainItem>,
)

@Serializable
data class SiteFilterOptionsHasCustomDomainItem(
    val label: String,
    val value: String,
)

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = SiteJourneyStepTypeSerializer::class)
enum class SiteJourneyStepType(val raw: String) {
    BOOKING("booking"),
    CART("cart"),
    EMAIL("email"),
    EVENT("event"),
    FORM("form"),
    ORDER("order"),
    OVERLAY("overlay"),
    PAGE("page"),
    UNKNOWN(""),
}

internal object SiteJourneyStepTypeSerializer :
    RawEnumSerializer<SiteJourneyStepType>("com.aglyn.contracts.SiteJourneyStepType", SiteJourneyStepType.entries, SiteJourneyStepType.UNKNOWN, { it.raw })

/** A newer server value decodes as [UNKNOWN], so an older app never fails on it. */
@Serializable(with = TenantEmailControlSerializer::class)
enum class TenantEmailControl(val raw: String) {
    BESIGNER("besigner"),
    EXTERNAL("external"),
    FIXED("fixed"),
    UNKNOWN(""),
}

internal object TenantEmailControlSerializer :
    RawEnumSerializer<TenantEmailControl>("com.aglyn.contracts.TenantEmailControl", TenantEmailControl.entries, TenantEmailControl.UNKNOWN, { it.raw })

@Serializable
data class TenantEmailEntry(
    val authoredIn: String? = null,
    val control: TenantEmailControl? = null,
    val defaultSubject: String? = null,
    val description: String? = null,
    val footerReason: String? = null,
    val key: String? = null,
    val name: String? = null,
    val plugin: String? = null,
    val pluginId: String? = null,
    val requiresFeature: String? = null,
)

@Serializable
internal data class ContractValuesPart1(
    @SerialName("AREA_SERVED_MAX") val areaServedMax: Long,
    @SerialName("BOOKING_FIELD_ASKS") val bookingFieldAsks: List<BookingFieldAsk>,
    @SerialName("BOOKING_IN_PERSON_MAX_CENTS") val bookingInPersonMaxCents: Long,
    @SerialName("BOOKING_IN_PERSON_MIN_CENTS") val bookingInPersonMinCents: Long,
    @SerialName("BOOKING_MAX_DAYS_AHEAD") val bookingMaxDaysAhead: Long,
    @SerialName("BOOKING_PRICE_DISPLAYS") val bookingPriceDisplays: List<BookingPriceDisplay>,
    @SerialName("BOOKING_PRICE_LABELS") val bookingPriceLabels: Map<String, String>,
    @SerialName("BOOKING_SERVICE_DESCRIPTION_MAX") val bookingServiceDescriptionMax: Long,
    @SerialName("BOOKING_SERVICE_NAME_MAX") val bookingServiceNameMax: Long,
    @SerialName("BOOKING_STATE_LABELS") val bookingStateLabels: Map<String, String>,
    @SerialName("BOOKING_WEEKDAYS") val bookingWeekdays: List<String>,
    @SerialName("CAMPAIGN_EMAILS_QUERY") val campaignEmailsQuery: ListQueryDeclaration,
    @SerialName("COMPANY_LIST_DECLARATION") val companyListDeclaration: ListQueryDeclaration,
    @SerialName("COMPONENT_LIST_QUERY") val componentListQuery: ListQueryDeclaration,
    @SerialName("CONTACT_LIFECYCLE_STAGE_LABELS") val contactLifecycleStageLabels: Map<String, String>,
    @SerialName("CONTACT_LIST_DECLARATION") val contactListDeclaration: ListQueryDeclaration,
    @SerialName("CONTENT_SCHEMA_TYPE_DEFAULT") val contentSchemaTypeDefault: ContentSchemaType,
    @SerialName("CONTENT_SCHEMA_TYPE_OPTIONS") val contentSchemaTypeOptions: List<ContentSchemaTypeOptionsItem>,
    @SerialName("CRM_ACTIVITIES_PER_RECORD_CEILING") val crmActivitiesPerRecordCeiling: Long,
    @SerialName("CRM_ACTIVITY_DIRECTION_LABELS") val crmActivityDirectionLabels: Map<String, String>,
    @SerialName("CRM_ACTIVITY_KIND_LABELS") val crmActivityKindLabels: Map<String, String>,
    @SerialName("CRM_EMAIL_BODY_MAX") val crmEmailBodyMax: Long,
    @SerialName("CRM_EMAIL_SUBJECT_MAX") val crmEmailSubjectMax: Long,
    @SerialName("CRM_FIELD_OBJECT_LABELS") val crmFieldObjectLabels: Map<String, String>,
    @SerialName("CRM_LEAD_STATUS_LABELS") val crmLeadStatusLabels: Map<String, String>,
    @SerialName("CRM_REPORT_PERIOD_LABELS") val crmReportPeriodLabels: Map<String, String>,
    @SerialName("CRM_TASK_KIND_LABELS") val crmTaskKindLabels: Map<String, String>,
    @SerialName("CROSS_MAX_DEPTH") val crossMaxDepth: Long,
    @SerialName("DEAL_LIST_DECLARATION") val dealListDeclaration: ListQueryDeclaration,
    @SerialName("DEFAULT_DEAL_STAGES") val defaultDealStages: List<CrmDealStage>,
    @SerialName("DEFAULT_TITLE_PATTERN") val defaultTitlePattern: String,
    @SerialName("DROP_OFF_MAX_HOURS") val dropOffMaxHours: Double,
    @SerialName("DROP_OFF_WAIT_HOURS") val dropOffWaitHours: List<Double>,
    @SerialName("DROP_OFF_WATCHES_MAX") val dropOffWatchesMax: Long,
    @SerialName("EMAIL_LIST_QUERY") val emailListQuery: ListQueryDeclaration,
    @SerialName("EMAIL_TEMPLATE_QUERY") val emailTemplateQuery: ListQueryDeclaration,
    @SerialName("ENTRY_LIST_FILTER_HEADERS") val entryListFilterHeaders: Map<String, String>,
    @SerialName("ENTRY_LIST_QUERY") val entryListQuery: ListQueryDeclaration,
    @SerialName("ENTRY_STATUS_OPTIONS") val entryStatusOptions: List<EntryStatusOptionsItem>,
    @SerialName("EVENT_COVER_ALT_MAX_LENGTH") val eventCoverAltMaxLength: Long,
    @SerialName("EVENT_DEFAULT_DURATION_MS") val eventDefaultDurationMs: Double,
    @SerialName("EVENT_DESCRIPTION_MAX_LENGTH") val eventDescriptionMaxLength: Long,
    @SerialName("EVENT_LOCATION_MAX_LENGTH") val eventLocationMaxLength: Long,
    @SerialName("EVENT_ORGANIZER_MAX_LENGTH") val eventOrganizerMaxLength: Long,
    @SerialName("EVENT_TITLE_MAX_LENGTH") val eventTitleMaxLength: Long,
    @SerialName("EXPERIMENT_LIST_QUERY") val experimentListQuery: ListQueryDeclaration,
    @SerialName("FORM_IN_USE") val formInUse: ListQueryFilter,
    @SerialName("FORM_LEAD_ROUTING_OPTIONS") val formLeadRoutingOptions: List<FormLeadRoutingOptionsItem>,
)

@Serializable
internal data class ContractValuesPart2(
    @SerialName("FORM_LIST_FILTER_HEADERS") val formListFilterHeaders: Map<String, String>,
    @SerialName("FORM_LIST_QUERY") val formListQuery: ListQueryDeclaration,
    @SerialName("FORM_SCOPED_SUBMISSION_LIST_QUERY") val formScopedSubmissionListQuery: ListQueryDeclaration,
    @SerialName("FORM_STATUS_OPTIONS") val formStatusOptions: List<FormStatusOptionsItem>,
    @SerialName("FUNCTION_BUILTIN_NAMES") val functionBuiltinNames: List<String>,
    @SerialName("FUNCTION_MAX_OPERATIONS") val functionMaxOperations: Long,
    @SerialName("FUNNEL_EMAIL_KEY_LABELS") val funnelEmailKeyLabels: Map<String, String>,
    @SerialName("FUNNEL_FEATURE") val funnelFeature: String,
    @SerialName("FUNNEL_LABEL_MAX") val funnelLabelMax: Long,
    @SerialName("FUNNEL_MAX_RANGE_DAYS") val funnelMaxRangeDays: Long,
    @SerialName("FUNNEL_MAX_STEPS") val funnelMaxSteps: Long,
    @SerialName("FUNNEL_MIN_STEPS") val funnelMinSteps: Long,
    @SerialName("FUNNEL_NAME_MAX") val funnelNameMax: Long,
    @SerialName("FUNNEL_STEP_TYPE_LABELS") val funnelStepTypeLabels: Map<String, String>,
    @SerialName("FUNNELS_MAX_PER_SITE") val funnelsMaxPerSite: Long,
    @SerialName("HOST_EVENTS") val hostEvents: List<HostEventDeclaration>,
    @SerialName("LAYOUT_LIST_QUERY") val layoutListQuery: ListQueryDeclaration,
    @SerialName("LEAD_LIST_DECLARATION") val leadListDeclaration: ListQueryDeclaration,
    @SerialName("LEAD_LIST_QUERY") val leadListQuery: ListQueryDeclaration,
    @SerialName("LEAD_SOURCE_OPTIONS") val leadSourceOptions: List<ListFilterOption>,
    @SerialName("LIST_MEMBER_QUERY") val listMemberQuery: ListQueryDeclaration,
    @SerialName("LIST_QUERY_DISJUNCTIONS") val listQueryDisjunctions: Long,
    @SerialName("LIST_QUERY_ID_PATH") val listQueryIdPath: String,
    @SerialName("LOCAL_BUSINESS_TYPE_OPTIONS") val localBusinessTypeOptions: List<LocalBusinessTypeOptionsItem>,
    @SerialName("LOCAL_FULFILLMENT_OPEN_STATUSES") val localFulfillmentOpenStatuses: List<String>,
    @SerialName("LOCAL_FULFILLMENT_QUEUE_FIELDS") val localFulfillmentQueueFields: LocalFulfillmentQueueFields,
    @SerialName("LOCAL_FULFILLMENT_QUEUE_LIMIT") val localFulfillmentQueueLimit: Long,
    @SerialName("LOCAL_FULFILLMENT_QUEUE_TABS") val localFulfillmentQueueTabs: List<LocalFulfillmentQueueTab>,
    @SerialName("MEDIA_ALT_MAX_LENGTH") val mediaAltMaxLength: Long,
    @SerialName("MEDIA_ALT_OPTIONS") val mediaAltOptions: List<ListFilterOption>,
    @SerialName("MEDIA_DISJUNCTION_LIMIT") val mediaDisjunctionLimit: Long,
    @SerialName("MEDIA_FILTER_HEADERS") val mediaFilterHeaders: Map<String, String>,
    @SerialName("MEDIA_FOLDER_MAX_DEPTH") val mediaFolderMaxDepth: Long,
    @SerialName("MEDIA_FOLDER_NAME_MAX_LENGTH") val mediaFolderNameMaxLength: Long,
    @SerialName("MEDIA_KINDS") val mediaKinds: List<MediaKind>,
    @SerialName("MEDIA_LIST_QUERY") val mediaListQuery: ListQueryDeclaration,
    @SerialName("MEDIA_ORIENTATION_OPTIONS") val mediaOrientationOptions: List<ListFilterOption>,
    @SerialName("MEDIA_SCOPED_SEARCH_NOTICE") val mediaScopedSearchNotice: String,
    @SerialName("MEDIA_SORT_LABELS") val mediaSortLabels: Map<String, String>,
    @SerialName("MEDIA_SORT_ORDER") val mediaSortOrder: Map<String, ListQuerySort>,
    @SerialName("MEDIA_SORTS") val mediaSorts: List<MediaSort>,
    @SerialName("MEDIA_TAG_MAX_COUNT") val mediaTagMaxCount: Long,
    @SerialName("MEDIA_TAG_MAX_LENGTH") val mediaTagMaxLength: Long,
    @SerialName("MEDIA_TYPE_OPTIONS") val mediaTypeOptions: List<ListFilterOption>,
    @SerialName("NAME_TOKEN_LIMIT") val nameTokenLimit: Long,
    @SerialName("NAME_TOKEN_MAX_PREFIX") val nameTokenMaxPrefix: Long,
    @SerialName("NATIVE_CAMPAIGN_SEND_STATUSES") val nativeCampaignSendStatuses: List<NativeCampaignSendStatusesItem>,
    @SerialName("NATIVE_CONTACT_LIFECYCLE_STAGES") val nativeContactLifecycleStages: List<String>,
)

@Serializable
internal data class ContractValuesPart3(
    @SerialName("NATIVE_CRM_ACTIVITY_DIRECTIONS") val nativeCrmActivityDirections: Map<String, List<String>>,
    @SerialName("NATIVE_CRM_ACTIVITY_KINDS") val nativeCrmActivityKinds: List<String>,
    @SerialName("NATIVE_CRM_FIELD_OBJECTS") val nativeCrmFieldObjects: List<String>,
    @SerialName("NATIVE_CRM_LEAD_OPEN_STATUSES") val nativeCrmLeadOpenStatuses: List<String>,
    @SerialName("NATIVE_CRM_LEAD_STATUSES") val nativeCrmLeadStatuses: List<String>,
    @SerialName("NATIVE_CRM_PICKLISTS") val nativeCrmPicklists: List<NativeCrmPicklist>,
    @SerialName("NATIVE_CRM_REPORT_PERIODS") val nativeCrmReportPeriods: List<String>,
    @SerialName("NATIVE_CRM_TASK_KINDS") val nativeCrmTaskKinds: List<String>,
    @SerialName("NATIVE_SITE_CAMPAIGNS_QUERY") val nativeSiteCampaignsQuery: ListQueryDeclaration,
    @SerialName("NATIVE_SITE_EMAILS_QUERY") val nativeSiteEmailsQuery: ListQueryDeclaration,
    @SerialName("OPEN_DISPUTE_CLAUSE") val openDisputeClause: ListFilterClause,
    @SerialName("ORDER_CHANNEL_LABELS") val orderChannelLabels: Map<String, String>,
    @SerialName("ORDER_CHANNEL_OPTIONS") val orderChannelOptions: List<ListFilterOption>,
    @SerialName("ORDER_DISPUTE_OPTIONS") val orderDisputeOptions: List<ListFilterOption>,
    @SerialName("ORDER_FULFILLMENT_METHOD_LABELS") val orderFulfillmentMethodLabels: Map<String, String>,
    @SerialName("ORDER_LIST_HEADERS") val orderListHeaders: Map<String, String>,
    @SerialName("ORDER_LIST_QUERY") val orderListQuery: ListQueryDeclaration,
    @SerialName("ORDER_LIST_SELECT_FIELDS") val orderListSelectFields: List<String>,
    @SerialName("ORDER_LOCAL_DELIVERY_STATUS_LABELS") val orderLocalDeliveryStatusLabels: Map<String, String>,
    @SerialName("ORDER_PICKUP_STATUS_LABELS") val orderPickupStatusLabels: Map<String, String>,
    @SerialName("ORDER_STATUS_COLOR") val orderStatusColor: Map<String, OrderStatusColorValue>,
    @SerialName("ORDER_STATUS_LABELS") val orderStatusLabels: Map<String, String>,
    @SerialName("ORDER_STATUS_OPTIONS") val orderStatusOptions: List<ListFilterOption>,
    @SerialName("ORG_SUBMISSION_LIST_QUERY") val orgSubmissionListQuery: ListQueryDeclaration,
    @SerialName("OUTREACH_DEFAULT_ALLOWED_COUNTRIES") val outreachDefaultAllowedCountries: List<String>,
    @SerialName("OUTREACH_DO_NOT_CONTACT_DOMAIN_LIST_QUERY") val outreachDoNotContactDomainListQuery: ListQueryDeclaration,
    @SerialName("OUTREACH_ENROLLMENT_LIST_QUERY") val outreachEnrollmentListQuery: ListQueryDeclaration,
    @SerialName("OUTREACH_MAX_EMAIL_STEPS") val outreachMaxEmailSteps: Long,
    @SerialName("OUTREACH_MAX_STEP_DELAY_BUSINESS_DAYS") val outreachMaxStepDelayBusinessDays: Long,
    @SerialName("OUTREACH_MAX_STEPS") val outreachMaxSteps: Long,
    @SerialName("OUTREACH_MIN_EMAIL_FOLLOW_UP_BUSINESS_DAYS") val outreachMinEmailFollowUpBusinessDays: Long,
    @SerialName("OUTREACH_SEQUENCE_LIST_QUERY") val outreachSequenceListQuery: ListQueryDeclaration,
    @SerialName("OUTREACH_SEQUENCE_NAME_MAX") val outreachSequenceNameMax: Long,
    @SerialName("OUTREACH_TASK_TITLE_MAX") val outreachTaskTitleMax: Long,
    @SerialName("PAYMENT_ACCEPTED_MAX_LENGTH") val paymentAcceptedMaxLength: Long,
    @SerialName("POS_KIOSK_CATALOG_LIMIT") val posKioskCatalogLimit: Long,
    @SerialName("POS_KIOSK_DONE_SECONDS") val posKioskDoneSeconds: Long,
    @SerialName("POS_KIOSK_IDLE_SECONDS_DEFAULT") val posKioskIdleSecondsDefault: Long,
    @SerialName("POS_KIOSK_IDLE_SECONDS_MAX") val posKioskIdleSecondsMax: Long,
    @SerialName("POS_KIOSK_IDLE_SECONDS_MIN") val posKioskIdleSecondsMin: Long,
    @SerialName("POS_KIOSK_IDLE_WARNING_SECONDS") val posKioskIdleWarningSeconds: Long,
    @SerialName("POS_KIOSK_MAX_LINES") val posKioskMaxLines: Long,
    @SerialName("POS_KIOSK_MAX_QUANTITY") val posKioskMaxQuantity: Long,
    @SerialName("POS_KIOSK_UNLOCK_LOCKOUT_MS") val posKioskUnlockLockoutMs: Double,
    @SerialName("POS_KIOSK_UNLOCK_MAX_ATTEMPTS") val posKioskUnlockMaxAttempts: Long,
    @SerialName("POS_KIOSK_UNLOCK_TTL_MS") val posKioskUnlockTtlMs: Double,
    @SerialName("POS_OFFLINE_CLOCK_SKEW_MS") val posOfflineClockSkewMs: Double,
    @SerialName("POS_OFFLINE_DISABLED_TENDERS") val posOfflineDisabledTenders: Map<String, String>,
)

@Serializable
internal data class ContractValuesPart4(
    @SerialName("POS_OFFLINE_FLAG_LABELS") val posOfflineFlagLabels: Map<String, String>,
    @SerialName("POS_OFFLINE_LATE_SYNC_MS") val posOfflineLateSyncMs: Double,
    @SerialName("POS_OFFLINE_MAX_AGE_MS") val posOfflineMaxAgeMs: Double,
    @SerialName("POS_OFFLINE_SALE_MAX_LINES") val posOfflineSaleMaxLines: Long,
    @SerialName("POS_OFFLINE_SYNC_BATCH_MAX") val posOfflineSyncBatchMax: Long,
    @SerialName("POS_OFFLINE_SYNC_ROUTE") val posOfflineSyncRoute: String,
    @SerialName("PRICE_RANGE_MAX_LENGTH") val priceRangeMaxLength: Long,
    @SerialName("PRODUCT_LIST_BASE") val productListBase: List<ListQueryFilter>,
    @SerialName("PRODUCT_LIST_HEADERS") val productListHeaders: Map<String, String>,
    @SerialName("PRODUCT_LIST_OPTIONS") val productListOptions: Map<String, List<ListFilterOption>>,
    @SerialName("PRODUCT_LIST_QUERY") val productListQuery: ListQueryDeclaration,
    @SerialName("PRODUCT_LIST_SELECT_FIELDS") val productListSelectFields: List<String>,
    @SerialName("REMINDER_WINDOW_END_HOURS") val reminderWindowEndHours: Long,
    @SerialName("REMINDER_WINDOW_START_HOURS") val reminderWindowStartHours: Long,
    @SerialName("REPLY_BODY_MAX") val replyBodyMax: Long,
    @SerialName("REPLY_SUBJECT_MAX") val replySubjectMax: Long,
    @SerialName("SCOPED_SEARCH_JOIN") val scopedSearchJoin: String,
    @SerialName("SEARCH_ENGINE_VERIFICATION_LABELS") val searchEngineVerificationLabels: Map<String, String>,
    @SerialName("SEARCH_ENGINE_VERIFICATION_META_NAMES") val searchEngineVerificationMetaNames: Map<String, String>,
    @SerialName("SITE_CARDS_PAGE_SIZE") val siteCardsPageSize: Long,
    @SerialName("SITE_FILTER_HEADERS") val siteFilterHeaders: Map<String, String>,
    @SerialName("SITE_FILTER_OPTIONS") val siteFilterOptions: SiteFilterOptions,
    @SerialName("SITE_JOURNEY_KEY_MAX") val siteJourneyKeyMax: Long,
    @SerialName("SITE_LIST_DECLARATION") val siteListDeclaration: ListQueryDeclaration,
    @SerialName("SITE_MEMBER_LIST_QUERY") val siteMemberListQuery: ListQueryDeclaration,
    @SerialName("SUBMISSION_FILTER_HEADERS") val submissionFilterHeaders: Map<String, String>,
    @SerialName("SUBMISSION_LIST_QUERY") val submissionListQuery: ListQueryDeclaration,
    @SerialName("SUBMISSION_READ_OPTIONS") val submissionReadOptions: List<ListFilterOption>,
    @SerialName("SUPPRESSION_LIST_QUERY") val suppressionListQuery: ListQueryDeclaration,
    @SerialName("TASK_LIST_DECLARATION") val taskListDeclaration: ListQueryDeclaration,
    @SerialName("TEMPLATE_KIND_OPTIONS") val templateKindOptions: List<ListFilterOption>,
    @SerialName("TEMPLATE_LIST_BASE") val templateListBase: List<ListQueryFilter>,
    @SerialName("TEMPLATE_LIST_QUERY") val templateListQuery: ListQueryDeclaration,
    @SerialName("TENANT_EMAIL_COLLECTION") val tenantEmailCollection: String,
    @SerialName("TENANT_EMAILS") val tenantEmails: List<TenantEmailEntry>,
    @SerialName("WORKFLOW_MAX_STEPS") val workflowMaxSteps: Long,
)

/**
 * The values in contracts.generated.json, keyed as the TypeScript exports are.
 * Each part decodes from the same JSON; split so no class passes the JVM's
 * 255-slot constructor limit (AGL-3703).
 */
class ContractValues internal constructor(
    private val part1: ContractValuesPart1,
    private val part2: ContractValuesPart2,
    private val part3: ContractValuesPart3,
    private val part4: ContractValuesPart4,
) {
    val areaServedMax: Long get() = part1.areaServedMax
    val bookingFieldAsks: List<BookingFieldAsk> get() = part1.bookingFieldAsks
    val bookingInPersonMaxCents: Long get() = part1.bookingInPersonMaxCents
    val bookingInPersonMinCents: Long get() = part1.bookingInPersonMinCents
    val bookingMaxDaysAhead: Long get() = part1.bookingMaxDaysAhead
    val bookingPriceDisplays: List<BookingPriceDisplay> get() = part1.bookingPriceDisplays
    val bookingPriceLabels: Map<String, String> get() = part1.bookingPriceLabels
    val bookingServiceDescriptionMax: Long get() = part1.bookingServiceDescriptionMax
    val bookingServiceNameMax: Long get() = part1.bookingServiceNameMax
    val bookingStateLabels: Map<String, String> get() = part1.bookingStateLabels
    val bookingWeekdays: List<String> get() = part1.bookingWeekdays
    val campaignEmailsQuery: ListQueryDeclaration get() = part1.campaignEmailsQuery
    val companyListDeclaration: ListQueryDeclaration get() = part1.companyListDeclaration
    val componentListQuery: ListQueryDeclaration get() = part1.componentListQuery
    val contactLifecycleStageLabels: Map<String, String> get() = part1.contactLifecycleStageLabels
    val contactListDeclaration: ListQueryDeclaration get() = part1.contactListDeclaration
    val contentSchemaTypeDefault: ContentSchemaType get() = part1.contentSchemaTypeDefault
    val contentSchemaTypeOptions: List<ContentSchemaTypeOptionsItem> get() = part1.contentSchemaTypeOptions
    val crmActivitiesPerRecordCeiling: Long get() = part1.crmActivitiesPerRecordCeiling
    val crmActivityDirectionLabels: Map<String, String> get() = part1.crmActivityDirectionLabels
    val crmActivityKindLabels: Map<String, String> get() = part1.crmActivityKindLabels
    val crmEmailBodyMax: Long get() = part1.crmEmailBodyMax
    val crmEmailSubjectMax: Long get() = part1.crmEmailSubjectMax
    val crmFieldObjectLabels: Map<String, String> get() = part1.crmFieldObjectLabels
    val crmLeadStatusLabels: Map<String, String> get() = part1.crmLeadStatusLabels
    val crmReportPeriodLabels: Map<String, String> get() = part1.crmReportPeriodLabels
    val crmTaskKindLabels: Map<String, String> get() = part1.crmTaskKindLabels
    val crossMaxDepth: Long get() = part1.crossMaxDepth
    val dealListDeclaration: ListQueryDeclaration get() = part1.dealListDeclaration
    val defaultDealStages: List<CrmDealStage> get() = part1.defaultDealStages
    val defaultTitlePattern: String get() = part1.defaultTitlePattern
    val dropOffMaxHours: Double get() = part1.dropOffMaxHours
    val dropOffWaitHours: List<Double> get() = part1.dropOffWaitHours
    val dropOffWatchesMax: Long get() = part1.dropOffWatchesMax
    val emailListQuery: ListQueryDeclaration get() = part1.emailListQuery
    val emailTemplateQuery: ListQueryDeclaration get() = part1.emailTemplateQuery
    val entryListFilterHeaders: Map<String, String> get() = part1.entryListFilterHeaders
    val entryListQuery: ListQueryDeclaration get() = part1.entryListQuery
    val entryStatusOptions: List<EntryStatusOptionsItem> get() = part1.entryStatusOptions
    val eventCoverAltMaxLength: Long get() = part1.eventCoverAltMaxLength
    val eventDefaultDurationMs: Double get() = part1.eventDefaultDurationMs
    val eventDescriptionMaxLength: Long get() = part1.eventDescriptionMaxLength
    val eventLocationMaxLength: Long get() = part1.eventLocationMaxLength
    val eventOrganizerMaxLength: Long get() = part1.eventOrganizerMaxLength
    val eventTitleMaxLength: Long get() = part1.eventTitleMaxLength
    val experimentListQuery: ListQueryDeclaration get() = part1.experimentListQuery
    val formInUse: ListQueryFilter get() = part1.formInUse
    val formLeadRoutingOptions: List<FormLeadRoutingOptionsItem> get() = part1.formLeadRoutingOptions
    val formListFilterHeaders: Map<String, String> get() = part2.formListFilterHeaders
    val formListQuery: ListQueryDeclaration get() = part2.formListQuery
    val formScopedSubmissionListQuery: ListQueryDeclaration get() = part2.formScopedSubmissionListQuery
    val formStatusOptions: List<FormStatusOptionsItem> get() = part2.formStatusOptions
    val functionBuiltinNames: List<String> get() = part2.functionBuiltinNames
    val functionMaxOperations: Long get() = part2.functionMaxOperations
    val funnelEmailKeyLabels: Map<String, String> get() = part2.funnelEmailKeyLabels
    val funnelFeature: String get() = part2.funnelFeature
    val funnelLabelMax: Long get() = part2.funnelLabelMax
    val funnelMaxRangeDays: Long get() = part2.funnelMaxRangeDays
    val funnelMaxSteps: Long get() = part2.funnelMaxSteps
    val funnelMinSteps: Long get() = part2.funnelMinSteps
    val funnelNameMax: Long get() = part2.funnelNameMax
    val funnelStepTypeLabels: Map<String, String> get() = part2.funnelStepTypeLabels
    val funnelsMaxPerSite: Long get() = part2.funnelsMaxPerSite
    val hostEvents: List<HostEventDeclaration> get() = part2.hostEvents
    val layoutListQuery: ListQueryDeclaration get() = part2.layoutListQuery
    val leadListDeclaration: ListQueryDeclaration get() = part2.leadListDeclaration
    val leadListQuery: ListQueryDeclaration get() = part2.leadListQuery
    val leadSourceOptions: List<ListFilterOption> get() = part2.leadSourceOptions
    val listMemberQuery: ListQueryDeclaration get() = part2.listMemberQuery
    val listQueryDisjunctions: Long get() = part2.listQueryDisjunctions
    val listQueryIdPath: String get() = part2.listQueryIdPath
    val localBusinessTypeOptions: List<LocalBusinessTypeOptionsItem> get() = part2.localBusinessTypeOptions
    val localFulfillmentOpenStatuses: List<String> get() = part2.localFulfillmentOpenStatuses
    val localFulfillmentQueueFields: LocalFulfillmentQueueFields get() = part2.localFulfillmentQueueFields
    val localFulfillmentQueueLimit: Long get() = part2.localFulfillmentQueueLimit
    val localFulfillmentQueueTabs: List<LocalFulfillmentQueueTab> get() = part2.localFulfillmentQueueTabs
    val mediaAltMaxLength: Long get() = part2.mediaAltMaxLength
    val mediaAltOptions: List<ListFilterOption> get() = part2.mediaAltOptions
    val mediaDisjunctionLimit: Long get() = part2.mediaDisjunctionLimit
    val mediaFilterHeaders: Map<String, String> get() = part2.mediaFilterHeaders
    val mediaFolderMaxDepth: Long get() = part2.mediaFolderMaxDepth
    val mediaFolderNameMaxLength: Long get() = part2.mediaFolderNameMaxLength
    val mediaKinds: List<MediaKind> get() = part2.mediaKinds
    val mediaListQuery: ListQueryDeclaration get() = part2.mediaListQuery
    val mediaOrientationOptions: List<ListFilterOption> get() = part2.mediaOrientationOptions
    val mediaScopedSearchNotice: String get() = part2.mediaScopedSearchNotice
    val mediaSortLabels: Map<String, String> get() = part2.mediaSortLabels
    val mediaSortOrder: Map<String, ListQuerySort> get() = part2.mediaSortOrder
    val mediaSorts: List<MediaSort> get() = part2.mediaSorts
    val mediaTagMaxCount: Long get() = part2.mediaTagMaxCount
    val mediaTagMaxLength: Long get() = part2.mediaTagMaxLength
    val mediaTypeOptions: List<ListFilterOption> get() = part2.mediaTypeOptions
    val nameTokenLimit: Long get() = part2.nameTokenLimit
    val nameTokenMaxPrefix: Long get() = part2.nameTokenMaxPrefix
    val nativeCampaignSendStatuses: List<NativeCampaignSendStatusesItem> get() = part2.nativeCampaignSendStatuses
    val nativeContactLifecycleStages: List<String> get() = part2.nativeContactLifecycleStages
    val nativeCrmActivityDirections: Map<String, List<String>> get() = part3.nativeCrmActivityDirections
    val nativeCrmActivityKinds: List<String> get() = part3.nativeCrmActivityKinds
    val nativeCrmFieldObjects: List<String> get() = part3.nativeCrmFieldObjects
    val nativeCrmLeadOpenStatuses: List<String> get() = part3.nativeCrmLeadOpenStatuses
    val nativeCrmLeadStatuses: List<String> get() = part3.nativeCrmLeadStatuses
    val nativeCrmPicklists: List<NativeCrmPicklist> get() = part3.nativeCrmPicklists
    val nativeCrmReportPeriods: List<String> get() = part3.nativeCrmReportPeriods
    val nativeCrmTaskKinds: List<String> get() = part3.nativeCrmTaskKinds
    val nativeSiteCampaignsQuery: ListQueryDeclaration get() = part3.nativeSiteCampaignsQuery
    val nativeSiteEmailsQuery: ListQueryDeclaration get() = part3.nativeSiteEmailsQuery
    val openDisputeClause: ListFilterClause get() = part3.openDisputeClause
    val orderChannelLabels: Map<String, String> get() = part3.orderChannelLabels
    val orderChannelOptions: List<ListFilterOption> get() = part3.orderChannelOptions
    val orderDisputeOptions: List<ListFilterOption> get() = part3.orderDisputeOptions
    val orderFulfillmentMethodLabels: Map<String, String> get() = part3.orderFulfillmentMethodLabels
    val orderListHeaders: Map<String, String> get() = part3.orderListHeaders
    val orderListQuery: ListQueryDeclaration get() = part3.orderListQuery
    val orderListSelectFields: List<String> get() = part3.orderListSelectFields
    val orderLocalDeliveryStatusLabels: Map<String, String> get() = part3.orderLocalDeliveryStatusLabels
    val orderPickupStatusLabels: Map<String, String> get() = part3.orderPickupStatusLabels
    val orderStatusColor: Map<String, OrderStatusColorValue> get() = part3.orderStatusColor
    val orderStatusLabels: Map<String, String> get() = part3.orderStatusLabels
    val orderStatusOptions: List<ListFilterOption> get() = part3.orderStatusOptions
    val orgSubmissionListQuery: ListQueryDeclaration get() = part3.orgSubmissionListQuery
    val outreachDefaultAllowedCountries: List<String> get() = part3.outreachDefaultAllowedCountries
    val outreachDoNotContactDomainListQuery: ListQueryDeclaration get() = part3.outreachDoNotContactDomainListQuery
    val outreachEnrollmentListQuery: ListQueryDeclaration get() = part3.outreachEnrollmentListQuery
    val outreachMaxEmailSteps: Long get() = part3.outreachMaxEmailSteps
    val outreachMaxStepDelayBusinessDays: Long get() = part3.outreachMaxStepDelayBusinessDays
    val outreachMaxSteps: Long get() = part3.outreachMaxSteps
    val outreachMinEmailFollowUpBusinessDays: Long get() = part3.outreachMinEmailFollowUpBusinessDays
    val outreachSequenceListQuery: ListQueryDeclaration get() = part3.outreachSequenceListQuery
    val outreachSequenceNameMax: Long get() = part3.outreachSequenceNameMax
    val outreachTaskTitleMax: Long get() = part3.outreachTaskTitleMax
    val paymentAcceptedMaxLength: Long get() = part3.paymentAcceptedMaxLength
    val posKioskCatalogLimit: Long get() = part3.posKioskCatalogLimit
    val posKioskDoneSeconds: Long get() = part3.posKioskDoneSeconds
    val posKioskIdleSecondsDefault: Long get() = part3.posKioskIdleSecondsDefault
    val posKioskIdleSecondsMax: Long get() = part3.posKioskIdleSecondsMax
    val posKioskIdleSecondsMin: Long get() = part3.posKioskIdleSecondsMin
    val posKioskIdleWarningSeconds: Long get() = part3.posKioskIdleWarningSeconds
    val posKioskMaxLines: Long get() = part3.posKioskMaxLines
    val posKioskMaxQuantity: Long get() = part3.posKioskMaxQuantity
    val posKioskUnlockLockoutMs: Double get() = part3.posKioskUnlockLockoutMs
    val posKioskUnlockMaxAttempts: Long get() = part3.posKioskUnlockMaxAttempts
    val posKioskUnlockTtlMs: Double get() = part3.posKioskUnlockTtlMs
    val posOfflineClockSkewMs: Double get() = part3.posOfflineClockSkewMs
    val posOfflineDisabledTenders: Map<String, String> get() = part3.posOfflineDisabledTenders
    val posOfflineFlagLabels: Map<String, String> get() = part4.posOfflineFlagLabels
    val posOfflineLateSyncMs: Double get() = part4.posOfflineLateSyncMs
    val posOfflineMaxAgeMs: Double get() = part4.posOfflineMaxAgeMs
    val posOfflineSaleMaxLines: Long get() = part4.posOfflineSaleMaxLines
    val posOfflineSyncBatchMax: Long get() = part4.posOfflineSyncBatchMax
    val posOfflineSyncRoute: String get() = part4.posOfflineSyncRoute
    val priceRangeMaxLength: Long get() = part4.priceRangeMaxLength
    val productListBase: List<ListQueryFilter> get() = part4.productListBase
    val productListHeaders: Map<String, String> get() = part4.productListHeaders
    val productListOptions: Map<String, List<ListFilterOption>> get() = part4.productListOptions
    val productListQuery: ListQueryDeclaration get() = part4.productListQuery
    val productListSelectFields: List<String> get() = part4.productListSelectFields
    val reminderWindowEndHours: Long get() = part4.reminderWindowEndHours
    val reminderWindowStartHours: Long get() = part4.reminderWindowStartHours
    val replyBodyMax: Long get() = part4.replyBodyMax
    val replySubjectMax: Long get() = part4.replySubjectMax
    val scopedSearchJoin: String get() = part4.scopedSearchJoin
    val searchEngineVerificationLabels: Map<String, String> get() = part4.searchEngineVerificationLabels
    val searchEngineVerificationMetaNames: Map<String, String> get() = part4.searchEngineVerificationMetaNames
    val siteCardsPageSize: Long get() = part4.siteCardsPageSize
    val siteFilterHeaders: Map<String, String> get() = part4.siteFilterHeaders
    val siteFilterOptions: SiteFilterOptions get() = part4.siteFilterOptions
    val siteJourneyKeyMax: Long get() = part4.siteJourneyKeyMax
    val siteListDeclaration: ListQueryDeclaration get() = part4.siteListDeclaration
    val siteMemberListQuery: ListQueryDeclaration get() = part4.siteMemberListQuery
    val submissionFilterHeaders: Map<String, String> get() = part4.submissionFilterHeaders
    val submissionListQuery: ListQueryDeclaration get() = part4.submissionListQuery
    val submissionReadOptions: List<ListFilterOption> get() = part4.submissionReadOptions
    val suppressionListQuery: ListQueryDeclaration get() = part4.suppressionListQuery
    val taskListDeclaration: ListQueryDeclaration get() = part4.taskListDeclaration
    val templateKindOptions: List<ListFilterOption> get() = part4.templateKindOptions
    val templateListBase: List<ListQueryFilter> get() = part4.templateListBase
    val templateListQuery: ListQueryDeclaration get() = part4.templateListQuery
    val tenantEmailCollection: String get() = part4.tenantEmailCollection
    val tenantEmails: List<TenantEmailEntry> get() = part4.tenantEmails
    val workflowMaxSteps: Long get() = part4.workflowMaxSteps

    override fun equals(other: Any?): Boolean = this === other || (other is ContractValues && part1 == other.part1 && part2 == other.part2 && part3 == other.part3 && part4 == other.part4)

    override fun hashCode(): Int = listOf<Any>(part1, part2, part3, part4).hashCode()

    companion object {
        /** Decodes every part from one JSON text; the format must ignore unknown keys. */
        fun decode(json: Json, text: String): ContractValues {
            val tree = json.parseToJsonElement(text)
            return ContractValues(
                json.decodeFromJsonElement(ContractValuesPart1.serializer(), tree),
                json.decodeFromJsonElement(ContractValuesPart2.serializer(), tree),
                json.decodeFromJsonElement(ContractValuesPart3.serializer(), tree),
                json.decodeFromJsonElement(ContractValuesPart4.serializer(), tree),
            )
        }
    }
}
