/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Tests for the legal Doc-vs-live drift normalizer (AGL-1611).
//
// The HTML fixture mirrors the real served shape (measured on
// aglyn.com/legal/eula, 2026-08-17): the TOC and the page title come BEFORE
// the "Last updated:" line, the body's own "©" line comes before a SECOND
// "©" in the footer chrome, and paragraphs are fragmented by inline
// elements. Every green here was made to fail first by breaking the input
// it certifies.

import assert from 'node:assert/strict'
import { describe, it } from 'node:test'
import { readFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  DOC_TO_SLUG,
  compareLegalDocument,
  decodeHtmlEntities,
  docToBlockLines,
  htmlToBlockLines,
  normalizeLegalLine,
  overallExitCode,
  parseGdocPointer,
  sliceContentBlock,
  slugForPointerName,
} from './legal-doc-diff.mjs'

const HERE = dirname(fileURLToPath(import.meta.url))

// The real served shape, shrunk: chrome, TOC, title, then the content block,
// then footer chrome with its own © line.
const LIVE_HTML = `
<html><head><style>.x{color:red}</style><script>self.__next_f.push([1,"**Last updated: bait**"])</script></head>
<body>
  <nav><a href="/">Aglyn</a><a href="/legal">Legal</a></nav>
  <aside><p>On this page</p><ul><li>1. Scope</li><li>2. Fees &amp; Taxes</li></ul></aside>
  <h1>Example Policy</h1>
  <p><strong>Last updated: August 5, 2026</strong></p>
  <p>This Example Policy (&quot;<strong>Policy</strong>&quot;) governs your use of Aglyn&#x27;s services.</p>
  <h2>1. Scope</h2>
  <p>It applies to  every&nbsp;site.</p>
  <h2>2. Fees &amp; Taxes</h2>
  <table><tr><th>Name</th><th>Fee</th></tr><tr><td>Basic</td><td>$5</td></tr></table>
  <p>&#169; 2026 Aglyn LLC. All rights reserved.</p>
  <footer><p>Contact</p><p>&#169; 2026 Aglyn LLC. All rights reserved.</p><p>Privacy</p></footer>
</body></html>`

// The same document as a Docs plain-text export: BOM, CRLF, typographic
// punctuation, a heading with no markdown marker, table cells one per line.
const DOC_PLAIN =
  '﻿' +
  [
    'Example Policy',
    '',
    'Last updated: August 5, 2026',
    '',
    'This Example Policy (“Policy”) governs your use of Aglyn’s services.',
    '1. Scope',
    'It applies to every site.',
    '2. Fees & Taxes',
    'Name',
    'Fee',
    'Basic',
    '$5',
    '© 2026 Aglyn LLC. All rights reserved.',
  ].join('\r\n')

describe('parseGdocPointer', () => {
  it('reads doc_id from a real pointer payload', () => {
    const real = JSON.stringify({
      '': 'WARNING! DO NOT EDIT THIS FILE! ANY CHANGES MADE WILL BE LOST!',
      doc_id: '1-ASAhzC-zEFZwW_2rhpU2et1o43wbF5BbeToizphMTU',
      resource_key: '',
      email: 'zach@aglyn.com',
    })
    assert.equal(parseGdocPointer(real), '1-ASAhzC-zEFZwW_2rhpU2et1o43wbF5BbeToizphMTU')
  })

  it('rejects non-JSON and pointer-less JSON', () => {
    assert.equal(parseGdocPointer('# markdown, not a pointer'), null)
    assert.equal(parseGdocPointer('{"email":"zach@aglyn.com"}'), null)
    assert.equal(parseGdocPointer('{"doc_id":"  "}'), null)
  })
})

describe('slugForPointerName', () => {
  it('maps the published nine and strips .md.gdoc', () => {
    assert.deepEqual(slugForPointerName('PRIVACY_POLICY.md.gdoc'), {
      name: 'PRIVACY_POLICY',
      slug: 'privacy',
      known: true,
    })
    assert.equal(slugForPointerName('TERMS_OF_SERVICE.md.gdoc').slug, 'terms')
    assert.equal(
      slugForPointerName('MARKETPLACE_PUBLISHER_AGREEMENT.md.gdoc').slug,
      'marketplace-publisher-agreement',
    )
  })

  it('marks internal docs known-but-pageless, and new docs unknown', () => {
    assert.deepEqual(slugForPointerName('README.md.gdoc'), {
      name: 'README',
      slug: null,
      known: true,
    })
    assert.equal(slugForPointerName('BRAND_NEW_POLICY.md.gdoc').known, false)
  })

  it('covers every pointer file the Legal folder actually holds', () => {
    // The mapping and the folder must not drift apart silently: every
    // published slug in the map is one of the repo's published paths.
    const published = readFileSync(
      join(HERE, '../../../libs/aglyn/src/lib/app-utils/published-legal-pages.ts'),
      'utf8',
    )
    for (const slug of Object.values(DOC_TO_SLUG)) {
      if (slug === null) continue
      assert.ok(
        published.includes(`'/legal/${slug}'`),
        `DOC_TO_SLUG names /legal/${slug}, which PUBLISHED_LEGAL_PATHS does not list`,
      )
    }
  })
})

describe('decodeHtmlEntities', () => {
  it('decodes named, decimal and hex entities', () => {
    assert.equal(
      decodeHtmlEntities('Fees &amp; Taxes &#169; Aglyn&#x27;s &quot;beta&quot;&nbsp;plan'),
      'Fees & Taxes © Aglyn\'s "beta" plan',
    )
  })

  it('leaves double-encoded entities literal', () => {
    assert.equal(decodeHtmlEntities('&amp;lt;script&amp;gt;'), '&lt;script&gt;')
  })
})

describe('htmlToBlockLines', () => {
  it('drops script/style, keeps inline text glued, splits blocks and cells', () => {
    const lines = htmlToBlockLines(LIVE_HTML)
    assert.ok(!lines.some((l) => l.includes('bait')), 'script content leaked')
    assert.ok(!lines.some((l) => l.includes('color:red')), 'style content leaked')
    assert.ok(lines.includes('Last updated: August 5, 2026'))
    assert.ok(
      lines.includes('This Example Policy ("Policy") governs your use of Aglyn\'s services.'),
      `inline fragments were not glued: ${JSON.stringify(lines)}`,
    )
    // Table cells become their own lines, matching the Docs plain export.
    assert.ok(lines.includes('Basic') && lines.includes('$5'))
  })
})

describe('docToBlockLines', () => {
  it('strips the BOM and CRLF line endings, drops blanks', () => {
    const lines = docToBlockLines(DOC_PLAIN)
    assert.equal(lines[0], 'Example Policy')
    assert.ok(lines.every((l) => !l.includes('\r') && l.trim() === l && l !== ''))
  })
})

describe('normalizeLegalLine', () => {
  it('folds typographic punctuation to ASCII', () => {
    assert.equal(
      normalizeLegalLine('“Aglyn’s” terms – the — dashes…'),
      '"Aglyn\'s" terms - the - dashes...',
    )
  })

  it('strips markdown markers the rendered page has consumed', () => {
    assert.equal(normalizeLegalLine('## 2. Fees & Taxes'), '2. Fees & Taxes')
    assert.equal(normalizeLegalLine('**Last updated: August 5, 2026**'), 'Last updated: August 5, 2026')
    assert.equal(normalizeLegalLine('- a [link](https://x.example) in `code`'), 'a link in code')
  })

  it('erases table drawing but never cell content', () => {
    assert.equal(normalizeLegalLine('| Basic | $5 |'), 'Basic $5')
    assert.equal(normalizeLegalLine('| --- | :---: |'), '')
    assert.equal(normalizeLegalLine('---'), '')
    // A real content line that merely contains a hyphen survives.
    assert.equal(normalizeLegalLine('opt-out'), 'opt-out')
  })

  it('collapses whitespace runs and NBSP', () => {
    assert.equal(normalizeLegalLine('It applies to  every site.'), 'It applies to every site.')
  })
})

describe('sliceContentBlock', () => {
  it('starts at Last updated, ends at the FIRST © line, keeping both', () => {
    const { lines, foundStart, foundEnd } = sliceContentBlock([
      'On this page',
      '1. Scope',
      'Example Policy',
      'Last updated: August 5, 2026',
      'Body text',
      '© 2026 Aglyn LLC. All rights reserved.',
      'Contact',
      '© 2026 Aglyn LLC. All rights reserved.',
      'Privacy',
    ])
    assert.ok(foundStart && foundEnd)
    assert.equal(lines[0], 'Last updated: August 5, 2026')
    assert.equal(lines.at(-1), '© 2026 Aglyn LLC. All rights reserved.')
    assert.equal(lines.length, 3, 'TOC/title before and footer after must be excluded')
  })

  it('accepts a bolded (markdown) Last updated line as the start', () => {
    const { lines, foundStart } = sliceContentBlock([
      'Title',
      '**Last updated: August 5, 2026**',
      'Body',
    ])
    assert.ok(foundStart)
    assert.equal(lines.length, 2)
  })

  it('degrades to full text when markers are missing, and says so', () => {
    const { lines, foundStart, foundEnd } = sliceContentBlock(['a', 'b'])
    assert.deepEqual(lines, ['a', 'b'])
    assert.equal(foundStart, false)
    assert.equal(foundEnd, false)
  })
})

describe('compareLegalDocument', () => {
  it('reports the fixture pair IN SYNC across every rendering difference', () => {
    const { inSync, live, doc, caveats } = compareLegalDocument(LIVE_HTML, DOC_PLAIN)
    assert.deepEqual(caveats, [])
    assert.equal(live.text, doc.text)
    assert.ok(inSync)
    assert.ok(live.text.startsWith('Last updated: August 5, 2026\n'))
    assert.ok(live.text.endsWith('All rights reserved.\n'))
  })

  it('flags a single changed word', () => {
    const edited = DOC_PLAIN.replace('every site', 'every workspace')
    const { inSync } = compareLegalDocument(LIVE_HTML, edited)
    assert.equal(inSync, false)
  })

  it('flags an added sentence', () => {
    const edited = DOC_PLAIN.replace(
      'It applies to every site.',
      'It applies to every site.\r\nExcept on Tuesdays.',
    )
    const { inSync } = compareLegalDocument(LIVE_HTML, edited)
    assert.equal(inSync, false)
  })

  it('carries caveats when a side lacks the block markers', () => {
    const { caveats } = compareLegalDocument(LIVE_HTML, 'just some text')
    assert.ok(caveats.some((c) => c.includes('Doc has no "Last updated:"')))
    assert.ok(caveats.some((c) => c.includes('Doc has no closing')))
  })
})

describe('overallExitCode', () => {
  const v = (status) => ({ status })
  it('is 0 only when something compared and nothing differs', () => {
    assert.equal(overallExitCode([v('in-sync'), v('skipped')]), 0)
  })
  it('is 1 on any DIFFERS — drift beats cannot-check', () => {
    assert.equal(overallExitCode([v('in-sync'), v('differs'), v('unreadable')]), 1)
  })
  it('is 2 when anything is unreadable and nothing differs', () => {
    assert.equal(overallExitCode([v('in-sync'), v('unreadable')]), 2)
  })
  it('is 2 — never a clean pass — when nothing was comparable at all', () => {
    assert.equal(overallExitCode([]), 2)
    assert.equal(overallExitCode([v('skipped')]), 2)
  })
})
