/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** The native theme tokens: color parsing, the type scale, and both sources, over a synthetic theme. */

import assert from 'node:assert/strict'
import test from 'node:test'

import {
  compositeOver,
  kotlinTokensContent,
  nativeThemeData,
  parseCssColor,
  primaryFontFamily,
  swiftTokensContent,
  TYPE_SCALE,
} from './native-theme.mjs'

test('CSS colors parse into channels', () => {
  assert.deepEqual(parseCssColor('#fff'), { r: 255, g: 255, b: 255, a: 1 })
  assert.deepEqual(parseCssColor('#00B0FF'), { r: 0, g: 176, b: 255, a: 1 })
  assert.deepEqual(parseCssColor('#000000DE'), { r: 0, g: 0, b: 0, a: 222 / 255 })
  assert.deepEqual(parseCssColor('rgb(44, 53, 64)'), { r: 44, g: 53, b: 64, a: 1 })
  assert.deepEqual(parseCssColor('rgba(0, 0, 0, 0.87)'), { r: 0, g: 0, b: 0, a: 0.87 })
  for (const bad of ['red', '#12345', 'rgb(1,2)', 'rgba(0,0,0,2)', 'hsl(0, 0%, 0%)']) {
    assert.throws(() => parseCssColor(bad), /is not #rgb/)
  }
})

test('compositing a translucent color over an opaque one', () => {
  assert.deepEqual(compositeOver({ r: 255, g: 0, b: 0, a: 0.5 }, { r: 0, g: 0, b: 255, a: 1 }), {
    r: 128,
    g: 0,
    b: 128,
    a: 1,
  })
})

test('the first family of the stack, unquoted', () => {
  assert.equal(primaryFontFamily('"Roboto Flex",-apple-system,Arial'), 'Roboto Flex')
  assert.equal(primaryFontFamily('Inter, sans-serif'), 'Inter')
})

const intent = { main: '#00b0ff', contrastText: '#FFFFFF', hoverText: '#0073a8', hover: '#0077ad' }
const variant = (fontSize, extra = {}) => ({ fontSize, fontWeight: 400, lineHeight: 1.5, ...extra })
const typography = {
  fontFamily: '"Roboto Flex",-apple-system',
  htmlFontSize: 16,
  ...Object.fromEntries(TYPE_SCALE.map(({ variant: name }) => [name, variant('1rem')])),
  h1: variant('2.25rem', {
    fontWeight: 900,
    lineHeight: 1.05,
    letterSpacing: '-0.025em',
    '@media (min-width:0px)': { fontSize: '2rem' },
    '@media (min-width:600px)': { fontSize: '3rem' },
  }),
  button: variant('0.875rem', { fontWeight: 500, textTransform: 'uppercase' }),
}
const theme = (ground) => ({
  shape: { borderRadius: 4 },
  spacing: (n) => `${n * 8}px`,
  typography,
  palette: {
    ...Object.fromEntries(['primary', 'secondary', 'tertiary', 'error', 'warning', 'success', 'info'].map((n) => [n, intent])),
    background: { default: ground, paper: '#FFFFFF' },
    text: { primary: 'rgba(0, 0, 0, 0.87)', secondary: 'rgba(0, 0, 0, 0.6)', disabled: 'rgba(0, 0, 0, 0.38)' },
    divider: 'rgba(0, 0, 0, 0.12)',
    grey: Object.fromEntries([50, 100, 200, 300, 400, 500, 600, 700, 800, 900].map((k) => [k, '#9E9E9E'])),
  },
})

test('the type scale is the phone rung, in points', () => {
  const data = nativeThemeData(theme('#F5F5F5'), theme('#161c21'))
  assert.equal(data.fontFamily, 'Roboto Flex')
  assert.deepEqual(data.typography.h1, { size: 32, weight: 900, lineHeight: 33.6, letterSpacing: -0.8, uppercase: false })
  assert.deepEqual(data.typography.button, { size: 14, weight: 500, lineHeight: 21, letterSpacing: 0, uppercase: true })
  assert.throws(
    () => nativeThemeData({ ...theme('#fff'), typography: { ...typography, h2: variant('1rem', { fontWeight: 450 }) } }, theme('#000')),
    /typography\.h2\.fontWeight 450/,
  )
  assert.throws(
    () => nativeThemeData({ ...theme('#fff'), typography: { ...typography, h2: variant('1rem', { lineHeight: '20px' }) } }, theme('#000')),
    /lineHeight is not a unitless ratio/,
  )
})

test('both sources carry the same tokens as literals', () => {
  const data = nativeThemeData(theme('#F5F5F5'), theme('#161c21'))
  const swift = swiftTokensContent(data)
  assert.match(swift, /GENERATED by tools\/scripts\/generate-mobile-theme-tokens\.mjs/)
  assert.match(swift, /main: Color\(\.sRGB, red: 0 \/ 255, green: 176 \/ 255, blue: 255 \/ 255, opacity: 1\)/)
  assert.match(swift, /background: \(default: Color\(\.sRGB, red: 22 \/ 255, green: 28 \/ 255, blue: 33 \/ 255/)
  assert.match(swift, /public static let h1 = AglynTextStyle\(\n\s+size: 32, weight: \.black, lineHeight: 33\.6, letterSpacing: -0\.8, uppercase: false, relativeTo: \.largeTitle\)/)
  assert.match(swift, /\.custom\(AglynTokens\.fontPostScriptName, size: size, relativeTo: relativeTo\)/)
  const kotlin = kotlinTokensContent(data)
  assert.match(kotlin, /^package com\.aglyn\.ui$/m)
  assert.match(kotlin, /textPrimary = Color\(0xDE000000\)/)
  assert.match(kotlin, /background = Color\(0xFF161C21\)/)
  assert.match(kotlin, /val h1 = AglynTextStyle\(size = 32f, weight = 900, lineHeight = 33\.6f, letterSpacing = -0\.8f, uppercase = false\)/)
  assert.match(kotlin, /val AglynLightColorScheme: ColorScheme = lightColorScheme\(\n {2}primary = Color\(0xFF00B0FF\),/)
  // 14% of #00b0ff over white paper.
  assert.match(kotlin, /primaryContainer = Color\(0xFFDBF4FF\)/)
  assert.match(kotlin, /titleLarge = AglynTokens\.Typography\.h6\.toTextStyle\(fontFamily\)/)
  assert.match(kotlin, /extraLarge = RoundedCornerShape\(28\.dp\)/)
})

test('a console stack that starts with a face the apps do not bundle is refused', () => {
  const other = { ...theme('#fff'), typography: { ...typography, fontFamily: 'Inter, sans-serif' } }
  assert.throws(() => nativeThemeData(other, theme('#000')), /starts with "Inter", and the native apps bundle "Roboto Flex"/)
})
