/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** The native brand assets: the SVG reader, the vector drawables and the asset-catalog JSON. */

import assert from 'node:assert/strict'
import test from 'node:test'

import { adaptiveForeground, brandTextOutputs, imageSetContents, svgPaths, vectorDrawable } from './native-brand.mjs'

const svg = (body, viewBox = '0 0 48 24') =>
  `<?xml version="1.0"?><svg viewBox="${viewBox}" style="fill-rule:evenodd;"><g id="x">${body}</g></svg>`
const mark = svg(
  '<rect x="0" y="0" width="24" height="24" style="fill:none;"/><path d="M0,0l1,1z" style="fill:#e040fb;"/><path d="M2,2l1,1z" style="fill:#fff;fill-rule:nonzero;"/>',
)

test('the paths of a brand SVG, with their fills and fill rules', () => {
  assert.deepEqual(svgPaths(mark, 'm.svg'), {
    width: 48,
    height: 24,
    paths: [
      { d: 'M0,0l1,1z', fill: '#FFE040FB', evenOdd: true },
      { d: 'M2,2l1,1z', fill: '#FFFFFFFF', evenOdd: false },
    ],
  })
})

test('refusals name the shape the converter will not draw', () => {
  const refuse = (body, pattern, viewBox) => assert.throws(() => svgPaths(svg(body, viewBox), 'x.svg'), pattern)
  refuse('<g transform="scale(2)"><path d="M0,0z" style="fill:#000;"/></g>', /<g> with a transform/)
  refuse('<rect width="1" height="1" style="fill:#000;"/>', /visible <rect>/)
  refuse('<circle r="1"/>', /<circle> is not a brand-SVG element/)
  refuse('<path d="M0,0z" style="fill:url(#g);"/>', /is not #rgb or #rrggbb/)
  refuse('<path d="M0,0z" style="fill:#000;"/>', /start at 0 0/, '1 0 24 24')
  refuse('', /no paths/)
})

test('a vector drawable keeps the viewBox and is 24dp tall', () => {
  const xml = vectorDrawable(mark, 'm.svg')
  assert.match(xml, /GENERATED by tools\/scripts\/generate-native-brand-assets\.mjs from m\.svg/)
  assert.match(xml, /android:width="48dp"\n {4}android:height="24dp"/)
  assert.match(xml, /android:fillType="evenOdd"\n {6}android:pathData="M0,0l1,1z"/)
  const icon = adaptiveForeground(svg('<path d="M0,0z" style="fill:#000;"/>', '0 0 24 24'), 'm.svg')
  assert.match(icon, /android:scaleX="2\.0089"/)
  assert.match(icon, /android:translateX="29\.8932"/)
})

test('an image set keeps the vector and adds a dark appearance only when the ink changes', () => {
  const same = JSON.parse(imageSetContents({ apple: 'M', light: 'a.svg', dark: 'a.svg' }))
  assert.equal(same.images.length, 1)
  assert.equal(same.properties['preserves-vector-representation'], true)
  const pair = JSON.parse(imageSetContents({ apple: 'L', light: 'l-dark.svg', dark: 'l-light.svg' }))
  assert.deepEqual(pair.images[1], {
    appearances: [{ appearance: 'luminosity', value: 'dark' }],
    filename: 'L-dark.svg',
    idiom: 'universal',
  })
})

test('every output is named, and the SVGs are copied byte for byte', () => {
  const outputs = brandTextOutputs((name) => Buffer.from(name.includes('text') || name.includes('full') ? svg('<path d="M0,0z" style="fill:#00b0ff;"/>') : mark))
  const files = outputs.map(({ file }) => file)
  assert.equal(new Set(files).size, files.length)
  assert.ok(files.includes('libs/native/apple/Sources/AglynUI/Resources/Brand.xcassets/AglynLogo.imageset/AglynLogo-dark.svg'))
  assert.ok(files.includes('libs/native/kotlin/ui/src/commonMain/composeResources/drawable-dark/aglyn_wordmark.xml'))
  assert.ok(files.includes('apps/android/pos/src/main/res/mipmap-anydpi-v26/ic_launcher.xml'))
  assert.ok(files.includes('apps/ios/AglynPOS/Assets.xcassets/AppIcon.appiconset/Contents.json'))
  const copy = outputs.find(({ file }) => file.endsWith('AglynMark.svg'))
  assert.ok(Buffer.isBuffer(copy.content) && copy.content.equals(Buffer.from(mark)))
})
