/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/** The native brand assets: the SVG reader, the vector drawables and the asset-catalog JSON. */

import assert from 'node:assert/strict'
import test from 'node:test'

import {
  adaptiveBackground,
  adaptiveForeground,
  APP_ICONS,
  appIconContents,
  appIconSvg,
  brandTextOutputs,
  sizedSvg,
  groundGradient,
  iconContainerCount,
  iconRasters,
  launcherBackground,
  imageSetContents,
  layerPaths,
  packIcns,
  packIco,
  RETIRED_OUTPUTS,
  svgPaths,
  vectorDrawable,
} from './native-brand.mjs'

const svg = (body, viewBox = '0 0 48 24') =>
  `<?xml version="1.0"?><svg viewBox="${viewBox}" style="fill-rule:evenodd;"><g id="x">${body}</g></svg>`
const ground =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><!-- note --><defs><linearGradient id="g" x1="0" y1="0" x2="1" y2="1">' +
  '<stop offset="0" stop-color="#00B0FF"/><stop offset="1" stop-color="#E040FB"/></linearGradient></defs><path d="M0 0H1024V1024H0Z" fill="url(#g)"/></svg>'
const receipt =
  '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1024 1024"><defs><filter id="s"><feGaussianBlur stdDeviation="1"/></filter></defs>' +
  '<path d="M1 1H9Z" fill="#FFFFFF" filter="url(#s)"/><path d="M1 1H9Z" fill="#FFFFFF"/><path d="M2 2H8Z" fill="#00B0FF"/></svg>'
const mark = svg(
  '<rect x="0" y="0" width="24" height="24" style="fill:none;"/><path d="M0,0l1,1z" style="fill:#e040fb;"/><path d="M2,2l1,1z" style="fill:#fff;fill-rule:nonzero;"/>',
)

const readIcon = (name) =>
  Buffer.from(
    name.endsWith('ground.svg')
      ? ground
      : name.endsWith('receipt.svg')
        ? receipt
        : svg('<path d="M0,0l1,1z" style="fill:#e040fb;"/>', '0 0 24 24'),
  )

test('the paths of a brand SVG, with their fills and fill rules', () => {
  assert.deepEqual(svgPaths(mark, 'm.svg'), {
    width: 48,
    height: 24,
    paths: [
      { d: 'M0,0l1,1z', fill: '#FFE040FB', evenOdd: true },
      { d: 'M2,2l1,1z', fill: '#FFFFFFFF', evenOdd: false },
    ],
  })
})

test('refusals name the shape the converter will not draw', () => {
  const refuse = (body, pattern, viewBox) =>
    assert.throws(() => svgPaths(svg(body, viewBox), 'x.svg'), pattern)
  refuse(
    '<g transform="scale(2)"><path d="M0,0z" style="fill:#000;"/></g>',
    /<g> with a transform/,
  )
  refuse('<rect width="1" height="1" style="fill:#000;"/>', /visible <rect>/)
  refuse('<circle r="1"/>', /<circle> is not a brand-SVG element/)
  refuse('<path d="M0,0z" style="fill:url(#g);"/>', /is not #rgb or #rrggbb/)
  refuse('<path d="M0,0z" style="fill:#000;"/>', /start at 0 0/, '1 0 24 24')
  refuse('', /no paths/)
})

test('a vector drawable keeps the viewBox and is 24dp tall', () => {
  const xml = vectorDrawable(mark, 'm.svg')
  assert.match(
    xml,
    /GENERATED by tools\/scripts\/generate-native-brand-assets\.mjs from m\.svg/,
  )
  assert.match(xml, /android:width="48dp"\n {4}android:height="24dp"/)
  assert.match(
    xml,
    /android:fillType="evenOdd"\n {6}android:pathData="M0,0l1,1z"/,
  )
})

test('an image set keeps the vector and adds a dark appearance only when the ink changes', () => {
  const same = JSON.parse(
    imageSetContents({ apple: 'M', light: 'a.svg', dark: 'a.svg' }),
  )
  assert.equal(same.images.length, 1)
  assert.equal(same.properties['preserves-vector-representation'], true)
  const pair = JSON.parse(
    imageSetContents({ apple: 'L', light: 'l-dark.svg', dark: 'l-light.svg' }),
  )
  assert.deepEqual(pair.images[1], {
    appearances: [{ appearance: 'luminosity', value: 'dark' }],
    filename: 'L-dark.svg',
    idiom: 'universal',
  })
})

test('every output is named, and the SVGs are copied byte for byte', () => {
  const outputs = brandTextOutputs((name) =>
    name.startsWith('app-icon/')
      ? readIcon(name)
      : Buffer.from(
          name.includes('text') || name.includes('full')
            ? svg('<path d="M0,0z" style="fill:#00b0ff;"/>')
            : mark,
        ),
  )
  const files = outputs.map(({ file }) => file)
  assert.equal(new Set(files).size, files.length)
  assert.ok(
    files.includes(
      'libs/native/apple/Sources/AglynUI/Resources/Brand.xcassets/AglynLogo.imageset/AglynLogo-dark.svg',
    ),
  )
  assert.ok(
    files.includes(
      'libs/native/kotlin/ui/src/commonMain/composeResources/drawable-dark/aglyn_wordmark.xml',
    ),
  )
  assert.ok(
    files.includes(
      'apps/android/pos/src/main/res/mipmap-anydpi-v26/ic_launcher.xml',
    ),
  )
  assert.ok(
    files.includes(
      'apps/ios/AglynPOS/Assets.xcassets/AppIcon.appiconset/Contents.json',
    ),
  )
  assert.ok(
    files.includes(
      'apps/android/app/src/main/res/drawable/ic_launcher_monochrome.xml',
    ),
  )
  const copy = outputs.find(({ file }) => file.endsWith('AglynMark.svg'))
  assert.ok(
    Buffer.isBuffer(copy.content) && copy.content.equals(Buffer.from(mark)),
  )
})

test('the ground gradient is read from its SVG, line and stops', () => {
  assert.deepEqual(groundGradient(ground, 'g.svg'), {
    x1: 0,
    y1: 0,
    x2: 1,
    y2: 1,
    stops: [
      { offset: 0, color: '#FF00B0FF' },
      { offset: 1, color: '#FFE040FB' },
    ],
  })
  assert.throws(() => groundGradient('<svg/>', 'x.svg'), /no <linearGradient>/)
})

test('an icon layer is paths only; a filtered path is its shadow', () => {
  assert.deepEqual(
    layerPaths(receipt, 'r.svg').map(({ fill, shadow }) => [fill, shadow]),
    [
      ['#FFFFFFFF', true],
      ['#FFFFFFFF', false],
      ['#FF00B0FF', false],
    ],
  )
  assert.throws(
    () => layerPaths('<svg><rect width="1"/></svg>', 'x.svg'),
    /<rect> is not an icon-layer element/,
  )
})

test('both apps get their own icon, the POS one printed on the receipt', () => {
  const [aglyn, pos] = APP_ICONS
  assert.equal(aglyn.mark.source, 'aglyn-logo-mark-white.svg')
  assert.equal(pos.mark.source, 'aglyn-logo-mark-multi.svg')
  assert.ok(
    pos.layers.some((layer) => layer.endsWith('native-pos-receipt.svg')),
  )
  const full = appIconSvg(pos, readIcon)
  assert.match(full, /^<svg [^>]*viewBox="0 0 1024 1024"/)
  assert.match(full, /fill="url\(#g\)"/)
  assert.match(
    full,
    /<g transform="translate\(296\.96 179\.2\) scale\(17\.92\)"><path d="M0,0l1,1z" fill="#E040FB"/,
  )
  assert.doesNotMatch(full, /<!--/)
  assert.match(
    appIconSvg(pos, readIcon, 'mac'),
    /<rect x="100" y="100" width="824" height="824" rx="185"\/><\/clipPath>/,
  )
  assert.match(appIconSvg(pos, readIcon, 'windows'), /clip-path="url\(#tile\)"/)
  assert.throws(() => appIconSvg(pos, readIcon, 'tv'), /no app-icon variant/)
})

test('the adaptive icon: gradient background, foreground on the 72dp viewport, outlined monochrome', () => {
  const pos = APP_ICONS[1]
  const bg = adaptiveBackground(pos, readIcon)
  assert.match(
    bg,
    /android:startX="0"\n {10}android:startY="0"\n {10}android:endX="108"\n {10}android:endY="108"/,
  )
  assert.match(bg, /<item android:offset="1" android:color="#FFE040FB" \/>/)
  const fg = adaptiveForeground(pos, readIcon)
  assert.match(
    fg,
    /android:translateX="18"\n {6}android:translateY="18"\n {6}android:scaleX="0\.0703"/,
  )
  assert.match(
    fg,
    /<group android:translateY="12\.288">\n {6}<path\n {10}android:fillColor="#1F001A33"/,
  )
  assert.match(
    launcherBackground(pos, readIcon),
    /<color name="ic_launcher_background">#00B0FF<\/color>/,
  )
  const mono = adaptiveForeground(pos, readIcon, { monochrome: true })
  assert.doesNotMatch(mono, /#1F001A33/)
  assert.match(mono, /android:strokeColor="#FFFFFFFF"/)
})

test('the icon sets: one universal iOS icon and every Mac size at 1x and 2x', () => {
  const { images } = JSON.parse(appIconContents())
  assert.equal(images.length, 11)
  assert.deepEqual(images[images.length - 1], {
    filename: 'AppIcon-mac-1024.png',
    idiom: 'mac',
    scale: '2x',
    size: '512x512',
  })
  const files = new Set(iconRasters().map(({ file }) => file))
  for (const { filename } of images)
    for (const app of ['Aglyn', 'AglynPOS'])
      assert.ok(
        files.has(
          `apps/ios/${app}/Assets.xcassets/AppIcon.appiconset/${filename}`,
        ),
      )
  assert.ok(
    RETIRED_OUTPUTS.includes(
      'apps/ios/AglynPOS/Assets.xcassets/AppIcon.appiconset/AppIcon-512.png',
    ),
  )
})

test('.ico and .icns hold PNGs and count back', () => {
  const png = Buffer.from([0x89, 0x50, 0x4e, 0x47])
  const ico = packIco([
    { size: 16, png },
    { size: 256, png },
  ])
  assert.equal(iconContainerCount(ico, 'ico'), 2)
  assert.equal(ico.readUInt8(6 + 16), 0)
  assert.equal(ico.readUInt32LE(6 + 12), 6 + 32)
  const icns = packIcns([
    { type: 'icp4', png },
    { type: 'ic10', png },
  ])
  assert.equal(icns.toString('ascii', 0, 4), 'icns')
  assert.equal(iconContainerCount(icns, 'icns'), 2)
  assert.equal(iconContainerCount(Buffer.from('nope'), 'icns'), null)
})

test('the launch logo is the full logo, sized on its root element, light and dark, in both apps', () => {
  const source =
    '<?xml version="1.0"?><svg width="100%" height="100%" viewBox="0 0 79 24"><path d="M0,0z"/></svg>'
  assert.equal(
    sizedSvg(Buffer.from(source), 184, 56),
    '<?xml version="1.0"?><svg width="184" height="56" viewBox="0 0 79 24"><path d="M0,0z"/></svg>',
  )
  assert.equal(
    sizedSvg('<svg viewBox="0 0 1 1"/>', 2, 3),
    '<svg height="3" width="2" viewBox="0 0 1 1"/>',
  )
  assert.throws(
    () => sizedSvg('<path/>', 1, 1, 'x.svg'),
    /x\.svg: no <svg> element/,
  )
  const outputs = brandTextOutputs((name) =>
    name.startsWith('app-icon/')
      ? readIcon(name)
      : Buffer.from(
          name.includes('full')
            ? `<svg width="100%" height="100%" viewBox="0 0 79 24" data-ink="${name}"><path d="M0,0z" style="fill:#00b0ff;"/></svg>`
            : mark,
        ),
  )
  for (const app of ['Aglyn', 'AglynPOS']) {
    const set = `apps/ios/${app}/Assets.xcassets/LaunchLogo.imageset`
    const light = outputs.find(({ file }) => file === `${set}/LaunchLogo.svg`)
    const dark = outputs.find(
      ({ file }) => file === `${set}/LaunchLogo-dark.svg`,
    )
    assert.match(
      light.content,
      /width="184" height="56".*data-ink="aglyn-logo-full-dark\.svg"/,
    )
    assert.match(dark.content, /data-ink="aglyn-logo-full-light\.svg"/)
    assert.ok(outputs.some(({ file }) => file === `${set}/Contents.json`))
  }
})
