/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// GENERATED FILE — do not edit. Regenerate with:
//   node tools/scripts/generate-docs-help.mjs
// Source of truth: apps/docs/docs frontmatter + headings (AGL-602).

import type { DocsHelpTopicKey } from './docs-help.generated'

/**
 * The tooltip prose for every help topic — each docs page's frontmatter
 * description, verbatim.
 *
 * Apart from the registry beside it because of when it is read: a help
 * button's `path` is its own `href` and its `title` its accessible name,
 * both wanted the moment the button renders, while the excerpt is wanted only
 * once someone opens the tooltip. Kept together they were ~20 KB of prose
 * parsed by every console page for a hover most visits never make;
 * `DocsHelpExcerpt` fetches this module when a tooltip mounts.
 *
 * A missing key is a compile error, so no topic can lose its excerpt quietly.
 */
export const DOCS_HELP_EXCERPTS = {
  abTestsWithAi: 'Have Aglyn AI write two to four variants for a page, section or email experiment, and put a finished test into plain language — with the verdict decided from the counts before the model is asked anything.',
  abuseReports: 'The public abuse-report queue — where outside reports land, how to triage by severity, which lever answers which report, and the CSAM and DMCA paths that are not takedown buttons.',
  account: 'How console sign-in works — Google sign-in on desktop and mobile, one session across all your workspaces, and automatic sign-out after inactivity.',
  acquisition: 'Where an account or workspace came from: its first visit, the door it signed up through, and whether the sales workspace already knew the person — recorded once at creation, read from one card.',
  actionsBuilder: 'Map a single event to a single action without building a full workflow.',
  activities: 'Log calls, emails, meetings and notes against a contact, a company, a deal or a lead, email one person from their record, and read it all in one timeline beside everything captured and every campaign sent.',
  addALocale: 'Create a language variant of your site and translate its pages.',
  addOns: 'Buy extra seats, sites, datasets, POS registers, the Event Calendar, and Aglyn AI from the Billing page — prorated, self-serve, no support ticket.',
  addSearch: 'Drop the Search Box element onto a page and publish — the built-in search page does the rest.',
  agencySites: 'Run one brief across many client sites: each is its own build job with its own plan and drafts, per-site allotments keep spend separate, and nothing reaches a client\'s live site until your team publishes it.',
  aglynAssist: 'Ask the built-in AI helper how to do anything in Aglyn — it answers from these docs and links you straight to the right page.',
  ai: 'Aglyn AI is an AI website builder inside your console: describe a page, form, email, product listing or theme change and it builds a draft you edit and publish yourself. An add-on on every paid plan, metered in credits.',
  aiAllotments: 'Give a member, a site collaborator or a whole site a monthly share of the workspace\'s AI credits, see your own usage while you work, and choose which model answers.',
  aiMonitoring: 'How staff watch one organization\'s AI usage — add-on, credits, overage, refusals, jobs, tokens, cache hits and margin — read its AI conversations, and find those figures across the staff console.',
  analytics: 'Built-in pageview analytics, the Traffic card and its growth figure, per-page metrics, and average time on a page.',
  animations: 'Add fade, slide and zoom motion to any element, stagger a row of cards, choose when it plays, and keep the page fast and accessible.',
  architectureMultiTenancy: 'How Aglyn organizes tenants — org workspaces, membership with per-site access, security rules, subdomains, and billing attribution.',
  assistSignals: 'The docs-gap and cost board behind Assist — how the ranking is ordered, why ungrounded questions are counted separately, and what the cache-read rate says about margin.',
  automations: 'The CRM events an automation can start on — a contact created or changing stage, a deal moved, won or lost, a task completed — the steps that tag, stage, assign, create a task or log an activity, and one-click recipes.',
  automationsWithAi: 'Aglyn AI drafts an automation from a description, changes or fixes one you already have as a copy switched off, explains what one does and tells you why one of its runs failed.',
  bandwidth: 'How much traffic each plan includes, what happens when a site goes past it, and why a Free site can be paused until the start of next month.',
  besigner: 'Aglyn\'s visual editor — canvas, hierarchy, inline text, multi-select, and placement rules.',
  billing: 'How Aglyn\'s tiers, entitlements, quotas, usage meters, and seat add-ons work.',
  bindings: 'Live values in your content — typed variables, no-code functions, and rename-safe id tokens.',
  bookings: 'Offer services with availability, let visitors book, take payment, and send reminders.',
  buildABlog: 'Create a collection, publish rich entries, and design how its list and entries look with template pages.',
  buildAndPublishASurvey: 'Create a dataset with a typed schema, design a survey form with dropdowns, radios, checkboxes, and a star rating, publish it, and watch responses arrive.',
  buildAWorkflow: 'Create a multi-step workflow that runs when a site event fires.',
  buildingFeaturePlugins: 'The console-extension + frontend-UI plugin pair pattern for shipping features as plugins.',
  bulkActions: 'Select rows in any CRM table — contacts, companies, deals, tasks or leads — and act on all of them at once, or export them as a CSV.',
  businessProfile: 'Tell Aglyn AI what your business does, who it is for and how it sounds. Every AI job for the site reads it, uses your real contact details only, and remembers the edits you keep.',
  catalog: 'Products with options and variants, categories, tags, and manual or smart collections.',
  comingSoonLaunch: 'Put a coming-soon page on your domain, keep the rest of the site out of search while you finish it, collect signups, and reverse all of it on launch day.',
  commerce: 'Sell physical, digital, and service products with a full catalog, orders pipeline, shipping, taxes, and your own Stripe account.',
  commerceEndToEnd: 'Create products with billing modes, design the storefront with Commerce blocks, take Stripe checkout for one-time and subscription sales, and run orders from the console.',
  companies: 'Group your contacts under the businesses they belong to — one record per company, with its domain, owner, type, industry, addresses, parent company and the people who work there.',
  components: 'Promote a subtree into a reusable component, give it properties, and insert instances across pages.',
  connectADomain: 'Point your own domain at your Aglyn site — a CNAME for a subdomain, an ALIAS for a bare apex — and verify with one click.',
  consoleAndSite: 'Task-ordered recipes for nav/pages/widgets/providers and canvas components/site runtimes.',
  consoleSearch: 'What the console search palette can find, how it matches what you type, and the two things it deliberately does not search.',
  consoleTour: 'Where things live in the Aglyn console app bar and navigation.',
  contactRecord: 'Add a contact by hand, keep a profile on them — Salesforce\'s standard contact fields, from salutation and phones to assistant and reports-to — open their own page in the CRM, and merge two records that are one person.',
  content: 'Start from templates, drop in pre-built sections and blocks, and publish a blog with collections.',
  cookieConsent: 'Ask visitors before analytics runs — or track immediately where the law allows, with an always-available opt-out. Google Analytics and Tag Manager tags never load for a visitor whose recorded state does not grant them.',
  copyAssist: 'An AI copywriter for the words already on your site: rewrite a headline, a paragraph, a button label or a blog entry in your own voice, as an unsaved change one undo takes back.',
  copyPaste: 'Copy any element — with its children — and paste it elsewhere, including into a different page, layout or component.',
  createARedirect: 'Add a redirect rule and read its hit metrics.',
  createImages: 'An AI image generator in the Aglyn media library: describe a picture and get an SVG icon or logo mark, a realistic photo, a watercolor, a 3D render or a banner, with alt text. Metered in AI credits.',
  crm: 'One place for the people who interact with your sites — contacts captured from forms, members, orders and bookings, with leads, companies, a deals pipeline, tasks, a timeline, reports and custom fields.',
  crmByAi: 'An AI CRM for small business: a short summary and a suggested next step on a contact, company, deal or lead, a one-to-one email drafted into the composer, and an import\'s columns matched to fields.',
  customDomains: 'Connect your own domain — subdomain or bare apex — with one-click DNS verification.',
  customFields: 'Define your own properties on contacts, companies, deals and leads — text, number, date, choice, checkbox or link — show them on every record and its list, and save form answers straight into a contact\'s.',
  customRoles: 'Define roles with unique permission sets and fine-tune access per member.',
  datasets: 'Model structured content with typed fields and relations, then bind it into repeatable components.',
  datasetsAndSchema: 'Field ids vs display names, the typed model, per-plan record quotas, import/export, repeatables with item bindings, and every writer that can append records.',
  deals: 'Every open deal by stage — with an amount, an owner and an expected close — as a board you drag across or a table you page through, and the won and lost history behind it.',
  deliverabilityChecks: 'Why an email is not sent to a domain that takes no mail, when bulk mail waits behind a gateway refusing your sender, and how sender readiness reads SPF, DKIM and DMARC.',
  designedEmails: 'Build campaign emails in the besigner with email-safe blocks and merge tokens — no separate editor.',
  domainProviders: 'Make hostnames actually resolve on a self-hosted install — choose a domain driver, run the wildcard path end to end, or implement the webhook contract against your own proxy.',
  downgradingAndCanceling: 'What happens when you downgrade, cancel, or delete — when each takes effect, what the cancel dialog offers you, and how to export first.',
  dragDropHierarchy: 'Everything drag-and-drop in the Besigner — where you can drag, how drop zones and placement markers work, containers vs. leaf elements, placement rules, and multi-drag.',
  editFromTheLiveSite: 'The admin bar on your published site — who sees it, how it appears on your Aglyn subdomain and on your own domain, what it links to, and how to hide it.',
  editYourTheme: 'Set colors, fonts, and light/dark schemes with a live preview.',
  elementCatalog: 'Every built-in element you can drop on the canvas, grouped by the categories in the ELEMENTS drawer.',
  emailCampaigns: 'Campaigns to audiences built from your contacts. Campaign email starts at Pro and needs a sending domain of the site\'s own; receipts and account email send on every plan.',
  emailPlatforms: 'Keep your contacts and their unsubscribes in step with your own Mailchimp, Klaviyo or Omnisend account, both ways, and send your orders to Klaviyo and Omnisend for their abandoned-cart and post-purchase flows.',
  emailTemplates: 'Keep the letters your team sends from a record — templates that fill in the subject and the message, snippets that drop in a paragraph, and merge fields that fill in the person\'s name, their company, the deal and you.',
  enterprise: 'What the Enterprise plan adds — single sign-on, a dedicated support commitment, and the security material a procurement review asks for.',
  errorScreens: 'Replace the generic 404/401/403/503 pages with branded ones you design.',
  events: 'Keep a schedule of events in the console and publish the ones you choose to any page, with search-engine event markup.',
  examples: 'Where to look for a working example of each plugin pattern.',
  export: 'Choose every field you want, custom fields included, and the records — the selection, the list\'s filter or everything — as a CSV, JSON or NDJSON file that imports back in.',
  extensionPoints: 'Every surface a plugin can extend, when it runs, and which part of Aglyn it reaches.',
  featureFlags: 'Release-gate console features with Firebase Remote Config — staff always see everything, customers see what\'s launched.',
  firstPartySurfaces: 'How to make a new site of ours — a forum, a status page, a second domain — count its visitors\' first touch: register its host, include one script tag. Nothing else, and nothing to configure on a self-hosted install.',
  firstPlugin: 'The full loop — scaffold, develop against a live workspace, verify, publish, install, uninstall.',
  forms: 'Add forms to your site, collect submissions in an inbox, and write them into datasets.',
  funnels: 'See how visitors move through the steps you care about, where they drop off and how long each step takes; build or explain a funnel with Aglyn AI, and follow up with people who dropped off.',
  generateAComponentWithAglynAi: 'Describe a block your site repeats, or point at one already on a page, and Aglyn AI makes it a reusable component with typed properties bound to the elements that show them.',
  generateAForm: 'An AI form generator inside Aglyn: describe the form you need and a build job makes it as a draft on the Forms page, with its fields, required answers, marketing consent and routing already agreed.',
  generateAPage: 'An AI landing page generator built into the canvas: describe a page and Aglyn AI plans it, then builds it section by section as an unpublished draft from your own theme, layout, components and forms.',
  generateASite: 'Generate a website from a prompt: describe a business and an Aglyn AI build job plans a small site — pages, navigation, layout, contact form and palette — then builds it. A guided start publishes it.',
  generateSection: 'Describe a section and Aglyn AI builds it from real components, on the page you have open, as an unsaved change you can undo.',
  generateWithAi: 'An AI email campaign generator that drafts rather than sends: turn a brief into a draft email design, or a draft campaign and the email it would send. Nothing is sent, and nothing is aimed at anybody, until you choose.',
  gettingStarted: 'Sign in, create your first site, and understand what a site contains.',
  glossary: 'What organization, workspace, tenant, host, and site each mean — and which word to use where.',
  googleAnalytics: 'Every event your site sends to your own GA4 property, with the exact parameters each one carries — so you can build a report against it before you have any data.',
  howAglynAiBuilds: 'Every AI build reuses what your site already has, takes its colors and spacing from your theme, and arrives as a draft. Every plan is checked against those rules before you see it, asked again, then stopped.',
  import: 'Bring people or companies into the CRM from a file — other CRMs\' exports map themselves — see every match and conflict in a dry run, choose how each is handled, and undo for seven days.',
  importAndExport: 'Render the field-picking export dialog and the eight-step import wizard for your plugin\'s records, with your own steps and locked rules.',
  importExport: 'Export the fields you choose, and import a file with column mapping, record matching, a choice for every conflict, a dry run and undo.',
  injectionZones: 'Every named console zone a plugin widget can render into, and what each receives.',
  insights: 'Ask Aglyn AI a question about your site\'s figures in plain words, and get answers where every number is traced to the figure it comes from — plus weekly insights by email.',
  installYourFirstPlugin: 'A click-by-click walkthrough of the Marketplace — find something, choose which sites get it, install it, and turn it off again.',
  interactions: 'Build element interactions in one dialog and drop sanitized custom markup anywhere.',
  inviteTeammates: 'Add people to your site and understand how team members act within your organization.',
  languageSwitcher: 'Let visitors move between your site\'s locales.',
  layouts: 'A layout is the shared frame your pages render inside — header, nav and footer in one place, nested up to five deep.',
  leads: 'Work the people your site has captured — a status, an owner and notes on every lead — and convert one into a contact, a company and a deal.',
  liveCoEditing: 'See who else is editing, work on the same document together, survive save conflicts, and recover unsaved changes after a crash.',
  lockdown: 'The staff panic button — disable access platform-wide or for one workspace, site, or account, with a real logout and a visitor notice.',
  logicWithAi: 'Aglyn AI writes a site function or variable from a description, changes or fixes a function you have, explains what one works out, and offers a fix for a broken automation reference. Nothing is saved until you save it.',
  longFormMarkdown: 'Put a whole policy, terms or handbook page on the canvas as one Markdown element, and let a Table of contents element build the "On this page" list from its headings.',
  maintenance: 'The staff maintenance jobs — whether each scheduled job is still running, what a run would do, and how to run one by hand without firing an irreversible sweep by accident.',
  maintenanceMode: 'Temporarily take your site offline behind a designed 503 page.',
  manageAccount: 'Your personal account — email, sign-in methods, avatar, name, and password.',
  manifestAndEnvs: 'The plugin manifest schema, the marketplace listing/version documents, the trust state machine, and every PLUGIN_* environment variable.',
  marketingOverlays: 'Site-wide announcement bars and promotional popups with triggers, scheduling, and email capture.',
  marketingWithAi: 'Use Aglyn AI on your site\'s Marketing page: write announcement bar and popup copy, create a switched-off overlay or a draft campaign from a brief, and ask what your conversions and campaign figures mean.',
  media: 'Organize images, video, and files in folders, transform them, and serve them fast over a CDN.',
  megaMenuWithInteractions: 'Add a SaaS-style mega menu to your nav bar, fill it with columns of links, and make it open on hover — entirely in the Besigner, on any plan.',
  members: 'Let visitors sign up on your site, design an account page with the Customer account block, gate pages to members, and manage members from the console Users page.',
  membersOnly: 'Let visitors sign up as members and gate pages so only members can view them.',
  menusAndNavigation: 'Dropdown menus, hover mega menus, and slide-in drawers — authorable entirely in the besigner.',
  migrationPatterns: 'Common redirect setups when you rename pages or move a site into Aglyn.',
  modelBuilder: 'Define a dataset model with typed fields and edit records in the typed editor.',
  multilingual: 'Offer your site in multiple languages with locale variants, hreflang, and a language switcher.',
  multiSelect: 'Select several elements at once and move the whole selection together.',
  onboardingDeepLinks: 'The plan-aware signup contract the marketing pricing page links into, and what the console does with it.',
  operatorAlerts: 'Every event an install operator must hear about: which alerts exist, where they go (email and an optional webhook), how staff switch them or batch them daily, and how health checks alert on their own.',
  orderNotifications: 'The emails your customers get about their orders, the private order status page they link to, and how to resend a receipt.',
  ordersAndReturns: 'Ship an order in parts with tracking links, run returns from request to refund, print invoices, and send order events to your own systems.',
  orgAutomations: 'Write an automation once for the whole organization and run it on the sites you choose, with a pause on each site.',
  passwordAScreen: 'Require a password to view a specific page.',
  pickupAndLocalDelivery: 'Let buyers pick up orders at your locations or have your own driver deliver them, with pickup hours, delivery zones, fees, minimums and delivery times.',
  platformHealth: 'The staff health board — serving, backups, rate limiters, signup volume, email delivery and CSP violations, with what each red light means and what to do.',
  pluginConfig: 'Declare a settings schema and get a console form for free — plus the three layers a setting is answered at, workspace defaults with per-site overrides, and the one write that clears one.',
  pluginManagerApi: 'Every public registration and loading API a plugin can use, from `@aglyn/aglyn` and `@aglyn/aglyn/server`.',
  plugins: 'Extend Aglyn with sandboxed plugins — install from the marketplace, configure them, and publish your own.',
  pos: 'Sell in person from the console register and take date-range reservations with deposits.',
  posHardware: 'Card readers, a customer display tablet, driverless receipt and kitchen printers, a cash drawer that opens on cash sales, camera and USB barcode scanning, and product and shipping labels.',
  posOperations: 'Shifts and the cash drawer with X and Z reports, staff PINs, customers at the register, returns and exchanges, printed thermal receipts, and selling cash while the register is offline.',
  productsWithAi: 'An AI product description generator for your catalog: write copy for one product or a whole import, propose a first catalog, and propose categories and discounts — all as proposals you review.',
  publishAPlugin: 'Ship your own plugin to the marketplace with version pinning.',
  publisherHandbook: 'Publishing to the Aglyn marketplace — from profile setup through listing authoring, review, updates, and getting paid.',
  publishYourFirstScreen: 'Create a page, design it in the Besigner, and publish it live.',
  realmBundles: 'The end-to-end path from a standalone bundle to first-party-grade code running in the app realm.',
  redirects: 'Manage URL redirects with validation, loop detection, and hit metrics.',
  refunds: 'Refunding an organization\'s subscription charge from its org page — how much each staff role may refund before it escalates, why a refund is a loss rather than a reversal, and the audit row it writes.',
  relations: 'Link records together with reference fields, including many-to-many.',
  repeat: 'Make any element render once per record — a list, a grid, a gallery — see the real copies on the canvas, and bound them with a filter, a sort and a limit.',
  reportAnIssue: 'File a bug, an idea, or a question from any page in the console — on every plan, including Free.',
  reports: 'New contacts, their sources and which convert, the lead funnel and lead sources, the open pipeline and its forecast, won and lost, who logged what, and the task load — counted on the server, all exportable as CSV.',
  responsiveStyling: 'Style per breakpoint from the artboard preview, use the box stylers, custom classes, and the CSS builder.',
  revenue: 'What Aglyn earned — contracted plan value and settled Stripe cash side by side, the gap between them broken into named causes, and every deduction between gross and net.',
  rewardsAndReferrals: 'Give customers points on every order, online and at the register, let them spend points and store credit at checkout or the till, and reward members whose friends buy.',
  runAnAgencyWorkspace: 'Set up one Aglyn workspace to build and hand off many client sites — templates, collaborator seats, per-site access, domains, backups and billing.',
  salesChannels: 'List your products on Google, YouTube, Facebook, Instagram, TikTok, Pinterest, Snapchat and Microsoft Shopping with a product feed for each.',
  salesTaxReturn: 'The quarterly Texas return — pick a period, read the Form 01-114 figures, check the rows that need attention, and export the working papers.',
  sandboxSecurity: 'How sandboxed marketplace plugins are isolated — separate origin, per-manifest CSP, pinned artifacts — and what that means when you write one.',
  saveATemplate: 'Turn a site into a reusable template and install marketplace templates.',
  screens: 'How each page of your site gets a slug, how the hierarchy builds your URLs, how groups organize pages without changing them, and which pages count against your plan.',
  screensAndLayouts: 'The four building blocks of a site\'s structure — pages, layouts, reusable components and templates — and which one you want.',
  securityAndCompliance: 'Where the security material for a procurement review lives, and what we do not have.',
  selfHosting: 'Run the whole Aglyn platform on your own infrastructure with Docker — your own Firebase project, your own domains, your own keys.',
  selfHostingEnvironment: 'Every environment variable a self-hosted Aglyn deployment reads — what it drives, where to get its value, what shape it takes, and whether changing it needs a rebuild.',
  seo: 'Per-page SEO, sitemap and robots, Open Graph/Twitter cards, and structured data.',
  seoByAi: 'AI SEO for websites, on the pages you already have: have AI write a page or product\'s search listing, propose a fix for each finding of the SEO check, and draft your structured data and /llms.txt.',
  sequences: 'One-to-one email sequences a rep sends to a person from their own connected mailbox, kept with the CRM. Rolling out.',
  serverApis: 'Plugin API routes behind the dispatchers, Stripe/Svix signature verification, billing hooks, and scheduled jobs.',
  serviceAndLocationPagesFromADataset: 'Give every record of a dataset its own page from one design — a page per service, per location or per team member, each at its own address, with search titles from your fields and every page in the sitemap.',
  settings: 'What the CRM does on its own for every site — whether a company is created from a contact\'s work email domain, who a new contact is assigned to, the address that files replies on a record, and each site\'s recipes.',
  sharing: 'Let another of your sites see a lead, a contact, a company or a deal — one record by hand, a selection from a list, or every record a sharing rule matches, now and later — without sharing the person\'s consent.',
  shipping: 'Shipping zones and rates, local pickup, and the postal address each inventory location ships from.',
  siteBackupAndPackages: 'Download a site or the items you pick as one package, import one into any of your sites, compare each item with the site\'s copy and choose how to handle it before anything is written, and undo an import.',
  siteProtection: 'Password-protect pages, design custom error pages, and put your site in maintenance mode.',
  siteSearch: 'Let visitors search your site\'s pages, blog entries, and dataset records with a built-in search page.',
  sso: 'How to set up SAML SSO yourself, how domain verification works, what enforcement does, and the consequences of SSO accounts living in their own identity pool.',
  staffConsole: 'Aglyn-staff tools for managing organizations, entitlements, users, and audits.',
  storeImportAndExport: 'Import products from a file or Shopify, update them by handle or SKU, issue gift cards, record shipments from a tracking file, and export store data with the fields you choose.',
  supportAndCommunity: 'Open a support ticket with the Aglyn team, and ask other builders in the community forum.',
  supportQueue: 'Triage customer support tickets from the staff console — filter, reply as Aglyn, and close or reopen.',
  supportTiers: 'The first-response commitment attached to each plan, why Enterprise is quoted in clock hours, and where ticket support starts.',
  supportTriage: 'How Aglyn staff triage an incoming support ticket — priority, the billing answers, and every escalation route out of the queue.',
  tasks: 'Calls, emails, meetings and to-dos with a status, a due date, an assignee and a link to the record they are for — overdue and today read off the clock, a snooze, a reminder at its own time, and a morning digest.',
  taxServices: 'Connect your own Avalara AvaTax or TaxJar account so checkout and the register charge the sales tax it calculates, and your paid orders and refunds are recorded there.',
  team: 'Invite teammates with custom roles, and offer members-only areas to your site\'s visitors.',
  templatesLibrary: 'Save pages, components and layouts as reusable templates — and the safe landing place for anything you install from the marketplace.',
  termReference: 'Every term Aglyn uses, in one place — brief definitions with links to the full documentation for each.',
  textEditing: 'Edit text directly on the canvas, on the element itself, with basic rich text on opt-in elements.',
  themeAssist: 'Describe a change to your site\'s theme and get a proposal for the theme editor\'s own controls, previewed before and after, that you save in the editor.',
  themeBuilder: 'Set your site\'s colors, fonts, and light/dark schemes with a live preview.',
  themeStyles: 'Style from your site\'s theme instead of typing pixels, so a brand change moves every page at once.',
  transferHub: 'Move records and packages in and out of your workspace — choose the fields you export, match columns and existing records on import, decide every conflict, review a dry run, and undo an import for seven days.',
  troubleshooting: 'Fix the common reasons a custom domain won\'t verify or attach.',
  uptimeAndStatus: 'The live status page, what it does and does not show, and why there is no committed uptime percentage yet.',
  usePirateShip: 'Export unshipped orders for Pirate Ship, buy the labels there, then import its shipment report to mark each order shipped and email tracking links. Works for Shippo and EasyPost too.',
  useShippingeasy: 'Connect your ShippingEasy account so paid orders go there as they are paid, and each label you buy marks the order shipped and emails your customer the tracking link.',
  useShipstation: 'Connect ShipStation to your Aglyn store as a Custom Store, so it imports the orders you still have to ship and each label you buy there marks the order shipped and emails your customer the tracking link.',
  versionsAndPublishing: 'Every page, layout and reusable component keeps named versions — publish one, roll back to an older one, or schedule one to go live.',
  video: 'The Video element — the poster frame that decides what a visitor downloads, captions, the lightbox, and the fields a video search result reads.',
  views: 'Keep a CRM list\'s filters, columns and sort under a name, open it from the views menu or a link, share it with the team, and use a contacts view as an email audience.',
  webhooks: 'Connect Aglyn to other systems with outbound and inbound webhooks.',
  whiteLabel: 'Replace the Aglyn brand across the console, your published sites, and transactional email — product name, logo, colors, support URL, and email from-name.',
  workflows: 'Automate your site — run multi-step workflows on site events, and connect to other systems with webhooks.',
  yourFirstApiCall: 'Create an API key in the console, make your first request, read the response, handle the four errors you will actually hit, and page through a whole dataset.',
} as const satisfies Record<DocsHelpTopicKey, string>

/**
 * The opening sentence under each linked heading — the tooltip's prose when a
 * call names an anchor and no excerpt of its own (AGL-3707). Without it every
 * anchor on a page printed that page's description, so one blurb stood in for
 * twenty different cards.
 */
export const DOCS_HELP_SECTION_EXCERPTS: {
  readonly [K in DocsHelpTopicKey]?: { readonly [anchor: `#${string}`]: string }
} = {
  abuseReports: {
    '#counter-notices': 'A subscriber whose material we removed can answer with a counter-notice under §512(g).',
    '#statuses': 'Dismissed is not the same as unread. If you dismiss without a reason, the next person to receive a report about the same site has no idea whether we already considered it.',
    '#triage-by-severity': 'Every category carries a severity. It is not a mood — it says how fast a human has to look.',
  },
  account: {
    '#closing-your-account': 'Manage Account → Close account permanently deletes your personal account.',
    '#downloading-your-data': 'Manage Account → Close account → Download my data gives you a machine-readable JSON copy of everything we hold about you: your profile and contact details, your workspace memberships, your passkeys, your public…',
    '#privacy-requests': 'Settings → Privacy is where a workspace answers the people its sites hold: someone who asks for the data you keep about them, or asks to be forgotten.',
    '#recent-sign-ins': 'When your account is signed in to from a device it has not been used on before, we email you: the device, the approximate location, the IP address, and the time.',
    '#resetting-your-password': 'Forgot your password? From the sign-in page, choose Account recovery and enter your email.',
  },
  actionsBuilder: {
    '#create-an-action': 'Open the actions builder from Automation → Actions. That\'s it — no multi-step logic to manage.',
  },
  addOns: {
    '#assigning-collaborator-seats': 'Collaborator seats work exactly like register seats: a seat is bought once for your workspace and then assigned to one site.',
    '#assigning-register-seats': 'Unlike every other add-on, a POS register seat is bought once for your workspace and then assigned to one site.',
    '#what-you-can-add': 'Prices are per unit per month. On annual billing, add-ons bill yearly alongside your plan (12× the monthly price) — a subscription has one billing interval.',
  },
  aglynAssist: {
    '#what-it-can-do': 'Answer how-to questions about building sites, publishing, domains, commerce, bookings, workflows, datasets, team roles, and billing.',
  },
  aiMonitoring: {
    '#ai-conversations': 'Below the AI card, AI conversations shows what people in the organization typed to Aglyn AI and what it answered.',
    '#one-account': 'Staff → Users → an account carries a card named after the AI add-on with the account\'s credits in every workspace it belongs to, month by month — the same rollup the customer\'s Team and Usage pages read, kept…',
    '#the-ai-card': 'On Staff → Organizations → an organization, between Effective entitlements and Metered usage, the card named after the AI add-on carries everything about that organization\'s AI in one place.',
    '#the-spend-leaderboard': 'Staff → Assist signal opens with AI spend this month, by workspace: each organization\'s plan, whether the add-on is on, credits drawn, provider dollars and refusals for the current month, dearest first, above the…',
  },
  analytics: {
    '#dwell-time': 'Beside Page views, that card shows Avg. time on this page — how long a visitor stayed before leaving it.',
    '#google-analytics': 'Prefer your own tooling? Add a Google Analytics measurement ID under Site → Setup → Tracking and Aglyn injects it alongside the built-in tracking.',
    '#per-screen-traffic': 'Pro+ sites get a per-page traffic panel in each page\'s detail view, with pageviews attributed to the page and broken down by referrer and device — and a Pages table on the site\'s analytics page comparing pageview…',
    '#traffic-card': 'The Traffic card on a site\'s dashboard is the one most people read.',
  },
  architectureMultiTenancy: {
    '#billing--cost-attribution': 'Plans and entitlements live on the org doc — the uid-keyed tenants collection retired with the AGL-238 cutover.',
    '#data-model': 'Everything lives in one Firestore database.',
    '#membership-lifecycle': 'All mutations flow through API routes so three places stay consistent — the member doc, the reverse index, and every affected host\'s projection.',
    '#workspace-subdomains': 'Each org gets a Slack-style workspace address.',
  },
  assistSignals: {
    '#docs-gaps': 'Cited pages ranked by thumbs-down first, then by how often a question landed there.',
    '#fleet': 'Totals across the scanned sample: messages, tokens, estimated cost, the thumbs tally, and how turns stopped.',
    '#questions-the-docs-could-not-answer': 'A turn with no cited docs paths is a question the corpus could not match at all, so the model answered ungrounded — from its own knowledge of the product, with nothing to link.',
    '#tokens-by-kind': 'What each kind of model request costs and weighs, one row per kind, dearest first: the console assistant (assist), the Besigner\'s copy modes (element, section, blog) and each generation job kind.',
    '#what-assist-costs-by-workspace': 'The same estimated cost as Where the money goes, per workspace, dearest first, with each workspace\'s thumbs-down count beside it.',
    '#what-people-actually-asked': 'The verbatim question behind each failing turn, with the answer it got.',
    '#where-the-money-goes': 'Costs on this board are our estimated provider cost at the serving model\'s list rates.',
  },
  bandwidth: {
    '#where-to-see-it': 'In the console, open Billing from the organization menu. The meter resets on the first of each month, in UTC.',
  },
  besigner: {
    '#what-you-can-do': 'Drag-and-drop components from the drawer onto the canvas, and reparent them by dragging in the hierarchy or on the canvas.',
  },
  billing: {
    '#ai-allotments': 'Beneath that table, AI allotments gives a team member, a site collaborator on one site, or a whole site a monthly share of the workspace\'s AI credits.',
    '#assist-overage': 'Paid plans include a monthly band of AI assist credits — the Aglyn Assist credits meter on the billing page shows how much of it this month\'s assistant use has drawn.',
    '#billing-address': 'The address Aglyn issues your invoices to, and the address sales tax on your Aglyn subscription is calculated from.',
    '#billing-email': 'Invoices are sent to the billing email, along with receipts and — the one that matters most — the notices we send when a card fails and a subscription is about to lapse.',
    '#crm-records': 'Your CRM — the contacts captured from forms, member sign-ups, buyers and bookings, and the companies and deals your team files beside them — is priced as one CRM records band, not a hard cap.',
    '#one-to-one-email': 'A one-to-one email is a message a teammate writes to one person from a CRM record — Send email on a contact\'s, a lead\'s or a deal\'s page, described under Activities & the timeline — as against a campaign, which is…',
    '#outstanding': 'If a payment fails, the invoice stays open and the Billing page shows it with a Pay now button.',
    '#payment-methods': 'The cards your subscription and any usage overage are charged to.',
    '#payments': 'Billing runs through Stripe. Paid features (commerce, bookings, campaigns) share the same Stripe integration.',
    '#plan-total': 'Before you subscribe, the Billing page quotes the plan you are looking at with tax included, taken from Stripe\'s own invoice preview rather than worked out here.',
    '#seats': 'Team seats (workspace-wide) and per-site collaborator seats are metered and enforced per tier — seats cover the people who build and manage your sites.',
    '#storage-overage': 'Your plan includes an amount of storage for each of its sites, and the workspace shares it as one allowance: every site\'s media library and the organization library draw on the same total.',
    '#tax-ids': 'A business tax ID — VAT, ABN, GST, EIN and the rest — printed on the invoices we issue you.',
    '#tiers--entitlements': 'Transaction fees are Aglyn platform fees on the sales you take through your site — storefront orders, paid memberships and paid bookings alike — separate from Stripe\'s payment-processing fees.',
    '#usage-budget': 'A usage budget is a monthly amount you choose, plus the percentages of it you want to hear about — the same shape as a Google Cloud billing budget.',
    '#usage-meters': 'The billing page shows meters for every quota — storage, bandwidth, datasets, seats, sends, CRM records (with the contacts, companies and deals beneath the total), one-to-one emails sent today, AI assist credits,…',
    '#who-is-generating-what': 'Beneath the meters on Billing → Usage, a table lists each member\'s AI credits for a month — their share of the workspace\'s spend, requests, and how often the assistant refused them — dearest first, with the kinds of…',
  },
  bindings: {
    '#insert-a-variable': 'You never have to hand-type token syntax. Every text-capable attribute field in the Besigner (Text, Link URL, Image URL, …) has a small {x} insert button at its end.',
    '#no-code-functions': 'Build functions in the in-editor function builder with a safe evaluator — no arbitrary code execution.',
    '#typed-variables': 'Create typed site variables and reference them as {{name}} in any prop.',
    '#where-used--safety': 'Before you rename or delete a variable or function, run the where-used scan to see every page and prop that references it, so changes are safe.',
  },
  bookings: {
    '#manage': 'Use the console bookings page to see and manage upcoming appointments.',
    '#reminders': 'Every confirmed booking gets one reminder email roughly a day before it starts.',
    '#set-up-bookings': 'Define services (what can be booked, duration, price).',
  },
  buildABlog: {
    '#2-write-entries': 'Add rich blog entries with images, a live preview, and scheduling so posts publish at the right time.',
    '#authors': 'Content is often published under a byline that is not the account that wrote it — a pen name, a guest contributor, or the company itself.',
    '#scheduling': 'The same three publication controls live in two places, so you can decide when a post goes live without leaving what you\'re doing: the entry row\'s actions menu in the list, and a Publication panel at the bottom of…',
    '#visual-editor': 'The body opens in a Visual tab — a WYSIWYG surface where you edit the formatted article directly.',
  },
  buildAWorkflow: {
    '#1-open-the-workflows-page': 'In the console, go to Automation → Workflows and choose New workflow.',
    '#4-save-and-test': 'Save the workflow. When the trigger fires, the workflow runs and each run counts once toward your tier\'s metered allowance — however many steps it has, and whatever they are.',
  },
  businessProfile: {
    '#contact-details-are-never-invented': 'The name, business type, email, phone, address, opening hours and social profiles come only from Setup → Basic details and Setup → SEO, exactly as entered.',
  },
  catalog: {
    '#categories-and-tags': 'Categories are hierarchical (each may have a parent) and slugged for URLs.',
    '#products-options-and-variants': 'A product is what you manage; a variant is what a customer actually buys.',
  },
  commerce: {
    '#dropshipping': 'Assign a supplier to a product and paid orders route automatically — by email and/or HMAC-signed webhook — with a token link the supplier uses to post tracking back, which fulfills the order.',
    '#gift-cards': 'Gift cards lists every card your store has issued, what is left on each one, and what that adds up to.',
    '#inventory': 'Per-variant stock; blank = untracked, 0 = sold out.',
    '#orders': 'Every paid checkout becomes an order with a sequential number, line-item snapshots, totals, and a timeline: Statuses: pending → paid → fulfilled (or partially) → delivered, with cancel/refund exits guarded by a…',
    '#orders-screen': 'Open your site\'s Products hub and choose the Orders tab. Before your first sale the tab is an invitation rather than a table: it explains where orders come from and offers Draft order, so you can invoice a customer…',
    '#payment-methods': 'Settings → Payment methods chooses what shoppers may pay with besides a card.',
    '#pickup-and-local-delivery': 'Buyers can choose to pick up an order at one of your locations, or have your own driver deliver it, instead of shipping.',
    '#products-hub': 'The Products page is the catalog manager: Products with up to 3 options and 100 variants each — per-variant SKU, barcode, price, compare-at (sale badge), weight, and stock.',
    '#recovery-and-alerts': 'Two queues the storefront fills and Aglyn drains for you, both visible so you can see they are moving.',
    '#shipping--taxes': 'Shipping zones own countries (\'*\' = rest of world); rates are flat, free-over-subtotal, or subtotal/weight tiers; optional local pickup.',
    '#stock-movements': 'Inventory → Stock movements is the history behind every tracked count — the answer to "the shelf says four and the console says six, what happened?"',
    '#storefront-sales-tax': 'Analytics → Storefront sales tax shows what your storefront collected in a period.',
  },
  commerceEndToEnd: {
    '#1-connect-payments': 'Aglyn sells from your own Stripe account via Stripe Connect.',
    '#4-what-checkout-does': 'Both buy buttons and the cart\'s Checkout open the payment form in place, on your own site, below the button.',
    '#the-product-page-template': 'Individual product URLs (/products/{slug}) render through a template page: design a page containing a Product detail block, then set it as the Product page template in the Products hub\'s Settings tab (store settings).',
  },
  companies: {
    '#a-companys-page': 'The page names the company in the heading and the trail, and holds its properties, its contacts, its deals, its open tasks and the activity logged against it.',
    '#contacts-at-a-company': 'The Contacts card lists the people linked to this company a page at a time, most recently updated first, with the total counted by the database in its footer; each row opens the person\'s page.',
    '#create-a-company': 'Choose New company above the list. A company needs a name; everything else is optional: Domain — the bare hostname (acme.com).',
    '#the-companies-list': 'The list shows every company your site may see, most recently changed first, with its domain, how many contacts are linked to it, its owner, when it was last changed and its next activity — when the earliest open…',
  },
  components: {
    '#properties': 'A component doesn\'t have to look identical everywhere. Give it properties and each place you use it supplies its own text, image, link, color or choice — while the layout and the styling still come from the one…',
    '#save-then-publish': 'Saving is not publishing. Live pages read the published component.',
    '#used-by': 'A component\'s detail page has a Used by card listing everything that places an instance of it, so deleting one is not a guess.',
  },
  connectADomain: {
    '#steps': 'In the site\'s Admin page, choose Custom Domain in its navigation.',
  },
  consoleTour: {
    '#a-sites-dashboard': 'Opening a site lands you on its dashboard.',
    '#alerts-on-this-device': 'At the foot of the Settings section, three switches control how a new notification reaches you in this browser: Unread count in tab title — badges the browser tab, e.g.',
    '#daily-digests': 'Daily CRM digest is on by default. Each morning it sends you one notification and one email listing your overdue and due-today tasks and the leads nobody has worked, across every workspace you belong to.',
    '#notification-settings': 'Everything about what reaches you lives on the second section, Settings.',
    '#the-app-bar': 'Site switcher (left) — jump between the sites you belong to, search them by name with Find site…, or create a new one.',
    '#the-sites-list': 'All Sites is the front door of a workspace: one card per site, for the workspace currently selected in the switcher, in name order.',
    '#workspace-and-site-overrides': 'One workspace or one site sets the same answers for a single workspace or a single site, rather than for your whole account.',
    '#workspace-settings--notifications': 'Organization-wide settings (name, workspace URL) live under Organization → Settings, which also holds Profile, API keys, Branding, Single sign-on, Privacy, Ownership and Delete.',
  },
  contactRecord: {
    '#likely-duplicates': 'The Likely duplicates card on the record page looks for other records with the same name and the same phone number, or the same name and the same company, among the contacts your site may see.',
    '#the-record-page': 'Clicking a row in the list opens the person\'s own page at …/crm/contacts/{id} — an address you can paste and that every other CRM record links to.',
    '#what-each-site-keeps-to-itself': 'A contact document is shared by every site in your workspace — one human who touched two of your sites is one row.',
  },
  cookieConsent: {
    '#how-it-works': 'Consent UI appears only on sites that use a consent-gated feature — today, a configured Google Analytics measurement ID or a Google Tag Manager container ID.',
  },
  crm: {
    '#at-the-organization-level': 'The CRM tab under Organization opens the same hub over every site in the organization at once: the same eight sections, the same record pages, the same bulk actions, import, saved views, reports and settings, at…',
  },
  customRoles: {
    '#create-a-custom-role': 'On the organization Team page, find the Custom roles card and choose New role.',
  },
  datasets: {
    '#filter-records': 'The records table filters through its own toolbar: Filters opens the filter panel, where each filterable field of the dataset\'s model is a column, and Search finds records by the words in their text.',
    '#who-a-dataset-is-shared-with': 'Datasets belong to the workspace, not to a single site, so one dataset can drive pages on every site you run.',
  },
  deals: {
    '#a-deals-page': 'Opening a deal shows: The header — the deal\'s title in the page heading and the trail, the pipeline and stage under its kind, its status, amount and owner as chips, Back to deals, Edit, and a menu (⋮) carrying Delete…',
    '#contact-roles': 'A deal can name more than one person: Salesforce\'s Opportunity Contact Roles.',
    '#line-items': 'A deal\'s amount can be a number you type, or the sum of the products behind it.',
    '#moving-winning-and-losing': 'Stage changes go through the server rather than being written directly, so that automations can hear them.',
    '#the-board-and-the-table': 'The section opens as a board of the chosen pipeline: one column per open stage, with Won and Lost folded away at the end until you expand them; a board wider than the window scrolls sideways.',
  },
  designedEmails: {
    '#find-a-template': 'The templates table filters through its toolbar by Template, the name (it contains a word, it is, or it starts with), and Search matches the start of any word of a template\'s name, up to its first twelve characters.',
    '#send-it': 'Open the email you want to send and choose Write this email.',
  },
  downgradingAndCanceling: {
    '#canceling-your-subscription': 'Cancel any time. Your subscription runs to the end of the paid period — a chip on the Billing page shows the end date, and you can resume before it hits.',
    '#deleting-a-single-site': 'To remove just one site (not the whole organization), open the site\'s Admin → Danger zone and use Delete site.',
    '#deleting-your-organization': 'Deletion is separate from canceling and is the only thing that removes your data.',
    '#when-changes-take-effect': 'Plan changes are deliberately asymmetric, and knowing which direction you\'re going tells you what you\'ll be charged — and when.',
  },
  dragDropHierarchy: {
    '#drop-zones-edges-vs-center': 'As you drag over an element, the Besigner splits it into drop zones and shows a placement marker for the zone you\'re pointing at.',
  },
  editYourTheme: {
    '#it-follows-you-into-the-besigner': 'The theme you set here is supplied to the Besigner canvas, so what you design previews under the real site theme in both light and dark.',
    '#set-colors-and-fonts': 'Choose your palette and typography.',
  },
  emailCampaigns: {
    '#a-domain-we-set-up-is-a-request': 'This is the part worth reading before you plan around it. Nothing is provisioned automatically.',
    '#add-to-a-list': 'Type an address (or paste a whole column of them) and press Check.',
    '#campaigns-group-emails': 'A campaign is a container, not a single message. It carries a name, a start and end date, and the lists it is aimed at; the emails you send inside it are its contents, and the campaign\'s page adds their figures up.',
    '#compliance': 'Every send includes an unsubscribe link in its footer, and by default the header mailbox providers look for — Gmail and Yahoo\'s one-click List-Unsubscribe — which is what makes a mail app show its own Unsubscribe button.',
    '#consent-group-confirmation': 'Where your organization has declared several sites one sender — a consent group, named on every signup form — a confirmation belongs to the site whose form asked for it.',
    '#consent-group-join': 'Edit group, in a group\'s menu, opens the same dialog with its sites ticked.',
    '#consent-groups': 'Every site is its own sender until you say otherwise: someone who signs up on one site hears only from that site, and an unsubscribe applies to that site alone.',
    '#domain-states': 'Add a domain and you are given the exact DNS records to publish — an authorization record, a signing key and a bounce-routing record.',
    '#email-lists': 'Lists are audiences shared across your organization\'s sites.',
    '#experiments': 'Business plans can A/B test pages, sections, and emails from the Experiments card on the Marketing page: weighted variants, deterministic visitor assignment, a conversion goal, and per-variant exposure/conversion…',
    '#experiments-across-sites': 'Your organization\'s own Marketing → A/B testing lists every site\'s tests, grouped by site, with what each one tests, how many variants it has and its status.',
    '#list-members': 'Press Members on any list row to open it. You get the membership a page at a time — address, name, when they joined, how they got there, and what their consent record says — plus the controls to change it.',
    '#lists-built-from-a-rule': 'A dynamic list holds everyone matching a rule, re-checked about every fifteen minutes.',
    '#manual-lists': 'A manual list holds the people you put in it. Grow it with the "Enroll in a list" automation step (e.g.',
    '#monthly-send-cap': 'From Pro up, a plan includes a number of campaign emails per calendar month.',
    '#opens--clicks': 'With the Resend webhook configured, campaign history shows opens and clicks per campaign, and clicks on A/B sends count as that variant\'s conversions — so the experiment results table fills in by itself.',
    '#organization-emails-page': 'Your organization has its own Emails page beside CRM and Marketing, with the same seven sections a site\'s has, each answering for every site at once.',
    '#preference-page': 'The link at the bottom of every campaign opens a page where the recipient sees your topics, ticks the ones they want to keep, and saves.',
    '#send-a-campaign': 'Create a campaign on Marketing → Campaigns — a name, the dates it runs between, the lists it is aimed at, and the sites it runs on.',
    '#senders': 'Under the domain, the same page lists this site\'s senders. Each one is a mailbox on the site\'s sending domain with a display name and a reply address stored beside it, and every email you compose goes out as one of them.',
    '#sending-domains': 'Emails → Sending is where you see what this site sends as, and where a workspace proves it owns a domain of its own.',
    '#suppressions': 'Emails ▸ Suppressions lists every address your campaigns skip, with the reason and the date: This is where the gap between a campaign\'s recipient count and what it actually sent comes from, and a rising Bounced count…',
    '#the-campaign-report': 'Report, beside any campaign that has been sent, opens the full picture for that one send.',
    '#topics': 'A topic is a stream of email somebody can leave on its own. Every campaign belongs to one, picked in the composer, and the link in that email offers to stop that stream rather than all of them.',
    '#two-ways-to-get-a-domain': 'A site\'s mail can leave from three places, and only the first is guaranteed.',
    '#what-belongs-to-a-campaign': 'A push is rarely only its mail. A campaign can also hold the landing pages, the forms those pages place, the contacts and leads you have filed under it, and the sequences a rep sends as part of it — so the campaign\'s…',
  },
  events: {
    '#manage-events': 'The console Events page lists your site\'s events, newest start first.',
  },
  featureFlags: {
    '#how-gating-behaves': 'Customers with a flag off don\'t see the feature: its dashboard tab disappears and deep links show a "coming soon" notice instead of the page content.',
    '#managing-flags': 'Open Staff → Feature flags. Each registered flag shows its live value from Firebase Remote Config: Toggle — on for everyone, or off (with optional rollout).',
  },
  forms: {
    '#build-a-form': 'Drop form components onto a page in the Besigner (fields, submit button).',
    '#every-sites-inbox-at-once': 'Your organization has an Inbox of its own, beside CRM and Marketing, for the people who span the whole organization — owners, admins, and members with access to every site.',
    '#field-types': 'Each Form Field has a type that controls what visitors see and what is submitted: Dropdown, radio, and checkbox fields take their choices from the field\'s Options setting — enter one choice per line (or separate them…',
    '#filter-the-inbox': 'Every Inbox table filters and searches through its toolbar, and every filter and the search reach everything the site holds, not only the page on screen: the table asks for the matches, newest first, and paging…',
    '#find-a-form': 'The Forms table filters through its toolbar by every column it shows: Display name, by the start of a word in it: contains "audit" finds "Multi-brand site audit".',
    '#one-forms-own-page': 'The Inbox answers "who is waiting for a reply" for the whole site.',
    '#replying-to-a-submission': 'Open a submission and, under the fields, there is a Reply composer.',
    '#the-inbox': 'The site\'s Inbox page collects everything visitors send, in three tabs — Submissions, Members & leads, and Campaigns.',
    '#where-submissions-go': 'Inbox — every submission is captured; open it in the console\'s mail reader dialog.',
  },
  gettingStarted: {
    '#create-your-first-site': 'Sign in to the console. When you can use Aglyn AI, the new site opens on Start your site, which asks how you want to start: Start from the starter site, or Start with AI, which plans your pages from a few questions —…',
    '#what-a-site-contains': 'Pages & layouts — the pages and the shared frames they render in.',
  },
  glossary: {
    '#organization-org': 'The entity. One subscription, one members roster (owner / admin / editor / viewer), one isolation boundary in Firestore (orgs/{orgId}), one plugin switchboard (enabledPlugins), org-scoped shared data (datasets,…',
    '#workspace': 'The same entity, in the user\'s language. "Your workspace" is what we call an organization in UI copy and user docs — Slack-style, including the {slug}.aglyn.com workspace subdomain.',
  },
  howAglynAiBuilds: {
    '#finding-your-ai-jobs': 'You never have to remember where a job went: The window that started it shows where it stands as it happens: queued, planning, plan ready, building, then done or stopped.',
  },
  installYourFirstPlugin: {
    '#step-3-reviews': 'Ratings on a listing come only from people with a verified email whose organization actually installed it.',
    '#step-4-targeting': 'This is the step to read. On the detail page you\'ll find an Install to dropdown with two options.',
    '#step-7-off': 'Three different actions, often confused: Uninstalling never deletes the data a plugin created.',
  },
  interactions: {
    '#fluent-interactions': 'Select any element, open the Interactions tab in the right-hand panel — beside Attributes and Styles — and use Add interaction.',
  },
  inviteTeammates: {
    '#activity-log': 'The organization\'s Team page shows a Recent Activity log: what happened at organization level — renames, workspace URL changes, ownership transfers, members added/removed or re-roled, and invites sent, revoked, or…',
    '#ai-usage': 'Each member\'s page carries an AI usage card: their AI credits this month and last, their share of the workspace\'s pool, their requests, the kinds of request they mostly made, and the split by site.',
    '#how-team-members-act': 'Team members act in the owner\'s organization, not their own — so their changes apply to your site, and permissions are enforced across the console\'s APIs and surfaces.',
    '#invite-someone': 'Open the organization\'s Team page and choose Add or invite.',
  },
  layouts: {
    '#nested-layouts': 'A layout can render inside another layout. Set Renders inside on a layout\'s detail page and its chrome is wrapped by the outer layout\'s, exactly as a page is wrapped by its own — so site-wide furniture can live in…',
    '#used-by': 'A layout\'s detail page has a Used by card listing everything that renders inside it, so you can see what a change or a deletion would reach.',
    '#what-a-layout-is': 'A layout holds the furniture many pages have in common — header, navigation, footer, a cookie banner, a site-wide search box.',
  },
  leads: {
    '#a-leads-page': 'Click a row to open the lead. Lead holds what the team decides: the status and the owner.',
  },
  liveCoEditing: {
    '#whos-here': 'When someone else has the document open, their avatar appears in the besigner toolbar (photo or initial, on their assigned color, ringed in that same color).',
  },
  lockdown: {
    '#cancel-billing': 'A lock does not touch Stripe. A locked workspace keeps its subscription, and the subscription keeps renewing.',
    '#deny-list': 'Everything above is per-file: you name a file and learn what refuses it.',
    '#disabled-files-page': 'Staff → Disabled files is the form. Reach for it first — it removes every transcription step the curl below still has.',
    '#feature-scope': 'The beta-week abuse-response kit: kill one capability platform-wide while everything else keeps serving.',
    '#never-take-a-lock-or-a-lift-on-trust': 'A click is a request. A click that misses — the page settles, a banner collapses, the button moves — looks exactly like one that worked, and the dangerous half is a lift you believe happened: a controlled 60-second…',
    '#operating-it': 'Open Staff → Lockdown (or suspend a workspace from its org detail page — same mechanism underneath).',
    '#owner-notices': 'Every lock and every lift at the org, host, domain and user scopes — and a feature lock placed for one workspace — emails the people it affects, from the platform\'s own sender.',
    '#quarantine-keys': 'Three limits, each a real hole rather than a caveat: The mint leg of a signed upload is not gated.',
    '#what-a-caller-is-told': 'You cannot check a lockdown by trying it yourself. Staff bypass every scope — that is the un-panic invariant, and it is deliberate — so your own request succeeds no matter what is locked.',
    '#which-digest': 'A media document may carry two digest fields, and they are not interchangeable.',
    '#who-keeps-access-the-un-panic-invariant': 'Staff are never locked out, by any scope, ever. A platform-wide lockdown leaves every verified staff session able to reach the staff console and lift it — this is spec-enforced (a panic button that panics its own…',
  },
  maintenance: {
    '#running-a-job-by-hand': 'For when something genuinely cannot wait for the next scheduled run.',
  },
  manageAccount: {
    '#email-addresses': 'You can keep up to five addresses on one account — a work address and a personal one, say — instead of running two accounts.',
  },
  manifestAndEnvs: {
    '#review--trust-lifecycle': 'Listed/verified (or legacy/absent) plugin listings appear in browse; everything else is owner-and-staff-only.',
  },
  marketingOverlays: {
    '#across-your-sites': 'Your organization has its own Marketing page beside CRM, with the same sections as a site\'s — Overview, Campaigns, Conversions, Overlays and A/B testing — each answering for every site at once.',
    '#announcement-bar': 'A site-wide announcement bar shows a message across every page — ideal for sales, notices, or launches.',
    '#engagement-stats': 'Each overlay tracks its own lifetime views, clicks, and dismissals, shown in the Engagement column of the overlays table — so you can tell whether a bar earns its screen space.',
    '#frequency': 'In the popup editor, Frequency offers two mutually exclusive choices.',
    '#promotional-popups': 'Popups give you more control: Triggers — After a delay (a number of seconds), On scroll (a percentage of the page), or On exit intent.',
  },
  media: {
    '#approved-image-hosts': 'Most images on your site are ones you uploaded here, and those always work.',
    '#who-an-asset-is-shared-with': 'Workspace media is shared across every site by default. The Shared with control narrows that, with the same two choices as datasets — All sites or Selected sites….',
  },
  members: {
    '#2-the-built-in-sign-in-and-sign-up-pages': 'Once User Accounts is on, the site serves three ready-made routes — no design work needed: /signup — "Create your account": name, email, and password (8 characters minimum).',
    '#5-manage-members-from-the-console': 'The site\'s Users page has two cards: Site users (your members — this guide) and Users (console collaborators).',
  },
  membersOnly: {
    '#manage-your-members': 'The site\'s Users page lists everyone who signed up on your published site — paged, newest first.',
  },
  operatorAlerts: {
    '#alert-list': 'Plugins add their own rows: an install without the commerce plugin shows no commerce alerts.',
    '#channels': 'Every alert does three things, in order: Writes a console notification for every staff member, in the bell.',
    '#health': 'Every health endpoint remembers its last verdict. When one goes from healthy to degraded, the Health check degraded alert goes out once.',
    '#settings': 'Every row has two controls: On: off keeps the console notification and sends no email and no webhook post.',
  },
  orderNotifications: {
    '#customer-emails': 'A dropship supplier who posts tracking for their part of an order sends the customer the same Order shipped email.',
  },
  ordersAndReturns: {
    '#buyer-requests': 'A buyer asks for a return themselves, from either of two places: the Request a return link beside an order in their account on your store, when they are signed in;',
    '#order-webhooks': 'An order webhook posts each order event to an address you choose, as it happens: a warehouse system, an ERP, a spreadsheet script.',
    '#run-a-return': 'Open a return from the list, or from the Returns section of its order\'s dialog, where Start return opens one for the buyer.',
  },
  orgAutomations: {
    '#every-sites-own-automations': 'The organization hub\'s Workflows, Actions and Webhooks sections list every site\'s own workflows, actions and webhooks side by side, with the site each belongs to.',
    '#pause-it-on-one-site': 'Each site\'s Automation → Actions section shows Org automations on this site: the ones placed on it, whether each runs here, and Pause here / Resume here.',
    '#what-an-org-automation-is': 'An org automation has a trigger, optional conditions and an ordered list of steps, exactly like an action — and a placement: the sites it runs on.',
  },
  platformHealth: {
    '#csp-violations': 'The durable Content-Security-Policy violation counters, over a window you choose.',
    '#idempotency-claims': 'Money-moving routes take a claim before they act and release it after, so a retry — Stripe\'s redelivery, a double-clicked button, a cron that overlapped itself — finds the claim held and does nothing rather than…',
    '#mail-gateway-ledger': 'What each mail gateway — Barracuda, Proofpoint, Mimecast, Google, Microsoft and the rest — did with mail from each sending domain the platform sends from: refusals and deliveries over the last thirty days, whether…',
    '#pending-erasures': 'An erasure request from a customer waits out a 7-day hold and is then executed by the 04:00 UTC job.',
    '#resolved-server-config': 'Every card above asks whether the platform is working. This one asks a different question: is production running the configuration we think it is?',
    '#sharing-scope-drift': 'A scoped document with no sharing scope is invisible to every scoped read — both enforcement layers fail closed on it, so the data is not leaked, it is simply gone from every list that should show it.',
  },
  plugins: {
    '#a-dependency-that-is-off-for-one-site': 'A site can switch off a plugin that another plugin on that same site depends on — by disabling it directly, or simply by never opting in.',
    '#browse-card': 'Every card in Browse All carries the same four claims, so two listings side by side are comparable: A price chip, always.',
    '#configure': 'A plugin declares the settings it takes, and the console renders the form.',
    '#configure-site': 'A site that needs a different answer overrides that one field and keeps inheriting the rest — including later changes the workspace makes to the fields it did not override.',
    '#how-plugins-run': 'Each plugin loads into a sandboxed PluginFrame host runtime, isolated by origin.',
    '#install--upgrade': 'Open Marketplace in the organization navigation and Browse the listings.',
    '#what-the-badges-on-a-listing-mean': 'Two badges can appear on a listing, and they say different things.',
    '#when-one-plugin-depends-on-another': 'Some plugins cannot run without another one. User Accounts is the case that exists today: its Members blocks and its membership/* API handlers ship inside the Commerce bundle, so User Accounts with Commerce switched…',
  },
  pos: {
    '#card-readers': 'A card reader takes card payments at the counter: the customer taps, inserts or swipes, and the reader can ask for a tip.',
    '#registers': 'Create your registers under Commerce → Settings → POS registers — one per till or device that takes in-person payments.',
    '#reservations': 'For stays (cabins, rooms, rentals): Add resources on the Products page — nightly rate, weekend multiplier, minimum nights, deposit percent, and free-cancellation window.',
  },
  posHardware: {
    '#receipt-printers': 'A cloud receipt printer collects its work from Aglyn over the internet, so a receipt prints from the register on any device, even one with no printer driver, and even when the printer is on a different network.',
  },
  posOperations: {
    '#shifts-and-the-cash-drawer': 'A shift is one stretch of trading on one register, counted against one cash drawer.',
    '#staff-pins': 'A shared tablet stays signed in; each person switches in with their own PIN instead of signing out.',
  },
  publishAPlugin: {
    '#paid-listings': 'You can list a plugin as paid: Payments run through Stripe Connect.',
    '#your-publisher-profile': 'Your publisher profile is a storefront: its own page in the marketplace listing everything you\'ve published, reachable from the Publisher card on any of your listings and from the by @handle link on every browse card.',
  },
  publisherHandbook: {
    '#asking-to-be-verified': 'Verification used to be something only a reviewer could start, which meant there was no way to ask and no sign that asking was allowed.',
    '#authoring-your-listing': 'Your listing IS your storefront — it renders on the detail page every buyer sees.',
    '#before-you-publish': 'The last section of the page asks you to confirm a short checklist, in full view of the publish button, and publishing is blocked until you do.',
    '#before-your-first-publish': 'Publisher profile (Marketplace → Profile) — your handle and display name appear on every listing.',
    '#getting-paid': 'One-time prices in whole USD: $0 (free), or $3 to $1000. Purchases flow through the platform\'s Stripe; your share (80%, or 70% on free plans) pays out via your Connect account.',
    '#how-installs-work-the-buyer-side': 'Browse is a catalog — cards link to the detail page, which is the only place an install happens.',
    '#private-plugins': 'Choose Only this organization under Who can install this when you upload, and the listing becomes private: never browsable in the marketplace by anyone, and installable only by your own organization\'s sites.',
    '#publishing-a-version': 'Run the local verifier first — the publish API enforces the same checks and rejects with the exact problem list: The verifier parses your bundle rather than reading it as text, so it sees what a source scan could…',
    '#review-what-happens-after-you-publish': 'New plugin listings enter the queue as submitted and don\'t appear in public browse until staff list them.',
    '#shipping-a-new-version': 'Publish new version on your listing — the button on the listing\'s own detail page, or the action in the row menu on Marketplace → Listings.',
    '#the-publisher-agreement': 'Your organization — not you personally — is the publishing party, so the organization accepts the Marketplace Publisher Agreement once.',
    '#the-two-badges-and-what-each-one-promises': 'The marketplace shows two separate claims, because they answer different questions and conflating them would let one vouch for the other.',
    '#where-to-publish-from': 'Publishing lives at the organization level — Marketplace → Publish.',
  },
  redirects: {
    '#manage-redirects': 'Create, edit, and delete redirect rules from the redirect manager page.',
  },
  refunds: {
    '#issuing-a-refund': 'Select the charge. The row shows what is left to refund. A refund cannot be undone from Aglyn.',
  },
  repeat: {
    '#what-repeats-the-element-or-whats-inside-it': 'Two things can sensibly repeat, and which one you want depends on the element: What is inside this element — the element stays as one frame and its contents are the item template.',
  },
  reportAnIssue: {
    '#is-it-us-or-your-site': 'This channel is for problems with Aglyn itself — the editor, the console, publishing, domains, billing.',
    '#what-to-write': 'The dialog asks different things depending on what kind of report it is, because a bug and an idea need different answers.',
  },
  responsiveStyling: {
    '#box-stylers': 'The spacing styler is one diagram of the element\'s box, drawn the way a browser actually builds it: margin on the outside, then the border, then padding, and the content in the middle.',
    '#custom-classes': 'Every element accepts Classes (chips input under Classes & custom CSS).',
    '#interaction-states': 'Under the breakpoint chip is a second row of chips: Default, Hover, Active, Focus and Disabled.',
    '#spacing-units': 'Space can be set two ways, and the difference matters more than it looks.',
    '#style-groups': 'The styles panel organizes every control into accordions, and every field has exactly one home — no custom CSS needed for the common properties.',
    '#unit-ch': 'The width of the digit 0 in the current font. 20ch is roughly the width of twenty characters.',
    '#unit-em': 'A multiple of this element\'s own text size. On a heading set to 32px, 1em is 32px; on body text at 16px, the same 1em is 16px.',
    '#unit-percent': 'A share of the parent element\'s width. The trap worth knowing: for padding and margin, percentages are measured against the parent\'s width even for the top and bottom sides.',
    '#unit-px': 'A fixed dot on the screen. 16px is 16px on every device and never changes, whatever the visitor\'s font settings are.',
    '#unit-rem': 'A multiple of the page\'s base text size, which is normally 16px — so 1rem is usually 16px and 1.5rem is usually 24px.',
    '#unit-viewport': 'A percentage of the browser window. 1vw is 1% of its width, 1vh is 1% of its height — so 50vh is half the window tall regardless of how much content is on the page.',
    '#visibility-per-device-band': 'The Visibility accordion hides the selected element on whole device bands — mobile (under 600px), tablet (600–899px), and desktop (900px and up).',
  },
  revenue: {
    '#gross-versus-net': 'Three deductions stand between money moving through Stripe and money Aglyn keeps.',
    '#how-each-org-is-treated': 'A plan tier is not a price. The page states each case rather than leaving it in the code: Trialing orgs are counted as contracted because the subscription is real; they settle nothing until the trial converts, which…',
    '#the-gap': 'The gap compares contracted MRR for the orgs that should be collecting — total contracted, less trialing and less past-due — against subscription cash that actually settled.',
    '#the-two-bases': 'Pick a month or a quarter from the Period menu. Settled figures are ranged over that period: paid invoices on Aglyn\'s own account, marketplace sales, and storefront orders that settled between the period\'s start and end.',
    '#where-the-money-came-from': 'Earned revenue by source. Every line is already net of the thing that would overstate it: Subscriptions, add-ons and metered usage — paid invoices, net of sales tax and of every reversal.',
  },
  salesChannels: {
    '#brand-barcode-and-category': 'Channels match listings to products they know by their identifiers.',
    '#how-fresh-the-feed-is': 'A product you edit and save reaches the next fetch at once. Stock that a sale takes reaches it within 30 minutes.',
    '#turn-on-a-channel': 'On the channel\'s card, switch the feed On. The card shows the feed\'s address.',
  },
  salesTaxReturn: {
    '#aglyns-own-sales-by-jurisdiction': 'Every buyer state in the period, Texas first — for Aglyn\'s own subscription and add-on revenue.',
    '#choosing-the-period': 'The Period menu lists every quarter and every month from September 2026 to the present, newest first.',
    '#refunds': 'Refunds are stated, never netted out of the figures above. A revenue row keeps one cumulative refunded amount and only the latest refund timestamp, so two refunds in different quarters cannot be told apart from the…',
    '#rows-that-need-attention': 'This is the part to read first, and it sits above the figures deliberately.',
    '#taxable-purchases': 'Item 3 is the one line on the return that nothing here can compute.',
    '#the-figures': 'The Form 01-114 figures card is Texas only. Aglyn sells everywhere; a Texas return reports Texas receipts, so these lines come from the Texas jurisdiction bucket and never from the platform totals.',
    '#where-this-deployment-files': 'Staff → Platform settings → Sales tax filing. Reading it needs any staff role; changing it needs super, and every change is written to the audit log with the reason you type.',
  },
  saveATemplate: {
    '#save-your-site-as-a-template': 'Saving a whole site is not done from the pages list — it lives in Setup.',
  },
  screens: {
    '#screens--routing': 'Each page has a title and a URL slug. Aglyn normalizes slugs and keeps a site routing map.',
  },
  seo: {
    '#how-a-page-title-is-built': 'A search title you write is the whole title — nothing is appended to it.',
    '#local-businesses': 'If customers visit you, or you go to them, pick a Business type on the Local business card in Setup → SEO — Plumber, Restaurant, Dentist, or plain LocalBusiness when nothing narrower fits.',
    '#per-screen-seo': 'Every page\'s detail view has an SEO card with four fields: Search title — up to 60 characters, published exactly as you type it.',
    '#search-engine-visibility': 'You decide what search engines are allowed to index, at two levels.',
    '#seo-check': 'Setup → SEO starts with an SEO check card. Press Run the check and it reads every page your sitemap lists — every published page whose visibility is Public, without template pages or error pages — and lists what a…',
    '#social-cards': 'Every published page emits Open Graph and Twitter metadata: title, description, canonical URL, site name, the page\'s language, and — once an image is set — og:image with its og:image:width, og:image:height and…',
    '#structured-data': 'Published sites emit JSON-LD, giving search engines and AI assistants rich context about your content.',
    '#verify-your-site-with-google-search-console': 'Search Console and Bing Webmaster Tools want proof the site is yours before they show you its search data.',
  },
  sequences: {
    '#allowed-countries': 'The countries a sequence may send to at all, United States by default.',
    '#build-a-sequence': 'Select New sequence, name it, and choose the site whose CRM the people you enroll are contacts of and the mailbox it sends from.',
    '#compliance-settings': 'Every email a sequence sends ends with a footer saying who sent it, where they can be reached by post, that the email is a sales email, and how to stop more of them.',
    '#connect-a-mailbox': 'Each rep connects their own Google or Microsoft 365 mailbox in Sequences → Mailboxes: Select Connect with Google or Connect with Microsoft and choose your account.',
    '#do-not-contact-domains': 'The domains no sequence emails anyone at, whoever enrolls them.',
    '#enroll': 'Select Enroll people on an active sequence, and choose them from a saved Contacts or Leads view, by searching your contacts at the sequence\'s site, or from the Leads tab — the site\'s open leads — up to 50 at a time.',
    '#link-domains': 'With Count link clicks on, every link in a sequence email is a short link that counts the click and then takes the reader where you meant.',
    '#mailbox-actions': 'Send a test to myself sends a short plain-text message from the mailbox to its own address, so you can check it arrives.',
    '#person-history': 'Select a person\'s row — or focus it and press Enter — to open their page.',
    '#send-a-test': 'Send a test on any email step of a saved sequence sends that step to your own inbox through the sequence\'s mailbox, so you read it as a recipient would — the merge fields filled, the footer on, the links as they will…',
    '#sequences': 'A sequence is the emails, and the tasks between them, one person gets from one rep.',
  },
  shipping: {
    '#carrier-accounts': 'The Carrier accounts card lists the carriers your labels and checkout rates come from, for every site in the workspace.',
    '#shipping-labels': 'A label bought on Aglyn\'s carrier accounts is charged to the workspace at the carrier\'s price, with nothing added.',
    '#where-parcels-ship-from': 'Each inventory location (Products → Settings → Inventory locations) can carry a postal address: choose Add address on its row, or Edit address once it has one.',
  },
  siteProtection: {
    '#per-screen-passwords': 'Protect individual pages with a password, so only people with the code can view them.',
  },
  siteSearch: {
    '#the-layout-built-in-pages-use': 'The results page is built for you, but the header, navigation and footer around it are yours.',
  },
  staffConsole: {
    '#acquisition': 'An Acquisition card on the detail page — and on each organization\'s page, for the account that created it — says where the account came from in one line ("Referral from g2.com → /pricing → signed up with password"):…',
    '#audit-archival': 'A nightly cron moves audit entries past the 90-day retention window into a Storage compliance trail (JSON lines, month-partitioned) and reminds staff of GDPR erasure requests past their 7-day hold.',
    '#audit-log': 'A record of staff actions, newest first. Click an entry to read its reason, note and before/after below the list.',
    '#billing-insight': 'Every organization\'s Stripe invoice history and default payment method (with delinquency state) render on its detail page.',
    '#contact-suppressions': 'The platform do-not-contact list for phone numbers — calls and texts.',
    '#coupons': 'Discount codes for Aglyn\'s own subscriptions. They live in Stripe — the console creates them there and reads them back, so a coupon made in the Stripe Dashboard shows up here and vice versa.',
    '#email-delivery': 'An Email delivery card on the same detail page answers "they say they never got it." It lists every message we sent the account\'s addresses, newest first, a page at a time: the subject, which of our senders produced…',
    '#emails-sent': 'Emails sent — on a site\'s staff page, and on an organization\'s for all of its sites — lists every email the site sent, newest first: the recipient, the subject and the sender tag (a campaign, a form notification,…',
    '#entitlement-editor': 'Full override editor for an organization\'s entitlements, its plan, and per-organization release flags.',
    '#existing-coupons': 'Existing coupons lists Stripe coupons with their promotion codes, redemption count, and a valid or expired state, a page at a time.',
    '#filter-the-directory': 'The grid\'s toolbar filters and searches the whole directory, not the page on screen.',
    '#filter-the-site-list': 'The grid\'s toolbar filters and searches every site, not the page on screen.',
    '#first-party-hosts': 'The hosts the platform serves itself, on Staff → Platform settings.',
    '#free-workspace-limit': 'How many free workspaces one account may hold, on a card at the top of the organizations page.',
    '#organizations-admin': 'Audited plan and entitlement overrides, suspension, and GDPR-erasure flags, per organization.',
    '#password-help': 'On that detail page, a Password card can email the account a reset link, or set its password directly for an account that cannot receive mail.',
    '#platform-suppressions': 'Also on the System emails page: every address that bounced permanently or reported spam on any send from any site.',
    '#plugin-reviews': 'The marketplace review queue, plus a Listed plugins — realm trust table for granting or revoking realm trust per version.',
    '#sign-one-device-out': 'A Sign-in history card on the same detail page lists every device that has signed in to the account — browser and system, location, IP, first and last seen — and can end the sessions on one of them.',
    '#site-content': 'The Content card lists what the site is built from, one tab per kind: Pages, Email designs, Layouts, Components, Templates and Forms.',
    '#site-detail': 'A site\'s staff page opens from its row in Sites, or from the Sites card on its organization\'s page.',
    '#site-ownership': 'A site belongs to an organization, and the organization has one owner.',
    '#sites-admin': 'Sites lists every site on the platform, across every organization, read server-side with the Admin SDK so it shows sites you are not a member of.',
    '#staff-automations': 'The Automations card — on a site\'s page, and Organization automations on an organization\'s — comes from the Automation plugin.',
    '#staff-org-email': 'The Email campaigns card, from the Marketing plugin, has two tabs, each paged in id order: Sends — every campaign send: its subject and site, status (and held for review when the outbound screen stopped it), how many…',
    '#system-emails': 'The mail Aglyn itself sends: organization invites, the monthly usage summary, the email copy of console notifications, staff alerts, workspace notices, the CRM digest and task reminders, the weekly insights digest,…',
    '#users-admin': 'Staff-claim management and disabling users, with gated listing; a whole email address typed in the search box looks the account up directly.',
  },
  supportAndCommunity: {
    '#community-forum': 'At Organization → Support → Community forum, and the page Free and Starter workspaces land on.',
    '#support-tickets': 'At Organization → Support → Support tickets. A ticket is a private conversation between your organization and Aglyn staff.',
  },
  tasks: {
    '#the-dashboard-card': 'The site dashboard shows a Tasks due card: how many of your tasks are overdue, how many are due today, and the next five assigned to you, each with its due date.',
  },
  taxServices: {
    '#connect': 'Go to Commerce → Settings and find the Tax service card. Only an admin of the site can connect, test or disconnect a service and change its address.',
    '#how-sales-are-taxed': 'A product you marked tax-exempt is sent as non-taxable and charged no tax.',
  },
  team: {
    '#organizations': 'Aglyn is built around organization workspaces: an organization subscribes once, owns multiple websites, and shares media, plugins, dynamic data and billing across them.',
    '#site-collaborators': 'A site\'s collaborators are listed in the Users card on that site\'s Users page, ordered by email address with the organization\'s owner first.',
    '#site-membership': 'Visitors can sign in / sign up to your site.',
    '#team-roles': 'Invite teammates to a site and assign roles.',
  },
  templatesLibrary: {
    '#using-a-template': 'Use creates something new from the template — the template itself stays in your library, so you can use it as many times as you like.',
    '#where-a-template-came-from': 'Every template shows a badge: Saved here — you created it on this site',
  },
  textEditing: {
    '#text-field-read-only': 'Once an element carries formatted text, the Text field goes read-only and says so: > This text is formatted — double-click the element on the canvas to edit it.',
    '#the-text-attribute': 'The Text field in the right-hand panel and double-clicking on the canvas edit the same value.',
  },
  transferHub: {
    '#history': 'History lists every import the workspace ran, newest first. It includes record imports, packages, and each site\'s package imports.',
  },
  versionsAndPublishing: {
    '#publish--roll-back': 'Publish on any row makes that version the live one — which is also how you roll back: publishing an older version moves the live pointer, destroys nothing, and is symmetrical, so rolling forward again is the same click.',
    '#scheduled-publishing': 'Schedule publishes a version automatically at a chosen future time; the row then shows a "Publishes …" chip you can clear to cancel.',
    '#the-versions-dialog': 'Open the version name in the Besigner\'s app bar to see the Versions dialog, with each version\'s created/updated times and a Published chip on the live one.',
  },
  webhooks: {
    '#outbound-webhooks': 'Send an HTTP request to a URL you control when a site event fires — for example, post to a Slack endpoint or your own API when a form is submitted or a new booking comes in.',
  },
  whiteLabel: {
    '#fields': 'Every field is optional. Leave one blank and it keeps the Aglyn default for that field — the grayed-out placeholder text in each box is that default, so a blank box is showing you exactly what will be used.',
  },
}
