/**
 * @license
 * Copyright 2026 Aglyn LLC
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *   http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
// GENERATED FILE — do not edit. Regenerate with:
//   node tools/scripts/generate-docs-help.mjs
// Source of truth: apps/docs/docs frontmatter + headings (AGL-602).

import type { DocsHelpTopicKey } from './docs-help.generated'

/**
 * The tooltip prose for every help topic — each docs page's frontmatter
 * description, verbatim.
 *
 * Apart from the registry beside it because of when it is read: a help
 * button's `path` is its own `href` and its `title` its accessible name,
 * both wanted the moment the button renders, while the excerpt is wanted only
 * once someone opens the tooltip. Kept together they were ~20 KB of prose
 * parsed by every console page for a hover most visits never make;
 * `DocsHelpExcerpt` fetches this module when a tooltip mounts.
 *
 * A missing key is a compile error, so no topic can lose its excerpt quietly.
 */
export const DOCS_HELP_EXCERPTS = {
  abuseReports: 'The public abuse-report queue — where outside reports land, how to triage by severity, which lever answers which report, and the CSAM and DMCA paths that are not takedown buttons.',
  account: 'How console sign-in works — Google sign-in on desktop and mobile, one session across all your workspaces, and automatic sign-out after inactivity.',
  actionsBuilder: 'Map a single event to a single action without building a full workflow.',
  activities: 'Log calls, emails, meetings and notes against a contact, a company, a deal or a lead, email one person from their record, and read it all in one timeline beside everything captured and every campaign sent.',
  addALocale: 'Create a language variant of your site and translate its screens.',
  addOns: 'Buy extra seats, sites, datasets, POS registers, and the Event Calendar from the Billing page — prorated, self-serve, no support ticket.',
  addSearch: 'Drop the Search Box element onto a screen and publish — the built-in search page does the rest.',
  aglynAssist: 'Ask the built-in AI helper how to do anything in Aglyn — it answers from these docs and links you straight to the right page.',
  aiAssist: 'Generate and rewrite copy, and build whole sections, with AI inside the Besigner.',
  analytics: 'Built-in pageview analytics, the Traffic card and its growth figure, per-screen metrics, and average time on a screen.',
  animations: 'Add fade, slide and zoom motion to any element, stagger a row of cards, choose when it plays, and keep the page fast and accessible.',
  architectureMultiTenancy: 'How Aglyn organizes tenants — org workspaces, membership with per-site access, security rules, subdomains, and billing attribution.',
  assistSignals: 'The docs-gap and cost board behind Assist — how the ranking is ordered, why ungrounded questions are counted separately, and what the cache-read rate says about margin.',
  automations: 'The CRM events an automation can start on — a contact created or changing stage, a deal moved, won or lost, a task completed — the steps that tag, stage, assign, create a task or log an activity, and one-click recipes.',
  bandwidth: 'How much traffic each plan includes, what happens when a site goes past it, and why a Free site can be paused until the start of next month.',
  besigner: 'Aglyn\'s visual editor — canvas, hierarchy, inline text, multi-select, and placement rules.',
  billing: 'How Aglyn\'s tiers, entitlements, quotas, usage meters, and seat add-ons work.',
  bindings: 'Live values in your content — typed variables, no-code functions, and rename-safe id tokens.',
  bookings: 'Offer services with availability, let visitors book, take payment, and send reminders.',
  buildABlog: 'Create a collection, publish rich entries, and design the list and entry pages with template screens.',
  buildAndPublishASurvey: 'Create a dataset with a typed schema, design a survey form with dropdowns, radios, checkboxes, and a star rating, publish it, and watch responses arrive.',
  buildAWorkflow: 'Create a multi-step workflow that runs when a site event fires.',
  buildingFeaturePlugins: 'The console-extension + frontend-UI plugin pair pattern for shipping features as plugins.',
  bulkActions: 'Select rows in any CRM table — contacts, companies, deals, tasks or leads — and act on all of them at once, or export them as a CSV.',
  catalog: 'Products with options and variants, categories, tags, and manual or smart collections.',
  comingSoonLaunch: 'Put a coming-soon page on your domain, keep the rest of the site out of search while you finish it, collect signups, and reverse all of it on launch day.',
  commerce: 'Sell physical, digital, and service products with a full catalog, orders pipeline, shipping, taxes, and your own Stripe account.',
  commerceEndToEnd: 'Create products with billing modes, design the storefront with Commerce blocks, take Stripe checkout for one-time and subscription sales, and run orders from the console.',
  companies: 'Group your contacts under the businesses they belong to — one record per company, with its domain, owner, address and the people who work there.',
  components: 'Promote a subtree into a reusable component, give it properties, and insert instances across screens.',
  connectADomain: 'Point your own domain at your Aglyn site — a CNAME for a subdomain, an ALIAS for a bare apex — and verify with one click.',
  consoleAndSite: 'Task-ordered recipes for nav/pages/widgets/providers and canvas components/site runtimes.',
  consoleSearch: 'What the console search palette can find, how it matches what you type, and the two things it deliberately does not search.',
  consoleTour: 'Where things live in the Aglyn console app bar and navigation.',
  contactRecord: 'Add a contact by hand, keep a profile on them — phone, company, title, address, owner and lifecycle stage — open their own page in the CRM, and merge two records that turn out to be one person.',
  content: 'Start from templates, drop in pre-built sections and blocks, and publish a blog with collections.',
  cookieConsent: 'Ask visitors before analytics runs — or track immediately where the law allows, with an always-available opt-out. Google Analytics and Tag Manager tags never load for a visitor whose recorded state does not grant them.',
  copyAssist: 'Generate and rewrite text for any canvas text prop with AI.',
  copyPaste: 'Copy any element — with its children — and paste it elsewhere, including into a different screen, layout or component.',
  createARedirect: 'Add a redirect rule and read its hit metrics.',
  crm: 'One place for the people who interact with your sites — contacts captured from forms, members, orders and bookings, with leads, companies, a deals pipeline, tasks, a timeline, reports and custom fields.',
  customDomains: 'Connect your own domain — subdomain or bare apex — with one-click DNS verification.',
  customFields: 'Define your own properties on contacts, companies and deals — text, number, date, choice, checkbox or link — show them on every record and its list, and save form answers straight into a contact\'s.',
  customRoles: 'Define roles with unique permission sets and fine-tune access per member.',
  datasets: 'Model structured content with typed fields and relations, then bind it into repeatable components.',
  datasetsAndSchema: 'Field ids vs display names, the typed model, per-plan record quotas, import/export, repeatables with item bindings, and every writer that can append records.',
  deals: 'Every open deal by stage — with an amount, an owner and an expected close — as a board you drag across or a table you page through, and the won and lost history behind it.',
  designedEmails: 'Build campaign emails in the besigner with email-safe blocks and merge tokens — no separate editor.',
  domainProviders: 'Make hostnames actually resolve on a self-hosted install — choose a domain driver, run the wildcard path end to end, or implement the webhook contract against your own proxy.',
  downgradingAndCanceling: 'What happens when you downgrade, cancel, or delete — when each takes effect, what the cancel dialog offers you, and how to export first.',
  dragDropHierarchy: 'Everything drag-and-drop in the Besigner — where you can drag, how drop zones and placement markers work, containers vs. leaf elements, placement rules, and multi-drag.',
  editFromTheLiveSite: 'The admin bar on published sites — jump from any live page straight into the besigner for the screen serving it.',
  editYourTheme: 'Set colors, fonts, and light/dark schemes with a live preview.',
  elementCatalog: 'Every built-in element you can drop on the canvas, grouped by the categories in the ELEMENTS drawer.',
  emailCampaigns: 'Campaigns to audiences built from your contacts. Campaign email starts at Pro and needs a sending domain of the site\'s own; receipts and account email send on every plan.',
  emailTemplates: 'Keep the letters your team sends from a record — templates that fill in the subject and the message, snippets that drop in a paragraph, and merge fields that fill in the person\'s name, their company, the deal and you.',
  enterprise: 'What the Enterprise plan adds — single sign-on, a dedicated support commitment, and the security material a procurement review asks for.',
  errorScreens: 'Replace generic 404/401/403/503 pages with branded screens you design.',
  events: 'Keep a schedule of events in the console and publish the ones you choose to any screen, with search-engine event markup.',
  examples: 'Where to look for a working example of each plugin pattern.',
  extensionPoints: 'Every surface a plugin can extend, when it runs, and which part of Aglyn it reaches.',
  featureFlags: 'Release-gate console features with Firebase Remote Config — staff always see everything, customers see what\'s launched.',
  firstPlugin: 'The full loop — scaffold, develop against a live workspace, verify, publish, install, uninstall.',
  forms: 'Add forms to your site, collect submissions in an inbox, and write them into datasets.',
  generateSection: 'Produce a whole section of components on the canvas from a prompt.',
  gettingStarted: 'Sign in, create your first site, and understand what a site contains.',
  glossary: 'What organization, workspace, tenant, host, and site each mean — and which word to use where.',
  googleAnalytics: 'Every event your site sends to your own GA4 property, with the exact parameters each one carries — so you can build a report against it before you have any data.',
  import: 'Bring a spreadsheet of people into the CRM — map its columns, preview the result, and import in batches with a report of what was added, updated and skipped.',
  importExport: 'Round-trip dataset records through CSV and JSON with validation on import.',
  injectionZones: 'Every named console zone a plugin widget can render into, and what each receives.',
  installYourFirstPlugin: 'A click-by-click walkthrough of the Marketplace — find something, choose which sites get it, install it, and turn it off again.',
  interactions: 'Build element interactions in one dialog and drop sanitized custom markup anywhere.',
  inviteTeammates: 'Add people to your site and understand how team members act within your organization.',
  languageSwitcher: 'Let visitors move between your site\'s locales.',
  layouts: 'A layout is the shared frame your screens render inside — header, nav and footer in one place, nested up to five deep.',
  leads: 'Work the people your site has captured — a status, an owner and notes on every lead — and convert one into a contact, a company and a deal.',
  liveCoEditing: 'See who else is editing, work on the same document together, survive save conflicts, and recover unsaved changes after a crash.',
  lockdown: 'The staff panic button — disable access platform-wide or for one workspace, site, or account, with a real logout and a visitor notice.',
  longFormMarkdown: 'Put a whole policy, terms or handbook page on the canvas as one Markdown element, and let a Table of contents element build the "On this page" list from its headings.',
  maintenance: 'The staff maintenance jobs — whether each scheduled job is still running, what a run would do, and how to run one by hand without firing an irreversible sweep by accident.',
  maintenanceMode: 'Temporarily take your site offline behind a designed 503 screen.',
  manageAccount: 'Your personal account — email, sign-in methods, avatar, name, and password.',
  manifestAndEnvs: 'The plugin manifest schema, the marketplace listing/version documents, the trust state machine, and every PLUGIN_* environment variable.',
  marketingOverlays: 'Site-wide announcement bars and promotional popups with triggers, scheduling, and email capture.',
  media: 'Organize images, video, and files in folders, transform them, and serve them fast over a CDN.',
  megaMenuWithInteractions: 'Add a SaaS-style mega menu to your nav bar, fill it with columns of links, and make it open on hover — entirely in the Besigner, on any plan.',
  members: 'Let visitors sign up on your site, design an account page with the Customer account block, gate screens to members, and manage members from the console Users page.',
  membersOnly: 'Let visitors sign up as members and gate screens so only members can view them.',
  menusAndNavigation: 'Dropdown menus, hover mega menus, and slide-in drawers — authorable entirely in the besigner.',
  migrationPatterns: 'Common redirect setups when you rename screens or move a site into Aglyn.',
  modelBuilder: 'Define a dataset model with typed fields and edit records in the typed editor.',
  multilingual: 'Offer your site in multiple languages with locale variants, hreflang, and a language switcher.',
  multiSelect: 'Select several elements at once and move the whole selection together.',
  onboardingDeepLinks: 'The plan-aware signup contract the marketing pricing page links into, and what the console does with it.',
  passwordAScreen: 'Require a password to view a specific screen.',
  platformHealth: 'The staff health board — serving, backups, rate limiters, signup volume, email delivery and CSP violations, with what each red light means and what to do.',
  pluginConfig: 'Declare a settings schema and get a console form for free — plus the three layers a setting is answered at, workspace defaults with per-site overrides, and the one write that clears one.',
  pluginManagerApi: 'Every public registration and loading API a plugin can use, from `@aglyn/aglyn` and `@aglyn/aglyn/server`.',
  plugins: 'Extend Aglyn with sandboxed plugins — install from the marketplace, configure them, and publish your own.',
  pos: 'Sell in person from the console register and take date-range reservations with deposits.',
  publishAPlugin: 'Ship your own plugin to the marketplace with version pinning.',
  publisherHandbook: 'Publishing to the Aglyn marketplace — from profile setup through listing authoring, review, updates, and getting paid.',
  publishYourFirstScreen: 'Create a screen, design it in the Besigner, and publish it live.',
  realmBundles: 'The end-to-end path from a standalone bundle to first-party-grade code running in the app realm.',
  redirects: 'Manage URL redirects with validation, loop detection, and hit metrics.',
  refunds: 'Refunding an organization\'s subscription charge from its org page — how much each staff role may refund before it escalates, why a refund is a loss rather than a reversal, and the audit row it writes.',
  relations: 'Link records together with reference fields, including many-to-many.',
  reportAnIssue: 'File a bug, an idea, or a question from any page in the console — on every plan, including Free.',
  reports: 'New contacts, where they came from and which sources convert, the lead funnel, the open pipeline and its forecast, won and lost, who logged what, and the task load — counted on the server, every table exportable as CSV.',
  responsiveStyling: 'Style per breakpoint from the artboard preview, use the box stylers, custom classes, and the CSS builder.',
  revenue: 'What Aglyn earned — contracted plan value and settled Stripe cash side by side, the gap between them broken into named causes, and every deduction between gross and net.',
  runAnAgencyWorkspace: 'Set up one Aglyn workspace to build and hand off many client sites — templates, collaborator seats, per-site access, domains, backups and billing.',
  salesTaxReturn: 'The quarterly Texas return — pick a period, read the Form 01-114 figures, check the rows that need attention, and export the working papers.',
  sandboxSecurity: 'How sandboxed marketplace plugins are isolated — separate origin, per-manifest CSP, pinned artifacts — and what that means when you write one.',
  saveATemplate: 'Turn a site into a reusable template and install marketplace templates.',
  screens: 'Screens are your pages — how each one gets a slug, how the hierarchy builds your URLs, and which screens count against your plan.',
  screensAndLayouts: 'The four building blocks of a site\'s structure — screens, layouts, reusable components and templates — and which one you want.',
  securityAndCompliance: 'Where the security material for a procurement review lives, and what we do not have.',
  selfHosting: 'Run the whole Aglyn platform on your own infrastructure with Docker — your own Firebase project, your own domains, your own keys.',
  selfHostingEnvironment: 'Every environment variable a self-hosted Aglyn deployment reads — what it drives, where to get its value, what shape it takes, and whether changing it needs a rebuild.',
  seo: 'Per-screen SEO, sitemap and robots, Open Graph/Twitter cards, and structured data.',
  serverApis: 'Plugin API routes behind the dispatchers, Stripe/Svix signature verification, billing hooks, and scheduled jobs.',
  settings: 'What the CRM does on its own for every site — whether a company is created from a contact\'s work email domain, who a new contact is assigned to, the address that files replies on a record, and each site\'s recipes.',
  siteProtection: 'Password-protect screens, design custom error pages, and put your site in maintenance mode.',
  siteSearch: 'Let visitors search your site\'s pages, blog entries, and dataset records with a built-in search page.',
  sso: 'How to set up SAML SSO yourself, how domain verification works, what enforcement does, and the consequences of SSO accounts living in their own identity pool.',
  staffConsole: 'Aglyn-staff tools for managing organizations, entitlements, users, and audits.',
  supportAndCommunity: 'Open a support ticket with the Aglyn team, and ask other builders in the community forum.',
  supportQueue: 'Triage customer support tickets from the staff console — filter, reply as Aglyn, and close or reopen.',
  supportTiers: 'The first-response commitment attached to each plan, why Enterprise is quoted in clock hours, and where ticket support starts.',
  supportTriage: 'How Aglyn staff triage an incoming support ticket — priority, the billing answers, and every escalation route out of the queue.',
  tasks: 'Calls, emails, meetings and to-dos with a due date, an assignee and a link to the record they are for — overdue and today read off the clock, a snooze, a reminder at its own time, and a morning digest.',
  team: 'Invite teammates with custom roles, and offer members-only areas to your site\'s visitors.',
  templatesLibrary: 'Save pages, components and layouts as reusable templates — and the safe landing place for anything you install from the marketplace.',
  termReference: 'Every term Aglyn uses, in one place — brief definitions with links to the full documentation for each.',
  textEditing: 'Edit text directly on the canvas, on the element itself, with basic rich text on opt-in elements.',
  themeBuilder: 'Set your site\'s colors, fonts, and light/dark schemes with a live preview.',
  themeStyles: 'Style from your site\'s theme instead of typing pixels, so a brand change moves every page at once.',
  troubleshooting: 'Fix the common reasons a custom domain won\'t verify or attach.',
  uptimeAndStatus: 'The live status page, what it does and does not show, and why there is no committed uptime percentage yet.',
  versionsAndPublishing: 'Every screen, layout and reusable component keeps named versions — publish one, roll back to an older one, or schedule one to go live.',
  views: 'Keep a CRM list\'s filters, columns and sort under a name, open it from the views menu or a link, share it with the team, and use a contacts view as an email audience.',
  webhooks: 'Connect Aglyn to other systems with outbound and inbound webhooks.',
  whiteLabel: 'Replace the Aglyn brand across the console, your published sites, and transactional email — product name, logo, colors, support URL, and email from-name.',
  workflows: 'Automate your site — run multi-step workflows on site events, and connect to other systems with webhooks.',
  yourFirstApiCall: 'Create an API key in the console, make your first request, read the response, handle the four errors you will actually hit, and page through a whole dataset.',
} as const satisfies Record<DocsHelpTopicKey, string>
